namespace MahApps.Metro.IconPacks
{
#if !(NETFX_CORE || WINDOWS_UWP)
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconMicrons" />.
    /// </summary>
    /// <remarks>
    /// Microns font files are available under the SIL Open Font Licence, artwork available under the CC BY-SA Licence <see><cref>https://github.com/stephenhutchings/microns?tab=License-1-ov-file#readme</cref></see>.
    /// Contributions, corrections and requests can be made on GitHub <see><cref>https://github.com/stephenhutchings/microns</cref></see>.
    /// </remarks>
    public enum PackIconMicronsKind
    {
        [Description("Empty placeholder")] None,
        [Description("mu-above (E78B, top, over, front, layers)")] Above,
        [Description("mu-align-center (E765, align, middle)")] AlignCenter,
        [Description("mu-align-left (E764, align, start)")] AlignLeft,
        [Description("mu-align-right (E766, align, end)")] AlignRight,
        [Description("mu-arrow-down (E703, direction, south)")] ArrowDown,
        [Description("mu-arrow-left (E700, direction, west)")] ArrowLeft,
        [Description("mu-arrow-right (E701, direction, east)")] ArrowRight,
        [Description("mu-arrow-up (E702, direction, north)")] ArrowUp,
        [Description("mu-at (0040, mail, tag, user, account, mention)")] At,
        [Description("mu-attach (E776, attachment, file)")] Attach,
        [Description("mu-audio (E73D, headphones)")] Audio,
        [Description("mu-audio-description (E725, media, accessibility)")] AudioDescription,
        [Description("mu-ban (E7A4, exclude, not allowed, disable, cancel)")] Ban,
        [Description("mu-bars (E740, hamburger, menu, vertical, drag)")] Bars,
        [Description("mu-below (E78C, under, bottom, behind, beneath, layers)")] Below,
        [Description("mu-bold (E75E, font, strong)")] Bold,
        [Description("mu-bookmark (E72F, save, for, later)")] Bookmark,
        [Description("mu-box (E750, box, checkbox)")] Box,
        [Description("mu-box-cross (E755, box, checkbox, ballot, bad, x)")] BoxCross,
        [Description("mu-box-cross-o (E77F, box, checkbox, ballot, outline, bad, x)")] BoxCrossOutline,
        [Description("mu-box-full (E751, box, checkbox, filled)")] BoxFull,
        [Description("mu-box-minus (E753, box, checkbox, partial, indeterminate)")] BoxMinus,
        [Description("mu-box-minus-o (E77C, box, checkbox, partial, indeterminate, outline)")] BoxMinusOutline,
        [Description("mu-box-plus (E752, box, checkbox, add)")] BoxPlus,
        [Description("mu-box-plus-o (E77D, box, checkbox, add, outline)")] BoxPlusOutline,
        [Description("mu-box-tick (E754, box, checkbox, selected, on, good)")] BoxTick,
        [Description("mu-box-tick-o (E77E, box, checkbox, selected, on, outline)")] BoxTickOutline,
        [Description("mu-calendar (E72A, date, schedule, year, month)")] Calendar,
        [Description("mu-cancel (E741, undo, close, exit, cross, x)")] Cancel,
        [Description("mu-captions (E723, media, closed)")] Captions,
        [Description("mu-caret (E70F, sort, select)")] Caret,
        [Description("mu-caret-down (E711, sort, select, descending, drop, down)")] CaretDown,
        [Description("mu-caret-up (E710, sort, select, ascending, drop, up)")] CaretUp,
        [Description("mu-chapters (E74B, list)")] Chapters,
        [Description("mu-chart-area (E7A3, graph, data, plot)")] ChartArea,
        [Description("mu-chart-bar (E727, graph, data, plot)")] ChartBar,
        [Description("mu-chart-line (E726, graph, data, plot)")] ChartLine,
        [Description("mu-chart-pie (E729, graph, data, plot)")] ChartPie,
        [Description("mu-chart-scatter (E728, graph, data, plot)")] ChartScatter,
        [Description("mu-chat (E730, message, comment, conversation)")] Chat,
        [Description("mu-clock (E72B, time, schedule, hour, second, minute)")] Clock,
        [Description("mu-cloud (E769, server)")] Cloud,
        [Description("mu-code (E74F, embed)")] Code,
        [Description("mu-cog (E736, settings, preferences)")] Cog,
        [Description("mu-columns (E7A2, text, split)")] Columns,
        [Description("mu-contract (E747, minimise, minimize)")] Contract,
        [Description("mu-copy (E78A, clone, clipboard, duplicate, layers)")] Copy,
        [Description("mu-delete (E732, trash, remove, archive)")] Delete,
        [Description("mu-difference (E797, without, exclude, layers)")] Difference,
        [Description("mu-down (E707, chevron, angle, south)")] Down,
        [Description("mu-download (E709, align, bottom, pull)")] Download,
        [Description("mu-drive (E787, disk)")] Drive,
        [Description("mu-edit (E731, create)")] Edit,
        [Description("mu-expand (E748, maximise, maximize)")] Expand,
        [Description("mu-external (E773, box, arrow, link, out)")] External,
        [Description("mu-fail (E75C, clear, error, bad)")] Fail,
        [Description("mu-file (E73A, document)")] File,
        [Description("mu-flag (E72E, remember, alert)")] Flag,
        [Description("mu-folder (E777, documents, directory, path)")] Folder,
        [Description("mu-grid (E749, square)")] Grid,
        [Description("mu-group (E739, user, collection, team)")] Group,
        [Description("mu-hash (0023, topic, subject, number, pound)")] Hash,
        [Description("mu-hd (E724, media, high, definition)")] Hd,
        [Description("mu-heart (E72D, favourite, favorite, love, like)")] Heart,
        [Description("mu-hide (E734, hidden, unpublished, eye, closed)")] Hide,
        [Description("mu-home (E77A, return, house)")] Home,
        [Description("mu-i-asterisk (E71B, check, correct, multiply)")] IAsterisk,
        [Description("mu-i-bullet (E71A, circle, dot, spot, multiply)")] IBullet,
        [Description("mu-i-cross (E719, cancel, undo, clear, wrong, incorrect, bad, x, times, multiply)")] ICross,
        [Description("mu-i-divide (E7A7, division, slash)")] IDivide,
        [Description("mu-i-down (E715, chevron, angle, south)")] IDown,
        [Description("mu-i-equal (E7A6, equality, same, equivalent)")] IEqual,
        [Description("mu-i-left (E712, chevron, angle, west)")] ILeft,
        [Description("mu-image (E73B, picture, photo, img)")] Image,
        [Description("mu-i-minus (E717, delete, remove, minimise, minimize)")] IMinus,
        [Description("mu-indent (E767, align, middle)")] Indent,
        [Description("mu-info (E759, notification, warning)")] Info,
        [Description("mu-internal (E795, box, arrow, save, in)")] Internal,
        [Description("mu-intersect (E798, overlap, join, layers)")] Intersect,
        [Description("mu-i-plus (E716, add, new, create, maximise, maximize)")] IPlus,
        [Description("mu-i-right (E713, chevron, angle, east)")] IRight,
        [Description("mu-italic (E75F, font, emphasis)")] Italic,
        [Description("mu-i-tick (E718, check, correct, good)")] ITick,
        [Description("mu-i-up (E714, chevron, angle, north)")] IUp,
        [Description("mu-justify-center (E781, justify, middle)")] JustifyCenter,
        [Description("mu-justify-left (E782, justify, start)")] JustifyLeft,
        [Description("mu-justify-right (E783, justify, end)")] JustifyRight,
        [Description("mu-landscape (E78D, orientation)")] Landscape,
        [Description("mu-left (E704, chevron, angle, west)")] Left,
        [Description("mu-link (E737, anchor, chain, url)")] Link,
        [Description("mu-list (E77B, section)")] List,
        [Description("mu-lock (E735, hidden)")] Lock,
        [Description("mu-mail (E74E, email, post, send)")] Mail,
        [Description("mu-matrix (E74A, square, grid)")] Matrix,
        [Description("mu-max (E792, maximise, maximize)")] Max,
        [Description("mu-menu (E73F, hamburger, bars, horizontal, drag)")] Menu,
        [Description("mu-microphone (E778, record, mike)")] Microphone,
        [Description("mu-min (E791, minimise, minimize)")] Min,
        [Description("mu-minus (E70E, delete, remove, minimise, minimize)")] Minus,
        [Description("mu-move (E794, drag)")] Move,
        [Description("mu-move-alt (E79D, drag)")] MoveAlt,
        [Description("mu-next (E775, media, forward, skip)")] Next,
        [Description("mu-opts-h (E742, dots, three, more, horizontal)")] OptsH,
        [Description("mu-opts-v (E743, dots, three, more, vertical)")] OptsV,
        [Description("mu-outdent (E768, align, end)")] Outdent,
        [Description("mu-outline (E799, transparent, split, layers)")] Outline,
        [Description("mu-panel-left (E78F, panel, left)")] PanelLeft,
        [Description("mu-panel-right (E790, panel, right)")] PanelRight,
        [Description("mu-paragraph (00B6, text, block)")] Paragraph,
        [Description("mu-pass (E75B, confirm, success, good)")] Pass,
        [Description("mu-pause (E71D, media, stop)")] Pause,
        [Description("mu-pipette (E7A5, eye, drop, pick, color)")] Pipette,
        [Description("mu-play (E71C, media, watch, go)")] Play,
        [Description("mu-plus (E70D, add, new, create, maximise, maximize)")] Plus,
        [Description("mu-portrait (E78E, orientation)")] Portrait,
        [Description("mu-power (E789, switch, logout)")] Power,
        [Description("mu-prev (E774, media, prev, back)")] Prev,
        [Description("mu-print (E73E, printer)")] Print,
        [Description("mu-radio-full (E758, ring, circle, filled, on)")] RadioFull,
        [Description("mu-radio-off (E756, ring, circle, off)")] RadioOff,
        [Description("mu-radio-on (E757, fisheye, selected, radio, on, record)")] RadioOn,
        [Description("mu-redo (E70B, forward, history, navigate, turn, right)")] Redo,
        [Description("mu-refresh (E796, skip, forward, ahead)")] Refresh,
        [Description("mu-replay (E70C, rewind, restart, skip, backward)")] Replay,
        [Description("mu-right (E705, chevron, angle, east)")] Right,
        [Description("mu-rss (E74C, feed)")] Rss,
        [Description("mu-scale (E793, resize)")] Scale,
        [Description("mu-scale-h (E79B, resize)")] ScaleH,
        [Description("mu-scale-v (E79C, resize)")] ScaleV,
        [Description("mu-search (E744, find, magnify)")] Search,
        [Description("mu-server (E788, drives)")] Server,
        [Description("mu-share (E74D, connect)")] Share,
        [Description("mu-show (E733, visible, published, eye, open, watch, view)")] Show,
        [Description("mu-shuffle (E79F, mix, reorder)")] Shuffle,
        [Description("mu-sort-asc (E784, order, a-z)")] SortAsc,
        [Description("mu-sort-desc (E785, order, z-a)")] SortDesc,
        [Description("mu-star (E72C, favourite, favorite, review, like)")] Star,
        [Description("mu-strikeout (E761, font, strikethrough, strike-out)")] Strikeout,
        [Description("mu-sub (E7A0, inferior, sinf)")] Sub,
        [Description("mu-subtitles (E71E, media, captions, text)")] Subtitles,
        [Description("mu-sup (E7A1, superior, sups)")] Sup,
        [Description("mu-swap (E79E, exchange, reverse, flip)")] Swap,
        [Description("mu-text (E75D, font, letter, A)")] Text,
        [Description("mu-text-size (E762, font)")] TextSize,
        [Description("mu-text-unstyle (E763, font, clear)")] TextUnstyle,
        [Description("mu-translate (E786, language)")] Translate,
        [Description("mu-underline (E760, )")] Underline,
        [Description("mu-undo (E70A, back, history, navigate, turn, left)")] Undo,
        [Description("mu-unite (E79A, combine, union, join, layers)")] Unite,
        [Description("mu-unknown (E780, lost, gone, question, error, help)")] Unknown,
        [Description("mu-up (E706, chevron, angle, north)")] Up,
        [Description("mu-upload (E708, align, top, push)")] Upload,
        [Description("mu-user (E738, person, individual)")] User,
        [Description("mu-video (E73C, play, circle)")] Video,
        [Description("mu-video-camera (E779, record, film)")] VideoCamera,
        [Description("mu-vol-high (E721, media, sound, listen, loud)")] VolHigh,
        [Description("mu-vol-low (E71F, media, sound, listen, mute, quiet)")] VolLow,
        [Description("mu-vol-mid (E720, media, sound, listen, medium)")] VolMid,
        [Description("mu-vol-mute (E722, media, sound, listen, silent)")] VolMute,
        [Description("mu-warn (E75A, notification, danger, warning, error)")] Warn,
        [Description("mu-web (E76A, world, map, sphere, internet)")] Web,
        [Description("mu-wifi (E76B, online)")] Wifi,
        [Description("mu-zoom-in (E745, magnify)")] ZoomIn,
        [Description("mu-zoom-out (E746, magnify)")] ZoomOut
    }
}