namespace MahApps.Metro.IconPacks
{
#if !(NETFX_CORE || WINDOWS_UWP)
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconOcticons" />.
    /// </summary>
    /// <remarks>
    /// All icons sourced from GitHub Octicons <see><cref>https://octicons.github.com</cref></see>
    /// In accordance of <see><cref>https://github.com/primer/octicons/blob/master/LICENSE</cref></see>.
    /// </remarks>
    public enum PackIconOcticonsKind
    {
        [Description("Empty placeholder")] None,
        [Description("Alert (Warning, Triangle, Exclamation, Point)")] Alert,
        [Description("Archive (Box, Catalog)")] Archive,
        [Description("ArrowBoth (Point, Direction, Left, Right)")] ArrowBoth,
        [Description("ArrowDown (Point, Direction)")] ArrowDown,
        [Description("ArrowLeft (Point, Direction)")] ArrowLeft,
        [Description("ArrowRight (Point, Direction)")] ArrowRight,
        [Description("ArrowSmallDown (Point, Direction, Little, Tiny)")] ArrowSmallDown,
        [Description("ArrowSmallLeft (Point, Direction, Little, Tiny)")] ArrowSmallLeft,
        [Description("ArrowSmallRight (Point, Direction, Little, Tiny)")] ArrowSmallRight,
        [Description("ArrowSmallUp (Point, Direction, Little, Tiny)")] ArrowSmallUp,
        [Description("ArrowUp (Point, Direction)")] ArrowUp,
        [Description("Beaker (Experiment, Labs, Experimental, Feature, Test, Science, Education, Study, Development, Testing)")] Beaker,
        [Description("Bell (Notification)")] Bell,
        [Description("Bold (Markdown, Bold, Text)")] Bold,
        [Description("Book (Book, Journal, Wiki, Readme)")] Book,
        [Description("Bookmark (Tab, Star)")] Bookmark,
        [Description("Briefcase (Suitcase, Business)")] Briefcase,
        [Description("Broadcast (Rss, Radio, Signal)")] Broadcast,
        [Description("Browser (Window, Web)")] Browser,
        [Description("Bug (Insect, Issue)")] Bug,
        [Description("Calendar (Time, Day, Month, Year, Date, Appointment)")] Calendar,
        [Description("Check (Mark, Yes, Confirm, Accept, Ok, Success)")] Check,
        [Description("Checklist (Todo, Tasks)")] Checklist,
        [Description("ChevronDown (Triangle, Arrow)")] ChevronDown,
        [Description("ChevronLeft (Triangle, Arrow)")] ChevronLeft,
        [Description("ChevronRight (Triangle, Arrow)")] ChevronRight,
        [Description("ChevronUp (Triangle, Arrow)")] ChevronUp,
        [Description("CircleSlash (No, Deny, Fail, Failure, Error, Bad)")] CircleSlash,
        [Description("CircuitBoard (Developer, Hardware, Electricity)")] CircuitBoard,
        [Description("Clippy (Copy, Paste, Save, Capture, Clipboard)")] Clippy,
        [Description("Clock (Time, Hour, Minute, Second, Watch)")] Clock,
        [Description("CloudDownload (Save, Install, Get)")] CloudDownload,
        [Description("CloudUpload (Put, Export)")] CloudUpload,
        [Description("Code (Brackets)")] Code,
        [Description("Comment (Speak, Bubble)")] Comment,
        [Description("CommentDiscussion (Converse, Talk)")] CommentDiscussion,
        [Description("CreditCard (Money, Billing, Payments, Transactions)")] CreditCard,
        [Description("Dash (Hyphen, Range)")] Dash,
        [Description("Dashboard (Speed, Dial)")] Dashboard,
        [Description("Database (Disks, Data)")] Database,
        [Description("Dependent (Dependency, Dependent, File)")] Dependent,
        [Description("DesktopDownload (Clone, Download)")] DesktopDownload,
        [Description("DeviceCamera (Photo, Picture, Image, Snapshot)")] DeviceCamera,
        [Description("DeviceCameraVideo (Watch, View, Media, Stream)")] DeviceCameraVideo,
        [Description("DeviceDesktop (Computer, Monitor)")] DeviceDesktop,
        [Description("DeviceMobile (Phone, Iphone, Cellphone)")] DeviceMobile,
        [Description("Diff (Difference, Changes, Compare)")] Diff,
        [Description("DiffAdded (New, Addition, Plus)")] DiffAdded,
        [Description("DiffIgnored (Slash)")] DiffIgnored,
        [Description("DiffModified (Dot, Changed, Updated)")] DiffModified,
        [Description("DiffRemoved (Deleted, Subtracted, Dash)")] DiffRemoved,
        [Description("DiffRenamed (Moved, Arrow)")] DiffRenamed,
        [Description("Ellipsis (Dot, Read, More, Hidden, Expand)")] Ellipsis,
        [Description("Eye (Look, Watch, See)")] Eye,
        [Description("EyeClosed (Hidden, Invisible, Concealed)")] EyeClosed,
        [Description("File (File, Text, Words)")] File,
        [Description("FileBinary (Image, Video, Word, Powerpoint, Excel)")] FileBinary,
        [Description("FileCode (Text, Javascript, Html, Css, Php, Ruby, Coffeescript, Sass, Scss)")] FileCode,
        [Description("FileDirectory (Folder)")] FileDirectory,
        [Description("FileMedia (Image, Video, Audio)")] FileMedia,
        [Description("FilePdf (Adobe)")] FilePdf,
        [Description("FileSubmodule (Folder)")] FileSubmodule,
        [Description("FileSymlinkDirectory (Folder, Subfolder, Link, Alias)")] FileSymlinkDirectory,
        [Description("FileSymlinkFile (Link, Alias)")] FileSymlinkFile,
        [Description("FileZip (Compress, Archive)")] FileZip,
        [Description("Flame (Fire, Hot, Burn, Trending)")] Flame,
        [Description("Fold (Unfold, Hide, Collapse)")] Fold,
        [Description("FoldDown (Unfold, Hide, Collapse, Down)")] FoldDown,
        [Description("FoldUp (Unfold, Hide, Collapse, Up)")] FoldUp,
        [Description("Gear (Settings)")] Gear,
        [Description("Gift (Package, Present, Skill, Craft, Freebie)")] Gift,
        [Description("Gist (Gist, Github)")] Gist,
        [Description("GistSecret (Gist, Secret, Private)")] GistSecret,
        [Description("GitBranch (Fork, Branch, Git, Duplicate)")] GitBranch,
        [Description("GitCommit (Save)")] GitCommit,
        [Description("GitCompare (Difference, Changes)")] GitCompare,
        [Description("GithubAction (Board, Workflow, Action, Automation)")] GithubAction,
        [Description("GitMerge (Join)")] GitMerge,
        [Description("GitPullRequest (Review)")] GitPullRequest,
        [Description("Globe (World, Earth, Planet)")] Globe,
        [Description("Grabber (Mover, Drap, Drop, Sort)")] Grabber,
        [Description("Graph (Trend, Stats, Statistics)")] Graph,
        [Description("Heart (Love, Beat)")] Heart,
        [Description("HeartOutline (Love, Beat)")] HeartOutline,
        [Description("History (Time, Past, Revert, Back)")] History,
        [Description("Home (Welcome, Index, House, Building)")] Home,
        [Description("HorizontalRule (Hr)")] HorizontalRule,
        [Description("Hubot (Robot, Bot)")] Hubot,
        [Description("Inbox (Mail, Todo, New, Messages)")] Inbox,
        [Description("Infinity (Unlimited, Infinite)")] Infinity,
        [Description("Info (Help)")] Info,
        [Description("InternalRepo (Internal,Repo,Repository)")] InternalRepo,
        [Description("IssueClosed (Done, Complete)")] IssueClosed,
        [Description("IssueOpened (New)")] IssueOpened,
        [Description("IssueReopened (Regression)")] IssueReopened,
        [Description("Italic (Font, Italic, Style)")] Italic,
        [Description("Jersey (Team, Game, Basketball)")] Jersey,
        [Description("KebabHorizontal (Kebab, Dot, Menu, More)")] KebabHorizontal,
        [Description("KebabVertical (Kebab, Dot, Menu, More)")] KebabVertical,
        [Description("Key (Key, Lock, Secure, Safe)")] Key,
        [Description("Keyboard (Type, Keys, Write, Shortcuts)")] Keyboard,
        [Description("Law (Legal, Bill)")] Law,
        [Description("LightBulb (Idea)")] LightBulb,
        [Description("LineArrowDown (Arrow, Point, Direction, Down)")] LineArrowDown,
        [Description("LineArrowLeft (Arrow, Point, Direction, Left)")] LineArrowLeft,
        [Description("LineArrowRight (Arrow, Point, Direction, Right)")] LineArrowRight,
        [Description("LineArrowUp (Arrow, Point, Direction, Up)")] LineArrowUp,
        [Description("Link (Connect, Hyperlink)")] Link,
        [Description("LinkExternal (Out, See, More, Go, To)")] LinkExternal,
        [Description("ListOrdered (Numbers, Tasks, Todo, Items)")] ListOrdered,
        [Description("ListUnordered (Bullet, Point, Tasks, Todo, Items)")] ListUnordered,
        [Description("Location (Here, Marker)")] Location,
        [Description("Lock (Secure, Safe, Protected)")] Lock,
        [Description("LogoGist (Brand, Github, Logo)")] LogoGist,
        [Description("LogoGithub (Brand, Github, Logo)")] LogoGithub,
        [Description("Mail (Email, Unread)")] Mail,
        [Description("MailRead (Email, Open)")] MailRead,
        [Description("Markdown (Markup, Style)")] Markdown,
        [Description("MarkGithub (Octocat, Brand, Github, Logo)")] MarkGithub,
        [Description("Megaphone (Bullhorn, Loud, Shout, Broadcast)")] Megaphone,
        [Description("Mention (At, Ping)")] Mention,
        [Description("Milestone (Marker)")] Milestone,
        [Description("Mirror (Reflect)")] Mirror,
        [Description("MortarBoard (Education, Learn, Teach)")] MortarBoard,
        [Description("Mute (Quiet, Sound, Audio, Turn, Off)")] Mute,
        [Description("NoNewline (Return)")] NoNewline,
        [Description("NorthStar (Star, Snowflake, Asterisk)")] NorthStar,
        [Description("Note (Card, Paper, Ticket)")] Note,
        [Description("Octoface (Octocat, Brand)")] Octoface,
        [Description("Organization (People, Group, Team)")] Organization,
        [Description("Package (Box, Ship)")] Package,
        [Description("Paintcan (Style, Theme, Art, Color)")] Paintcan,
        [Description("Pencil (Edit, Change, Update, Write)")] Pencil,
        [Description("Person (People, Man, Woman, Human)")] Person,
        [Description("Pin (Save, Star, Bookmark)")] Pin,
        [Description("Play (Play, Start, Begin, Action)")] Play,
        [Description("Plug (Hook, Webhook)")] Plug,
        [Description("Plus (Add, New, More)")] Plus,
        [Description("PlusSmall (Add, New, More, Small)")] PlusSmall,
        [Description("PrimitiveDot (Circle)")] PrimitiveDot,
        [Description("PrimitiveDotStroke (Circle, Dot, Unread)")] PrimitiveDotStroke,
        [Description("PrimitiveSquare (Box)")] PrimitiveSquare,
        [Description("Project (Board, Kanban, Columns, Scrum)")] Project,
        [Description("Pulse (Graph, Trend, Line, Activity)")] Pulse,
        [Description("Question (Help, Explain)")] Question,
        [Description("Quote (Quotation)")] Quote,
        [Description("RadioTower (Broadcast)")] RadioTower,
        [Description("Reply (ReplyAll, Back)")] Reply,
        [Description("Repo (Book, Journal, Repository)")] Repo,
        [Description("RepoClone (Book, Journal, Repository)")] RepoClone,
        [Description("RepoForcePush (Book, Journal, Put)")] RepoForcePush,
        [Description("RepoForked (Book, Journal, Copy)")] RepoForked,
        [Description("RepoPull (Book, Journal, Get)")] RepoPull,
        [Description("RepoPush (Book, Journal, Repository, Put)")] RepoPush,
        [Description("Report (Report, Abuse, Flag)")] Report,
        [Description("RepoTemplate (Book, New, Add, Template)")] RepoTemplate,
        [Description("RepoTemplatePrivate (Book, New, Template)")] RepoTemplatePrivate,
        [Description("RequestChanges (Diff, Changes, Request)")] RequestChanges,
        [Description("Rocket (Staff, Stafftools, Blast, Off, Space, Launch, Ship)")] Rocket,
        [Description("Rss (Broadcast, Feed, Atom)")] Rss,
        [Description("Ruby (Code, Language)")] Ruby,
        [Description("Saved (Saved, Bookmark)")] Saved,
        [Description("ScreenFull (Fullscreen, Expand)")] ScreenFull,
        [Description("ScreenNormal (Fullscreen, Expand, Exit)")] ScreenNormal,
        [Description("Search (Magnifying, Glass)")] Search,
        [Description("Server (Computers, Racks, Ops)")] Server,
        [Description("Settings (Sliders, Filters, Controls, Levels)")] Settings,
        [Description("Shield (Security, Shield, Protection)")] Shield,
        [Description("ShieldCheck (Security, Shield, Protection, Check, Success)")] ShieldCheck,
        [Description("ShieldLock (Protect, Shield, Lock)")] ShieldLock,
        [Description("ShieldX (Security, Shield, Protection, Fail)")] ShieldX,
        [Description("SignIn (Door, Arrow, Direction, Enter, LogIn)")] SignIn,
        [Description("SignOut (Door, Arrow, Direction, Leave, LogOut)")] SignOut,
        [Description("Skip (Skip, Slash)")] Skip,
        [Description("Smiley (Emoji, Smile, Mood, Emotion)")] Smiley,
        [Description("Squirrel (Ship, Shipit, Launch)")] Squirrel,
        [Description("Star (Save, Remember, Like)")] Star,
        [Description("Stop (Block, Spam, Report)")] Stop,
        [Description("Sync (Cycle, Refresh, Loop)")] Sync,
        [Description("Tag (Release)")] Tag,
        [Description("Tasklist (Todo)")] Tasklist,
        [Description("Telescope (Science, Space, Look, View, Explore)")] Telescope,
        [Description("Terminal (Code, Ops, Shell)")] Terminal,
        [Description("TextSize (Font, Size, Text)")] TextSize,
        [Description("ThreeBars (Hamburger, Menu, Dropdown)")] ThreeBars,
        [Description("Thumbsdown (Thumb, Thumbsdown, Rejected, Dislike)")] Thumbsdown,
        [Description("Thumbsup (Thumb, Thumbsup, Prop, Ship, Like)")] Thumbsup,
        [Description("Tools (Screwdriver, Wrench, Settings)")] Tools,
        [Description("Trashcan (Garbage, Rubbish, Recycle, Delete)")] Trashcan,
        [Description("TriangleDown (Arrow, Point, Direction)")] TriangleDown,
        [Description("TriangleLeft (Arrow, Point, Direction)")] TriangleLeft,
        [Description("TriangleRight (Arrow, Point, Direction)")] TriangleRight,
        [Description("TriangleUp (Arrow, Point, Direction)")] TriangleUp,
        [Description("Unfold (Expand, Open, Reveal)")] Unfold,
        [Description("Unmute (Loud, Volume, Audio, Sound, Play)")] Unmute,
        [Description("Unsaved (Unsaved, Bookmark)")] Unsaved,
        [Description("Unverified (Insecure, Untrusted, Signed)")] Unverified,
        [Description("Verified (Trusted, Secure, Trustworthy, Signed)")] Verified,
        [Description("Versions (History, Commits)")] Versions,
        [Description("Watch (Wait, Hourglass, Time, Date)")] Watch,
        [Description("Workflow (Workflow, Actions)")] Workflow,
        [Description("WorkflowAll (Workflow, Actions)")] WorkflowAll,
        [Description("X (Remove, Close, Delete)")] X,
        [Description("Zap (Electricity, Lightning, Props, Like, Star, Save)")] Zap
    }
}