namespace MahApps.Metro.IconPacks
{
#if !(NETFX_CORE || WINDOWS_UWP)
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconOcticons" />.
    /// </summary>
    /// <remarks>
    /// All icons sourced from GitHub Octicons <see><cref>https://github.com/primer/octicons</cref></see>
    /// In accordance of <see><cref>https://github.com/primer/octicons?tab=MIT-1-ov-file#readme</cref></see>.
    /// </remarks>
    public enum PackIconOcticonsKind
    {
        [Description("Empty placeholder")] None,
        [Description("accessibility-16")] Accessibility16,
        [Description("accessibility-inset-16")] AccessibilityInset16,
        [Description("alert-16 (warning, triangle, exclamation, point)")] Alert16,
        [Description("alert-24 (warning, triangle, exclamation, point)")] Alert24,
        [Description("alert-fill-12")] AlertFill12,
        [Description("alert-fill-16")] AlertFill16,
        [Description("alert-fill-24")] AlertFill24,
        [Description("apps-16")] Apps16,
        [Description("archive-16 (box, catalog)")] Archive16,
        [Description("archive-24 (box, catalog)")] Archive24,
        [Description("arrow-both-16 (point, direction, left, right)")] ArrowBoth16,
        [Description("arrow-both-24 (point, direction, left, right)")] ArrowBoth24,
        [Description("arrow-down-16 (point, direction)")] ArrowDown16,
        [Description("arrow-down-24 (point, direction)")] ArrowDown24,
        [Description("arrow-down-left-16")] ArrowDownLeft16,
        [Description("arrow-down-left-24")] ArrowDownLeft24,
        [Description("arrow-down-right-16")] ArrowDownRight16,
        [Description("arrow-down-right-24")] ArrowDownRight24,
        [Description("arrow-left-16 (point, direction)")] ArrowLeft16,
        [Description("arrow-left-24 (point, direction)")] ArrowLeft24,
        [Description("arrow-right-16 (point, direction)")] ArrowRight16,
        [Description("arrow-right-24 (point, direction)")] ArrowRight24,
        [Description("arrow-switch-16")] ArrowSwitch16,
        [Description("arrow-switch-24")] ArrowSwitch24,
        [Description("arrow-up-16 (point, direction)")] ArrowUp16,
        [Description("arrow-up-24 (point, direction)")] ArrowUp24,
        [Description("arrow-up-left-16")] ArrowUpLeft16,
        [Description("arrow-up-left-24")] ArrowUpLeft24,
        [Description("arrow-up-right-16")] ArrowUpRight16,
        [Description("arrow-up-right-24")] ArrowUpRight24,
        [Description("beaker-16 (experiment, labs, experimental, feature, test, science, education, study, development, testing)")] Beaker16,
        [Description("beaker-24 (experiment, labs, experimental, feature, test, science, education, study, development, testing)")] Beaker24,
        [Description("bell-16 (notification)")] Bell16,
        [Description("bell-24 (notification)")] Bell24,
        [Description("bell-fill-16")] BellFill16,
        [Description("bell-fill-24")] BellFill24,
        [Description("bell-slash-16")] BellSlash16,
        [Description("bell-slash-24")] BellSlash24,
        [Description("blocked-16")] Blocked16,
        [Description("blocked-24")] Blocked24,
        [Description("bold-16 (markdown, bold, text)")] Bold16,
        [Description("bold-24 (markdown, bold, text)")] Bold24,
        [Description("book-16 (book, journal, wiki, readme)")] Book16,
        [Description("book-24 (book, journal, wiki, readme)")] Book24,
        [Description("bookmark-16 (tab, star)")] Bookmark16,
        [Description("bookmark-24 (tab, star)")] Bookmark24,
        [Description("bookmark-fill-24")] BookmarkFill24,
        [Description("bookmark-slash-16")] BookmarkSlash16,
        [Description("bookmark-slash-24")] BookmarkSlash24,
        [Description("bookmark-slash-fill-24")] BookmarkSlashFill24,
        [Description("briefcase-16 (suitcase, business)")] Briefcase16,
        [Description("briefcase-24 (suitcase, business)")] Briefcase24,
        [Description("broadcast-16 (rss, radio, signal)")] Broadcast16,
        [Description("broadcast-24 (rss, radio, signal)")] Broadcast24,
        [Description("browser-16 (window, web)")] Browser16,
        [Description("browser-24 (window, web)")] Browser24,
        [Description("bug-16 (insect, issue)")] Bug16,
        [Description("bug-24 (insect, issue)")] Bug24,
        [Description("cache-16")] Cache16,
        [Description("calendar-16 (time, day, month, year, date, appointment)")] Calendar16,
        [Description("calendar-24 (time, day, month, year, date, appointment)")] Calendar24,
        [Description("check-16 (mark, yes, confirm, accept, ok, success)")] Check16,
        [Description("check-24 (mark, yes, confirm, accept, ok, success)")] Check24,
        [Description("checkbox-16")] Checkbox16,
        [Description("checkbox-24")] Checkbox24,
        [Description("check-circle-16")] CheckCircle16,
        [Description("check-circle-24")] CheckCircle24,
        [Description("check-circle-fill-12")] CheckCircleFill12,
        [Description("check-circle-fill-16")] CheckCircleFill16,
        [Description("check-circle-fill-24")] CheckCircleFill24,
        [Description("checklist-16 (todo, tasks)")] Checklist16,
        [Description("checklist-24 (todo, tasks)")] Checklist24,
        [Description("chevron-down-12 (triangle, arrow)")] ChevronDown12,
        [Description("chevron-down-16 (triangle, arrow)")] ChevronDown16,
        [Description("chevron-down-24 (triangle, arrow)")] ChevronDown24,
        [Description("chevron-left-16 (triangle, arrow)")] ChevronLeft16,
        [Description("chevron-left-24 (triangle, arrow)")] ChevronLeft24,
        [Description("chevron-right-12 (triangle, arrow)")] ChevronRight12,
        [Description("chevron-right-16 (triangle, arrow)")] ChevronRight16,
        [Description("chevron-right-24 (triangle, arrow)")] ChevronRight24,
        [Description("chevron-up-12 (triangle, arrow)")] ChevronUp12,
        [Description("chevron-up-16 (triangle, arrow)")] ChevronUp16,
        [Description("chevron-up-24 (triangle, arrow)")] ChevronUp24,
        [Description("circle-16")] Circle16,
        [Description("circle-24")] Circle24,
        [Description("circle-slash-16 (no, deny, fail, failure, error, bad)")] CircleSlash16,
        [Description("circle-slash-24 (no, deny, fail, failure, error, bad)")] CircleSlash24,
        [Description("clock-16 (time, hour, minute, second, watch)")] Clock16,
        [Description("clock-24 (time, hour, minute, second, watch)")] Clock24,
        [Description("clock-fill-16")] ClockFill16,
        [Description("clock-fill-24")] ClockFill24,
        [Description("cloud-16")] Cloud16,
        [Description("cloud-24")] Cloud24,
        [Description("cloud-offline-16")] CloudOffline16,
        [Description("cloud-offline-24")] CloudOffline24,
        [Description("code-16 (brackets)")] Code16,
        [Description("code-24 (brackets)")] Code24,
        [Description("code-of-conduct-16")] CodeOfConduct16,
        [Description("code-of-conduct-24")] CodeOfConduct24,
        [Description("code-review-16")] CodeReview16,
        [Description("code-review-24")] CodeReview24,
        [Description("codescan-16")] Codescan16,
        [Description("codescan-24")] Codescan24,
        [Description("codescan-checkmark-16")] CodescanCheckmark16,
        [Description("codescan-checkmark-24")] CodescanCheckmark24,
        [Description("codespaces-16")] Codespaces16,
        [Description("codespaces-24")] Codespaces24,
        [Description("code-square-16")] CodeSquare16,
        [Description("code-square-24")] CodeSquare24,
        [Description("columns-16")] Columns16,
        [Description("columns-24")] Columns24,
        [Description("command-palette-16")] CommandPalette16,
        [Description("command-palette-24")] CommandPalette24,
        [Description("comment-16 (speak, bubble)")] Comment16,
        [Description("comment-24 (speak, bubble)")] Comment24,
        [Description("comment-discussion-16 (converse, talk)")] CommentDiscussion16,
        [Description("comment-discussion-24 (converse, talk)")] CommentDiscussion24,
        [Description("commit-24")] Commit24,
        [Description("container-16")] Container16,
        [Description("container-24")] Container24,
        [Description("copilot-16")] Copilot16,
        [Description("copilot-24")] Copilot24,
        [Description("copilot-48")] Copilot48,
        [Description("copilot-96")] Copilot96,
        [Description("copilot-error-16")] CopilotError16,
        [Description("copilot-warning-16")] CopilotWarning16,
        [Description("copy-16")] Copy16,
        [Description("copy-24")] Copy24,
        [Description("cpu-16")] Cpu16,
        [Description("cpu-24")] Cpu24,
        [Description("credit-card-16 (money, billing, payments, transactions)")] CreditCard16,
        [Description("credit-card-24 (money, billing, payments, transactions)")] CreditCard24,
        [Description("cross-reference-16")] CrossReference16,
        [Description("cross-reference-24")] CrossReference24,
        [Description("dash-16 (hyphen, range)")] Dash16,
        [Description("dash-24 (hyphen, range)")] Dash24,
        [Description("database-16 (disks, data)")] Database16,
        [Description("database-24 (disks, data)")] Database24,
        [Description("dependabot-16")] Dependabot16,
        [Description("dependabot-24")] Dependabot24,
        [Description("desktop-download-16 (clone, download)")] DesktopDownload16,
        [Description("desktop-download-24 (clone, download)")] DesktopDownload24,
        [Description("device-camera-16 (photo, picture, image, snapshot)")] DeviceCamera16,
        [Description("device-camera-video-16 (watch, view, media, stream)")] DeviceCameraVideo16,
        [Description("device-camera-video-24 (watch, view, media, stream)")] DeviceCameraVideo24,
        [Description("device-desktop-16 (computer, monitor)")] DeviceDesktop16,
        [Description("device-desktop-24 (computer, monitor)")] DeviceDesktop24,
        [Description("device-mobile-16 (phone, iphone, cellphone)")] DeviceMobile16,
        [Description("device-mobile-24 (phone, iphone, cellphone)")] DeviceMobile24,
        [Description("devices-16")] Devices16,
        [Description("devices-24")] Devices24,
        [Description("diamond-16")] Diamond16,
        [Description("diamond-24")] Diamond24,
        [Description("diff-16 (difference, changes, compare)")] Diff16,
        [Description("diff-24 (difference, changes, compare)")] Diff24,
        [Description("diff-added-16 (new, addition, plus)")] DiffAdded16,
        [Description("diff-ignored-16 (slash)")] DiffIgnored16,
        [Description("diff-modified-16 (dot, changed, updated)")] DiffModified16,
        [Description("diff-removed-16 (deleted, subtracted, dash)")] DiffRemoved16,
        [Description("diff-renamed-16 (moved, arrow)")] DiffRenamed16,
        [Description("discussion-closed-16")] DiscussionClosed16,
        [Description("discussion-closed-24")] DiscussionClosed24,
        [Description("discussion-duplicate-16")] DiscussionDuplicate16,
        [Description("discussion-duplicate-24")] DiscussionDuplicate24,
        [Description("discussion-outdated-16")] DiscussionOutdated16,
        [Description("discussion-outdated-24")] DiscussionOutdated24,
        [Description("dot-16")] Dot16,
        [Description("dot-24")] Dot24,
        [Description("dot-fill-16")] DotFill16,
        [Description("dot-fill-24")] DotFill24,
        [Description("download-16")] Download16,
        [Description("download-24")] Download24,
        [Description("duplicate-16")] Duplicate16,
        [Description("duplicate-24")] Duplicate24,
        [Description("ellipsis-16 (dot, read, more, hidden, expand)")] Ellipsis16,
        [Description("eye-16 (look, watch, see)")] Eye16,
        [Description("eye-24 (look, watch, see)")] Eye24,
        [Description("eye-closed-16 (hidden, invisible, concealed, )")] EyeClosed16,
        [Description("eye-closed-24 (hidden, invisible, concealed, )")] EyeClosed24,
        [Description("feed-discussion-16")] FeedDiscussion16,
        [Description("feed-forked-16")] FeedForked16,
        [Description("feed-heart-16")] FeedHeart16,
        [Description("feed-issue-closed-16")] FeedIssueClosed16,
        [Description("feed-issue-draft-16")] FeedIssueDraft16,
        [Description("feed-issue-open-16")] FeedIssueOpen16,
        [Description("feed-issue-reopen-16")] FeedIssueReopen16,
        [Description("feed-merged-16")] FeedMerged16,
        [Description("feed-person-16")] FeedPerson16,
        [Description("feed-plus-16")] FeedPlus16,
        [Description("feed-public-16")] FeedPublic16,
        [Description("feed-pull-request-closed-16")] FeedPullRequestClosed16,
        [Description("feed-pull-request-draft-16")] FeedPullRequestDraft16,
        [Description("feed-pull-request-open-16")] FeedPullRequestOpen16,
        [Description("feed-repo-16")] FeedRepo16,
        [Description("feed-rocket-16")] FeedRocket16,
        [Description("feed-star-16")] FeedStar16,
        [Description("feed-tag-16")] FeedTag16,
        [Description("feed-trophy-16")] FeedTrophy16,
        [Description("file-16 (file, text, words)")] File16,
        [Description("file-24 (file, text, words)")] File24,
        [Description("file-added-16")] FileAdded16,
        [Description("file-badge-16")] FileBadge16,
        [Description("file-binary-16 (image, video, word, powerpoint, excel)")] FileBinary16,
        [Description("file-binary-24 (image, video, word, powerpoint, excel)")] FileBinary24,
        [Description("file-code-16 (text, javascript, html, css, php, ruby, coffeescript, sass, scss)")] FileCode16,
        [Description("file-code-24 (text, javascript, html, css, php, ruby, coffeescript, sass, scss)")] FileCode24,
        [Description("file-diff-16")] FileDiff16,
        [Description("file-diff-24")] FileDiff24,
        [Description("file-directory-16 (folder)")] FileDirectory16,
        [Description("file-directory-24 (folder)")] FileDirectory24,
        [Description("file-directory-fill-16")] FileDirectoryFill16,
        [Description("file-directory-fill-24")] FileDirectoryFill24,
        [Description("file-directory-open-fill-16")] FileDirectoryOpenFill16,
        [Description("file-directory-symlink-16")] FileDirectorySymlink16,
        [Description("file-directory-symlink-24")] FileDirectorySymlink24,
        [Description("file-media-24 (image, video, audio)")] FileMedia24,
        [Description("file-moved-16")] FileMoved16,
        [Description("file-removed-16")] FileRemoved16,
        [Description("file-submodule-16 (folder)")] FileSubmodule16,
        [Description("file-submodule-24 (folder)")] FileSubmodule24,
        [Description("file-symlink-file-16 (link, alias)")] FileSymlinkFile16,
        [Description("file-symlink-file-24 (link, alias)")] FileSymlinkFile24,
        [Description("file-zip-16 (compress, archive)")] FileZip16,
        [Description("file-zip-24 (compress, archive)")] FileZip24,
        [Description("filter-16")] Filter16,
        [Description("filter-24")] Filter24,
        [Description("filter-remove-16 (funnel, filter, remove, delete)")] FilterRemove16,
        [Description("filter-remove-24 (funnel, filter, remove, delete)")] FilterRemove24,
        [Description("fiscal-host-16 (safe, money)")] FiscalHost16,
        [Description("flame-16 (fire, hot, burn, trending)")] Flame16,
        [Description("flame-24 (fire, hot, burn, trending)")] Flame24,
        [Description("fold-16 (unfold, hide, collapse)")] Fold16,
        [Description("fold-24 (unfold, hide, collapse)")] Fold24,
        [Description("fold-down-16 (unfold, hide, collapse, down)")] FoldDown16,
        [Description("fold-down-24 (unfold, hide, collapse, down)")] FoldDown24,
        [Description("fold-up-16 (unfold, hide, collapse, up)")] FoldUp16,
        [Description("fold-up-24 (unfold, hide, collapse, up)")] FoldUp24,
        [Description("gear-16 (settings)")] Gear16,
        [Description("gear-24 (settings)")] Gear24,
        [Description("gift-16 (package, present, skill, craft, freebie)")] Gift16,
        [Description("gift-24 (package, present, skill, craft, freebie)")] Gift24,
        [Description("git-branch-16 (fork, branch, git, duplicate)")] GitBranch16,
        [Description("git-branch-24 (fork, branch, git, duplicate)")] GitBranch24,
        [Description("git-commit-16 (save)")] GitCommit16,
        [Description("git-commit-24 (save)")] GitCommit24,
        [Description("git-compare-16 (difference, changes)")] GitCompare16,
        [Description("git-compare-24 (difference, changes)")] GitCompare24,
        [Description("git-merge-16 (join)")] GitMerge16,
        [Description("git-merge-24 (join)")] GitMerge24,
        [Description("git-merge-queue-16")] GitMergeQueue16,
        [Description("git-merge-queue-24")] GitMergeQueue24,
        [Description("git-pull-request-16 (review)")] GitPullRequest16,
        [Description("git-pull-request-24 (review)")] GitPullRequest24,
        [Description("git-pull-request-closed-16")] GitPullRequestClosed16,
        [Description("git-pull-request-closed-24")] GitPullRequestClosed24,
        [Description("git-pull-request-draft-16")] GitPullRequestDraft16,
        [Description("git-pull-request-draft-24")] GitPullRequestDraft24,
        [Description("globe-16 (world, earth, planet, enterprise)")] Globe16,
        [Description("globe-24 (world, earth, planet, enterprise)")] Globe24,
        [Description("goal-16")] Goal16,
        [Description("goal-24")] Goal24,
        [Description("grabber-16 (mover, drag, drop, sort)")] Grabber16,
        [Description("grabber-24 (mover, drag, drop, sort)")] Grabber24,
        [Description("graph-16 (trend, stats, statistics)")] Graph16,
        [Description("graph-24 (trend, stats, statistics)")] Graph24,
        [Description("hash-16")] Hash16,
        [Description("hash-24")] Hash24,
        [Description("heading-16")] Heading16,
        [Description("heading-24")] Heading24,
        [Description("heart-16 (love, beat)")] Heart16,
        [Description("heart-24 (love, beat)")] Heart24,
        [Description("heart-fill-16")] HeartFill16,
        [Description("heart-fill-24")] HeartFill24,
        [Description("history-16 (time, past, revert, back)")] History16,
        [Description("history-24 (time, past, revert, back)")] History24,
        [Description("home-16 (welcome, index, house, building)")] Home16,
        [Description("home-24 (welcome, index, house, building)")] Home24,
        [Description("home-fill-24")] HomeFill24,
        [Description("horizontal-rule-16 (hr)")] HorizontalRule16,
        [Description("horizontal-rule-24 (hr)")] HorizontalRule24,
        [Description("hourglass-16")] Hourglass16,
        [Description("hourglass-24")] Hourglass24,
        [Description("hubot-16 (robot, bot)")] Hubot16,
        [Description("hubot-24 (robot, bot)")] Hubot24,
        [Description("id-badge-16")] IdBadge16,
        [Description("image-16")] Image16,
        [Description("image-24")] Image24,
        [Description("inbox-16 (mail, todo, new, messages)")] Inbox16,
        [Description("inbox-24 (mail, todo, new, messages)")] Inbox24,
        [Description("infinity-16 (unlimited, infinite)")] Infinity16,
        [Description("infinity-24 (unlimited, infinite)")] Infinity24,
        [Description("info-16 (help)")] Info16,
        [Description("info-24 (help)")] Info24,
        [Description("issue-closed-16 (done, complete)")] IssueClosed16,
        [Description("issue-closed-24 (done, complete)")] IssueClosed24,
        [Description("issue-draft-16")] IssueDraft16,
        [Description("issue-draft-24")] IssueDraft24,
        [Description("issue-opened-16 (new)")] IssueOpened16,
        [Description("issue-opened-24 (new)")] IssueOpened24,
        [Description("issue-reopened-16 (regression)")] IssueReopened16,
        [Description("issue-reopened-24 (regression)")] IssueReopened24,
        [Description("issue-tracked-by-16")] IssueTrackedBy16,
        [Description("issue-tracked-by-24")] IssueTrackedBy24,
        [Description("issue-tracks-16")] IssueTracks16,
        [Description("issue-tracks-24")] IssueTracks24,
        [Description("italic-16 (font, italic, style)")] Italic16,
        [Description("italic-24 (font, italic, style)")] Italic24,
        [Description("iterations-16")] Iterations16,
        [Description("iterations-24")] Iterations24,
        [Description("kebab-horizontal-16 (kebab, dot, menu, more)")] KebabHorizontal16,
        [Description("kebab-horizontal-24 (kebab, dot, menu, more)")] KebabHorizontal24,
        [Description("key-16 (key, lock, secure, safe)")] Key16,
        [Description("key-24 (key, lock, secure, safe)")] Key24,
        [Description("key-asterisk-16")] KeyAsterisk16,
        [Description("law-16 (legal, bill)")] Law16,
        [Description("law-24 (legal, bill)")] Law24,
        [Description("light-bulb-16 (idea)")] LightBulb16,
        [Description("light-bulb-24 (idea)")] LightBulb24,
        [Description("link-16 (connect, hyperlink)")] Link16,
        [Description("link-24 (connect, hyperlink)")] Link24,
        [Description("link-external-16 (out, see, more, go, to)")] LinkExternal16,
        [Description("link-external-24 (out, see, more, go, to)")] LinkExternal24,
        [Description("list-ordered-16 (numbers, tasks, todo, items)")] ListOrdered16,
        [Description("list-ordered-24 (numbers, tasks, todo, items)")] ListOrdered24,
        [Description("list-unordered-16 (bullet, point, tasks, todo, items)")] ListUnordered16,
        [Description("list-unordered-24 (bullet, point, tasks, todo, items)")] ListUnordered24,
        [Description("location-16 (here, marker)")] Location16,
        [Description("location-24 (here, marker)")] Location24,
        [Description("lock-16 (secure, safe, protected)")] Lock16,
        [Description("lock-24 (secure, safe, protected)")] Lock24,
        [Description("log-16")] Log16,
        [Description("log-24")] Log24,
        [Description("logo-gist-16 (brand, github, logo)")] LogoGist16,
        [Description("logo-github-16 (brand, github, logo)")] LogoGithub16,
        [Description("mail-16 (email, unread)")] Mail16,
        [Description("mail-24 (email, unread)")] Mail24,
        [Description("markdown-16 (markup, style)")] Markdown16,
        [Description("mark-github-16 (octocat, brand, github, logo)")] MarkGithub16,
        [Description("megaphone-16 (bullhorn, loud, shout, broadcast)")] Megaphone16,
        [Description("megaphone-24 (bullhorn, loud, shout, broadcast)")] Megaphone24,
        [Description("mention-16 (at, ping)")] Mention16,
        [Description("mention-24 (at, ping)")] Mention24,
        [Description("meter-16")] Meter16,
        [Description("milestone-16 (marker)")] Milestone16,
        [Description("milestone-24 (marker)")] Milestone24,
        [Description("mirror-16 (reflect)")] Mirror16,
        [Description("mirror-24 (reflect)")] Mirror24,
        [Description("moon-16")] Moon16,
        [Description("moon-24")] Moon24,
        [Description("mortar-board-16 (education, learn, teach)")] MortarBoard16,
        [Description("mortar-board-24 (education, learn, teach)")] MortarBoard24,
        [Description("move-to-bottom-16 (terminal, end, down, end)")] MoveToBottom16,
        [Description("move-to-bottom-24 (terminal, end, down, end)")] MoveToBottom24,
        [Description("move-to-end-16 (terminal, right, finish)")] MoveToEnd16,
        [Description("move-to-end-24 (terminal, right, finish)")] MoveToEnd24,
        [Description("move-to-start-16 (terminal, left, beginning)")] MoveToStart16,
        [Description("move-to-start-24 (terminal, left, beginning)")] MoveToStart24,
        [Description("move-to-top-16 (terminal, up, start, beginning)")] MoveToTop16,
        [Description("move-to-top-24 (terminal, up, start, beginning)")] MoveToTop24,
        [Description("multi-select-16")] MultiSelect16,
        [Description("multi-select-24")] MultiSelect24,
        [Description("mute-16 (quiet, sound, audio, turn, off)")] Mute16,
        [Description("mute-24 (quiet, sound, audio, turn, off)")] Mute24,
        [Description("no-entry-16")] NoEntry16,
        [Description("no-entry-24")] NoEntry24,
        [Description("no-entry-fill-12")] NoEntryFill12,
        [Description("north-star-16 (star, snowflake, asterisk)")] NorthStar16,
        [Description("north-star-24 (star, snowflake, asterisk)")] NorthStar24,
        [Description("note-16 (card, paper, ticket)")] Note16,
        [Description("note-24 (card, paper, ticket)")] Note24,
        [Description("number-16")] Number16,
        [Description("number-24")] Number24,
        [Description("organization-16 (people, group, team)")] Organization16,
        [Description("organization-24 (people, group, team)")] Organization24,
        [Description("package-16 (box, ship)")] Package16,
        [Description("package-24 (box, ship)")] Package24,
        [Description("package-dependencies-16")] PackageDependencies16,
        [Description("package-dependencies-24")] PackageDependencies24,
        [Description("package-dependents-16")] PackageDependents16,
        [Description("package-dependents-24")] PackageDependents24,
        [Description("paintbrush-16")] Paintbrush16,
        [Description("paper-airplane-16")] PaperAirplane16,
        [Description("paper-airplane-24")] PaperAirplane24,
        [Description("paperclip-16")] Paperclip16,
        [Description("paperclip-24")] Paperclip24,
        [Description("passkey-fill-16")] PasskeyFill16,
        [Description("passkey-fill-24")] PasskeyFill24,
        [Description("paste-16")] Paste16,
        [Description("paste-24")] Paste24,
        [Description("pencil-16 (edit, change, update, write)")] Pencil16,
        [Description("pencil-24 (edit, change, update, write)")] Pencil24,
        [Description("people-16")] People16,
        [Description("people-24")] People24,
        [Description("person-16 (people, man, woman, human)")] Person16,
        [Description("person-24 (people, man, woman, human)")] Person24,
        [Description("person-add-16")] PersonAdd16,
        [Description("person-add-24")] PersonAdd24,
        [Description("person-fill-16")] PersonFill16,
        [Description("person-fill-24")] PersonFill24,
        [Description("pin-16 (save, star, bookmark)")] Pin16,
        [Description("pin-24 (save, star, bookmark)")] Pin24,
        [Description("pin-slash-16 (unpin, unsave, unstar, unbookmark)")] PinSlash16,
        [Description("pin-slash-24 (unpin, unsave, unstar, unbookmark)")] PinSlash24,
        [Description("pivot-column-16 (pivot, column, table, project, filter)")] PivotColumn16,
        [Description("pivot-column-24 (pivot, column, table, project, filter)")] PivotColumn24,
        [Description("play-16 (play, start, begin, action)")] Play16,
        [Description("play-24 (play, start, begin, action)")] Play24,
        [Description("plug-16 (hook, webhook)")] Plug16,
        [Description("plug-24 (hook, webhook)")] Plug24,
        [Description("plus-16 (add, new, more)")] Plus16,
        [Description("plus-24 (add, new, more)")] Plus24,
        [Description("plus-circle-16")] PlusCircle16,
        [Description("plus-circle-24")] PlusCircle24,
        [Description("project-16 (board, kanban, columns, scrum)")] Project16,
        [Description("project-24 (board, kanban, columns, scrum)")] Project24,
        [Description("project-roadmap-16")] ProjectRoadmap16,
        [Description("project-roadmap-24")] ProjectRoadmap24,
        [Description("project-symlink-16")] ProjectSymlink16,
        [Description("project-symlink-24")] ProjectSymlink24,
        [Description("project-template-16")] ProjectTemplate16,
        [Description("project-template-24")] ProjectTemplate24,
        [Description("pulse-16 (graph, trend, line, activity)")] Pulse16,
        [Description("pulse-24 (graph, trend, line, activity)")] Pulse24,
        [Description("question-16 (help, explain)")] Question16,
        [Description("question-24 (help, explain)")] Question24,
        [Description("quote-16 (quotation)")] Quote16,
        [Description("quote-24 (quotation)")] Quote24,
        [Description("read-16")] Read16,
        [Description("read-24")] Read24,
        [Description("redo-16")] Redo16,
        [Description("rel-file-path-16")] RelFilePath16,
        [Description("rel-file-path-24")] RelFilePath24,
        [Description("reply-16 (reply all, back)")] Reply16,
        [Description("reply-24 (reply all, back)")] Reply24,
        [Description("repo-16 (book, journal, repository)")] Repo16,
        [Description("repo-24 (book, journal, repository)")] Repo24,
        [Description("repo-clone-16 (book, journal, repository)")] RepoClone16,
        [Description("repo-clone-24 (book, journal, repository)")] RepoClone24,
        [Description("repo-deleted-16")] RepoDeleted16,
        [Description("repo-forked-16 (book, journal, copy)")] RepoForked16,
        [Description("repo-forked-24 (book, journal, copy)")] RepoForked24,
        [Description("repo-locked-16")] RepoLocked16,
        [Description("repo-locked-24")] RepoLocked24,
        [Description("repo-pull-16 (book, journal, get)")] RepoPull16,
        [Description("repo-pull-24 (book, journal, get)")] RepoPull24,
        [Description("repo-push-16 (book, journal, repository, put)")] RepoPush16,
        [Description("repo-push-24 (book, journal, repository, put)")] RepoPush24,
        [Description("report-16 (report, abuse, flag)")] Report16,
        [Description("report-24 (report, abuse, flag)")] Report24,
        [Description("repo-template-16 (book, new, add, template)")] RepoTemplate16,
        [Description("repo-template-24 (book, new, add, template)")] RepoTemplate24,
        [Description("rocket-16 (staff, stafftools, blast, off, space, launch, ship)")] Rocket16,
        [Description("rocket-24 (staff, stafftools, blast, off, space, launch, ship)")] Rocket24,
        [Description("rows-16")] Rows16,
        [Description("rows-24")] Rows24,
        [Description("rss-16 (broadcast, feed, atom)")] Rss16,
        [Description("rss-24 (broadcast, feed, atom)")] Rss24,
        [Description("ruby-16 (code, language)")] Ruby16,
        [Description("ruby-24 (code, language)")] Ruby24,
        [Description("screen-full-16 (fullscreen, expand)")] ScreenFull16,
        [Description("screen-full-24 (fullscreen, expand)")] ScreenFull24,
        [Description("screen-normal-16 (fullscreen, expand, exit)")] ScreenNormal16,
        [Description("screen-normal-24 (fullscreen, expand, exit)")] ScreenNormal24,
        [Description("search-16 (magnifying, glass)")] Search16,
        [Description("search-24 (magnifying, glass)")] Search24,
        [Description("server-16 (computers, racks, ops)")] Server16,
        [Description("server-24 (computers, racks, ops)")] Server24,
        [Description("share-16")] Share16,
        [Description("share-24")] Share24,
        [Description("share-android-16")] ShareAndroid16,
        [Description("share-android-24")] ShareAndroid24,
        [Description("shield-16 (security, shield, protection)")] Shield16,
        [Description("shield-24 (security, shield, protection)")] Shield24,
        [Description("shield-check-16 (security, shield, protection, check, success)")] ShieldCheck16,
        [Description("shield-check-24 (security, shield, protection, check, success)")] ShieldCheck24,
        [Description("shield-lock-16 (protect, shield, lock)")] ShieldLock16,
        [Description("shield-lock-24 (protect, shield, lock)")] ShieldLock24,
        [Description("shield-slash-16 (shield, slash, protect, unsafe, unprotected, security)")] ShieldSlash16,
        [Description("shield-slash-24 (shield, slash, protect, unsafe, unprotected, security)")] ShieldSlash24,
        [Description("shield-x-16 (security, shield, protection, fail)")] ShieldX16,
        [Description("shield-x-24 (security, shield, protection, fail)")] ShieldX24,
        [Description("sidebar-collapse-16")] SidebarCollapse16,
        [Description("sidebar-collapse-24")] SidebarCollapse24,
        [Description("sidebar-expand-16")] SidebarExpand16,
        [Description("sidebar-expand-24")] SidebarExpand24,
        [Description("sign-in-16 (door, arrow, direction, enter, log in)")] SignIn16,
        [Description("sign-in-24 (door, arrow, direction, enter, log in)")] SignIn24,
        [Description("sign-out-16 (door, arrow, direction, leave, log out)")] SignOut16,
        [Description("sign-out-24 (door, arrow, direction, leave, log out)")] SignOut24,
        [Description("single-select-16")] SingleSelect16,
        [Description("single-select-24")] SingleSelect24,
        [Description("skip-16 (skip, slash)")] Skip16,
        [Description("skip-24 (skip, slash)")] Skip24,
        [Description("skip-fill-16")] SkipFill16,
        [Description("skip-fill-24")] SkipFill24,
        [Description("sliders-16")] Sliders16,
        [Description("smiley-16 (emoji, smile, mood, emotion)")] Smiley16,
        [Description("smiley-24 (emoji, smile, mood, emotion)")] Smiley24,
        [Description("sort-asc-16")] SortAsc16,
        [Description("sort-asc-24")] SortAsc24,
        [Description("sort-desc-16")] SortDesc16,
        [Description("sort-desc-24")] SortDesc24,
        [Description("sparkle-fill-16")] SparkleFill16,
        [Description("sponsor-tiers-16")] SponsorTiers16,
        [Description("sponsor-tiers-24")] SponsorTiers24,
        [Description("square-16")] Square16,
        [Description("square-24")] Square24,
        [Description("square-fill-16")] SquareFill16,
        [Description("square-fill-24")] SquareFill24,
        [Description("squirrel-16 (ship, shipit, launch)")] Squirrel16,
        [Description("squirrel-24 (ship, shipit, launch)")] Squirrel24,
        [Description("stack-16")] Stack16,
        [Description("stack-24")] Stack24,
        [Description("star-16 (save, remember, like)")] Star16,
        [Description("star-24 (save, remember, like)")] Star24,
        [Description("star-fill-16")] StarFill16,
        [Description("star-fill-24")] StarFill24,
        [Description("stop-16 (block, spam, report)")] Stop16,
        [Description("stop-24 (block, spam, report)")] Stop24,
        [Description("stopwatch-16")] Stopwatch16,
        [Description("stopwatch-24")] Stopwatch24,
        [Description("strikethrough-16")] Strikethrough16,
        [Description("strikethrough-24")] Strikethrough24,
        [Description("sun-16")] Sun16,
        [Description("sun-24")] Sun24,
        [Description("sync-16 (cycle, refresh, loop)")] Sync16,
        [Description("sync-24 (cycle, refresh, loop)")] Sync24,
        [Description("tab-24")] Tab24,
        [Description("tab-external-16")] TabExternal16,
        [Description("table-16")] Table16,
        [Description("table-24")] Table24,
        [Description("tag-16 (release)")] Tag16,
        [Description("tag-24 (release)")] Tag24,
        [Description("tasklist-16 (todo)")] Tasklist16,
        [Description("tasklist-24 (todo)")] Tasklist24,
        [Description("telescope-16 (science, space, look, view, explore)")] Telescope16,
        [Description("telescope-24 (science, space, look, view, explore)")] Telescope24,
        [Description("telescope-fill-16")] TelescopeFill16,
        [Description("telescope-fill-24")] TelescopeFill24,
        [Description("terminal-16 (code, ops, shell)")] Terminal16,
        [Description("terminal-24 (code, ops, shell)")] Terminal24,
        [Description("three-bars-16 (hamburger, menu, dropdown)")] ThreeBars16,
        [Description("thumbsdown-16 (thumb, thumbsdown, rejected, dislike)")] Thumbsdown16,
        [Description("thumbsdown-24 (thumb, thumbsdown, rejected, dislike)")] Thumbsdown24,
        [Description("thumbsup-16 (thumb, thumbsup, prop, ship, like)")] Thumbsup16,
        [Description("thumbsup-24 (thumb, thumbsup, prop, ship, like)")] Thumbsup24,
        [Description("tools-16 (screwdriver, wrench, settings)")] Tools16,
        [Description("tools-24 (screwdriver, wrench, settings)")] Tools24,
        [Description("tracked-by-closed-completed-16")] TrackedByClosedCompleted16,
        [Description("tracked-by-closed-completed-24")] TrackedByClosedCompleted24,
        [Description("tracked-by-closed-not-planned-16")] TrackedByClosedNotPlanned16,
        [Description("tracked-by-closed-not-planned-24")] TrackedByClosedNotPlanned24,
        [Description("trash-16")] Trash16,
        [Description("trash-24")] Trash24,
        [Description("triangle-down-16 (arrow, point, direction)")] TriangleDown16,
        [Description("triangle-down-24 (arrow, point, direction)")] TriangleDown24,
        [Description("triangle-left-16 (arrow, point, direction)")] TriangleLeft16,
        [Description("triangle-left-24 (arrow, point, direction)")] TriangleLeft24,
        [Description("triangle-right-16 (arrow, point, direction)")] TriangleRight16,
        [Description("triangle-right-24 (arrow, point, direction)")] TriangleRight24,
        [Description("triangle-up-16 (arrow, point, direction)")] TriangleUp16,
        [Description("triangle-up-24 (arrow, point, direction)")] TriangleUp24,
        [Description("trophy-16")] Trophy16,
        [Description("trophy-24")] Trophy24,
        [Description("typography-16")] Typography16,
        [Description("typography-24")] Typography24,
        [Description("undo-16")] Undo16,
        [Description("unfold-16 (expand, open, reveal)")] Unfold16,
        [Description("unfold-24 (expand, open, reveal)")] Unfold24,
        [Description("unlink-16")] Unlink16,
        [Description("unlink-24")] Unlink24,
        [Description("unlock-16")] Unlock16,
        [Description("unlock-24")] Unlock24,
        [Description("unmute-16 (loud, volume, audio, sound, play)")] Unmute16,
        [Description("unmute-24 (loud, volume, audio, sound, play)")] Unmute24,
        [Description("unread-16")] Unread16,
        [Description("unread-24")] Unread24,
        [Description("unverified-16 (insecure, untrusted, signed)")] Unverified16,
        [Description("unverified-24 (insecure, untrusted, signed)")] Unverified24,
        [Description("upload-16")] Upload16,
        [Description("upload-24")] Upload24,
        [Description("verified-16 (trusted, secure, trustworthy, signed)")] Verified16,
        [Description("verified-24 (trusted, secure, trustworthy, signed)")] Verified24,
        [Description("versions-16 (history, commits)")] Versions16,
        [Description("versions-24 (history, commits)")] Versions24,
        [Description("video-16")] Video16,
        [Description("video-24")] Video24,
        [Description("webhook-16")] Webhook16,
        [Description("workflow-16 (workflow, actions)")] Workflow16,
        [Description("workflow-24 (workflow, actions)")] Workflow24,
        [Description("x-12 (remove, close, delete)")] X12,
        [Description("x-16 (remove, close, delete)")] X16,
        [Description("x-24 (remove, close, delete)")] X24,
        [Description("x-circle-16")] XCircle16,
        [Description("x-circle-24")] XCircle24,
        [Description("x-circle-fill-12")] XCircleFill12,
        [Description("x-circle-fill-16")] XCircleFill16,
        [Description("x-circle-fill-24")] XCircleFill24,
        [Description("zap-16 (electricity, lightning, props, like, star, save)")] Zap16,
        [Description("zap-24 (electricity, lightning, props, like, star, save)")] Zap24,
        [Description("zoom-in-16 (zoom, in, plus, bigger)")] ZoomIn16,
        [Description("zoom-in-24 (zoom, in, plus, bigger)")] ZoomIn24,
        [Description("zoom-out-16 (zoom, out, minus, smaller)")] ZoomOut16,
        [Description("zoom-out-24 (zoom, out, minus, smaller)")] ZoomOut24
    }
}