namespace MahApps.Metro.IconPacks
{
#if !(NETFX_CORE || WINDOWS_UWP)
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconFontaudio" />.
    /// </summary>
    /// <remarks>
    /// Fontaudio by @fefanto <see><cref>https://github.com/fefanto</cref></see>. License: Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License. <see><cref>https://github.com/fefanto/fontaudio#license</cref></see>
    /// Contributions, corrections and requests can be made on GitHub <see><cref>https://github.com/fefanto/fontaudio</cref></see>.
    /// </remarks>
    public enum PackIconFontaudioKind
    {
        [Description("Empty placeholder")] None,
        [Description("fad-ADR (F101)")] Adr,
        [Description("fad-ADSR (F102)")] Adsr,
        [Description("fad-AHDSR (F103)")] Ahdsr,
        [Description("fad-AR (F104)")] Ar,
        [Description("fad-armrecording (F105)")] Armrecording,
        [Description("fad-arpchord (F106)")] Arpchord,
        [Description("fad-arpdown (F107)")] Arpdown,
        [Description("fad-arpdownandup (F108)")] Arpdownandup,
        [Description("fad-arpdownup (F109)")] Arpdownup,
        [Description("fad-arpplayorder (F10A)")] Arpplayorder,
        [Description("fad-arprandom (F10B)")] Arprandom,
        [Description("fad-arpup (F10C)")] Arpup,
        [Description("fad-arpupandown (F10D)")] Arpupandown,
        [Description("fad-arpupdown (F10E)")] Arpupdown,
        [Description("fad-arrows-horz (F10F)")] ArrowsHorz,
        [Description("fad-arrows-vert (F110)")] ArrowsVert,
        [Description("fad-automation-2p (F111)")] Automation2p,
        [Description("fad-automation-3p (F112)")] Automation3p,
        [Description("fad-automation-4p (F113)")] Automation4p,
        [Description("fad-backward (F114)")] Backward,
        [Description("fad-bluetooth (F115)")] Bluetooth,
        [Description("fad-caret-down (F116)")] CaretDown,
        [Description("fad-caret-left (F117)")] CaretLeft,
        [Description("fad-caret-right (F118)")] CaretRight,
        [Description("fad-caret-up (F119)")] CaretUp,
        [Description("fad-close (F11A)")] Close,
        [Description("fad-copy (F11B)")] Copy,
        [Description("fad-cpu (F11C)")] Cpu,
        [Description("fad-cutter (F11D)")] Cutter,
        [Description("fad-digital0 (F120)")] Digital0,
        [Description("fad-digital1 (F121)")] Digital1,
        [Description("fad-digital2 (F122)")] Digital2,
        [Description("fad-digital3 (F123)")] Digital3,
        [Description("fad-digital4 (F124)")] Digital4,
        [Description("fad-digital5 (F125)")] Digital5,
        [Description("fad-digital6 (F126)")] Digital6,
        [Description("fad-digital7 (F127)")] Digital7,
        [Description("fad-digital8 (F128)")] Digital8,
        [Description("fad-digital9 (F129)")] Digital9,
        [Description("fad-digital-colon (F11E)")] DigitalColon,
        [Description("fad-digital-dot (F11F)")] DigitalDot,
        [Description("fad-diskio (F12A)")] Diskio,
        [Description("fad-drumpad (F12B)")] Drumpad,
        [Description("fad-duplicate (F12C)")] Duplicate,
        [Description("fad-eraser (F12D)")] Eraser,
        [Description("fad-ffwd (F12E)")] Ffwd,
        [Description("fad-filter-bandpass (F12F)")] FilterBandpass,
        [Description("fad-filter-bell (F130)")] FilterBell,
        [Description("fad-filter-bypass (F131)")] FilterBypass,
        [Description("fad-filter-highpass (F132)")] FilterHighpass,
        [Description("fad-filter-lowpass (F133)")] FilterLowpass,
        [Description("fad-filter-notch (F134)")] FilterNotch,
        [Description("fad-filter-rez-highpass (F135)")] FilterRezHighpass,
        [Description("fad-filter-rez-lowpass (F136)")] FilterRezLowpass,
        [Description("fad-filter-shelving-hi (F137)")] FilterShelvingHi,
        [Description("fad-filter-shelving-lo (F138)")] FilterShelvingLo,
        [Description("fad-foldback (F139)")] Foldback,
        [Description("fad-forward (F13A)")] Forward,
        [Description("fad-hardclip (F13C)")] Hardclip,
        [Description("fad-hardclipcurve (F13D)")] Hardclipcurve,
        [Description("fad-headphones (F13E)")] Headphones,
        [Description("fad-h-expand (F13B)")] HExpand,
        [Description("fad-keyboard (F13F)")] Keyboard,
        [Description("fad-lock (F140)")] Lock,
        [Description("fad-logo-aax (F141)")] LogoAax,
        [Description("fad-logo-abletonlink (F142)")] LogoAbletonlink,
        [Description("fad-logo-au (F143)")] LogoAu,
        [Description("fad-logo-audacity (F144)")] LogoAudacity,
        [Description("fad-logo-audiobus (F145)")] LogoAudiobus,
        [Description("fad-logo-cubase (F146)")] LogoCubase,
        [Description("fad-logo-fl (F147)")] LogoFl,
        [Description("fad-logo-juce (F148)")] LogoJuce,
        [Description("fad-logo-ladspa (F149)")] LogoLadspa,
        [Description("fad-logo-live (F14A)")] LogoLive,
        [Description("fad-logo-lv2 (F14B)")] LogoLv2,
        [Description("fad-logo-protools (F14C)")] LogoProtools,
        [Description("fad-logo-rackext (F14D)")] LogoRackext,
        [Description("fad-logo-reaper (F14E)")] LogoReaper,
        [Description("fad-logo-reason (F14F)")] LogoReason,
        [Description("fad-logo-rewire (F150)")] LogoRewire,
        [Description("fad-logo-studioone (F151)")] LogoStudioone,
        [Description("fad-logo-tracktion (F152)")] LogoTracktion,
        [Description("fad-logo-vst (F153)")] LogoVst,
        [Description("fad-logo-waveform (F154)")] LogoWaveform,
        [Description("fad-loop (F155)")] Loop,
        [Description("fad-metronome (F156)")] Metronome,
        [Description("fad-microphone (F157)")] Microphone,
        [Description("fad-midiplug (F158)")] Midiplug,
        [Description("fad-modrandom (F159)")] Modrandom,
        [Description("fad-modsawdown (F15A)")] Modsawdown,
        [Description("fad-modsawup (F15B)")] Modsawup,
        [Description("fad-modsh (F15C)")] Modsh,
        [Description("fad-modsine (F15D)")] Modsine,
        [Description("fad-modsquare (F15E)")] Modsquare,
        [Description("fad-modtri (F15F)")] Modtri,
        [Description("fad-modularplug (F160)")] Modularplug,
        [Description("fad-mono (F161)")] Mono,
        [Description("fad-mute (F162)")] Mute,
        [Description("fad-next (F163)")] Next,
        [Description("fad-open (F164)")] Open,
        [Description("fad-paste (F165)")] Paste,
        [Description("fad-pause (F166)")] Pause,
        [Description("fad-pen (F167)")] Pen,
        [Description("fad-phase (F168)")] Phase,
        [Description("fad-play (F169)")] Play,
        [Description("fad-pointer (F16A)")] Pointer,
        [Description("fad-powerswitch (F16B)")] Powerswitch,
        [Description("fad-preset-a (F16C)")] PresetA,
        [Description("fad-preset-ab (F16D)")] PresetAb,
        [Description("fad-preset-b (F16E)")] PresetB,
        [Description("fad-preset-ba (F16F)")] PresetBa,
        [Description("fad-prev (F170)")] Prev,
        [Description("fad-punch-in (F171)")] PunchIn,
        [Description("fad-punch-out (F172)")] PunchOut,
        [Description("fad-ram (F173)")] Ram,
        [Description("fad-random-1dice (F174)")] Random1dice,
        [Description("fad-random-2dice (F175)")] Random2dice,
        [Description("fad-record (F176)")] Record,
        [Description("fad-redo (F177)")] Redo,
        [Description("fad-repeat (F179)")] Repeat,
        [Description("fad-repeat-one (F178)")] RepeatOne,
        [Description("fad-rew (F17A)")] Rew,
        [Description("fad-roundswitch-off (F17B)")] RoundswitchOff,
        [Description("fad-roundswitch-on (F17C)")] RoundswitchOn,
        [Description("fad-save (F17D)")] Save,
        [Description("fad-saveas (F17E)")] Saveas,
        [Description("fad-scissors (F17F)")] Scissors,
        [Description("fad-shuffle (F180)")] Shuffle,
        [Description("fad-sliderhandle-1 (F184)")] Sliderhandle1,
        [Description("fad-sliderhandle-2 (F185)")] Sliderhandle2,
        [Description("fad-slider-round-1 (F181)")] SliderRound1,
        [Description("fad-slider-round-2 (F182)")] SliderRound2,
        [Description("fad-slider-round-3 (F183)")] SliderRound3,
        [Description("fad-softclip (F186)")] Softclip,
        [Description("fad-softclipcurve (F187)")] Softclipcurve,
        [Description("fad-solo (F188)")] Solo,
        [Description("fad-speaker (F189)")] Speaker,
        [Description("fad-squareswitch-off (F18A)")] SquareswitchOff,
        [Description("fad-squareswitch-on (F18B)")] SquareswitchOn,
        [Description("fad-stereo (F18C)")] Stereo,
        [Description("fad-stop (F18D)")] Stop,
        [Description("fad-thunderbolt (F18E)")] Thunderbolt,
        [Description("fad-timeselect (F18F)")] Timeselect,
        [Description("fad-undo (F190)")] Undo,
        [Description("fad-unlock (F191)")] Unlock,
        [Description("fad-usb (F192)")] Usb,
        [Description("fad-v-expand (F193)")] VExpand,
        [Description("fad-vroundswitch-off (F194)")] VroundswitchOff,
        [Description("fad-vroundswitch-on (F195)")] VroundswitchOn,
        [Description("fad-vsquareswitch-off (F196)")] VsquareswitchOff,
        [Description("fad-vsquareswitch-on (F197)")] VsquareswitchOn,
        [Description("fad-waveform (F198)")] Waveform,
        [Description("fad-xlrplug (F199)")] Xlrplug,
        [Description("fad-zoomin (F19A)")] Zoomin,
        [Description("fad-zoomout (F19B)")] Zoomout
    }
}