//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahApps.Metro.IconPacks.Browser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccentColorNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccentColorNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MahApps.Metro.IconPacks.Browser.Properties.AccentColorNames", typeof(AccentColorNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobalt.
        /// </summary>
        internal static string _FF0050EF {
            get {
                return ResourceManager.GetString("#FF0050EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string _FF0078D7 {
            get {
                return ResourceManager.GetString("#FF0078D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerald.
        /// </summary>
        internal static string _FF008A00 {
            get {
                return ResourceManager.GetString("#FF008A00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        internal static string _FF00ABA9 {
            get {
                return ResourceManager.GetString("#FF00ABA9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        internal static string _FF1BA1E2 {
            get {
                return ResourceManager.GetString("#FF1BA1E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string _FF60A917 {
            get {
                return ResourceManager.GetString("#FF60A917", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string _FF6459DF {
            get {
                return ResourceManager.GetString("#FF6459DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        internal static string _FF647687 {
            get {
                return ResourceManager.GetString("#FF647687", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        internal static string _FF6A00FF {
            get {
                return ResourceManager.GetString("#FF6A00FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive.
        /// </summary>
        internal static string _FF6D8764 {
            get {
                return ResourceManager.GetString("#FF6D8764", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauve.
        /// </summary>
        internal static string _FF76608A {
            get {
                return ResourceManager.GetString("#FF76608A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string _FF825A2C {
            get {
                return ResourceManager.GetString("#FF825A2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taupe.
        /// </summary>
        internal static string _FF87794E {
            get {
                return ResourceManager.GetString("#FF87794E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sienna.
        /// </summary>
        internal static string _FFA0522D {
            get {
                return ResourceManager.GetString("#FFA0522D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crimson.
        /// </summary>
        internal static string _FFA20025 {
            get {
                return ResourceManager.GetString("#FFA20025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime.
        /// </summary>
        internal static string _FFA4C400 {
            get {
                return ResourceManager.GetString("#FFA4C400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        internal static string _FFAA00FF {
            get {
                return ResourceManager.GetString("#FFAA00FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        internal static string _FFD80073 {
            get {
                return ResourceManager.GetString("#FFD80073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string _FFE51400 {
            get {
                return ResourceManager.GetString("#FFE51400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber.
        /// </summary>
        internal static string _FFF0A30A {
            get {
                return ResourceManager.GetString("#FFF0A30A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string _FFF472D0 {
            get {
                return ResourceManager.GetString("#FFF472D0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string _FFFA6800 {
            get {
                return ResourceManager.GetString("#FFFA6800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string _FFFEDE06 {
            get {
                return ResourceManager.GetString("#FFFEDE06", resourceCulture);
            }
        }
    }
}
