namespace MahApps.Metro.IconPacks
{
#if !(NETFX_CORE || WINDOWS_UWP)
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconSimpleIcons" />.
    /// </summary>
    /// <remarks>
    /// All SVG icons for popular brands, maintained by Dan Leech <see><cref>https://twitter.com/bathtype</cref></see>.
    /// Contributions, corrections and requests can be made on GitHub <see><cref>https://github.com/danleech/simple-icons</cref></see>.
    /// </remarks>
    public enum PackIconSimpleIconsKind
    {
        [Description("Empty placeholder")] None,
        [Description("1001Tracklists, https://www.1001tracklists.com/")] _1001Tracklists,
        [Description("1Password, https://1password.com/press/")] _1Password,
        [Description("500px, https://about.500px.com/press")] _500px,
        [Description("ABB RobotStudio, https://new.abb.com/products/robotics/en/robotstudio/downloads")] AbbRobotStudio,
        [Description("About.me, https://about.me/assets")] AboutMe,
        [Description("Abstract, https://www.abstract.com/about/")] Abstract,
        [Description("Academia, https://www.academia.edu/")] Academia,
        [Description("Accusoft, https://company-39138.frontify.com/d/7EKFm12NQSa8/accusoft-corporation-style-guide#/style-guide/logo")] Accusoft,
        [Description("ACM, http://identitystandards.acm.org/")] Acm,
        [Description("ActiGraph, http://www.actigraphcorp.com/")] ActiGraph,
        [Description("Activision, https://www.activision.com/")] Activision,
        [Description("AddThis, http://www.addthis.com/")] AddThis,
        [Description("AdGuard, https://adguard.com/en/contribute.html")] AdGuard,
        [Description("Adobe, https://www.adobe.com/")] Adobe,
        [Description("Adobe Acrobat Reader, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobeAcrobatReader,
        [Description("Adobe After Effects, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobeAfterEffects,
        [Description("Adobe Audition, https://helpx.adobe.com/content/dam/help/mnemonics/au_cc_app_RGB.svg")] AdobeAudition,
        [Description("Adobe Creative Cloud, https://www.adobe.io/apis/creativecloud/creativesdk/docs/websdk/adobe-creative-sdk-for-web_master/branding-guidelines.html")] AdobeCreativeCloud,
        [Description("Adobe Dreamweaver, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobeDreamweaver,
        [Description("Adobe Illustrator, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobeIllustrator,
        [Description("Adobe InDesign, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobeInDesign,
        [Description("Adobe Lightroom CC, https://www.adobe.com/products/photoshop-lightroom.html")] AdobeLightroomCc,
        [Description("Adobe Lightroom Classic, https://www.adobe.com/products/photoshop-lightroom-classic.html")] AdobeLightroomClassic,
        [Description("Adobe PhoneGap, https://phonegap.com/about/logos/")] AdobePhoneGap,
        [Description("Adobe Photoshop, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobePhotoshop,
        [Description("Adobe Premiere, https://helpx.adobe.com/content/dam/help/mnemonics/pr_cc_app_RGB.svg")] AdobePremiere,
        [Description("Adobe Typekit, https://helpx.adobe.com/content/dam/help/mnemonics/tk_appicon_RGB.svg")] AdobeTypekit,
        [Description("Adobe XD, https://www.adobe.com/products/xd.html")] AdobeXd,
        [Description("AdonisJS, https://adonisjs.com/")] AdonisJs,
        [Description("Aer Lingus, https://www.aerlingus.com/")] AerLingus,
        [Description("Affinity, https://affinity.serif.com/")] Affinity,
        [Description("Affinity Designer, https://affinity.serif.com/en-gb/designer/")] AffinityDesigner,
        [Description("Affinity Photo, https://affinity.serif.com/en-gb/photo/")] AffinityPhoto,
        [Description("Affinity Publisher, https://affinity.serif.com/en-gb/publisher/")] AffinityPublisher,
        [Description("Aiqfome, https://aiqfome.com")] Aiqfome,
        [Description("Airbnb, https://www.airbnb.com")] Airbnb,
        [Description("Airbus, https://brand.airbus.com/brand-elements/logo.html")] Airbus,
        [Description("Aircall, https://aircall.io/")] Aircall,
        [Description("AirPlay Audio, https://developer.apple.com/design/human-interface-guidelines/airplay/overview/icons/")] AirPlayAudio,
        [Description("AirPlay Video, https://developer.apple.com/design/human-interface-guidelines/airplay/overview/icons/")] AirPlayVideo,
        [Description("Airtable, https://airtable.com/press")] Airtable,
        [Description("Algolia, https://www.algolia.com/press/?section=brand-guidelines")] Algolia,
        [Description("Alipay, https://gw.alipayobjects.com/os/rmsportal/trUJZfSrlnRCcFgfZGjD.ai")] Alipay,
        [Description("AlliedModders, https://forums.alliedmods.net/index.php")] AlliedModders,
        [Description("AlloCiné, http://www.allocine.fr/favicon.ico")] AlloCiné,
        [Description("Alpine Linux, https://alpinelinux.org/")] AlpineLinux,
        [Description("Amazon, https://worldvectorlogo.com/logo/amazon-icon")] Amazon,
        [Description("Amazon Alexa, https://developer.amazon.com/docs/alexa-voice-service/logo-and-brand.html")] AmazonAlexa,
        [Description("Amazon AWS, https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg")] AmazonAws,
        [Description("Amazon Lumberyard, https://github.com/aws/lumberyard")] AmazonLumberyard,
        [Description("AMD, https://subscriptions.amd.com/greatpower/img/amd-logo-black.svg")] Amd,
        [Description("American Express, https://commons.wikimedia.org/wiki/File:American_Express_logo.svg")] AmericanExpress,
        [Description("Anaconda, https://www.anaconda.com/media-kit/")] Anaconda,
        [Description("Analogue, https://www.analogue.co/")] Analogue,
        [Description("Anchor, https://anchor.fm/")] Anchor,
        [Description("Andela, https://andela.com/press/")] Andela,
        [Description("Android, https://developer.android.com/distribute/marketing-tools/brand-guidelines")] Android,
        [Description("Android Studio, https://en.wikipedia.org/wiki/Android_Studio")] AndroidStudio,
        [Description("AngelList, https://angel.co/logo")] AngelList,
        [Description("Angular, https://angular.io/assets/images/logos/angular/angular_solidBlack.svg")] Angular,
        [Description("AngularJS, https://angularjs.org/")] AngularJs,
        [Description("Angular Universal, https://angular.io/presskit")] AngularUniversal,
        [Description("Ansible, https://www.ansible.com/logos")] Ansible,
        [Description("Antena 3, https://www.antena3.com/")] Antena3,
        [Description("Apache, https://www.apache.org/foundation/press/kit/")] Apache,
        [Description("Apache Airflow, https://github.com/apache/airflow/tree/master/docs/img/logos")] ApacheAirflow,
        [Description("Apache Ant, https://commons.wikimedia.org/wiki/File:Apache-Ant-logo.svg")] ApacheAnt,
        [Description("Apache Cordova, https://cordova.apache.org/artwork/")] ApacheCordova,
        [Description("Apache ECharts, https://echarts.apache.org/")] ApacheECharts,
        [Description("Apache Flink, https://flink.apache.org/material.html")] ApacheFlink,
        [Description("Apache Kafka, https://commons.wikimedia.org/wiki/File:Apache_kafka.svg")] ApacheKafka,
        [Description("Apache Maven, https://en.wikipedia.org/wiki/Apache_Maven")] ApacheMaven,
        [Description("Apache NetBeans IDE, https://netbeans.apache.org/images/")] ApacheNetBeansIde,
        [Description("Apache OpenOffice, https://www.openoffice.org/marketing/art/galleries/logos/index.html")] ApacheOpenOffice,
        [Description("Apache Pulsar, https://pulsar.apache.org/")] ApachePulsar,
        [Description("Apache RocketMQ, https://rocketmq.apache.org/")] ApacheRocketMq,
        [Description("Apache Solr, https://lucene.apache.org/solr/")] ApacheSolr,
        [Description("Apache Spark, https://spark.apache.org/images/")] ApacheSpark,
        [Description("Apollo GraphQL, https://github.com/apollographql/space-kit/blob/9a42083746a49c9a734563f427c13233e42adcc9/logos/mark.svg")] ApolloGraphQl,
        [Description("Apple, https://worldvectorlogo.com/logo/apple")] Apple,
        [Description("Apple Music, https://www.apple.com/itunes/marketing-on-music/identity-guidelines.html#apple-music-icon")] AppleMusic,
        [Description("Apple Pay, https://developer.apple.com/apple-pay/marketing/")] ApplePay,
        [Description("Apple Podcasts, https://www.apple.com/itunes/marketing-on-podcasts/identity-guidelines.html#apple-podcasts-icon")] ApplePodcasts,
        [Description("AppVeyor, https://commons.wikimedia.org/wiki/File:Appveyor_logo.svg")] AppVeyor,
        [Description("ARAL, https://upload.wikimedia.org/wikipedia/commons/6/60/Aral_Logo.svg")] Aral,
        [Description("ARCHICAD, https://www.graphisoft.com/archicad/")] Archicad,
        [Description("Archive of Our Own, https://archiveofourown.org/")] ArchiveOfOurOwn,
        [Description("Arch Linux, https://www.archlinux.org/art/")] ArchLinux,
        [Description("Arduino, https://cdn.arduino.cc/projecthub/img/Arduino-logo.svg")] Arduino,
        [Description("ArtStation, https://www.artstation.com/about/logo")] ArtStation,
        [Description("arXiv, https://static.arxiv.org/static/base/0.15.2/images/arxiv-logo-web.svg")] ArXiv,
        [Description("Asana, https://asana.com/styles")] Asana,
        [Description("Asciidoctor, https://github.com/asciidoctor/brand")] Asciidoctor,
        [Description("asciinema, https://github.com/asciinema/asciinema-logo")] Asciinema,
        [Description("AT&T, https://commons.wikimedia.org/wiki/File:AT%26T_logo_2016.svg")] AtAndT,
        [Description("Atlassian, https://atlassian.design/guidelines/brand/logos-1")] Atlassian,
        [Description("Atom, https://commons.wikimedia.org/wiki/File:Atom_editor_logo.svg")] Atom,
        [Description("Audi, https://www.audi.com/ci/en/intro/basics/rings.html")] Audi,
        [Description("Audible, https://commons.wikimedia.org/wiki/File:Audible_logo.svg")] Audible,
        [Description("Audiomack, https://styleguide.audiomack.com/")] Audiomack,
        [Description("Aurelia, https://aurelia.io/")] Aurelia,
        [Description("Auth0, https://styleguide.auth0.com")] Auth0,
        [Description("Authy, https://authy.com/")] Authy,
        [Description("Automatic, https://www.automatic.com/press")] Automatic,
        [Description("Autotask, https://www.autotask.com/branding")] Autotask,
        [Description("Aventrix, https://www.aventrix.com/press")] Aventrix,
        [Description("awesomeWM, https://awesomewm.org/")] AwesomeWm,
        [Description("Azure Artifacts, https://azure.microsoft.com/en-us/services/devops/artifacts/")] AzureArtifacts,
        [Description("Azure DevOps, http://azure.com/devops")] AzureDevOps,
        [Description("Azure Pipelines, https://github.com/vscode-icons/vscode-icons/pull/1741")] AzurePipelines,
        [Description("Babel, https://github.com/babel/website/blob/93330158b6ecca1ab88d3be8dbf661f5c2da6c76/website/static/img/babel-black.svg")] Babel,
        [Description("Baidu, https://en.wikipedia.org/wiki/File:Baidu.svg")] Baidu,
        [Description("Bamboo, https://www.atlassian.design/guidelines/marketing/resources/logo-files")] Bamboo,
        [Description("Bancontact, https://www.bancontact.com/en/promotion-material/guidelines-logo")] Bancontact,
        [Description("Bandcamp, https://bandcamp.com/buttons")] Bandcamp,
        [Description("BandLab, https://blog.bandlab.com/press/")] BandLab,
        [Description("Bandsintown, https://corp.bandsintown.com/media-library")] Bandsintown,
        [Description("Basecamp, https://basecamp.com/about/press")] Basecamp,
        [Description("Bath ASU, https://bathasu.com/press/")] BathAsu,
        [Description("Battle.net, https://www.blizzard.com/en-gb/")] BattleNet,
        [Description("Beatport, https://support.beatport.com/hc/en-us/articles/200353255-Beatport-Logos-and-Images")] Beatport,
        [Description("Beats, https://www.elastic.co/brand")] Beats,
        [Description("Beats by Dre, https://www.beatsbydre.com/")] BeatsByDre,
        [Description("Behance, https://www.behance.net/dev/api/brand")] Behance,
        [Description("Big Cartel, https://www.bigcartel.com")] BigCartel,
        [Description("Bing, https://commons.wikimedia.org/wiki/File:Bing_logo_(2016).svg")] Bing,
        [Description("Bit, https://bit.dev")] Bit,
        [Description("Bitbucket, https://www.atlassian.com/company/news/press-kit")] Bitbucket,
        [Description("Bitcoin, https://bitcoin.org/en")] Bitcoin,
        [Description("Bitdefender, https://www.bitdefender.com/funzone/logos.html")] Bitdefender,
        [Description("Bitly, https://bitly.com/pages/press")] Bitly,
        [Description("Bitrise, https://www.bitrise.io/presskit")] Bitrise,
        [Description("Blackberry, https://www.blackberry.com/")] Blackberry,
        [Description("Blender, https://www.blender.org/about/logo/")] Blender,
        [Description("Blogger, https://www.blogger.com")] Blogger,
        [Description("Bluetooth, https://www.bluetooth.com/develop-with-bluetooth/marketing-branding/")] Bluetooth,
        [Description("BMC Software, https://www.bmc.com/")] BmcSoftware,
        [Description("BMW, https://www.bmwgroup-classic.com/en/bmw-clubs/downloadbereich.html")] Bmw,
        [Description("Boeing, https://upload.wikimedia.org/wikipedia/commons/4/4f/Boeing_full_logo.svg")] Boeing,
        [Description("Boost, https://www.boostmobile.com/")] Boost,
        [Description("Bootstrap, http://getbootstrap.com/about")] Bootstrap,
        [Description("Bower, https://bower.io/docs/about/#brand")] Bower,
        [Description("Box, https://www.box.com/en-gb/about-us/press")] Box,
        [Description("Brand.ai, https://brand.ai/brand-ai/style")] BrandAi,
        [Description("Brandfolder, https://brandfolder.com/brandfolder")] Brandfolder,
        [Description("Brave, https://brave.com/brave-branding-assets/")] Brave,
        [Description("Breaker, https://www.breaker.audio/i/brand")] Breaker,
        [Description("Broadcom, https://en.wikipedia.org/wiki/Broadcom_Inc")] Broadcom,
        [Description("Buddy, https://buddy.works/about")] Buddy,
        [Description("Buffer, https://buffer.com/press")] Buffer,
        [Description("Bugsnag, https://www.bugsnag.com/newsroom")] Bugsnag,
        [Description("Bulma, https://github.com/jgthms/bulma/")] Bulma,
        [Description("Buy Me A Coffee, https://www.buymeacoffee.com/brand")] BuyMeACoffee,
        [Description("BuzzFeed, http://www.buzzfeed.com/press/downloads")] BuzzFeed,
        [Description("C, https://commons.wikimedia.org/wiki/File:The_C_Programming_Language_logo.svg")] C,
        [Description("CakePHP, https://cakephp.org/logos")] CakePhp,
        [Description("Campaign Monitor, https://www.campaignmonitor.com/company/brand/")] CampaignMonitor,
        [Description("Canva, https://www.canva.com/")] Canva,
        [Description("Cash App, https://cash.app/press")] CashApp,
        [Description("Cassandra, https://upload.wikimedia.org/wikipedia/commons/5/5e/Cassandra_logo.svg")] Cassandra,
        [Description("Castorama, https://www.castorama.fr/")] Castorama,
        [Description("Castro, http://supertop.co/castro/press/")] Castro,
        [Description("CD Projekt, https://www.cdprojekt.com/en/media/logotypes/")] CdProjekt,
        [Description("Celery, http://www.celeryproject.org/")] Celery,
        [Description("CentOS, https://wiki.centos.org/ArtWork/Brand/Logo")] CentOs,
        [Description("Cesium, https://cesium.com/press/")] Cesium,
        [Description("CEVO, https://cevo.com/")] Cevo,
        [Description("ChartMogul, https://chartmogul.com/company/")] ChartMogul,
        [Description("Chase, https://commons.wikimedia.org/wiki/File:Chase_logo_2007.svg")] Chase,
        [Description("Chef, https://www.chef.io/")] Chef,
        [Description("Cinema 4D, https://www.maxon.net/de/header-meta-navigation/ueber-maxon/pressematerial/")] Cinema4D,
        [Description("Circle, https://www.circle.com/")] Circle,
        [Description("CircleCI, https://circleci.com/press")] CircleCi,
        [Description("Cirrus CI, https://cirrus-ci.org")] CirrusCi,
        [Description("Cisco, https://www.cisco.com/")] Cisco,
        [Description("Citrix, https://www.citrix.com/news/media-resources.html")] Citrix,
        [Description("CiviCRM, https://civicrm.org/trademark")] CiviCrm,
        [Description("Claris, https://www.claris.com/")] Claris,
        [Description("Clockify, https://clockify.me/")] Clockify,
        [Description("Clojure, https://commons.wikimedia.org/wiki/File:Clojure_logo.svg")] Clojure,
        [Description("CloudBees, https://www.cloudbees.com/")] CloudBees,
        [Description("CloudCannon, https://cloudcannon.com/")] CloudCannon,
        [Description("Cloudflare, https://www.cloudflare.com/logo/")] Cloudflare,
        [Description("Cloudsmith, https://cloudsmith.io/branding/")] Cloudsmith,
        [Description("CMake, https://www.kitware.com/platforms/")] CMake,
        [Description("CNN, https://edition.cnn.com/")] Cnn,
        [Description("Codacy, https://www.codacy.com/blog/")] Codacy,
        [Description("Codecademy, https://www.codecademy.com/")] Codecademy,
        [Description("CodeChef, https://www.codechef.com/")] CodeChef,
        [Description("Code Climate, https://codeclimate.com/")] CodeClimate,
        [Description("Codecov, https://codecov.io/")] Codecov,
        [Description("CodeFactor, https://www.codefactor.io/")] CodeFactor,
        [Description("Codeforces, http://codeforces.com/")] Codeforces,
        [Description("CodeIgniter, https://www.codeigniter.com/help/legal")] CodeIgniter,
        [Description("CodePen, https://blog.codepen.io/documentation/brand-assets/logos/")] CodePen,
        [Description("Coderwall, https://github.com/twolfson/coderwall-svg")] Coderwall,
        [Description("CodeSandbox, https://codesandbox.io")] CodeSandbox,
        [Description("Codeship, https://app.codeship.com/")] Codeship,
        [Description("Codewars, https://www.codewars.com")] Codewars,
        [Description("Codio, https://codio.com")] Codio,
        [Description("CoffeeScript, https://coffeescript.org/")] CoffeeScript,
        [Description("Coinbase, https://www.coinbase.com/press")] Coinbase,
        [Description("Common Workflow Language, https://github.com/common-workflow-language/logo/blob/master/CWL-Logo-nofonts.svg")] CommonWorkflowLanguage,
        [Description("Composer, https://getcomposer.org/")] Composer,
        [Description("ComproPago, https://compropago.com")] ComproPago,
        [Description("Concourse, https://concourse-ci.org/")] Concourse,
        [Description("Conda-Forge, https://github.com/conda-forge/conda-forge.github.io/")] CondaForge,
        [Description("Conekta, https://www.conekta.io")] Conekta,
        [Description("Confluence, https://www.atlassian.com/company/news/press-kit")] Confluence,
        [Description("Convertio, https://convertio.co/")] Convertio,
        [Description("Co-op, http://www.co-operative.coop/corporate/press/logos/")] CoOp,
        [Description("Corona Engine, https://coronalabs.com/")] CoronaEngine,
        [Description("Corona Renderer, https://corona-renderer.com/about")] CoronaRenderer,
        [Description("Coursera, https://about.coursera.org/press")] Coursera,
        [Description("Coveralls, https://coveralls.io/")] Coveralls,
        [Description("cPanel, https://cpanel.net/company/cpanel-brand-guide/")] CPanel,
        [Description("C++, https://github.com/isocpp/logos")] CPlusPlus,
        [Description("Craft CMS, https://craftcms.com/brand-resources")] CraftCms,
        [Description("Creative Commons, https://creativecommons.org/")] CreativeCommons,
        [Description("Crehana, https://www.crehana.com/")] Crehana,
        [Description("Crunchbase, https://www.crunchbase.com/home")] Crunchbase,
        [Description("Crunchyroll, https://www.crunchyroll.com")] Crunchyroll,
        [Description("CRYENGINE, https://www.cryengine.com/brand")] Cryengine,
        [Description("C Sharp, https://upload.wikimedia.org/wikipedia/commons/0/0d/C_Sharp_wordmark.svg")] CSharp,
        [Description("CSS3, http://www.w3.org/html/logo/")] Css3,
        [Description("CSS Wizardry, http://csswizardry.com")] CssWizardry,
        [Description("curl, https://curl.haxx.se/logo/")] Curl,
        [Description("D3.js, https://github.com/d3/d3-logo")] D3Js,
        [Description("Dailymotion, http://press.dailymotion.com/?page_id=346")] Dailymotion,
        [Description("Dart, https://github.com/dart-lang/site-shared/tree/master/src/_assets/image/dart/logo")] Dart,
        [Description("Das Erste, https://en.wikipedia.org/wiki/Das_Erste")] DasErste,
        [Description("Dashlane, https://www.dashlane.com/")] Dashlane,
        [Description("Dassault Systèmes, https://www.3ds.com/statics/menu/2/assets/img/logo/3ds-dark.svg")] DassaultSystèmes,
        [Description("DataCamp, https://www.datacamp.com/")] DataCamp,
        [Description("Datadog, https://www.datadoghq.com/")] Datadog,
        [Description("DAZN, https://media.dazn.com/en/assets/")] Dazn,
        [Description("dblp, https://dblp.org/")] Dblp,
        [Description("DC Entertainment, https://www.readdc.com/")] DcEntertainment,
        [Description("Debian, https://www.debian.org/logos")] Debian,
        [Description("deepin, https://commons.wikimedia.org/wiki/File:Deepin_logo.svg")] Deepin,
        [Description("Deezer, https://deezerbrand.com/")] Deezer,
        [Description("Delicious, https://en.wikipedia.org/wiki/Delicious_(website)")] Delicious,
        [Description("Deliveroo, https://www.deliveroo.design/")] Deliveroo,
        [Description("Dell, https://datasecurity.dell.com/wp-content/themes/dell/images/logo-dell.svg")] Dell,
        [Description("Deno, https://github.com/denoland/deno/tree/1cc02a5d9d867f1a239ee4b69f587d8afac07b02/website/images")] Deno,
        [Description("Dependabot, https://dependabot.com/dependabot-logo-symbol-square-mono.svg")] Dependabot,
        [Description("Designer News, https://www.designernews.co")] DesignerNews,
        [Description("DeviantArt, http://help.deviantart.com/21")] DeviantArt,
        [Description("devRant, https://devrant.com")] DevRant,
        [Description("dev.to, https://dev.to/")] DevTo,
        [Description("Diaspora, https://wiki.diasporafoundation.org/Branding")] Diaspora,
        [Description("Digg, https://en.wikipedia.org/wiki/Digg")] Digg,
        [Description("DigitalOcean, https://www.digitalocean.com/company/logos-and-badges/")] DigitalOcean,
        [Description("Directus, https://directus.io/resources.html")] Directus,
        [Description("Discogs, https://www.discogs.com/brand")] Discogs,
        [Description("Discord, https://discordapp.com/branding")] Discord,
        [Description("Discourse, https://www.discourse.org/")] Discourse,
        [Description("Discover, https://www.discovernetwork.com/en-us/business-resources/free-signage-logos")] Discover,
        [Description("Disqus, https://disqus.com/brand")] Disqus,
        [Description("Disroot, https://git.fosscommunity.in/disroot/assests/blob/master/d.svg")] Disroot,
        [Description("Django, https://www.djangoproject.com/community/logos/")] Django,
        [Description("DLNA, https://upload.wikimedia.org/wikipedia/de/e/eb/Digital_Living_Network_Alliance_logo.svg")] Dlna,
        [Description("Docker, https://www.docker.com/company/newsroom/media-resources")] Docker,
        [Description("DocuSign, https://github.com/simple-icons/simple-icons/issues/1098")] DocuSign,
        [Description("Dolby, https://www.dolby.com/us/en/about/brand-identity.html")] Dolby,
        [Description(".NET, https://docs.microsoft.com/en-us/dotnet/images/hub/net.svg")] DotNet,
        [Description("Douban, https://zh.wikipedia.org/wiki/Douban")] Douban,
        [Description("Draugiem.lv, https://www.frype.com/applications/dev/docs/logos/")] DraugiemLv,
        [Description("Dribbble, https://dribbble.com/branding")] Dribbble,
        [Description("Drone, https://github.com/drone/brand")] Drone,
        [Description("Dropbox, https://www.dropbox.com/branding")] Dropbox,
        [Description("Drupal, https://www.drupal.org/drupalorg/style-guide/colors")] Drupal,
        [Description("DTube, https://about.d.tube/mediakit.html")] DTube,
        [Description("DuckDuckGo, https://duckduckgo.com/")] DuckDuckGo,
        [Description("Dunked, https://dunked.com/")] Dunked,
        [Description("Duolingo, https://www.duolingo.com/")] Duolingo,
        [Description("Dynamics 365, http://thepartnerchannel.com/wp-content/uploads/Dynamics365_styleguide_092816.pdf")] Dynamics365,
        [Description("Dynatrace, https://www.dynatrace.com/company/press-kit/")] Dynatrace,
        [Description("EA, https://www.ea.com")] Ea,
        [Description("easyJet, https://www.easyjet.com")] EasyJet,
        [Description("eBay, https://go.developer.ebay.com/logos")] EBay,
        [Description("Eclipse IDE, https://www.eclipse.org/artwork/")] EclipseIde,
        [Description("Elastic, https://www.elastic.co/brand")] Elastic,
        [Description("Elastic Cloud, https://www.elastic.co/brand")] ElasticCloud,
        [Description("Elasticsearch, https://www.elastic.co/brand")] Elasticsearch,
        [Description("Elastic Stack, https://www.elastic.co/brand")] ElasticStack,
        [Description("Electron, https://electronjs.org/images/electron-logo.svg")] Electron,
        [Description("elementary, https://elementary.io/brand")] Elementary,
        [Description("Eleventy, https://www.11ty.io")] Eleventy,
        [Description("Elixir, https://github.com/elixir-lang/elixir-lang.github.com/tree/master/images/logo")] Elixir,
        [Description("Ello, https://ello.co")] Ello,
        [Description("Elm, https://github.com/elm/foundation.elm-lang.org/blob/2d097b317d8af2aaeab49284830260a32d817305/assets/elm_logo.svg")] Elm,
        [Description("Elsevier, https://www.elsevier.com")] Elsevier,
        [Description("Ember.js, https://emberjs.com/logos/")] EmberJs,
        [Description("Emby, https://emby.media/")] Emby,
        [Description("Emlakjet, https://www.emlakjet.com/kurumsal-materyaller/")] Emlakjet,
        [Description("Empire Kred, http://www.empire.kred")] EmpireKred,
        [Description("Envato, https://envato.com/")] Envato,
        [Description("EPEL, https://fedoraproject.org/wiki/EPEL")] Epel,
        [Description("Epic Games, https://www.epicgames.com/")] EpicGames,
        [Description("Epson, https://global.epson.com/IR/library/")] Epson,
        [Description("ESEA, https://play.esea.net/")] Esea,
        [Description("ESLint, https://eslint.org/img/logo.svg")] EsLint,
        [Description("Ethereum, https://www.ethereum.org/images/logos/Ethereum_Visual_Identity_1.0.0.pdf")] Ethereum,
        [Description("Etsy, https://www.etsy.com/uk/press")] Etsy,
        [Description("Eventbrite, https://www.eventbrite.com/signin/")] Eventbrite,
        [Description("Event Store, https://github.com/eventstore/brand")] EventStore,
        [Description("Evernote, https://evernote.com/press")] Evernote,
        [Description("Everplaces, https://everplaces.com")] Everplaces,
        [Description("EVRY, https://www.evry.com/en/")] Evry,
        [Description("Exercism, https://github.com/exercism/website-icons/blob/master/exercism/logo-icon.svg")] Exercism,
        [Description("Experts Exchange, https://www.experts-exchange.com/")] ExpertsExchange,
        [Description("Expo, http://expo.io")] Expo,
        [Description("EyeEm, https://www.eyeem.com/")] EyeEm,
        [Description("Facebook, https://en.facebookbrand.com/")] Facebook,
        [Description("FACEIT, https://corporate.faceit.com/branding/")] Faceit,
        [Description("Fandango, https://www.fandango.com")] Fandango,
        [Description("Fandom, https://fandomdesignsystem.com/")] Fandom,
        [Description("Fastly, https://assets.fastly.com/style-guide/docs/")] Fastly,
        [Description("Favro, https://favro.com/login")] Favro,
        [Description("F-Droid, https://f-droid.org/")] FDroid,
        [Description("FeatHub, http://feathub.com/")] FeatHub,
        [Description("Fedora, https://fedoraproject.org/wiki/Logo/UsageGuidelines")] Fedora,
        [Description("FedRAMP, https://www.fedramp.gov/assets/resources/documents/FedRAMP_Branding_Guidance.pdf")] FedRamp,
        [Description("Feedly, https://blog.feedly.com/wp-content/themes/feedly-2017-v1.19.3/assets/images/logos/logo.svg")] Feedly,
        [Description("Ferrari, https://www.ferrari.com/")] Ferrari,
        [Description("Ferrari N.V., https://corporate.ferrari.com/")] FerrariNV_,
        [Description("Fido Alliance, https://fidoalliance.org/overview/legal/logo-usage/")] FidoAlliance,
        [Description("FIFA, https://en.wikipedia.org/wiki/FIFA")] Fifa,
        [Description("Figma, https://figma.com/")] Figma,
        [Description("figshare, https://en.wikipedia.org/wiki/Figshare")] Figshare,
        [Description("Fila, https://en.wikipedia.org/wiki/Fila_(company)")] Fila,
        [Description("FileZilla, https://upload.wikimedia.org/wikipedia/commons/0/01/FileZilla_logo.svg")] FileZilla,
        [Description("Firebase, https://firebase.google.com/brand-guidelines/")] Firebase,
        [Description("FIRST, https://www.firstinspires.org/brand")] First,
        [Description("Fitbit, http://www.fitbit.com/uk/home")] Fitbit,
        [Description("FITE, https://www.fite.tv/")] Fite,
        [Description("Fiverr, https://www.fiverr.com/press-kit")] Fiverr,
        [Description("Flask, http://flask.pocoo.org/community/logos/")] Flask,
        [Description("Flattr, https://flattr.com/")] Flattr,
        [Description("Flickr, https://worldvectorlogo.com/logo/flickr-1")] Flickr,
        [Description("Flipboard, https://about.flipboard.com/brand-guidelines")] Flipboard,
        [Description("Floatplane, https://www.floatplane.com/")] Floatplane,
        [Description("Flood, https://flood.io/")] Flood,
        [Description("Fluentd, https://docs.fluentd.org/quickstart/logo")] Fluentd,
        [Description("Flutter, https://flutter.dev/brand")] Flutter,
        [Description("Fnac, http://www.fnac.com/")] Fnac,
        [Description("Font Awesome, https://fontawesome.com/icons/font-awesome")] FontAwesome,
        [Description("Formstack, https://www.formstack.com/brand/guidelines")] Formstack,
        [Description("Fortinet, http://www.fortinet.com/")] Fortinet,
        [Description("Fossa, https://fossa.com/press/")] Fossa,
        [Description("Fossil SCM, https://fossil-scm.org/")] FossilScm,
        [Description("Foursquare, https://foursquare.com/about/logos")] Foursquare,
        [Description("Framer, https://framer.com")] Framer,
        [Description("FreeBSD, https://www.freebsdfoundation.org/about/project/")] FreeBsd,
        [Description("freeCodeCamp, https://freecodecamp.com")] FreeCodeCamp,
        [Description("Freelancer, https://www.freelancer.com/")] Freelancer,
        [Description("F-Secure, https://vip.f-secure.com/en/marketing/logos")] FSecure,
        [Description("Fujifilm, https://upload.wikimedia.org/wikipedia/commons/a/a1/Fujifilm_logo.svg")] Fujifilm,
        [Description("Fujitsu, https://www.fujitsu.com/global/about/brandmanagement/logo/")] Fujitsu,
        [Description("Fur Affinity, https://www.furaffinity.net/")] FurAffinity,
        [Description("Furry Network, https://furrynetwork.com")] FurryNetwork,
        [Description("Garmin, https://developer.garmin.com/resources/brand-guidelines/")] Garmin,
        [Description("Gatsby, https://www.gatsbyjs.org/")] Gatsby,
        [Description("Gauges, http://get.gaug.es/")] Gauges,
        [Description("General Motors, https://commons.wikimedia.org/wiki/File:General_Motors_logo.svg")] GeneralMotors,
        [Description("Genius, https://upload.wikimedia.org/wikipedia/en/a/ad/Genius_website_logo.svg")] Genius,
        [Description("Gentoo, https://wiki.gentoo.org/wiki/Project:Artwork/Artwork#Variations_of_the_.22g.22_logo")] Gentoo,
        [Description("Geocaching, https://www.geocaching.com/about/logousage.aspx")] Geocaching,
        [Description("Gerrit, https://gerrit-review.googlesource.com/c/75842/")] Gerrit,
        [Description("Ghost, https://ghost.org/design")] Ghost,
        [Description("GIMP, https://www.gimp.org/about/linking.html#wilber-the-gimp-mascot")] Gimp,
        [Description("Git, http://git-scm.com/downloads/logos")] Git,
        [Description("Gitea, https://github.com/go-gitea/gitea/tree/master/assets")] Gitea,
        [Description("GitHub, https://github.com/logos")] GitHub,
        [Description("GitHub Actions, https://github.com/features/actions")] GitHubActions,
        [Description("GitKraken, https://www.gitkraken.com/")] GitKraken,
        [Description("GitLab, https://about.gitlab.com/press/press-kit/")] GitLab,
        [Description("Gitpod, https://www.gitpod.io/")] Gitpod,
        [Description("Gitter, https://gitter.im/")] Gitter,
        [Description("Glassdoor, https://www.glassdoor.com/press/images/")] Glassdoor,
        [Description("Glitch, https://glitch.com/about/press/")] Glitch,
        [Description("Gmail, https://material.io/guidelines/resources/sticker-sheets-icons.html#sticker-sheets-icons-components")] Gmail,
        [Description("GNOME, https://wiki.gnome.org/Engagement/BrandGuidelines")] Gnome,
        [Description("GNU, https://gnu.org")] Gnu,
        [Description("GNU Bash, https://github.com/odb/official-bash-logo")] GnuBash,
        [Description("GNU Emacs, https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/images/icons/hicolor/scalable/apps/emacs.svg")] GnuEmacs,
        [Description("GNU IceCat, https://git.savannah.gnu.org/cgit/gnuzilla.git/plain/artwork/simple.svg")] GnuIceCat,
        [Description("GNU Privacy Guard, https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=tree;f=artwork/icons")] GnuPrivacyGuard,
        [Description("GNU social, https://www.gnu.org/graphics/social.html")] GnuSocial,
        [Description("Go, https://blog.golang.org/go-brand")] Go,
        [Description("Godot Engine, https://godotengine.org/themes/godotengine/assets/download/godot_logo.svg")] GodotEngine,
        [Description("GOG.com, https://www.cdprojekt.com/en/media/logotypes/")] GogCom,
        [Description("GoldenLine, http://www.goldenline.pl")] GoldenLine,
        [Description("Goodreads, https://www.goodreads.com/about/press")] Goodreads,
        [Description("Google, https://developers.google.com/+/branding-guidelines?hl=en")] Google,
        [Description("Google Ads, https://designguidelines.withgoogle.com/ads-branding/google-ads/logos.html#logos-brand-logo-lockups")] GoogleAds,
        [Description("Google Analytics, https://analytics.google.com")] GoogleAnalytics,
        [Description("Google Assistant, https://assistant.google.com/")] GoogleAssistant,
        [Description("Google Cardboard, https://arvr.google.com/cardboard/")] GoogleCardboard,
        [Description("Google Cast, https://partnermarketinghub.withgoogle.com/#/brands")] GoogleCast,
        [Description("Google Chrome, https://blog.google/press/?product_tag=chrome")] GoogleChrome,
        [Description("Google Classroom, https://classroom.google.com/")] GoogleClassroom,
        [Description("Google Cloud, https://cloud.google.com/")] GoogleCloud,
        [Description("Google Drive, https://developers.google.com/drive/web/branding")] GoogleDrive,
        [Description("Google Earth, https://earth.google.com/web/")] GoogleEarth,
        [Description("Google Fit, https://partnermarketinghub.withgoogle.com/#/brands/")] GoogleFit,
        [Description("Google Hangouts, https://material.google.com/resources/sticker-sheets-icons.html#sticker-sheets-icons-components")] GoogleHangouts,
        [Description("Google Hangouts Chat, https://chat.google.com/error/noaccess")] GoogleHangoutsChat,
        [Description("Google Keep, https://play.google.com/store/apps/details?id=com.google.android.keep")] GoogleKeep,
        [Description("Google Lens, https://partnermarketinghub.withgoogle.com/#/brands/")] GoogleLens,
        [Description("Google Maps, https://upload.wikimedia.org/wikipedia/commons/a/a9/Google_Maps_icon.svg")] GoogleMaps,
        [Description("Google Messages, https://messages.google.com/")] GoogleMessages,
        [Description("Google My Business, https://business.google.com/")] GoogleMyBusiness,
        [Description("Google Nearby, https://developers.google.com/nearby/developer-guidelines")] GoogleNearby,
        [Description("Google Pay, https://partnermarketinghub.withgoogle.com/#/brands/")] GooglePay,
        [Description("Google Play, https://partnermarketinghub.withgoogle.com/#/brands/")] GooglePlay,
        [Description("Google Podcasts, https://developers.google.com/search/docs/data-types/podcast")] GooglePodcasts,
        [Description("Google Scholar, https://scholar.google.com/intl/fr/scholar/images/2x/sprite_20161020.png")] GoogleScholar,
        [Description("Google Search Console, https://search.google.com/search-console")] GoogleSearchConsole,
        [Description("Google Sheets, http://sheets.google.com/")] GoogleSheets,
        [Description("Google Street View, https://developers.google.com/streetview/ready/branding")] GoogleStreetView,
        [Description("Google Tag Manager, https://tagmanager.google.com/#/home")] GoogleTagManager,
        [Description("Google Translate, https://en.wikipedia.org/wiki/Google_Translate")] GoogleTranslate,
        [Description("GOV.UK, https://github.com/alphagov/design-assets/tree/master/Icons")] GovUk,
        [Description("Gradle, https://gradle.com/brand")] Gradle,
        [Description("Grafana, https://grafana.com/")] Grafana,
        [Description("Graphcool, https://www.graph.cool")] Graphcool,
        [Description("GraphQL, http://graphql.org/")] GraphQl,
        [Description("Grav, http://getgrav.org/media")] Grav,
        [Description("Gravatar, https://automattic.com/press")] Gravatar,
        [Description("Greenkeeper, https://greenkeeper.io/")] Greenkeeper,
        [Description("GreenSock, https://greensock.com/")] GreenSock,
        [Description("Groovy, https://groovy-lang.org/")] Groovy,
        [Description("Groupon, https://brandplaybook.groupon.com/guidelines/logo/")] Groupon,
        [Description("Grunt, https://github.com/gruntjs/gruntjs.com/tree/master/src/media")] Grunt,
        [Description("Gulp, https://github.com/gulpjs/artwork/blob/master/gulp.svg")] Gulp,
        [Description("Gumroad, https://gumroad.com/press")] Gumroad,
        [Description("Gumtree, https://www.gumtree.com")] Gumtree,
        [Description("Gutenberg, https://github.com/WordPress/gutenberg/blob/master/docs/final-g-wapuu-black.svg")] Gutenberg,
        [Description("Habr, https://habr.com/")] Habr,
        [Description("Hackaday, https://hackaday.com/")] Hackaday,
        [Description("HackerEarth, https://www.hackerearth.com/logo/")] HackerEarth,
        [Description("HackerOne, https://www.hackerone.com/branding")] HackerOne,
        [Description("HackerRank, https://www.hackerrank.com/")] HackerRank,
        [Description("HackHands, https://hackhands.com/")] HackHands,
        [Description("Hackster, https://drive.google.com/file/d/0B3aqzR8LzoqdT1p4ZUlWVnJ1elk/view?usp=sharing")] Hackster,
        [Description("HappyCow, https://www.happycow.net/press-kits")] HappyCow,
        [Description("Harbor, https://github.com/goharbor/harbor/blob/13686cbe83d22259216da7658612e86201070e94/src/portal/src/images/harbor-logo.svg")] Harbor,
        [Description("Hashnode, https://hashnode.com/media")] Hashnode,
        [Description("Haskell, https://commons.wikimedia.org/wiki/File:Haskell-Logo.svg")] Haskell,
        [Description("Hatena Bookmark, http://hatenacorp.jp/press/resource")] HatenaBookmark,
        [Description("haveibeenpwned, https://haveibeenpwned.com/")] Haveibeenpwned,
        [Description("Haxe, https://haxe.org/foundation/branding.html")] Haxe,
        [Description("HelloFresh, https://www.hellofresh.com/landing/student")] HelloFresh,
        [Description("Helm, https://helm.sh")] Helm,
        [Description("HERE, https://www.here.com")] Here,
        [Description("Heroku, https://www.heroku.com")] Heroku,
        [Description("Hexo, https://hexo.io/")] Hexo,
        [Description("Highly, https://highly.co/")] Highly,
        [Description("HipChat, https://www.atlassian.com/company/news/press-kit")] HipChat,
        [Description("Hitachi, https://commons.wikimedia.org/wiki/File:Hitachi_inspire_the_next-Logo.svg")] Hitachi,
        [Description("Hive, https://www.hivehome.com/")] Hive,
        [Description("HockeyApp, https://hockeyapp.net/brand-guidelines/")] HockeyApp,
        [Description("Home Assistant, https://github.com/home-assistant/home-assistant-assets")] HomeAssistant,
        [Description("homify, http://lsg.homify.com/")] Homify,
        [Description("Hootsuite, https://hootsuite.com/en-gb/about/media-kit")] Hootsuite,
        [Description("Houdini, https://www.sidefx.com/products/houdini/")] Houdini,
        [Description("Houzz, https://www.houzz.com/logoGuidelines")] Houzz,
        [Description("HP, https://commons.wikimedia.org/wiki/File:HP_New_Logo_2D.svg")] Hp,
        [Description("HTML5, http://www.w3.org/html/logo/")] Html5,
        [Description("HTML Academy, https://htmlacademy.ru/")] HtmlAcademy,
        [Description("Huawei, https://en.wikipedia.org/wiki/File:Huawei.svg")] Huawei,
        [Description("HubSpot, https://www.hubspot.com/style-guide")] HubSpot,
        [Description("Hugo, https://gohugo.io/")] Hugo,
        [Description("Hulu, https://www.hulu.com/press/brand-assets/")] Hulu,
        [Description("Humble Bundle, https://support.humblebundle.com/hc/en-us/articles/202742060-Bundle-Logos")] HumbleBundle,
        [Description("Hurriyetemlak, https://ilan.hurriyetemlak.com/emlak-ilani-yayinlama-kurallari")] Hurriyetemlak,
        [Description("Hypothesis, https://web.hypothes.is/")] Hypothesis,
        [Description("Iata, https://upload.wikimedia.org/wikipedia/commons/f/f7/IATAlogo.svg")] Iata,
        [Description("IBM, https://www.ibm.com/design/language/elements/logos/8-bar/")] Ibm,
        [Description("iCloud, https://www.icloud.com/")] ICloud,
        [Description("IcoMoon, https://icomoon.io/")] IcoMoon,
        [Description("ICON, https://icon.foundation/")] Icon,
        [Description("Iconify, https://iconify.design/")] Iconify,
        [Description("IconJar, https://geticonjar.com/press-kit/")] IconJar,
        [Description("ICQ, https://en.wikipedia.org/wiki/File:ICQ.svg")] Icq,
        [Description("iDEAL, https://www.ideal.nl/cms/files/Manual_iDEAL_logo.pdf")] IDeal,
        [Description("iFixit, https://www.ifixit.com/")] IFixit,
        [Description("iFood, https://ifood.com.br/")] IFood,
        [Description("IMDb, http://www.imdb.com/pressroom/brand_guidelines")] ImDb,
        [Description("Imgur, https://s.imgur.com/images/favicon-152.png")] Imgur,
        [Description("Indeed, https://www.indeed.com")] Indeed,
        [Description("InfluxDB, https://www.influxdata.com/")] InfluxDb,
        [Description("Inkscape, https://commons.wikimedia.org/wiki/File:Inkscape_Logo.svg")] Inkscape,
        [Description("Instacart, https://www.instacart.com/press")] Instacart,
        [Description("Instagram, https://www.instagram-brand.com")] Instagram,
        [Description("Instapaper, https://www.instapaper.com/")] Instapaper,
        [Description("Intel, https://www.intel.com")] Intel,
        [Description("IntelliJ IDEA, https://www.jetbrains.com/idea/")] IntelliJIdea,
        [Description("Intercom, https://www.intercom.io")] Intercom,
        [Description("Internet Archive, https://openlibrary.org/static/images/ia-logo.svg")] InternetArchive,
        [Description("Internet Explorer, https://compass-ssl.microsoft.com/assets/c8/67/c867db4c-f328-45b8-817c-33834c70aae6.svg?n=IE.svg")] InternetExplorer,
        [Description("InVision, https://projects.invisionapp.com/boards/BX4P1DY5H46R")] InVision,
        [Description("Invoice Ninja, https://github.com/invoiceninja/invoiceninja")] InvoiceNinja,
        [Description("ioBroker, https://github.com/ioBroker/awesome-iobroker/blob/master/images/")] IoBroker,
        [Description("Ionic, https://ionicframework.com/press")] Ionic,
        [Description("iOS, https://en.wikipedia.org/wiki/IOS")] IOs,
        [Description("IPFS, https://github.com/ipfs/logo")] Ipfs,
        [Description("Issuu, https://issuu.com/press")] Issuu,
        [Description("Itch.io, https://itch.io/press-kit")] ItchIo,
        [Description("iTunes, https://upload.wikimedia.org/wikipedia/commons/d/df/ITunes_logo.svg")] ITunes,
        [Description("Jabber, https://commons.wikimedia.org/wiki/File:Jabber-bulb.svg")] Jabber,
        [Description("Java, https://www.oracle.com/legal/logos.html")] Java,
        [Description("JavaScript, https://github.com/voodootikigod/logo.js")] JavaScript,
        [Description("JCB, https://www.global.jcb/en/about-us/brand-concept/")] Jcb,
        [Description("Jekyll, https://github.com/jekyll/brand")] Jekyll,
        [Description("Jenkins, https://wiki.jenkins-ci.org/display/JENKINS/Logo")] Jenkins,
        [Description("Jenkins X, https://github.com/cdfoundation/artwork")] JenkinsX,
        [Description("Jest, https://jestjs.io/")] Jest,
        [Description("JET, https://de.wikipedia.org/wiki/Datei:JET.svg")] Jet,
        [Description("JetBrains, https://www.jetbrains.com/company/brand/")] JetBrains,
        [Description("Jinja, https://github.com/pallets/jinja/")] Jinja,
        [Description("Jira, https://www.atlassian.com/company/news/press-kit")] Jira,
        [Description("Joomla, https://docs.joomla.org/Joomla:Brand_Identity_Elements")] Joomla,
        [Description("jQuery, https://brand.jquery.org/logos/")] JQuery,
        [Description("jsDelivr, https://github.com/jsdelivr/www.jsdelivr.com/blob/eff02f3a8879cf7c7296840584e1293fe04e3a76/src/public/img/logo_horizontal.svg")] JsDelivr,
        [Description("JSFiddle, https://jsfiddle.net/")] JsFiddle,
        [Description("JSON, https://commons.wikimedia.org/wiki/File:JSON_vector_logo.svg")] Json,
        [Description("JSON Web Tokens, https://jwt.io/")] JsonWebTokens,
        [Description("Jupyter, https://github.com/jupyter/design")] Jupyter,
        [Description("Just Eat, https://d2vkuayfhnkplp.cloudfront.net/assets/dist/img/logos/je-logo-v3.svg")] JustEat,
        [Description("JustGiving, https://justgiving.com")] JustGiving,
        [Description("Kaggle, https://www.kaggle.com/contact")] Kaggle,
        [Description("KaiOS, https://www.dropbox.com/sh/2qihtgrzllws8ki/AABmo9X1KMT6lHnvh4Em7dpWa?dl=0")] KaiOs,
        [Description("Kaspersky, https://www.kaspersky.com")] Kaspersky,
        [Description("Katana, https://www.foundry.com/products/katana")] Katana,
        [Description("KeePassXC, https://github.com/keepassxreboot/keepassxc/")] KeePassXc,
        [Description("Kentico, https://brand.kentico.com")] Kentico,
        [Description("Keras, https://keras.io/")] Keras,
        [Description("Keybase, https://github.com/keybase/client/tree/master/media/logos")] Keybase,
        [Description("KeyCDN, https://www.keycdn.com/logos")] KeyCdn,
        [Description("Khan Academy, https://khanacademy.zendesk.com/hc/en-us/articles/202483630-Press-room")] KhanAcademy,
        [Description("Khronos Group, https://www.khronos.org/legal/trademarks/")] KhronosGroup,
        [Description("Kibana, https://www.elastic.co/brand")] Kibana,
        [Description("Kickstarter, https://www.kickstarter.com/help/brand_assets")] Kickstarter,
        [Description("Kik, http://www.kik.com/press")] Kik,
        [Description("Kirby, https://getkirby.com/press")] Kirby,
        [Description("KLM, https://www.klm.com")] Klm,
        [Description("Klout, https://klout.com/s/developers/styleguide")] Klout,
        [Description("Known, https://withknown.com/img/logo_k.png")] Known,
        [Description("Kodi, https://kodi.tv/")] Kodi,
        [Description("Koding, https://koding.com/About")] Koding,
        [Description("Ko-fi, https://ko-fi.com/home/about")] KoFi,
        [Description("Kotlin, https://resources.jetbrains.com/storage/products/kotlin/docs/kotlin_logos.zip")] Kotlin,
        [Description("Krita, https://krita.org/en/about/press/")] Krita,
        [Description("Kubernetes, https://github.com/kubernetes/kubernetes/tree/master/logo")] Kubernetes,
        [Description("Kyocera, https://en.wikipedia.org/wiki/Kyocera")] Kyocera,
        [Description("LabVIEW, http://download.ni.com/evaluation/2018_Partner_Cobranding_Style_Guide.pdf")] LabView,
        [Description("Laravel, https://github.com/laravel/art")] Laravel,
        [Description("Laravel Horizon, https://horizon.laravel.com/")] LaravelHorizon,
        [Description("Laravel Nova, https://nova.laravel.com/")] LaravelNova,
        [Description("Last.fm, http://www.last.fm/about/resources")] LastFm,
        [Description("LastPass, https://lastpass.com/press-room/")] LastPass,
        [Description("LaTeX, https://github.com/latex3/branding")] LaTeX,
        [Description("Launchpad, https://help.launchpad.net/logo/submissions")] Launchpad,
        [Description("LeetCode, https://leetcode.com")] LeetCode,
        [Description("Lenovo, https://www.lenovopartnernetwork.com/us/branding/")] Lenovo,
        [Description("Let’s Encrypt, https://letsencrypt.org/trademarks/")] LetSEncrypt,
        [Description("Letterboxd, https://letterboxd.com/about/logos/")] Letterboxd,
        [Description("LG, https://en.wikipedia.org/wiki/LG_Corporation")] Lg,
        [Description("LGTM, https://lgtm.com/")] Lgtm,
        [Description("Liberapay, https://liberapay.com/assets/liberapay/icon-v2_yellow-r.svg")] Liberapay,
        [Description("LibraryThing, https://twitter.com/LibraryThing/status/1054466649271656448")] LibraryThing,
        [Description("LibreOffice, https://wiki.documentfoundation.org/Marketing/Branding")] LibreOffice,
        [Description("Lighthouse, https://github.com/GoogleChrome/lighthouse/blob/80d2e6c1948f232ec4f1bdeabc8bc632fc5d0bfd/assets/lh_favicon.svg")] Lighthouse,
        [Description("Line, http://line.me/en/logo")] Line,
        [Description("LineageOS, https://www.lineageos.org/")] LineageOs,
        [Description("LINE WEBTOON, http://webtoons.com/")] LineWebtoon,
        [Description("LinkedIn, https://brand.linkedin.com")] LinkedIn,
        [Description("Linode, https://www.linode.com/company/press/")] Linode,
        [Description("Linux, http://www.linuxfoundation.org/about/about-linux")] Linux,
        [Description("Linux Foundation, http://www.linuxfoundation.org/about/about-linux")] LinuxFoundation,
        [Description("Linux Mint, https://commons.wikimedia.org/wiki/File:Linux_Mint_logo_without_wordmark.svg")] LinuxMint,
        [Description("Litecoin, https://litecoin-foundation.org/wp-content/uploads/2019/01/LC18-007-Brand-guidelines.pdf")] Litecoin,
        [Description("LiveJournal, http://www.livejournal.com")] LiveJournal,
        [Description("Livestream, https://livestream.com/press")] Livestream,
        [Description("LLVM, https://llvm.org/Logo.html")] Llvm,
        [Description("LMMS, https://lmms.io/branding")] Lmms,
        [Description("LogMeIn, https://www.logmein.com/")] LogMeIn,
        [Description("Logstash, https://www.elastic.co/brand")] Logstash,
        [Description("Loop, https://loop.frontiersin.org/")] Loop,
        [Description("Lua, https://www.lua.org/docs.html")] Lua,
        [Description("Lufthansa, https://www.lufthansa.com/")] Lufthansa,
        [Description("Lumen, https://lumen.laravel.com/")] Lumen,
        [Description("Lyft, https://www.lyft.com/press")] Lyft,
        [Description("MAAS, https://design.ubuntu.com/downloads/")] Maas,
        [Description("Macy’s, http://www.macysinc.com/press-room/logo-photo-gallery/logos-macys-inc/default.aspx")] MacyS,
        [Description("Magento, http://magento.com")] Magento,
        [Description("Magisk, https://github.com/topjohnwu/Magisk/blob/master/app/src/main/res/drawable/ic_magisk.xml")] Magisk,
        [Description("MailChimp, http://mailchimp.com/about/brand-assets")] MailChimp,
        [Description("Mail.Ru, https://corp.mail.ru/en/press/identity/")] MailRu,
        [Description("MakerBot, http://www.makerbot.com/makerbot-press-assets")] MakerBot,
        [Description("ManageIQ, https://www.manageiq.org/logo/")] ManageIq,
        [Description("Manjaro, https://commons.wikimedia.org/wiki/File:Manjaro-logo.svg")] Manjaro,
        [Description("Mapbox, https://www.mapbox.com/about/press/brand-guidelines")] Mapbox,
        [Description("MariaDB, https://mariadb.com/")] MariaDb,
        [Description("MariaDB Foundation, https://mariadb.org/")] MariaDbFoundation,
        [Description("Markdown, https://github.com/dcurtis/markdown-mark")] Markdown,
        [Description("Marketo, https://www.marketo.com/")] Marketo,
        [Description("MasterCard, https://brand.mastercard.com/brandcenter/mastercard-brand-mark/downloads.html")] MasterCard,
        [Description("Mastodon, https://source.joinmastodon.org/mastodon/joinmastodon/blob/master/public/press-kit.zip")] Mastodon,
        [Description("Material Design, https://material.io/design/")] MaterialDesign,
        [Description("Material Design Icons, https://materialdesignicons.com/icon/vector-square")] MaterialDesignIcons,
        [Description("Material-UI, https://material-ui.com/")] MaterialUi,
        [Description("Mathworks, https://www.mathworks.com/brand/visual-design/mathworks-logo.html")] Mathworks,
        [Description("Matrix, https://matrix.org")] Matrix,
        [Description("Mattermost, https://www.mattermost.org/brand-guidelines/")] Mattermost,
        [Description("Matternet, http://mttr.net")] Matternet,
        [Description("McAfee, https://www.mcafee.com/")] McAfee,
        [Description("MDN Web Docs, https://developer.mozilla.org/")] MdnWebDocs,
        [Description("MediaFire, https://www.mediafire.com/press/")] MediaFire,
        [Description("MediaTemple, https://mediatemple.net/company/about-us")] MediaTemple,
        [Description("Medium, https://medium.design/logos-and-brand-guidelines-f1a01a733592")] Medium,
        [Description("Meetup, https://www.meetup.com/media/")] Meetup,
        [Description("MEGA, https://en.wikipedia.org/wiki/File:01_mega_logo.svg")] Mega,
        [Description("Mendeley, https://www.mendeley.com/")] Mendeley,
        [Description("Mercedes, https://www.mercedes-benz.com/")] Mercedes,
        [Description("Messenger, https://en.facebookbrand.com/assets/messenger/")] Messenger,
        [Description("Meteor, http://logo.meteorapp.com/")] Meteor,
        [Description("micro:bit, https://microbit.org/")] Microbit,
        [Description("Micro.blog, https://twitter.com/BradEllis/status/943956921886715904")] MicroBlog,
        [Description("Microgenetics, http://microgenetics.co.uk/")] Microgenetics,
        [Description("Microsoft, https://ratnacahayarina.files.wordpress.com/2014/03/microsoft.pdf")] Microsoft,
        [Description("Microsoft Access, https://developer.microsoft.com/en-us/fabric#/styles/web/colors/products")] MicrosoftAccess,
        [Description("Microsoft Azure, https://upload.wikimedia.org/wikipedia/commons/a/a8/Microsoft_Azure_Logo.svg")] MicrosoftAzure,
        [Description("Microsoft Edge, https://support.microsoft.com/en-us/help/17171/microsoft-edge-get-to-know")] MicrosoftEdge,
        [Description("Microsoft Excel, https://developer.microsoft.com/en-us/fabric#/styles/web/colors/products")] MicrosoftExcel,
        [Description("Microsoft Office, https://developer.microsoft.com/en-us/microsoft-365")] MicrosoftOffice,
        [Description("Microsoft OneDrive, https://developer.microsoft.com/en-us/fabric#/styles/web/colors/products")] MicrosoftOneDrive,
        [Description("Microsoft OneNote, https://developer.microsoft.com/en-us/fabric#/styles/web/colors/products")] MicrosoftOneNote,
        [Description("Microsoft Outlook, https://developer.microsoft.com/en-us/outlook/docs")] MicrosoftOutlook,
        [Description("Microsoft PowerPoint, https://developer.microsoft.com/en-us/fabric#/styles/web/colors/products")] MicrosoftPowerPoint,
        [Description("Microsoft SQL Server, https://de.wikipedia.org/wiki/Microsoft_SQL_Server")] MicrosoftSqlServer,
        [Description("Microsoft Teams, https://developer.microsoft.com/en-us/fabric#/styles/web/colors/products")] MicrosoftTeams,
        [Description("Microsoft Word, https://developer.microsoft.com/en-us/fabric#/styles/web/colors/products")] MicrosoftWord,
        [Description("MicroStrategy, https://www.microstrategy.com/us/company/press-kit")] MicroStrategy,
        [Description("MIDI, https://en.wikipedia.org/wiki/MIDI")] Midi,
        [Description("Minds, https://www.minds.com/")] Minds,
        [Description("Minetest, https://www.minetest.net/")] Minetest,
        [Description("Minutemailer, https://minutemailer.com/press")] Minutemailer,
        [Description("Mitsubishi, https://www.mitsubishi.com/")] Mitsubishi,
        [Description("Mix, https://mix.com")] Mix,
        [Description("Mixcloud, https://www.mixcloud.com/branding")] Mixcloud,
        [Description("Mixer, https://github.com/mixer/branding-kit/")] Mixer,
        [Description("Mocha, https://mochajs.org/")] Mocha,
        [Description("Mojang, https://www.mojang.com/")] Mojang,
        [Description("Monero, https://getmonero.org")] Monero,
        [Description("MongoDB, https://www.mongodb.com/pressroom")] MongoDb,
        [Description("Monkey tie, https://www.monkey-tie.com/presse")] MonkeyTie,
        [Description("Monogram, http://monogram.me")] Monogram,
        [Description("Monster, https://www.monster.com/")] Monster,
        [Description("Monzo, https://monzo.com/press/")] Monzo,
        [Description("Moo, https://www.moo.com/uk/about/press.html")] Moo,
        [Description("Mozilla, https://mozilla.ninja/our-logo")] Mozilla,
        [Description("Mozilla Firefox, https://mozilla.design/firefox/logos-usage/")] MozillaFirefox,
        [Description("MuseScore, https://musescore.org/en/about/logos-and-graphics")] MuseScore,
        [Description("MX Linux, https://mxlinux.org/art/")] MxLinux,
        [Description("Myspace, https://myspace.com/pressroom/assetslogos")] Myspace,
        [Description("MySQL, https://www.mysql.com/about/legal/logos.html")] MySql,
        [Description("NativeScript, https://docs.nativescript.org/")] NativeScript,
        [Description("NDR, https://www.ndr.de/")] Ndr,
        [Description("NEC, https://commons.wikimedia.org/wiki/File:NEC_logo.svg")] Nec,
        [Description("Neo4j, https://neo4j.com/style-guide/")] Neo4j,
        [Description("Neovim, https://github.com/neovim/neovim.github.io/tree/master/logos")] Neovim,
        [Description("NetApp, http://www.netapp.com/")] NetApp,
        [Description("Netflix, https://commons.wikimedia.org/wiki/File:Netflix_2014_logo.svg")] Netflix,
        [Description("Netlify, https://www.netlify.com/press/")] Netlify,
        [Description("New York Times, https://www.nytimes.com/")] NewYorkTimes,
        [Description("Nextcloud, https://nextcloud.com/press/")] Nextcloud,
        [Description("Nextdoor, https://nextdoor.com/newsroom/")] Nextdoor,
        [Description("Next.js, https://nextjs.org/")] NextJs,
        [Description("NFC, https://nfc-forum.org/our-work/nfc-branding/n-mark/guidelines-and-brand-assets/")] Nfc,
        [Description("NGINX, https://www.nginx.com/")] Nginx,
        [Description("Nim, https://nim-lang.org")] Nim,
        [Description("Nintendo, https://en.wikipedia.org/wiki/Nintendo#/media/File:Nintendo.svg")] Nintendo,
        [Description("Nintendo 3DS, https://www.nintendo.de/")] Nintendo3Ds,
        [Description("Nintendo GameCube, https://www.nintendo.com/consumer/systems/nintendogamecube/index.jsp")] NintendoGameCube,
        [Description("Nintendo Switch, http://www.nintendo.co.uk/")] NintendoSwitch,
        [Description("NixOS, https://github.com/NixOS/nixos-homepage/tree/master/logo")] NixOs,
        [Description("Node.js, https://nodejs.org/en/about/resources/")] NodeJs,
        [Description("Nodemon, https://nodemon.io/")] Nodemon,
        [Description("Node-RED, https://nodered.org/about/resources/")] NodeRed,
        [Description("Nokia, https://www.nokia.com/")] Nokia,
        [Description("Notion, https://www.notion.so/")] Notion,
        [Description("Notist, https://noti.st/")] Notist,
        [Description("NPM, https://github.com/npm/logos")] Npm,
        [Description("Nucleo, https://nucleoapp.com/wp-content/themes/nucleo-webapp-12/img/logo.svg")] Nucleo,
        [Description("NuGet, https://github.com/NuGet/Media")] NuGet,
        [Description("Nuke, https://www.foundry.com/products/nuke")] Nuke,
        [Description("Nutanix, https://www.nutanix.com/content/dam/nutanix/en/cmn/documents/nutanix-brandbook.pdf")] Nutanix,
        [Description("Nuxt.js, https://nuxtjs.org/")] NuxtJs,
        [Description("NVIDIA, https://www.nvidia.com/etc/designs/nvidiaGDC/clientlibs_base/images/NVIDIA-Logo.svg")] Nvidia,
        [Description("OBS Studio, https://upload.wikimedia.org/wikipedia/commons/7/78/OBS.svg")] ObsStudio,
        [Description("OCaml, http://ocaml.org/img/OCaml_Sticker.svg")] OCaml,
        [Description("Octave, https://www.gnu.org/software/octave/")] Octave,
        [Description("Octopus Deploy, https://octopus.com/company/brand")] OctopusDeploy,
        [Description("Oculus, https://www.oculus.com/en-us/press-kit")] Oculus,
        [Description("Odnoklassniki, http://v.ok.ru/logo.html")] Odnoklassniki,
        [Description("OnStar, https://www.onstar.com/")] OnStar,
        [Description("Opel, https://de.wikipedia.org/wiki/Opel")] Opel,
        [Description("Open Access, https://commons.wikimedia.org/wiki/File:Open_Access_logo_PLoS_white.svg")] OpenAccess,
        [Description("OpenAPI Initiative, https://www.openapis.org/faq/style-guide")] OpenApiInitiative,
        [Description("OpenBSD, https://en.wikipedia.org/wiki/OpenBSD")] OpenBsd,
        [Description("Open Collective, https://docs.opencollective.com/help/about#media-logo")] OpenCollective,
        [Description("Open Containers Initiative, https://github.com/opencontainers/artwork/tree/master/oci/icon")] OpenContainersInitiative,
        [Description("OpenGL, https://www.khronos.org/legal/trademarks/")] OpenGl,
        [Description("OpenID, https://openid.net/add-openid/logos/")] OpenId,
        [Description("Open Source Initiative, https://opensource.org/logo-usage-guidelines")] OpenSourceInitiative,
        [Description("OpenSSL, https://www.openssl.org/")] OpenSsl,
        [Description("OpenStreetMap, https://www.openstreetmap.org")] OpenStreetMap,
        [Description("openSUSE, https://en.opensuse.org/Portal:Artwork")] OpenSuse,
        [Description("OpenVPN, https://openvpn.net/wp-content/themes/openvpn/assets/images/logo.svg")] OpenVpn,
        [Description("Opera, https://github.com/operasoftware/logo")] Opera,
        [Description("Opsgenie, https://www.atlassian.com/company/news/press-kit")] Opsgenie,
        [Description("OpsLevel, https://www.opslevel.com/")] OpsLevel,
        [Description("Oracle, https://www.oracle.com/webfolder/s/brand/identity/index.html")] Oracle,
        [Description("ORCID, https://orcid.org/trademark-and-id-display-guidelines")] Orcid,
        [Description("Origin, https://www.origin.com/gbr/en-us/store")] Origin,
        [Description("OSMC, https://github.com/osmc/osmc/tree/master/assets")] Osmc,
        [Description("Overcast, https://overcast.fm")] Overcast,
        [Description("Overleaf, https://www.overleaf.com/for/press/media-resources")] Overleaf,
        [Description("OVH, https://www.ovh.com/fr/news/logo-ovh.xml")] Ovh,
        [Description("Pagekit, https://pagekit.com/logo-guide")] Pagekit,
        [Description("Palantir, https://github.com/palantir/conjure/blob/master/docs/media/palantir-logo.svg")] Palantir,
        [Description("Palo Alto Software, https://press.paloalto.com/logos")] PaloAltoSoftware,
        [Description("Pandora, https://www.pandoraforbrands.com/")] Pandora,
        [Description("Pantheon, https://projects.invisionapp.com/boards/8UOJQWW2J3G5#/1145336")] Pantheon,
        [Description("Parity Substrate, http://substrate.dev/")] ParitySubstrate,
        [Description("Parse.ly, https://www.parse.ly/")] ParseLy,
        [Description("Pastebin, https://pastebin.com/")] Pastebin,
        [Description("Patreon, https://www.patreon.com/brand/downloads")] Patreon,
        [Description("PayPal, https://www.paypal-marketing.com/html/partner/na/portal-v2/pdf/PP_Masterbrandguidelines_v21_mm.pdf")] PayPal,
        [Description("PeerTube, https://github.com/Chocobozzz/PeerTube/tree/develop/client/src/assets/images")] PeerTube,
        [Description("Pepsi, https://commons.wikimedia.org/wiki/File:Pepsi_logo_new.svg")] Pepsi,
        [Description("Periscope, https://www.periscope.tv/press")] Periscope,
        [Description("Peugeot, https://www.groupe-psa.com/en/brands-and-services/peugeot/")] Peugeot,
        [Description("Pexels, https://www.pexels.com/")] Pexels,
        [Description("Photocrowd, https://www.photocrowd.com/")] Photocrowd,
        [Description("PHP, http://php.net/download-logos.php")] Php,
        [Description("Picarto.TV, https://picarto.tv/site/press")] PicartoTv,
        [Description("Pi-hole, https://github.com/pi-hole/web/")] PiHole,
        [Description("Pinboard, https://commons.wikimedia.org/wiki/File:Feedbin-Icon-share-pinboard.svg")] Pinboard,
        [Description("Pingdom, https://tools.pingdom.com")] Pingdom,
        [Description("Pingup, http://pingup.com/resources")] Pingup,
        [Description("Pinterest, https://business.pinterest.com/en/brand-guidelines")] Pinterest,
        [Description("Pivotal Tracker, https://www.pivotaltracker.com/branding-guidelines")] PivotalTracker,
        [Description("Pixabay, https://pixabay.com/service/about/")] Pixabay,
        [Description("PJSIP, https://www.pjsip.org/favicon.ico")] Pjsip,
        [Description("PlanGrid, https://plangrid.com/en/")] PlanGrid,
        [Description("Platzi, https://github.com/PlatziDev/oss/blob/932bd83d43e061e1c38fbc116db31aa6d0145be6/static/logo.svg")] Platzi,
        [Description("Player FM, https://player.fm/")] PlayerFm,
        [Description("Player.me, https://player.me/p/about-us")] PlayerMe,
        [Description("PlayStation, http://uk.playstation.com/media/DPBjbK0o/CECH-4202_4203%20PS3_QSG_GB_Eastern_3_web_vf1.pdf")] PlayStation,
        [Description("PlayStation 2, https://commons.wikimedia.org/wiki/File:PlayStation_2_logo.svg")] PlayStation2,
        [Description("PlayStation 3, https://commons.wikimedia.org/wiki/File:PlayStation_3_Logo_neu.svg#/media/File:PS3.svg")] PlayStation3,
        [Description("PlayStation 4, https://commons.wikimedia.org/wiki/File:PlayStation_4_logo_and_wordmark.svg")] PlayStation4,
        [Description("Pleroma, https://pleroma.social/")] Pleroma,
        [Description("Plesk, https://www.plesk.com/brand/")] Plesk,
        [Description("Plex, http://brand.plex.tv/d/qxmJ3odkK0fj/plex-style-guide")] Plex,
        [Description("Pluralsight, https://www.pluralsight.com/newsroom/brand-assets")] Pluralsight,
        [Description("Plurk, https://www.plurk.com/brandInfo")] Plurk,
        [Description("Pocket, https://getpocket.com/blog/press/")] Pocket,
        [Description("Pocket Casts, https://blog.pocketcasts.com/press/")] PocketCasts,
        [Description("Pokémon, https://commons.wikimedia.org/wiki/File:International_Pok%C3%A9mon_logo.svg")] Pokémon,
        [Description("Poly, https://www.poly.com/")] Poly,
        [Description("Polymer Project, https://github.com/Polymer/polymer-project.org/tree/master/app/images/logos")] PolymerProject,
        [Description("Porsche, https://www.porsche.com/")] Porsche,
        [Description("PostgreSQL, https://wiki.postgresql.org/wiki/Logo")] PostgreSql,
        [Description("Postman, https://www.getpostman.com/resources/media-assets/")] Postman,
        [Description("Postwoman, https://github.com/liyasthomas/postwoman")] Postwoman,
        [Description("PowerShell, https://github.com/PowerShell/PowerShell")] PowerShell,
        [Description("pr.co, https://www.pr.co/")] PrCo,
        [Description("pre-commit, https://github.com/pre-commit/pre-commit.github.io")] PreCommit,
        [Description("PrestaShop, https://www.prestashop.com/en/media-kit")] PrestaShop,
        [Description("Prettier, https://github.com/prettier/prettier-logo/tree/master/images")] Prettier,
        [Description("Prezi, https://prezi.com/press/kit/")] Prezi,
        [Description("Prismic, https://prismic.io/")] Prismic,
        [Description("Probot, https://github.com/probot/probot")] Probot,
        [Description("ProcessWire, https://github.com/processwire")] ProcessWire,
        [Description("Product Hunt, https://www.producthunt.com/branding")] ProductHunt,
        [Description("Prometheus, https://prometheus.io/")] Prometheus,
        [Description("protocols.io, https://www.protocols.io/brand")] ProtocolsIo,
        [Description("Proto.io, https://proto.io/en/presskit")] ProtoIo,
        [Description("ProtonMail, https://protonmail.com/media-kit")] ProtonMail,
        [Description("Proxmox, https://www.proxmox.com/en/news/media-kit")] Proxmox,
        [Description("Publons, https://publons.com/about/logos")] Publons,
        [Description("PureScript, https://github.com/purescript/logo")] PureScript,
        [Description("PyPI, https://pypi.org/")] PyPi,
        [Description("Python, https://www.python.org/community/logos/")] Python,
        [Description("PyTorch, https://github.com/pytorch/pytorch/tree/master/docs/source/_static/img")] PyTorch,
        [Description("PyUp, https://pyup.io/")] PyUp,
        [Description("QEMU, https://wiki.qemu.org/Logo")] Qemu,
        [Description("Qgis, https://www.qgis.org/en/site/getinvolved/styleguide.html")] Qgis,
        [Description("Qi, https://www.wirelesspowerconsortium.com/knowledge-base/retail/qi-logo-guidelines-and-artwork.html")] Qi,
        [Description("Qiita, https://www.qiita.com")] Qiita,
        [Description("QIWI, https://qiwi.com/")] Qiwi,
        [Description("Qualcomm, https://www.qualcomm.com")] Qualcomm,
        [Description("Qualtrics, https://www.qualtrics.com/brand-book/")] Qualtrics,
        [Description("Quantcast, http://branding.quantcast.com/logouse/")] Quantcast,
        [Description("Quantopian, https://www.quantopian.com/about")] Quantopian,
        [Description("Quarkus, https://design.jboss.org/quarkus/")] Quarkus,
        [Description("Quest, https://www.quest.com/legal/trademark-information.aspx")] Quest,
        [Description("QuickTime, https://support.apple.com/quicktime")] QuickTime,
        [Description("Quip, https://quip.com/")] Quip,
        [Description("Quora, https://www.quora.com")] Quora,
        [Description("Qwiklabs, https://www.qwiklabs.com")] Qwiklabs,
        [Description("Qzone, https://qzone.qq.com/")] Qzone,
        [Description("R, https://www.r-project.org/logo/")] R,
        [Description("RabbitMQ, https://www.rabbitmq.com/")] RabbitMq,
        [Description("RadioPublic, https://help.radiopublic.com/hc/en-us/articles/360002546754-RadioPublic-logos")] RadioPublic,
        [Description("Rails, http://rubyonrails.org/images/rails-logo.svg")] Rails,
        [Description("Raspberry Pi, https://www.raspberrypi.org/trademark-rules")] RaspberryPi,
        [Description("React, https://facebook.github.io/react/")] React,
        [Description("ReactOS, https://github.com/reactos/press-media")] ReactOs,
        [Description("React Router, https://reacttraining.com/react-router/")] ReactRouter,
        [Description("Read the Docs, https://github.com/rtfd/readthedocs.org/blob/master/media/readthedocsbranding.ai")] ReadTheDocs,
        [Description("Realm, https://realm.io/press")] Realm,
        [Description("Reason, https://reasonml.github.io/img/reason.svg")] Reason,
        [Description("Reason Studios, https://www.reasonstudios.com/press")] ReasonStudios,
        [Description("Redbubble, https://www.redbubble.com/explore/client/4196122a442ab3f429ec802f71717465.svg")] Redbubble,
        [Description("Reddit, https://www.redditinc.com/brand")] Reddit,
        [Description("Red Hat, https://www.redhat.com/en/about/brand/new-brand/details")] RedHat,
        [Description("Red Hat Open Shift, https://www.openshift.com/")] RedHatOpenShift,
        [Description("Redis, https://redis.io/images/redis-logo.svg")] Redis,
        [Description("Redux, https://github.com/reactjs/redux/tree/master/logo")] Redux,
        [Description("Renren, https://seeklogo.com/vector-logo/184137/renren-inc")] Renren,
        [Description("repl.it, https://repl.it/")] ReplIt,
        [Description("ResearchGate, https://c5.rgstatic.net/m/428059296771819/images/favicon/favicon.svg")] ResearchGate,
        [Description("ReverbNation, https://www.reverbnation.com")] ReverbNation,
        [Description("Rhinoceros, https://www.rhino3d.com/")] Rhinoceros,
        [Description("Riot, https://github.com/vector-im/logos/tree/master/riot")] Riot,
        [Description("Ripple, https://www.ripple.com/media-kit/")] Ripple,
        [Description("Riseup, https://riseup.net/en/about-us/images")] Riseup,
        [Description("rollup.js, https://rollupjs.org/")] RollupJs,
        [Description("Roots, https://roots.io/")] Roots,
        [Description("Roundcube, https://roundcube.net/images/roundcube_logo_icon.svg")] Roundcube,
        [Description("RSS, https://en.wikipedia.org/wiki/Feed_icon")] Rss,
        [Description("RStudio, https://www.rstudio.com/about/logos/")] RStudio,
        [Description("RTLZWEI, https://www.rtl2.de/")] Rtlzwei,
        [Description("Ruby, https://www.ruby-lang.org/en/about/logo/")] Ruby,
        [Description("RubyGems, https://rubygems.org/pages/about")] RubyGems,
        [Description("Runkeeper, https://runkeeper.com/partnerships")] Runkeeper,
        [Description("Rust, https://www.rust-lang.org/")] Rust,
        [Description("Ryanair, https://corporate.ryanair.com/media-centre/stock-images-gallery/#album-container-3")] Ryanair,
        [Description("Safari, https://images.techhive.com/images/article/2014/11/safari-favorites-100530680-large.jpg")] Safari,
        [Description("Sahibinden, https://www.sahibinden.com/favicon.ico")] Sahibinden,
        [Description("Salesforce, https://www.salesforce.com/")] Salesforce,
        [Description("SaltStack, https://www.saltstack.com/resources/brand/")] SaltStack,
        [Description("Samsung, https://www.samsung.com/us")] Samsung,
        [Description("Samsung Pay, https://pay.samsung.com/developers/resource/brand")] SamsungPay,
        [Description("SAP, https://support.sap.com/content/dam/support/sap-logo.svg")] Sap,
        [Description("Sass, http://sass-lang.com/styleguide/brand")] Sass,
        [Description("Sat.1, https://www.prosiebensat1.com/presse/downloads/logos")] Sat1,
        [Description("Sauce Labs, https://saucelabs.com/")] SauceLabs,
        [Description("Scala, https://www.scala-lang.org/")] Scala,
        [Description("Scaleway, https://www.scaleway.com")] Scaleway,
        [Description("Scribd, https://www.scribd.com")] Scribd,
        [Description("Scrutinizer CI, https://scrutinizer-ci.com")] ScrutinizerCi,
        [Description("Seagate, https://www.seagate.com")] Seagate,
        [Description("SEAT, https://www.seat.es/")] Seat,
        [Description("Sega, https://en.wikipedia.org/wiki/Sega#/media/File:Sega_logo.svg")] Sega,
        [Description("Sellfy, https://sellfy.com/about/")] Sellfy,
        [Description("Semantic Web, https://www.w3.org/2007/10/sw-logos.html")] SemanticWeb,
        [Description("Semaphore CI, https://semaphoreci.com/")] SemaphoreCi,
        [Description("Sencha, http://design.sencha.com/")] Sencha,
        [Description("Sensu, https://github.com/sensu/sensu-go/blob/master/dashboard/src/assets/logo/graphic/green.svg")] Sensu,
        [Description("Sentry, https://sentry.io/branding/")] Sentry,
        [Description("Server Fault, http://stackoverflow.com/company/logos")] ServerFault,
        [Description("Serverless, https://serverless.com/")] Serverless,
        [Description("Shazam, https://brandfolder.com/shazam")] Shazam,
        [Description("Shell, https://en.wikipedia.org/wiki/File:Shell_logo.svg")] Shell,
        [Description("Shopify, https://press.shopify.com/brand")] Shopify,
        [Description("Showpad, https://www.showpad.com/")] Showpad,
        [Description("Siemens, https://siemens.com/")] Siemens,
        [Description("Signal, https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms")] Signal,
        [Description("Simple Icons, https://simpleicons.org/")] SimpleIcons,
        [Description("Sina Weibo, https://en.wikipedia.org/wiki/Sina_Weibo")] SinaWeibo,
        [Description("SitePoint, http://www.sitepoint.com")] SitePoint,
        [Description("Sketch, https://www.sketch.com/press/")] Sketch,
        [Description("Skillshare, https://company-89494.frontify.com/d/Tquwc3XMiaBb/skillshare-style-guide")] Skillshare,
        [Description("Skyliner, https://www.skyliner.io/help")] Skyliner,
        [Description("Skype, http://blogs.skype.com/?attachment_id=56273")] Skype,
        [Description("Skype for Business, https://en.wikipedia.org/wiki/Skype_for_Business_Server")] SkypeForBusiness,
        [Description("Slack, https://slack.com/brand-guidelines")] Slack,
        [Description("Slackware, https://en.wikipedia.org/wiki/Slackware")] Slackware,
        [Description("Slashdot, https://commons.wikimedia.org/wiki/File:Slashdot_wordmark_and_logo.svg")] Slashdot,
        [Description("SlickPic, https://www.slickpic.com/")] SlickPic,
        [Description("Slides, https://slides.com/about")] Slides,
        [Description("SmartThings, https://www.smartthings.com/press-kit")] SmartThings,
        [Description("Smashing Magazine, https://www.smashingmagazine.com/")] SmashingMagazine,
        [Description("SmugMug, https://help.smugmug.com/using-smugmug's-logo-HJulJePkEBf")] SmugMug,
        [Description("Snapchat, https://www.snapchat.com/brand-guidelines")] Snapchat,
        [Description("Snapcraft, https://github.com/snapcore/snap-store-badges")] Snapcraft,
        [Description("Snyk, https://snyk.io/press-kit")] Snyk,
        [Description("Society6, https://blog.society6.com/app/themes/society6/dist/images/mark.svg")] Society6,
        [Description("Socket.io, https://socket.io")] SocketIo,
        [Description("Sogou, https://www.sogou.com/")] Sogou,
        [Description("Solus, https://getsol.us/branding/")] Solus,
        [Description("SonarCloud, https://sonarcloud.io/about")] SonarCloud,
        [Description("SonarLint, https://github.com/SonarSource/sonarlint-website/")] SonarLint,
        [Description("SonarQube, https://www.sonarqube.org/logos/")] SonarQube,
        [Description("SonarSource, https://www.sonarsource.com/")] SonarSource,
        [Description("Songkick, http://blog.songkick.com/media-assets")] Songkick,
        [Description("SonicWall, https://brandfolder.com/sonicwall/sonicwall-external")] SonicWall,
        [Description("Sonos, https://www.sonos.com/en-gb/home")] Sonos,
        [Description("SoundCloud, https://soundcloud.com/press")] SoundCloud,
        [Description("Source Engine, https://developer.valvesoftware.com/favicon.ico")] SourceEngine,
        [Description("SourceForge, https://sourceforge.net/")] SourceForge,
        [Description("Sourcegraph, https://github.com/sourcegraph/about")] Sourcegraph,
        [Description("Spacemacs, http://spacemacs.org/")] Spacemacs,
        [Description("SpaceX, https://www.spacex.com/sites/all/themes/spacex2012/images/logo.svg")] SpaceX,
        [Description("SparkFun, https://www.sparkfun.com/brand_assets")] SparkFun,
        [Description("SparkPost, https://www.sparkpost.com/")] SparkPost,
        [Description("SPDX, https://spdx.org/Resources")] Spdx,
        [Description("Speaker Deck, https://speakerdeck.com/")] SpeakerDeck,
        [Description("Spectrum, https://spectrum.chat")] Spectrum,
        [Description("Spinnaker, https://github.com/spinnaker/spinnaker.github.io/tree/master/assets/images")] Spinnaker,
        [Description("Spinrilla, https://spinrilla.com")] Spinrilla,
        [Description("Spotify, https://developer.spotify.com/design")] Spotify,
        [Description("Spotlight, https://www.spotlight.com/")] Spotlight,
        [Description("Spreaker, http://www.spreaker.com/press")] Spreaker,
        [Description("Spring, https://spring.io/trademarks")] Spring,
        [Description("Sprint, https://www.sprint.com/")] Sprint,
        [Description("Square, https://squareup.com/")] Square,
        [Description("Square Enix, https://www.square-enix.com/")] SquareEnix,
        [Description("Squarespace, http://squarespace.com/brand-guidelines")] Squarespace,
        [Description("Stackbit, https://www.stackbit.com/")] Stackbit,
        [Description("Stack Exchange, http://stackoverflow.com/company/logos")] StackExchange,
        [Description("Stack Overflow, http://stackoverflow.com")] StackOverflow,
        [Description("StackPath, https://www.stackpath.com/company/logo-and-branding/")] StackPath,
        [Description("StackShare, https://stackshare.io/branding")] StackShare,
        [Description("Stadia, https://stadia.dev")] Stadia,
        [Description("Staffbase, https://staffbase.com/en/about/press-assets/")] Staffbase,
        [Description("Statamic, http://statamic.com/press")] Statamic,
        [Description("Staticman, https://staticman.net/")] Staticman,
        [Description("Statuspage, https://www.atlassian.com/company/news/press-kit")] Statuspage,
        [Description("Steam, https://partner.steamgames.com/public/marketing/Steam_Guidelines_02102016.pdf")] Steam,
        [Description("Steamworks, https://partner.steamgames.com/")] Steamworks,
        [Description("Steem, https://steem.io/")] Steem,
        [Description("Steemit, https://steemit.com/")] Steemit,
        [Description("Steinberg, https://www.steinberg.net/en/company/press.html")] Steinberg,
        [Description("Stellar, https://www.stellar.org/blog/announcing-the-new-stellar-logo")] Stellar,
        [Description("Stencyl, http://www.stencyl.com/about/press/")] Stencyl,
        [Description("Stitcher, https://www.stitcher.com/")] Stitcher,
        [Description("Storify, https://storify.com")] Storify,
        [Description("Storybook, https://github.com/storybookjs/brand")] Storybook,
        [Description("Strapi, https://strapi.io/")] Strapi,
        [Description("Strava, https://itunes.apple.com/us/app/strava-running-and-cycling-gps/id426826309")] Strava,
        [Description("Stripe, https://stripe.com/about/resources")] Stripe,
        [Description("strongSwan, https://www.strongswan.org/images/")] StrongSwan,
        [Description("StubHub, http://www.stubhub.com")] StubHub,
        [Description("styled-components, https://www.styled-components.com/")] StyledComponents,
        [Description("StyleShare, https://www.stylesha.re/")] StyleShare,
        [Description("Stylus, http://stylus-lang.com/img/stylus-logo.svg")] Stylus,
        [Description("Sublime Text, https://www.sublimetext.com/images/logo.svg")] SublimeText,
        [Description("Subversion, http://subversion.apache.org/logo")] Subversion,
        [Description("Super User, http://stackoverflow.com/company/logos")] SuperUser,
        [Description("Suzuki, https://www.suzuki.ie/")] Suzuki,
        [Description("Svelte, https://github.com/sveltejs/svelte/tree/master/site/static")] Svelte,
        [Description("SVG, https://www.w3.org/2009/08/svg-logos.html")] Svg,
        [Description("SVGO, https://github.com/svg/svgo")] Svgo,
        [Description("Swagger, https://swagger.io/swagger/media/assets/images/swagger_logo.svg")] Swagger,
        [Description("Swarm, https://foursquare.com/about/logos")] Swarm,
        [Description("Swift, https://developer.apple.com/develop/")] Swift,
        [Description("Symantec, https://commons.wikimedia.org/wiki/File:Symantec_logo10.svg")] Symantec,
        [Description("Symfony, https://symfony.com/logo")] Symfony,
        [Description("Symphony, https://symphony.com/")] Symphony,
        [Description("Synology, https://www.synology.com/en-global/company/branding")] Synology,
        [Description("Tableau, https://www.tableau.com/about/media-download-center")] Tableau,
        [Description("Tails, https://tails.boum.org/contribute/how/promote/material/logo/")] Tails,
        [Description("Tailwind CSS, https://tailwindcss.com/")] TailwindCss,
        [Description("Tapas, https://tapas.io/site/about#media")] Tapas,
        [Description("Tata, https://www.tata.com/")] Tata,
        [Description("TeamViewer, https://www.teamviewer.com/resources/images/logos/teamviewer-logo-big.svg")] TeamViewer,
        [Description("TED, https://www.ted.com/participate/organize-a-local-tedx-event/tedx-organizer-guide/branding-promotions/logo-and-design/your-tedx-logo")] Ted,
        [Description("Teespring, https://teespring.com")] Teespring,
        [Description("TELE5, https://www.tele5.de")] Tele5,
        [Description("Telegram, https://commons.wikimedia.org/wiki/File:Telegram_alternative_logo.svg")] Telegram,
        [Description("Tencent QQ, https://en.wikipedia.org/wiki/File:Tencent_QQ.svg#/media/File:Tencent_QQ.svg")] TencentQq,
        [Description("Tencent Weibo, http://t.qq.com/")] TencentWeibo,
        [Description("TensorFlow, https://www.tensorflow.org/extras/tensorflow_brand_guidelines.pdf")] TensorFlow,
        [Description("Teradata, https://github.com/Teradata/teradata.github.io/")] Teradata,
        [Description("Terraform, https://www.hashicorp.com/brand#terraform")] Terraform,
        [Description("Tesla, http://www.teslamotors.com/en_GB/about")] Tesla,
        [Description("The Mighty, https://themighty.com/")] TheMighty,
        [Description("The Movie Database, https://www.themoviedb.org/about/logos-attribution")] TheMovieDatabase,
        [Description("The Register, https://www.theregister.co.uk/")] TheRegister,
        [Description("The Washington Post, https://www.washingtonpost.com/brand-studio/archive/")] TheWashingtonPost,
        [Description("Threema, https://threema.ch/en/press")] Threema,
        [Description("Tidal, https://tidal.com")] Tidal,
        [Description("Tide, https://www.tide.co/newsroom/")] Tide,
        [Description("Tik Tok, https://tiktok.com")] TikTok,
        [Description("Timescale, https://www.timescale.com/")] Timescale,
        [Description("Tinder, http://www.gotinder.com/press")] Tinder,
        [Description("T-Mobile, https://www.t-mobile.com/news/media-library?fulltext=logo")] TMobile,
        [Description("Todoist, https://doist.com/press/")] Todoist,
        [Description("Toggl, https://toggl.com/media-toolkit")] Toggl,
        [Description("Tomorrowland, https://global.tomorrowland.com/")] Tomorrowland,
        [Description("Topcoder, http://topcoder.com/")] Topcoder,
        [Description("Toptal, https://www.toptal.com/branding")] Toptal,
        [Description("Tor, https://github.com/TheTorProject/tor-media/tree/master/Onion%20Icon")] Tor,
        [Description("Toshiba, https://commons.wikimedia.org/wiki/File:Toshiba_logo.svg")] Toshiba,
        [Description("TrainerRoad, https://www.trainerroad.com/")] TrainerRoad,
        [Description("Trakt, https://trakt.tv")] Trakt,
        [Description("Transport for Ireland, https://www.transportforireland.ie/")] TransportForIreland,
        [Description("Travis CI, https://travis-ci.com/logo")] TravisCi,
        [Description("Treehouse, https://teamtreehouse.com/about")] Treehouse,
        [Description("Trello, https://trello.com/about/branding")] Trello,
        [Description("Trend Micro, https://www.trendmicro.com/")] TrendMicro,
        [Description("Tripadvisor, https://tripadvisor.mediaroom.com/logo-guidelines")] Tripadvisor,
        [Description("Trulia, http://www.trulia.com")] Trulia,
        [Description("Trustpilot, https://support.trustpilot.com/hc/en-us/articles/206289947-Trustpilot-Brand-Assets-Style-Guide")] Trustpilot,
        [Description("Try It Online, https://tio.run/")] TryItOnline,
        [Description("Tumblr, https://www.tumblr.com/logo")] Tumblr,
        [Description("Turkish Airlines, https://www.turkishairlines.com/tr-int/basin-odasi/logo-arsivi/index.html")] TurkishAirlines,
        [Description("Twilio, https://www.twilio.com/company/brand")] Twilio,
        [Description("Twitch, https://brand.twitch.tv")] Twitch,
        [Description("Twitter, https://brand.twitter.com")] Twitter,
        [Description("Twoo, http://www.twoo.com/about/press")] Twoo,
        [Description("TypeScript, https://github.com/remojansen/logo.ts")] TypeScript,
        [Description("TYPO3, https://typo3.com/fileadmin/assets/typo3logos/typo3_bullet_01.svg")] Typo3,
        [Description("Uber, https://www.uber.com/media/")] Uber,
        [Description("Uber Eats, https://about.ubereats.com/en/logo/")] UberEats,
        [Description("Ubisoft, https://www.ubisoft.com/en-US/company/overview.aspx")] Ubisoft,
        [Description("uBlock Origin, https://github.com/gorhill/uBlock/blob/master/src/img/ublock.svg")] UBlockOrigin,
        [Description("Ubuntu, https://design.ubuntu.com/brand/ubuntu-logo/")] Ubuntu,
        [Description("Udacity, https://www.udacity.com")] Udacity,
        [Description("Udemy, https://about.udemy.com/newbrand/")] Udemy,
        [Description("UIkit, https://getuikit.com")] UIkit,
        [Description("Umbraco, https://umbraco.com/")] Umbraco,
        [Description("Unicode, https://en.wikipedia.org/wiki/Unicode")] Unicode,
        [Description("Unity, https://unity.com/")] Unity,
        [Description("Unreal Engine, https://www.unrealengine.com/en-US/branding")] UnrealEngine,
        [Description("Unsplash, https://unsplash.com/")] Unsplash,
        [Description("Untangle, https://www.untangle.com/company-overview/")] Untangle,
        [Description("Untappd, https://untappd.com/")] Untappd,
        [Description("Upwork, https://www.upwork.com/press/")] Upwork,
        [Description("V, https://github.com/vlang/v-logo")] V,
        [Description("V8, https://v8.dev/logo")] V8,
        [Description("Vagrant, https://www.hashicorp.com/brand#vagrant")] Vagrant,
        [Description("Valve, https://www.valvesoftware.com/")] Valve,
        [Description("Veeam, https://www.veeam.com/newsroom/veeam-graphics.html")] Veeam,
        [Description("Venmo, https://venmo.com/about/brand/")] Venmo,
        [Description("Veritas, https://my.veritas.com/cs/groups/partner/documents/styleguide/mdaw/mdq5/~edisp/tus3cpeapp3855186572.pdf")] Veritas,
        [Description("Verizon, https://www.verizondigitalmedia.com/about/logo-usage/")] Verizon,
        [Description("Viadeo, http://corporate.viadeo.com/en/media/resources")] Viadeo,
        [Description("Viber, https://www.viber.com/brand-center/")] Viber,
        [Description("Vim, https://commons.wikimedia.org/wiki/File:Vimlogo.svg")] Vim,
        [Description("Vimeo, https://vimeo.com/about/brand_guidelines")] Vimeo,
        [Description("Vine, https://vine.co/logo")] Vine,
        [Description("Virb, http://virb.com/about")] Virb,
        [Description("Visa, https://commons.wikimedia.org/wiki/File:Visa_2014_logo_detail.svg")] Visa,
        [Description("Visual Studio, https://visualstudio.microsoft.com/")] VisualStudio,
        [Description("Visual Studio Code, https://commons.wikimedia.org/wiki/File:Visual_Studio_Code_1.35_icon.svg")] VisualStudioCode,
        [Description("Vivino, https://www.vivino.com/press")] Vivino,
        [Description("VK, https://vk.com/brand")] Vk,
        [Description("VLC media player, http://git.videolan.org/?p=vlc.git;a=tree;f=extras/package/macosx/asset_sources")] VlcMediaPlayer,
        [Description("VMware, https://myvmware.workspaceair.com/")] VMware,
        [Description("Vodafone, https://web.vodafone.com.eg/")] Vodafone,
        [Description("Volkswagen, https://www.volkswagen.ie/")] Volkswagen,
        [Description("VSCO, https://vsco.co/about/press/vsco-releases-redesigned-mobile-app")] Vsco,
        [Description("Vue.js, https://github.com/vuejs/art")] VueJs,
        [Description("Vuetify, https://vuetifyjs.com/")] Vuetify,
        [Description("Vulkan, https://www.khronos.org/legal/trademarks/")] Vulkan,
        [Description("W3C, https://www.w3.org/Consortium/Legal/logo-usage-20000308")] W3C,
        [Description("Wattpad, https://www.wattpad.com/press/#assets")] Wattpad,
        [Description("Waze, https://www.waze.com/")] Waze,
        [Description("Wear OS, https://partnermarketinghub.withgoogle.com/#/brands/")] WearOs,
        [Description("Weasyl, https://www.weasyl.com/")] Weasyl,
        [Description("WebAssembly, https://webassembly.org/")] WebAssembly,
        [Description("WebAuthn, https://github.com/apowers313/webauthn-logos")] WebAuthn,
        [Description("webcomponents.org, https://www.webcomponents.org/")] WebcomponentsOrg,
        [Description("WebGL, https://www.khronos.org/legal/trademarks/")] WebGl,
        [Description("Webmin, https://github.com/webmin/webmin")] Webmin,
        [Description("Webpack, https://webpack.js.org/branding/")] Webpack,
        [Description("WebRTC, https://webrtc.org/press/")] WebRtc,
        [Description("WebStorm, https://www.jetbrains.com/company/brand/logos/")] WebStorm,
        [Description("WeChat, https://worldvectorlogo.com/logo/wechat-3")] WeChat,
        [Description("WhatsApp, https://www.whatsappbrand.com")] WhatsApp,
        [Description("When I Work, https://wheniwork.com/")] WhenIWork,
        [Description("WhiteSource, https://www.whitesourcesoftware.com/whitesource-media-kit/")] WhiteSource,
        [Description("Wii, https://de.wikipedia.org/wiki/Datei:WiiU.svg")] Wii,
        [Description("Wii U, https://de.wikipedia.org/wiki/Datei:WiiU.svg")] WiiU,
        [Description("Wikipedia, https://en.wikipedia.org/wiki/Logo_of_Wikipedia")] Wikipedia,
        [Description("Windows, https://commons.wikimedia.org/wiki/File:Windows_10_Logo.svg")] Windows,
        [Description("Wire, http://brand.wire.com")] Wire,
        [Description("WireGuard, https://www.wireguard.com/img/wireguard.svg")] WireGuard,
        [Description("Wish, https://wish.com/")] Wish,
        [Description("Wix, http://www.wix.com/about/design-assets")] Wix,
        [Description("Wolfram, http://company.wolfram.com/press-center/wolfram-corporate/")] Wolfram,
        [Description("Wolfram Language, http://company.wolfram.com/press-center/language/")] WolframLanguage,
        [Description("Wolfram Mathematica, http://company.wolfram.com/press-center/mathematica/")] WolframMathematica,
        [Description("Woo, https://woocommerce.com/style-guide/")] Woo,
        [Description("WooCommerce, https://woocommerce.com/style-guide/")] WooCommerce,
        [Description("WordPress, https://wordpress.org/about/logos")] WordPress,
        [Description("Workplace, https://en.facebookbrand.com/")] Workplace,
        [Description("WP Engine, https://wpengine.com/")] WpEngine,
        [Description("WP Rocket, https://wp-rocket.me/")] WpRocket,
        [Description("write.as, https://write.as/brand")] WriteAs,
        [Description("Xamarin, https://github.com/dotnet/swag/tree/master/xamarin")] Xamarin,
        [Description("XAML, https://github.com/microsoft/microsoft-ui-xaml/issues/1185")] Xaml,
        [Description("XAMPP, https://www.apachefriends.org/en/")] Xampp,
        [Description("Xbox, http://mspartner-public.sharepoint.com/XBOX%20Games/Xbox%20logo's%20+%20Guidelines/Xbox%20Live/Xbox_Live_Guidelines_10-4-13.pdf")] Xbox,
        [Description("Xcode, https://developer.apple.com/develop/")] Xcode,
        [Description("XDA Developers, https://www.xda-developers.com/")] XdaDevelopers,
        [Description("Xero, https://www.xero.com/uk/about/media/downloads")] Xero,
        [Description("XFCE, https://www.xfce.org/download#artwork")] Xfce,
        [Description("Xiaomi, https://www.mi.com/global")] Xiaomi,
        [Description("Xing, https://dev.xing.com/logo_rules")] Xing,
        [Description("XMPP, https://commons.wikimedia.org/wiki/File:XMPP_logo.svg")] Xmpp,
        [Description("X.Org, https://upload.wikimedia.org/wikipedia/commons/9/90/X.Org_Logo.svg")] XOrg,
        [Description("X-Pack, https://www.elastic.co/brand")] XPack,
        [Description("XRP, https://xrpl.org/")] Xrp,
        [Description("XSplit, https://www.xsplit.com/presskit")] XSplit,
        [Description("Yahoo!, https://yahoo.com/")] Yahoo,
        [Description("Yamaha Corporation, https://www.yamaha.com/en/")] YamahaCorporation,
        [Description("Yamaha Motor Corporation, https://en.wikipedia.org/wiki/Yamaha_Motor_Company")] YamahaMotorCorporation,
        [Description("Yammer, https://developer.yammer.com/docs/branding-guide")] Yammer,
        [Description("Yandex, https://yandex.com/company/general_info/logotype_rules")] Yandex,
        [Description("Yarn, https://github.com/yarnpkg/assets")] Yarn,
        [Description("Y Combinator, https://www.ycombinator.com/press/")] YCombinator,
        [Description("Yelp, http://www.yelp.com/brand")] Yelp,
        [Description("YouTube, https://www.youtube.com/yt/about/brand-resources/#logos-icons-colors")] YouTube,
        [Description("YouTube Gaming, https://gaming.youtube.com/")] YouTubeGaming,
        [Description("YouTube Studio, https://www.youtube.com/")] YouTubeStudio,
        [Description("YouTube TV, https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.unplugged")] YouTubeTv,
        [Description("Zalando, https://www.zalando.co.uk/")] Zalando,
        [Description("Zapier, https://zapier.com/about/brand")] Zapier,
        [Description("ZDF, https://www.zdf.de/")] Zdf,
        [Description("Zeit, https://zeit.co/design/brand")] Zeit,
        [Description("Zend, https://www.zend.com/")] Zend,
        [Description("Zendesk, https://www.zendesk.com/company/brand-assets/#logo")] Zendesk,
        [Description("Zend Framework, https://framework.zend.com/")] ZendFramework,
        [Description("ZeroMQ, https://github.com/zeromq/zeromq.org/blob/master/static/safari-pinned-tab.svg")] ZeroMq,
        [Description("Zerply, https://zerply.com/about/resources")] Zerply,
        [Description("Zhihu, https://www.zhihu.com/")] Zhihu,
        [Description("Zigbee, https://zigbeealliance.org/solution/zigbee/")] Zigbee,
        [Description("Zillow, http://zillow.mediaroom.com/logos")] Zillow,
        [Description("Zingat, https://www.zingat.com/kurumsal-logolar")] Zingat,
        [Description("Zoom, https://zoom.us/brandguidelines")] Zoom,
        [Description("Zorin, https://zorinos.com/press/")] Zorin,
        [Description("Zulip, https://github.com/zulip/zulip/")] Zulip,
        [Description("Z-Wave, https://www.z-wave.com/")] ZWave,
    }
}