namespace MahApps.Metro.IconPacks
{
#if NETFX_CORE
    //using MahApps.Metro.IconPacks.Core;
#else
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconFontAwesome" />.
    /// </summary>
    /// <remarks>
    /// All icons sourced from FontAwesome Icons Font v4.6.3 - <see><cref>http://fontawesome.io</cref></see> - 
    /// <see><cref>https://github.com/FortAwesome/Font-Awesome</cref></see>.
    /// </remarks>
    public enum PackIconFontAwesomeKind
    {
        [Description("Empty placeholder")] None,
        [Description("500px (f26e)")] _500pxBrands,
        [Description("Accessible Icon (f368, accessibility, handicap, person, wheelchair, wheelchair-alt)")] AccessibleIconBrands,
        [Description("Accusoft (f369)")] AccusoftBrands,
        [Description("Address Book (f2b9)")] AddressBookRegular,
        [Description("Address Book (f2b9)")] AddressBookSolid,
        [Description("Address Card (f2bb)")] AddressCardRegular,
        [Description("Address Card (f2bb)")] AddressCardSolid,
        [Description("adjust (f042, contrast)")] AdjustSolid,
        [Description("App.net (f170)")] AdnBrands,
        [Description("Adversal (f36a)")] AdversalBrands,
        [Description("affiliatetheme (f36b)")] AffiliatethemeBrands,
        [Description("Algolia (f36c)")] AlgoliaBrands,
        [Description("align-center (f037, middle, text)")] AlignCenterSolid,
        [Description("align-justify (f039, text)")] AlignJustifySolid,
        [Description("align-left (f036, text)")] AlignLeftSolid,
        [Description("align-right (f038, text)")] AlignRightSolid,
        [Description("Allergies (f461, freckles, hand, intolerances, pox, spots)")] AllergiesSolid,
        [Description("Amazon (f270)")] AmazonBrands,
        [Description("Amazon Pay (f42c)")] AmazonPayBrands,
        [Description("ambulance (f0f9, help, machine, support, vehicle)")] AmbulanceSolid,
        [Description("American Sign Language Interpreting (f2a3)")] AmericanSignLanguageInterpretingSolid,
        [Description("Amilia (f36d)")] AmiliaBrands,
        [Description("Anchor (f13d, link)")] AnchorSolid,
        [Description("Android (f17b, robot)")] AndroidBrands,
        [Description("AngelList (f209)")] AngellistBrands,
        [Description("Angle Double Down (f103, arrows)")] AngleDoubleDownSolid,
        [Description("Angle Double Left (f100, arrows, back, laquo, previous, quote)")] AngleDoubleLeftSolid,
        [Description("Angle Double Right (f101, arrows, forward, next, quote, raquo)")] AngleDoubleRightSolid,
        [Description("Angle Double Up (f102, arrows)")] AngleDoubleUpSolid,
        [Description("angle-down (f107, arrow)")] AngleDownSolid,
        [Description("angle-left (f104, arrow, back, previous)")] AngleLeftSolid,
        [Description("angle-right (f105, arrow, forward, next)")] AngleRightSolid,
        [Description("angle-up (f106, arrow)")] AngleUpSolid,
        [Description("Angry Creative (f36e)")] AngrycreativeBrands,
        [Description("Angry Face (f556)")] AngryRegular,
        [Description("Angry Face (f556)")] AngrySolid,
        [Description("Angular (f420)")] AngularBrands,
        [Description("Apper Systems AB (f371)")] ApperBrands,
        [Description("Apple (f179, food, fruit, osx)")] AppleBrands,
        [Description("Apple Pay (f415)")] ApplePayBrands,
        [Description("App Store (f36f)")] AppStoreBrands,
        [Description("iOS App Store (f370)")] AppStoreIosBrands,
        [Description("Archive (f187, box, package, storage)")] ArchiveSolid,
        [Description("Archway (f557, monument, road, street)")] ArchwaySolid,
        [Description("Alternate Arrow Circle Down (f358, arrow-circle-o-down, download)")] ArrowAltCircleDownRegular,
        [Description("Alternate Arrow Circle Down (f358, arrow-circle-o-down, download)")] ArrowAltCircleDownSolid,
        [Description("Alternate Arrow Circle Left (f359, arrow-circle-o-left, back, previous)")] ArrowAltCircleLeftRegular,
        [Description("Alternate Arrow Circle Left (f359, arrow-circle-o-left, back, previous)")] ArrowAltCircleLeftSolid,
        [Description("Alternate Arrow Circle Right (f35a, arrow-circle-o-right, forward, next)")] ArrowAltCircleRightRegular,
        [Description("Alternate Arrow Circle Right (f35a, arrow-circle-o-right, forward, next)")] ArrowAltCircleRightSolid,
        [Description("Alternate Arrow Circle Up (f35b, arrow-circle-o-up)")] ArrowAltCircleUpRegular,
        [Description("Alternate Arrow Circle Up (f35b, arrow-circle-o-up)")] ArrowAltCircleUpSolid,
        [Description("Arrow Circle Down (f0ab, download)")] ArrowCircleDownSolid,
        [Description("Arrow Circle Left (f0a8, back, previous)")] ArrowCircleLeftSolid,
        [Description("Arrow Circle Right (f0a9, forward, next)")] ArrowCircleRightSolid,
        [Description("Arrow Circle Up (f0aa)")] ArrowCircleUpSolid,
        [Description("arrow-down (f063, download)")] ArrowDownSolid,
        [Description("arrow-left (f060, back, previous)")] ArrowLeftSolid,
        [Description("arrow-right (f061, forward, next)")] ArrowRightSolid,
        [Description("Alternate Arrows Horizontal (f337, arrows-h, resize)")] ArrowsAltHSolid,
        [Description("Alternate Arrows (f0b2, arrow, arrows, bigger, enlarge, expand, fullscreen, move, position, reorder, resize)")] ArrowsAltSolid,
        [Description("Alternate Arrows Vertical (f338, arrows-v, resize)")] ArrowsAltVSolid,
        [Description("arrow-up (f062)")] ArrowUpSolid,
        [Description("Assistive Listening Systems (f2a2)")] AssistiveListeningSystemsSolid,
        [Description("asterisk (f069, details)")] AsteriskSolid,
        [Description("Asymmetrik, Ltd. (f372)")] AsymmetrikBrands,
        [Description("Atlas (f558, book, geography, map, wayfinding)")] AtlasSolid,
        [Description("At (f1fa, e-mail, email)")] AtSolid,
        [Description("Audible (f373)")] AudibleBrands,
        [Description("Audio Description (f29e)")] AudioDescriptionSolid,
        [Description("Autoprefixer (f41c)")] AutoprefixerBrands,
        [Description("avianex (f374)")] AvianexBrands,
        [Description("Aviato (f421)")] AviatoBrands,
        [Description("Award (f559)")] AwardSolid,
        [Description("Amazon Web Services (AWS) (f375)")] AwsBrands,
        [Description("Backspace (f55a, command, delete, keyboard, undo)")] BackspaceSolid,
        [Description("backward (f04a, previous, rewind)")] BackwardSolid,
        [Description("Balance Scale (f24e, balanced, justice, legal, measure, weight)")] BalanceScaleSolid,
        [Description("Band-Aid (f462, bandage, boo boo, ouch)")] BandAidSolid,
        [Description("Bandcamp (f2d5)")] BandcampBrands,
        [Description("ban (f05e, abort, ban, block, cancel, delete, hide, prohibit, remove, stop, trash)")] BanSolid,
        [Description("barcode (f02a, scan)")] BarcodeSolid,
        [Description("Bars (f0c9, checklist, drag, hamburger, list, menu, nav, navigation, ol, reorder, settings, todo, ul)")] BarsSolid,
        [Description("Baseball Ball (f433)")] BaseballBallSolid,
        [Description("Basketball Ball (f434)")] BasketballBallSolid,
        [Description("Bath (f2cd)")] BathSolid,
        [Description("Battery Empty (f244, power, status)")] BatteryEmptySolid,
        [Description("Battery Full (f240, power, status)")] BatteryFullSolid,
        [Description("Battery 1/2 Full (f242, power, status)")] BatteryHalfSolid,
        [Description("Battery 1/4 Full (f243, power, status)")] BatteryQuarterSolid,
        [Description("Battery 3/4 Full (f241, power, status)")] BatteryThreeQuartersSolid,
        [Description("Bed (f236, travel)")] BedSolid,
        [Description("beer (f0fc, alcohol, bar, drink, liquor, mug, stein)")] BeerSolid,
        [Description("Behance (f1b4)")] BehanceBrands,
        [Description("Behance Square (f1b5)")] BehanceSquareBrands,
        [Description("bell (f0f3, alert, notification, reminder)")] BellRegular,
        [Description("Bell Slash (f1f6)")] BellSlashRegular,
        [Description("Bell Slash (f1f6)")] BellSlashSolid,
        [Description("bell (f0f3, alert, notification, reminder)")] BellSolid,
        [Description("Bezier Curve (f55b, curves, illustrator, lines, path, vector)")] BezierCurveSolid,
        [Description("Bicycle (f206, bike, gears, transportation, vehicle)")] BicycleSolid,
        [Description("BIMobject (f378)")] BimobjectBrands,
        [Description("Binoculars (f1e5)")] BinocularsSolid,
        [Description("Birthday Cake (f1fd)")] BirthdayCakeSolid,
        [Description("Bitbucket (f171, bitbucket-square, git)")] BitbucketBrands,
        [Description("Bitcoin (f379)")] BitcoinBrands,
        [Description("Bity (f37a)")] BityBrands,
        [Description("BlackBerry (f37b)")] BlackberryBrands,
        [Description("Font Awesome Black Tie (f27e)")] BlackTieBrands,
        [Description("Blender (f517)")] BlenderSolid,
        [Description("Blind (f29d)")] BlindSolid,
        [Description("Blogger B (f37d)")] BloggerBBrands,
        [Description("Blogger (f37c)")] BloggerBrands,
        [Description("Bluetooth (f294)")] BluetoothBBrands,
        [Description("Bluetooth (f293)")] BluetoothBrands,
        [Description("bold (f032)")] BoldSolid,
        [Description("Lightning Bolt (f0e7, electricity, lightning, weather, zap)")] BoltSolid,
        [Description("Bomb (f1e2)")] BombSolid,
        [Description("Bong (f55c, aparatus, cannabis, marijuana, pipe, smoke, smoking)")] BongSolid,
        [Description("bookmark (f02e, save)")] BookmarkRegular,
        [Description("bookmark (f02e, save)")] BookmarkSolid,
        [Description("Book Open (f518, notebook, open book, reading)")] BookOpenSolid,
        [Description("book (f02d, documentation, read)")] BookSolid,
        [Description("Bowling Ball (f436)")] BowlingBallSolid,
        [Description("Boxes (f468)")] BoxesSolid,
        [Description("Box Open (f49e)")] BoxOpenSolid,
        [Description("Box (f466, package)")] BoxSolid,
        [Description("Braille (f2a1)")] BrailleSolid,
        [Description("Medical Briefcase (f469, health briefcase)")] BriefcaseMedicalSolid,
        [Description("Briefcase (f0b1, bag, business, luggage, office, work)")] BriefcaseSolid,
        [Description("Broadcast Tower (f519, airwaves, radio, waves)")] BroadcastTowerSolid,
        [Description("Broom (f51a)")] BroomSolid,
        [Description("Brush (f55d, bristles, color, painting)")] BrushSolid,
        [Description("BTC (f15a)")] BtcBrands,
        [Description("Bug (f188, insect, report)")] BugSolid,
        [Description("Building (f1ad, apartment, business, company, office, work)")] BuildingRegular,
        [Description("Building (f1ad, apartment, business, company, office, work)")] BuildingSolid,
        [Description("bullhorn (f0a1, announcement, broadcast, louder, megaphone, share)")] BullhornSolid,
        [Description("Bullseye (f140, target)")] BullseyeSolid,
        [Description("Burn (f46a, energy)")] BurnSolid,
        [Description("Büromöbel-Experte GmbH & Co. KG. (f37f)")] BuromobelexperteBrands,
        [Description("Bus Alt (f55e, machine, public transportation, transportation, vehicle)")] BusAltSolid,
        [Description("Bus (f207, machine, public transportation, transportation, vehicle)")] BusSolid,
        [Description("BuySellAds (f20d)")] BuyselladsBrands,
        [Description("Calculator (f1ec)")] CalculatorSolid,
        [Description("Alternate Calendar (f073, calendar, date, event, schedule, time, when)")] CalendarAltRegular,
        [Description("Alternate Calendar (f073, calendar, date, event, schedule, time, when)")] CalendarAltSolid,
        [Description("Calendar Check (f274, accept, agree, appointment, confirm, correct, done, ok, select, success, todo)")] CalendarCheckRegular,
        [Description("Calendar Check (f274, accept, agree, appointment, confirm, correct, done, ok, select, success, todo)")] CalendarCheckSolid,
        [Description("Calendar Minus (f272)")] CalendarMinusRegular,
        [Description("Calendar Minus (f272)")] CalendarMinusSolid,
        [Description("Calendar Plus (f271)")] CalendarPlusRegular,
        [Description("Calendar Plus (f271)")] CalendarPlusSolid,
        [Description("Calendar (f133, calendar-o, date, event, schedule, time, when)")] CalendarRegular,
        [Description("Calendar (f133, calendar-o, date, event, schedule, time, when)")] CalendarSolid,
        [Description("Calendar Times (f273)")] CalendarTimesRegular,
        [Description("Calendar Times (f273)")] CalendarTimesSolid,
        [Description("Retro Camera (f083, photo, picture, record)")] CameraRetroSolid,
        [Description("camera (f030, photo, picture, record)")] CameraSolid,
        [Description("Cannabis (f55f, bud, chronic, drugs, endica, endo, ganja, marijuana, mary jane, pot, reefer, sativa, spliff, weed, whacky-tabacky)")] CannabisSolid,
        [Description("Capsules (f46b, drugs, medicine)")] CapsulesSolid,
        [Description("Caret Down (f0d7, arrow, dropdown, menu, more, triangle down)")] CaretDownSolid,
        [Description("Caret Left (f0d9, arrow, back, previous, triangle left)")] CaretLeftSolid,
        [Description("Caret Right (f0da, arrow, forward, next, triangle right)")] CaretRightSolid,
        [Description("Caret Square Down (f150, caret-square-o-down, dropdown, menu, more)")] CaretSquareDownRegular,
        [Description("Caret Square Down (f150, caret-square-o-down, dropdown, menu, more)")] CaretSquareDownSolid,
        [Description("Caret Square Left (f191, back, caret-square-o-left, previous)")] CaretSquareLeftRegular,
        [Description("Caret Square Left (f191, back, caret-square-o-left, previous)")] CaretSquareLeftSolid,
        [Description("Caret Square Right (f152, caret-square-o-right, forward, next)")] CaretSquareRightRegular,
        [Description("Caret Square Right (f152, caret-square-o-right, forward, next)")] CaretSquareRightSolid,
        [Description("Caret Square Up (f151, caret-square-o-up)")] CaretSquareUpRegular,
        [Description("Caret Square Up (f151, caret-square-o-up)")] CaretSquareUpSolid,
        [Description("Caret Up (f0d8, arrow, triangle up)")] CaretUpSolid,
        [Description("Car (f1b9, machine, transportation, vehicle)")] CarSolid,
        [Description("Shopping Cart Arrow Down (f218, shopping)")] CartArrowDownSolid,
        [Description("Add to Shopping Cart (f217, add, shopping)")] CartPlusSolid,
        [Description("Amazon Pay Credit Card (f42d)")] CcAmazonPayBrands,
        [Description("American Express Credit Card (f1f3, amex)")] CcAmexBrands,
        [Description("Apple Pay Credit Card (f416)")] CcApplePayBrands,
        [Description("Diner's Club Credit Card (f24c)")] CcDinersClubBrands,
        [Description("Discover Credit Card (f1f2)")] CcDiscoverBrands,
        [Description("JCB Credit Card (f24b)")] CcJcbBrands,
        [Description("MasterCard Credit Card (f1f1)")] CcMastercardBrands,
        [Description("Paypal Credit Card (f1f4)")] CcPaypalBrands,
        [Description("Stripe Credit Card (f1f5)")] CcStripeBrands,
        [Description("Visa Credit Card (f1f0)")] CcVisaBrands,
        [Description("Centercode (f380)")] CentercodeBrands,
        [Description("certificate (f0a3, badge, star)")] CertificateSolid,
        [Description("Chalkboard (f51b, blackboard, learning, school, teaching, whiteboard, writing)")] ChalkboardSolid,
        [Description("Chalkboard Teacher (f51c, blackboard, instructor, learning, professor, school, whiteboard, writing)")] ChalkboardTeacherSolid,
        [Description("Area Chart (f1fe, analytics, area-chart, graph)")] ChartAreaSolid,
        [Description("Bar Chart (f080, analytics, bar-chart, graph)")] ChartBarRegular,
        [Description("Bar Chart (f080, analytics, bar-chart, graph)")] ChartBarSolid,
        [Description("Line Chart (f201, activity, analytics, dashboard, graph, line-chart)")] ChartLineSolid,
        [Description("Pie Chart (f200, analytics, graph, pie-chart)")] ChartPieSolid,
        [Description("Check Circle (f058, accept, agree, confirm, correct, done, ok, select, success, todo, yes)")] CheckCircleRegular,
        [Description("Check Circle (f058, accept, agree, confirm, correct, done, ok, select, success, todo, yes)")] CheckCircleSolid,
        [Description("Check Double (f560)")] CheckDoubleSolid,
        [Description("Check (f00c, accept, agree, checkmark, confirm, correct, done, notice, notification, notify, ok, select, success, tick, todo, yes)")] CheckSolid,
        [Description("Check Square (f14a, accept, agree, checkmark, confirm, correct, done, ok, select, success, todo, yes)")] CheckSquareRegular,
        [Description("Check Square (f14a, accept, agree, checkmark, confirm, correct, done, ok, select, success, todo, yes)")] CheckSquareSolid,
        [Description("Chess Bishop (f43a)")] ChessBishopSolid,
        [Description("Chess Board (f43c)")] ChessBoardSolid,
        [Description("Chess King (f43f)")] ChessKingSolid,
        [Description("Chess Knight (f441)")] ChessKnightSolid,
        [Description("Chess Pawn (f443)")] ChessPawnSolid,
        [Description("Chess Queen (f445)")] ChessQueenSolid,
        [Description("Chess Rook (f447)")] ChessRookSolid,
        [Description("Chess (f439)")] ChessSolid,
        [Description("Chevron Circle Down (f13a, arrow, dropdown, menu, more)")] ChevronCircleDownSolid,
        [Description("Chevron Circle Left (f137, arrow, back, previous)")] ChevronCircleLeftSolid,
        [Description("Chevron Circle Right (f138, arrow, forward, next)")] ChevronCircleRightSolid,
        [Description("Chevron Circle Up (f139, arrow)")] ChevronCircleUpSolid,
        [Description("chevron-down (f078)")] ChevronDownSolid,
        [Description("chevron-left (f053, back, bracket, previous)")] ChevronLeftSolid,
        [Description("chevron-right (f054, bracket, forward, next)")] ChevronRightSolid,
        [Description("chevron-up (f077)")] ChevronUpSolid,
        [Description("Child (f1ae)")] ChildSolid,
        [Description("Chrome (f268, browser)")] ChromeBrands,
        [Description("Church (f51d, building, community, religion)")] ChurchSolid,
        [Description("Circle Notched (f1ce, circle-o-notch)")] CircleNotchSolid,
        [Description("Circle (f111, circle-thin, dot, notification)")] CircleRegular,
        [Description("Circle (f111, circle-thin, dot, notification)")] CircleSolid,
        [Description("Clipboard Check (f46c, accept, agree, confirm, done, ok, select, success, todo, yes)")] ClipboardCheckSolid,
        [Description("Clipboard List (f46d, checklist, completed, done, finished, intinerary, ol, schedule, todo, ul)")] ClipboardListSolid,
        [Description("Clipboard (f328, paste)")] ClipboardRegular,
        [Description("Clipboard (f328, paste)")] ClipboardSolid,
        [Description("Clock (f017, date, late, schedule, timer, timestamp, watch)")] ClockRegular,
        [Description("Clock (f017, date, late, schedule, timer, timestamp, watch)")] ClockSolid,
        [Description("Clone (f24d, copy, duplicate)")] CloneRegular,
        [Description("Clone (f24d, copy, duplicate)")] CloneSolid,
        [Description("Closed Captioning (f20a, cc)")] ClosedCaptioningRegular,
        [Description("Closed Captioning (f20a, cc)")] ClosedCaptioningSolid,
        [Description("Alternate Cloud Download (f381, cloud-download)")] CloudDownloadAltSolid,
        [Description("cloudscale.ch (f383)")] CloudscaleBrands,
        [Description("Cloudsmith (f384)")] CloudsmithBrands,
        [Description("Cloud (f0c2, save)")] CloudSolid,
        [Description("Alternate Cloud Upload (f382, cloud-upload)")] CloudUploadAltSolid,
        [Description("cloudversify (f385)")] CloudversifyBrands,
        [Description("Cocktail (f561, alcohol, drink)")] CocktailSolid,
        [Description("Code Branch (f126, branch, code-fork, fork, git, github, rebase, svn, vcs, version)")] CodeBranchSolid,
        [Description("Codepen (f1cb)")] CodepenBrands,
        [Description("Code (f121, brackets, html)")] CodeSolid,
        [Description("Codie Pie (f284)")] CodiepieBrands,
        [Description("Coffee (f0f4, breakfast, cafe, drink, morning, mug, tea)")] CoffeeSolid,
        [Description("cog (f013, settings)")] CogSolid,
        [Description("cogs (f085, gears, settings)")] CogsSolid,
        [Description("Coins (f51e)")] CoinsSolid,
        [Description("Columns (f0db, dashboard, panes, split)")] ColumnsSolid,
        [Description("Alternate Comment (f27a, bubble, chat, commenting, commenting, conversation, feedback, message, note, notification, sms, speech, texting)")] CommentAltRegular,
        [Description("Alternate Comment (f27a, bubble, chat, commenting, commenting, conversation, feedback, message, note, notification, sms, speech, texting)")] CommentAltSolid,
        [Description("Comment Dots (f4ad)")] CommentDotsRegular,
        [Description("Comment Dots (f4ad)")] CommentDotsSolid,
        [Description("comment (f075, bubble, chat, conversation, feedback, message, note, notification, sms, speech, texting)")] CommentRegular,
        [Description("Comment Slash (f4b3)")] CommentSlashSolid,
        [Description("comment (f075, bubble, chat, conversation, feedback, message, note, notification, sms, speech, texting)")] CommentSolid,
        [Description("comments (f086, bubble, chat, conversation, feedback, message, note, notification, sms, speech, texting)")] CommentsRegular,
        [Description("comments (f086, bubble, chat, conversation, feedback, message, note, notification, sms, speech, texting)")] CommentsSolid,
        [Description("Compact Disc (f51f, bluray, cd, disc, media)")] CompactDiscSolid,
        [Description("Compass (f14e, directory, location, menu, safari)")] CompassRegular,
        [Description("Compass (f14e, directory, location, menu, safari)")] CompassSolid,
        [Description("Compress (f066, collapse, combine, contract, merge, smaller)")] CompressSolid,
        [Description("Concierge Bell (f562, attention, hotel, service, support)")] ConciergeBellSolid,
        [Description("Connect Develop (f20e)")] ConnectdevelopBrands,
        [Description("Contao (f26d)")] ContaoBrands,
        [Description("Cookie Bite (f564)")] CookieBiteSolid,
        [Description("Cookie (f563)")] CookieSolid,
        [Description("Copy (f0c5, clone, duplicate, file, files-o)")] CopyRegular,
        [Description("Copyright (f1f9)")] CopyrightRegular,
        [Description("Copyright (f1f9)")] CopyrightSolid,
        [Description("Copy (f0c5, clone, duplicate, file, files-o)")] CopySolid,
        [Description("Couch (f4b8)")] CouchSolid,
        [Description("cPanel (f388)")] CpanelBrands,
        [Description("Creative Commons (f25e)")] CreativeCommonsBrands,
        [Description("Creative Commons Attribution (f4e7)")] CreativeCommonsByBrands,
        [Description("Creative Commons Noncommercial (f4e8)")] CreativeCommonsNcBrands,
        [Description("Creative Commons Noncommercial (Euro Sign) (f4e9)")] CreativeCommonsNcEuBrands,
        [Description("Creative Commons Noncommercial (Yen Sign) (f4ea)")] CreativeCommonsNcJpBrands,
        [Description("Creative Commons No Derivative Works (f4eb)")] CreativeCommonsNdBrands,
        [Description("Creative Commons Public Domain Alternate (f4ed)")] CreativeCommonsPdAltBrands,
        [Description("Creative Commons Public Domain (f4ec)")] CreativeCommonsPdBrands,
        [Description("Creative Commons Remix (f4ee)")] CreativeCommonsRemixBrands,
        [Description("Creative Commons Share Alike (f4ef)")] CreativeCommonsSaBrands,
        [Description("Creative Commons Sampling (f4f0)")] CreativeCommonsSamplingBrands,
        [Description("Creative Commons Sampling + (f4f1)")] CreativeCommonsSamplingPlusBrands,
        [Description("Creative Commons Share (f4f2)")] CreativeCommonsShareBrands,
        [Description("Credit Card (f09d, buy, checkout, credit-card-alt, debit, money, payment, purchase)")] CreditCardRegular,
        [Description("Credit Card (f09d, buy, checkout, credit-card-alt, debit, money, payment, purchase)")] CreditCardSolid,
        [Description("Alternate Crop (f565)")] CropAltSolid,
        [Description("crop (f125, design)")] CropSolid,
        [Description("Crosshairs (f05b, gpd, picker, position)")] CrosshairsSolid,
        [Description("Crown (f521)")] CrownSolid,
        [Description("Crow (f520, bird, bullfrog, toad)")] CrowSolid,
        [Description("Alternate CSS3 Logo (f38b)")] Css3AltBrands,
        [Description("CSS 3 Logo (f13c, code)")] Css3Brands,
        [Description("Cube (f1b2, package)")] CubeSolid,
        [Description("Cubes (f1b3, packages)")] CubesSolid,
        [Description("Cut (f0c4, scissors, scissors)")] CutSolid,
        [Description("Cuttlefish (f38c)")] CuttlefishBrands,
        [Description("Dungeons & Dragons (f38d)")] DAndDBrands,
        [Description("DashCube (f210)")] DashcubeBrands,
        [Description("Database (f1c0)")] DatabaseSolid,
        [Description("Deaf (f2a4)")] DeafSolid,
        [Description("Delicious Logo (f1a5)")] DeliciousBrands,
        [Description("deploy.dog (f38e)")] DeploydogBrands,
        [Description("Deskpro (f38f)")] DeskproBrands,
        [Description("Desktop (f108, computer, cpu, demo, desktop, device, machine, monitor, pc, screen)")] DesktopSolid,
        [Description("deviantART (f1bd)")] DeviantartBrands,
        [Description("Diagnoses (f470)")] DiagnosesSolid,
        [Description("Dice Five (f523, chance, gambling, game, roll)")] DiceFiveSolid,
        [Description("Dice Four (f524, chance, gambling, game, roll)")] DiceFourSolid,
        [Description("Dice One (f525, chance, gambling, game, roll)")] DiceOneSolid,
        [Description("Dice Six (f526, chance, gambling, game, roll)")] DiceSixSolid,
        [Description("Dice (f522, chance, gambling, game, roll)")] DiceSolid,
        [Description("Dice Three (f527, chance, gambling, game, roll)")] DiceThreeSolid,
        [Description("Dice Two (f528, chance, gambling, game, roll)")] DiceTwoSolid,
        [Description("Digg Logo (f1a6)")] DiggBrands,
        [Description("Digital Ocean (f391)")] DigitalOceanBrands,
        [Description("Digital Tachograph (f566)")] DigitalTachographSolid,
        [Description("Discord (f392)")] DiscordBrands,
        [Description("Discourse (f393)")] DiscourseBrands,
        [Description("Divide (f529)")] DivideSolid,
        [Description("Dizzy Face (f567)")] DizzyRegular,
        [Description("Dizzy Face (f567)")] DizzySolid,
        [Description("DNA (f471, double helix, helix)")] DnaSolid,
        [Description("DocHub (f394)")] DochubBrands,
        [Description("Docker (f395)")] DockerBrands,
        [Description("Dollar Sign (f155, $, dollar-sign, money, price, usd)")] DollarSignSolid,
        [Description("Dolly Flatbed (f474)")] DollyFlatbedSolid,
        [Description("Dolly (f472)")] DollySolid,
        [Description("Donate (f4b9, generosity, give)")] DonateSolid,
        [Description("Door Closed (f52a)")] DoorClosedSolid,
        [Description("Door Open (f52b)")] DoorOpenSolid,
        [Description("Dot Circle (f192, bullseye, notification, target)")] DotCircleRegular,
        [Description("Dot Circle (f192, bullseye, notification, target)")] DotCircleSolid,
        [Description("Dove (f4ba)")] DoveSolid,
        [Description("Download (f019, import)")] DownloadSolid,
        [Description("Draft2digital (f396)")] Draft2digitalBrands,
        [Description("Drafting Compass (f568)")] DraftingCompassSolid,
        [Description("Dribbble (f17d)")] DribbbleBrands,
        [Description("Dribbble Square (f397)")] DribbbleSquareBrands,
        [Description("Dropbox (f16b)")] DropboxBrands,
        [Description("Drum (f569)")] DrumSolid,
        [Description("Drum Steelpan (f56a)")] DrumSteelpanSolid,
        [Description("Drupal Logo (f1a9)")] DrupalBrands,
        [Description("Dumbbell (f44b, exercise, gym, strength, weight, weight-lifting)")] DumbbellSolid,
        [Description("Dyalog (f399)")] DyalogBrands,
        [Description("Earlybirds (f39a)")] EarlybirdsBrands,
        [Description("eBay (f4f4)")] EbayBrands,
        [Description("Edge Browser (f282, browser, ie)")] EdgeBrands,
        [Description("Edit (f044, edit, pen, pencil, update, write)")] EditRegular,
        [Description("Edit (f044, edit, pen, pencil, update, write)")] EditSolid,
        [Description("eject (f052)")] EjectSolid,
        [Description("Elementor (f430)")] ElementorBrands,
        [Description("Horizontal Ellipsis (f141, dots, drag, kebab, list, menu, nav, navigation, ol, reorder, settings, ul)")] EllipsisHSolid,
        [Description("Vertical Ellipsis (f142, dots, drag, kebab, list, menu, nav, navigation, ol, reorder, settings, ul)")] EllipsisVSolid,
        [Description("Ember (f423)")] EmberBrands,
        [Description("Galactic Empire (f1d1)")] EmpireBrands,
        [Description("Envelope Open (f2b6, e-mail, email, letter, mail, message, notification, support)")] EnvelopeOpenRegular,
        [Description("Envelope Open (f2b6, e-mail, email, letter, mail, message, notification, support)")] EnvelopeOpenSolid,
        [Description("Envelope (f0e0, e-mail, email, letter, mail, message, notification, support)")] EnvelopeRegular,
        [Description("Envelope (f0e0, e-mail, email, letter, mail, message, notification, support)")] EnvelopeSolid,
        [Description("Envelope Square (f199, e-mail, email, letter, mail, message, notification, support)")] EnvelopeSquareSolid,
        [Description("Envira Gallery (f299, leaf)")] EnviraBrands,
        [Description("Equals (f52c)")] EqualsSolid,
        [Description("eraser (f12d, delete, remove)")] EraserSolid,
        [Description("Erlang (f39d)")] ErlangBrands,
        [Description("Ethereum (f42e)")] EthereumBrands,
        [Description("Etsy (f2d7)")] EtsyBrands,
        [Description("Euro Sign (f153, eur, eur)")] EuroSignSolid,
        [Description("Alternate Exchange (f362, arrow, arrows, exchange, reciprocate, return, swap, transfer)")] ExchangeAltSolid,
        [Description("Exclamation Circle (f06a, alert, danger, error, important, notice, notification, notify, problem, warning)")] ExclamationCircleSolid,
        [Description("exclamation (f12a, alert, danger, error, important, notice, notification, notify, problem, warning)")] ExclamationSolid,
        [Description("Exclamation Triangle (f071, alert, danger, error, important, notice, notification, notify, problem, warning)")] ExclamationTriangleSolid,
        [Description("Alternate Expand Arrows (f31e, arrows-alt, bigger, enlarge, move, resize)")] ExpandArrowsAltSolid,
        [Description("Expand (f065, bigger, enlarge, resize)")] ExpandSolid,
        [Description("ExpeditedSSL (f23e)")] ExpeditedsslBrands,
        [Description("Alternate External Link (f35d, external-link, new, open)")] ExternalLinkAltSolid,
        [Description("Alternate External Link Square (f360, external-link-square, new, open)")] ExternalLinkSquareAltSolid,
        [Description("Eye Dropper (f1fb, eyedropper)")] EyeDropperSolid,
        [Description("Eye (f06e, optic, see, seen, show, sight, views, visible)")] EyeRegular,
        [Description("Eye Slash (f070, blind, hide, show, toggle, unseen, views, visible, visiblity)")] EyeSlashRegular,
        [Description("Eye Slash (f070, blind, hide, show, toggle, unseen, views, visible, visiblity)")] EyeSlashSolid,
        [Description("Eye (f06e, optic, see, seen, show, sight, views, visible)")] EyeSolid,
        [Description("Facebook (f09a, facebook-official, social network)")] FacebookBrands,
        [Description("Facebook F (f39e, facebook)")] FacebookFBrands,
        [Description("Facebook Messenger (f39f)")] FacebookMessengerBrands,
        [Description("Facebook Square (f082, social network)")] FacebookSquareBrands,
        [Description("fast-backward (f049, beginning, first, previous, rewind, start)")] FastBackwardSolid,
        [Description("fast-forward (f050, end, last, next)")] FastForwardSolid,
        [Description("Fax (f1ac)")] FaxSolid,
        [Description("Feather Alt (f56b)")] FeatherAltSolid,
        [Description("Feather (f52d)")] FeatherSolid,
        [Description("Female (f182, human, person, profile, user, woman)")] FemaleSolid,
        [Description("fighter-jet (f0fb, airplane, fast, fly, goose, maverick, plane, quick, top gun, transportation, travel)")] FighterJetSolid,
        [Description("Alternate File (f15c, document, file-text, invoice, new, page, pdf)")] FileAltRegular,
        [Description("Alternate File (f15c, document, file-text, invoice, new, page, pdf)")] FileAltSolid,
        [Description("Archive File (f1c6, .zip, bundle, compress, compression, download, zip)")] FileArchiveRegular,
        [Description("Archive File (f1c6, .zip, bundle, compress, compression, download, zip)")] FileArchiveSolid,
        [Description("Audio File (f1c7)")] FileAudioRegular,
        [Description("Audio File (f1c7)")] FileAudioSolid,
        [Description("Code File (f1c9)")] FileCodeRegular,
        [Description("Code File (f1c9)")] FileCodeSolid,
        [Description("File Contract (f56c, agreement, binding, document, legal, signature)")] FileContractSolid,
        [Description("File Download (f56d)")] FileDownloadSolid,
        [Description("Excel File (f1c3)")] FileExcelRegular,
        [Description("Excel File (f1c3)")] FileExcelSolid,
        [Description("File Export (f56e)")] FileExportSolid,
        [Description("Image File (f1c5)")] FileImageRegular,
        [Description("Image File (f1c5)")] FileImageSolid,
        [Description("File Import (f56f)")] FileImportSolid,
        [Description("File Invoice with US Dollar (f571, $, bill, document, dollar-sign, money, receipt, usd)")] FileInvoiceDollarSolid,
        [Description("File Invoice (f570, bill, document, receipt)")] FileInvoiceSolid,
        [Description("Alternate Medical File (f478)")] FileMedicalAltSolid,
        [Description("Medical File (f477)")] FileMedicalSolid,
        [Description("PDF File (f1c1)")] FilePdfRegular,
        [Description("PDF File (f1c1)")] FilePdfSolid,
        [Description("Powerpoint File (f1c4)")] FilePowerpointRegular,
        [Description("Powerpoint File (f1c4)")] FilePowerpointSolid,
        [Description("File Prescription (f572, drugs, medical, medicine, rx)")] FilePrescriptionSolid,
        [Description("File (f15b, document, new, page, pdf, resume)")] FileRegular,
        [Description("File Signature (f573, John Hancock, contract, document, name)")] FileSignatureSolid,
        [Description("File (f15b, document, new, page, pdf, resume)")] FileSolid,
        [Description("File Upload (f574)")] FileUploadSolid,
        [Description("Video File (f1c8)")] FileVideoRegular,
        [Description("Video File (f1c8)")] FileVideoSolid,
        [Description("Word File (f1c2)")] FileWordRegular,
        [Description("Word File (f1c2)")] FileWordSolid,
        [Description("Fill Drip (f576)")] FillDripSolid,
        [Description("Fill (f575)")] FillSolid,
        [Description("Film (f008, movie)")] FilmSolid,
        [Description("Filter (f0b0, funnel, options)")] FilterSolid,
        [Description("Fingerprint (f577)")] FingerprintSolid,
        [Description("fire-extinguisher (f134)")] FireExtinguisherSolid,
        [Description("Firefox (f269, browser)")] FirefoxBrands,
        [Description("fire (f06d, flame, hot, popular)")] FireSolid,
        [Description("First Aid (f479)")] FirstAidSolid,
        [Description("firstdraft (f3a1)")] FirstdraftBrands,
        [Description("Alternate First Order (f50a)")] FirstOrderAltBrands,
        [Description("First Order (f2b0)")] FirstOrderBrands,
        [Description("Fish (f578)")] FishSolid,
        [Description("flag-checkered (f11e, notice, notification, notify, report)")] FlagCheckeredSolid,
        [Description("flag (f024, notice, notification, notify, report)")] FlagRegular,
        [Description("flag (f024, notice, notification, notify, report)")] FlagSolid,
        [Description("Flask (f0c3, beaker, experimental, labs, science)")] FlaskSolid,
        [Description("Flickr (f16e)")] FlickrBrands,
        [Description("Flipboard (f44d)")] FlipboardBrands,
        [Description("Flushed Face (f579)")] FlushedRegular,
        [Description("Flushed Face (f579)")] FlushedSolid,
        [Description("Fly (f417)")] FlyBrands,
        [Description("Folder Open (f07c)")] FolderOpenRegular,
        [Description("Folder Open (f07c)")] FolderOpenSolid,
        [Description("Folder (f07b)")] FolderRegular,
        [Description("Folder (f07b)")] FolderSolid,
        [Description("Alternate Font Awesome (f35c)")] FontAwesomeAltBrands,
        [Description("Font Awesome (f2b4, meanpath)")] FontAwesomeBrands,
        [Description("Font Awesome Flag (f425)")] FontAwesomeFlagBrands,
        [Description("Font Awesome Full Logo (f4e6)")] FontAwesomeLogoFullBrands,
        [Description("Font Awesome Full Logo (f4e6)")] FontAwesomeLogoFullRegular,
        [Description("Font Awesome Full Logo (f4e6)")] FontAwesomeLogoFullSolid,
        [Description("Fonticons (f280)")] FonticonsBrands,
        [Description("Fonticons Fi (f3a2)")] FonticonsFiBrands,
        [Description("font (f031, text)")] FontSolid,
        [Description("Football Ball (f44e)")] FootballBallSolid,
        [Description("Alternate Fort Awesome (f3a3, castle)")] FortAwesomeAltBrands,
        [Description("Fort Awesome (f286, castle)")] FortAwesomeBrands,
        [Description("Forumbee (f211)")] ForumbeeBrands,
        [Description("forward (f04e, forward, next)")] ForwardSolid,
        [Description("Foursquare (f180)")] FoursquareBrands,
        [Description("FreeBSD (f3a4)")] FreebsdBrands,
        [Description("Free Code Camp (f2c5)")] FreeCodeCampBrands,
        [Description("Frog (f52e, bullfrog, kermit, kiss, prince, toad, wart)")] FrogSolid,
        [Description("Frowning Face With Open Mouth (f57a)")] FrownOpenRegular,
        [Description("Frowning Face With Open Mouth (f57a)")] FrownOpenSolid,
        [Description("Frowning Face (f119, disapprove, emoticon, face, rating, sad)")] FrownRegular,
        [Description("Frowning Face (f119, disapprove, emoticon, face, rating, sad)")] FrownSolid,
        [Description("Fulcrum (f50b)")] FulcrumBrands,
        [Description("Futbol (f1e3, ball, football, soccer)")] FutbolRegular,
        [Description("Futbol (f1e3, ball, football, soccer)")] FutbolSolid,
        [Description("Galactic Republic (f50c)")] GalacticRepublicBrands,
        [Description("Galactic Senate (f50d)")] GalacticSenateBrands,
        [Description("Gamepad (f11b, controller)")] GamepadSolid,
        [Description("Gas Pump (f52f)")] GasPumpSolid,
        [Description("Gavel (f0e3, hammer, judge, lawyer, opinion)")] GavelSolid,
        [Description("Gem (f3a5, diamond)")] GemRegular,
        [Description("Gem (f3a5, diamond)")] GemSolid,
        [Description("Genderless (f22d)")] GenderlessSolid,
        [Description("Get Pocket (f265)")] GetPocketBrands,
        [Description("GG Currency (f260)")] GgBrands,
        [Description("GG Currency Circle (f261)")] GgCircleBrands,
        [Description("gift (f06b, generosity, giving, party, present, wrapped)")] GiftSolid,
        [Description("Git (f1d3)")] GitBrands,
        [Description("Alternate GitHub (f113, octocat)")] GithubAltBrands,
        [Description("GitHub (f09b, octocat)")] GithubBrands,
        [Description("GitHub Square (f092, octocat)")] GithubSquareBrands,
        [Description("GitKraken (f3a6)")] GitkrakenBrands,
        [Description("GitLab (f296, Axosoft)")] GitlabBrands,
        [Description("Git Square (f1d2)")] GitSquareBrands,
        [Description("Gitter (f426)")] GitterBrands,
        [Description("Glasses (f530, foureyes, hipster, nerd, reading, sight, spectacles)")] GlassesSolid,
        [Description("Glass Martini-alt (f57b)")] GlassMartiniAltSolid,
        [Description("Martini Glass (f000, alcohol, bar, drink, glass, liquor, martini)")] GlassMartiniSolid,
        [Description("Glide (f2a5)")] GlideBrands,
        [Description("Glide G (f2a6)")] GlideGBrands,
        [Description("Globe with Africa shown (f57c, all, country, earth, global, gps, language, localize, location, map, online, place, planet, translate, travel, world)")] GlobeAfricaSolid,
        [Description("Globe with Americas shown (f57d, all, country, earth, global, gps, language, localize, location, map, online, place, planet, translate, travel, world)")] GlobeAmericasSolid,
        [Description("Globe with Asia shown (f57e, all, country, earth, global, gps, language, localize, location, map, online, place, planet, translate, travel, world)")] GlobeAsiaSolid,
        [Description("Globe (f0ac, all, coordinates, country, earth, global, gps, language, localize, location, map, online, place, planet, translate, travel, world)")] GlobeSolid,
        [Description("Gofore (f3a7)")] GoforeBrands,
        [Description("Golf Ball (f450)")] GolfBallSolid,
        [Description("Goodreads (f3a8)")] GoodreadsBrands,
        [Description("Goodreads G (f3a9)")] GoodreadsGBrands,
        [Description("Google Logo (f1a0)")] GoogleBrands,
        [Description("Google Drive (f3aa)")] GoogleDriveBrands,
        [Description("Google Play (f3ab)")] GooglePlayBrands,
        [Description("Google Plus (f2b3, google-plus-circle, google-plus-official)")] GooglePlusBrands,
        [Description("Google Plus G (f0d5, google-plus, social network)")] GooglePlusGBrands,
        [Description("Google Plus Square (f0d4, social network)")] GooglePlusSquareBrands,
        [Description("Google Wallet (f1ee)")] GoogleWalletBrands,
        [Description("Graduation Cap (f19d, learning, school, student)")] GraduationCapSolid,
        [Description("Gratipay (Gittip) (f184, favorite, heart, like, love)")] GratipayBrands,
        [Description("Grav (f2d6)")] GravBrands,
        [Description("Greater Than Equal To (f532)")] GreaterThanEqualSolid,
        [Description("Greater Than (f531)")] GreaterThanSolid,
        [Description("Grimacing Face (f57f)")] GrimaceRegular,
        [Description("Grimacing Face (f57f)")] GrimaceSolid,
        [Description("Alternate Grinning Face (f581)")] GrinAltRegular,
        [Description("Alternate Grinning Face (f581)")] GrinAltSolid,
        [Description("Grinning Face With Smiling Eyes (f582)")] GrinBeamRegular,
        [Description("Grinning Face With Smiling Eyes (f582)")] GrinBeamSolid,
        [Description("Grinning Face With Sweat (f583)")] GrinBeamSweatRegular,
        [Description("Grinning Face With Sweat (f583)")] GrinBeamSweatSolid,
        [Description("Smiling Face With Heart-Eyes (f584)")] GrinHeartsRegular,
        [Description("Smiling Face With Heart-Eyes (f584)")] GrinHeartsSolid,
        [Description("Grinning Face (f580)")] GrinRegular,
        [Description("Grinning Face (f580)")] GrinSolid,
        [Description("Grinning Squinting Face (f585)")] GrinSquintRegular,
        [Description("Grinning Squinting Face (f585)")] GrinSquintSolid,
        [Description("Rolling on the Floor Laughing (f586)")] GrinSquintTearsRegular,
        [Description("Rolling on the Floor Laughing (f586)")] GrinSquintTearsSolid,
        [Description("Star-Struck (f587)")] GrinStarsRegular,
        [Description("Star-Struck (f587)")] GrinStarsSolid,
        [Description("Face With Tears of Joy (f588)")] GrinTearsRegular,
        [Description("Face With Tears of Joy (f588)")] GrinTearsSolid,
        [Description("Face With Tongue (f589)")] GrinTongueRegular,
        [Description("Face With Tongue (f589)")] GrinTongueSolid,
        [Description("Squinting Face With Tongue (f58a)")] GrinTongueSquintRegular,
        [Description("Squinting Face With Tongue (f58a)")] GrinTongueSquintSolid,
        [Description("Winking Face With Tongue (f58b)")] GrinTongueWinkRegular,
        [Description("Winking Face With Tongue (f58b)")] GrinTongueWinkSolid,
        [Description("Grinning Winking Face (f58c)")] GrinWinkRegular,
        [Description("Grinning Winking Face (f58c)")] GrinWinkSolid,
        [Description("Gripfire, Inc. (f3ac)")] GripfireBrands,
        [Description("Grip Horizontal (f58d, affordance, grab, handle)")] GripHorizontalSolid,
        [Description("Grip Vertical (f58e, affordance, grab, handle)")] GripVerticalSolid,
        [Description("Grunt (f3ad)")] GruntBrands,
        [Description("Gulp (f3ae)")] GulpBrands,
        [Description("Hacker News (f1d4)")] HackerNewsBrands,
        [Description("Hacker News Square (f3af)")] HackerNewsSquareBrands,
        [Description("Hand Holding Heart (f4be)")] HandHoldingHeartSolid,
        [Description("Hand Holding (f4bd)")] HandHoldingSolid,
        [Description("Hand Holding US Dollar (f4c0, $, dollar sign, donation, giving, money, price)")] HandHoldingUsdSolid,
        [Description("Lizard (Hand) (f258)")] HandLizardRegular,
        [Description("Lizard (Hand) (f258)")] HandLizardSolid,
        [Description("Paper (Hand) (f256, stop)")] HandPaperRegular,
        [Description("Paper (Hand) (f256, stop)")] HandPaperSolid,
        [Description("Peace (Hand) (f25b)")] HandPeaceRegular,
        [Description("Peace (Hand) (f25b)")] HandPeaceSolid,
        [Description("Hand Pointing Down (f0a7, finger, hand-o-down, point)")] HandPointDownRegular,
        [Description("Hand Pointing Down (f0a7, finger, hand-o-down, point)")] HandPointDownSolid,
        [Description("Pointer (Hand) (f25a, select)")] HandPointerRegular,
        [Description("Pointer (Hand) (f25a, select)")] HandPointerSolid,
        [Description("Hand Pointing Left (f0a5, back, finger, hand-o-left, left, point, previous)")] HandPointLeftRegular,
        [Description("Hand Pointing Left (f0a5, back, finger, hand-o-left, left, point, previous)")] HandPointLeftSolid,
        [Description("Hand Pointing Right (f0a4, finger, forward, hand-o-right, next, point, right)")] HandPointRightRegular,
        [Description("Hand Pointing Right (f0a4, finger, forward, hand-o-right, next, point, right)")] HandPointRightSolid,
        [Description("Hand Pointing Up (f0a6, finger, hand-o-up, point)")] HandPointUpRegular,
        [Description("Hand Pointing Up (f0a6, finger, hand-o-up, point)")] HandPointUpSolid,
        [Description("Rock (Hand) (f255)")] HandRockRegular,
        [Description("Rock (Hand) (f255)")] HandRockSolid,
        [Description("Scissors (Hand) (f257)")] HandScissorsRegular,
        [Description("Scissors (Hand) (f257)")] HandScissorsSolid,
        [Description("Handshake (f2b5, greeting, partnership)")] HandshakeRegular,
        [Description("Handshake (f2b5, greeting, partnership)")] HandshakeSolid,
        [Description("Helping Hands (f4c4, aid, assistance, partnership, volunteering)")] HandsHelpingSolid,
        [Description("Spock (Hand) (f259)")] HandSpockRegular,
        [Description("Spock (Hand) (f259)")] HandSpockSolid,
        [Description("Hands (f4c2)")] HandsSolid,
        [Description("Hashtag (f292)")] HashtagSolid,
        [Description("HDD (f0a0, cpu, hard drive, harddrive, machine, save, storage)")] HddRegular,
        [Description("HDD (f0a0, cpu, hard drive, harddrive, machine, save, storage)")] HddSolid,
        [Description("heading (f1dc, header, header)")] HeadingSolid,
        [Description("Headphones Alt (f58f)")] HeadphonesAltSolid,
        [Description("headphones (f025, audio, listen, music, sound, speaker)")] HeadphonesSolid,
        [Description("Headset (f590)")] HeadsetSolid,
        [Description("Heartbeat (f21e, ekg, lifeline, vital signs)")] HeartbeatSolid,
        [Description("Heart (f004, favorite, like, love)")] HeartRegular,
        [Description("Heart (f004, favorite, like, love)")] HeartSolid,
        [Description("Helicopter (f533, airwolf, apache, chopper, flight, fly)")] HelicopterSolid,
        [Description("Highlighter (f591, edit, marker, sharpie, update, write)")] HighlighterSolid,
        [Description("Hips (f452)")] HipsBrands,
        [Description("HireAHelper (f3b0)")] HireAHelperBrands,
        [Description("History (f1da)")] HistorySolid,
        [Description("Hockey Puck (f453)")] HockeyPuckSolid,
        [Description("home (f015, house, main)")] HomeSolid,
        [Description("Hooli (f427)")] HooliBrands,
        [Description("Hornbill (f592)")] HornbillBrands,
        [Description("Alternate Hospital (f47d, building, emergency room, medical center)")] HospitalAltSolid,
        [Description("hospital (f0f8, building, emergency room, medical center)")] HospitalRegular,
        [Description("hospital (f0f8, building, emergency room, medical center)")] HospitalSolid,
        [Description("Hospital Symbol (f47e)")] HospitalSymbolSolid,
        [Description("Hotel (f594, building, lodging)")] HotelSolid,
        [Description("Hotjar (f3b1)")] HotjarBrands,
        [Description("Hot Tub (f593)")] HotTubSolid,
        [Description("Hourglass End (f253)")] HourglassEndSolid,
        [Description("Hourglass Half (f252)")] HourglassHalfSolid,
        [Description("Hourglass (f254)")] HourglassRegular,
        [Description("Hourglass (f254)")] HourglassSolid,
        [Description("Hourglass Start (f251)")] HourglassStartSolid,
        [Description("Houzz (f27c)")] HouzzBrands,
        [Description("H Square (f0fd, hospital, hotel)")] HSquareSolid,
        [Description("HTML 5 Logo (f13b)")] Html5Brands,
        [Description("HubSpot (f3b2)")] HubspotBrands,
        [Description("I Beam Cursor (f246)")] ICursorSolid,
        [Description("Identification Badge (f2c1)")] IdBadgeRegular,
        [Description("Identification Badge (f2c1)")] IdBadgeSolid,
        [Description("Alternate Identification Card (f47f, demographics)")] IdCardAltSolid,
        [Description("Identification Card (f2c2, document, identification, issued)")] IdCardRegular,
        [Description("Identification Card (f2c2, document, identification, issued)")] IdCardSolid,
        [Description("Image (f03e, album, photo, picture, picture)")] ImageRegular,
        [Description("Image (f03e, album, photo, picture, picture)")] ImageSolid,
        [Description("Images (f302, album, photo, picture)")] ImagesRegular,
        [Description("Images (f302, album, photo, picture)")] ImagesSolid,
        [Description("IMDB (f2d8)")] ImdbBrands,
        [Description("inbox (f01c)")] InboxSolid,
        [Description("Indent (f03c)")] IndentSolid,
        [Description("Industry (f275, factory, manufacturing)")] IndustrySolid,
        [Description("Infinity (f534)")] InfinitySolid,
        [Description("Info Circle (f05a, details, help, information, more)")] InfoCircleSolid,
        [Description("Info (f129, details, help, information, more)")] InfoSolid,
        [Description("Instagram (f16d)")] InstagramBrands,
        [Description("Internet-explorer (f26b, browser, ie)")] InternetExplorerBrands,
        [Description("ioxhost (f208)")] IoxhostBrands,
        [Description("italic (f033, italics)")] ItalicSolid,
        [Description("iTunes (f3b4)")] ItunesBrands,
        [Description("Itunes Note (f3b5)")] ItunesNoteBrands,
        [Description("Java (f4e4)")] JavaBrands,
        [Description("Jedi Order (f50e)")] JediOrderBrands,
        [Description("Jenkis (f3b6)")] JenkinsBrands,
        [Description("Joget (f3b7)")] JogetBrands,
        [Description("Joint (f595, blunt, cannabis, doobie, drugs, marijuana, roach, smoke, smoking, spliff)")] JointSolid,
        [Description("Joomla Logo (f1aa)")] JoomlaBrands,
        [Description("JavaScript (JS) (f3b8)")] JsBrands,
        [Description("jsFiddle (f1cc)")] JsfiddleBrands,
        [Description("JavaScript (JS) Square (f3b9)")] JsSquareBrands,
        [Description("Keybase (f4f5)")] KeybaseBrands,
        [Description("Keyboard (f11c, input, type)")] KeyboardRegular,
        [Description("Keyboard (f11c, input, type)")] KeyboardSolid,
        [Description("KeyCDN (f3ba)")] KeycdnBrands,
        [Description("key (f084, password, unlock)")] KeySolid,
        [Description("Kickstarter (f3bb)")] KickstarterBrands,
        [Description("Kickstarter K (f3bc)")] KickstarterKBrands,
        [Description("Kissing Face With Smiling Eyes (f597)")] KissBeamRegular,
        [Description("Kissing Face With Smiling Eyes (f597)")] KissBeamSolid,
        [Description("Kissing Face (f596)")] KissRegular,
        [Description("Kissing Face (f596)")] KissSolid,
        [Description("Face Blowing a Kiss (f598)")] KissWinkHeartRegular,
        [Description("Face Blowing a Kiss (f598)")] KissWinkHeartSolid,
        [Description("Kiwi Bird (f535)")] KiwiBirdSolid,
        [Description("KORVUE (f42f)")] KorvueBrands,
        [Description("Language (f1ab)")] LanguageSolid,
        [Description("Laptop (f109, computer, cpu, dell, demo, device, dude you're getting, mac, macbook, machine, pc, pc)")] LaptopSolid,
        [Description("Laravel (f3bd)")] LaravelBrands,
        [Description("last.fm (f202)")] LastfmBrands,
        [Description("last.fm Square (f203)")] LastfmSquareBrands,
        [Description("Laugh Face with Beaming Eyes (f59a)")] LaughBeamRegular,
        [Description("Laugh Face with Beaming Eyes (f59a)")] LaughBeamSolid,
        [Description("Grinning Face With Big Eyes (f599)")] LaughRegular,
        [Description("Grinning Face With Big Eyes (f599)")] LaughSolid,
        [Description("Laughing Squinting Face (f59b)")] LaughSquintRegular,
        [Description("Laughing Squinting Face (f59b)")] LaughSquintSolid,
        [Description("Laughing Winking Face (f59c)")] LaughWinkRegular,
        [Description("Laughing Winking Face (f59c)")] LaughWinkSolid,
        [Description("leaf (f06c, eco, nature, plant)")] LeafSolid,
        [Description("Leanpub (f212)")] LeanpubBrands,
        [Description("Lemon (f094, food)")] LemonRegular,
        [Description("Lemon (f094, food)")] LemonSolid,
        [Description("Less (f41d)")] LessBrands,
        [Description("Less Than Equal To (f537)")] LessThanEqualSolid,
        [Description("Less Than (f536)")] LessThanSolid,
        [Description("Alternate Level Down (f3be, level-down)")] LevelDownAltSolid,
        [Description("Alternate Level Up (f3bf, level-up)")] LevelUpAltSolid,
        [Description("Life Ring (f1cd, support)")] LifeRingRegular,
        [Description("Life Ring (f1cd, support)")] LifeRingSolid,
        [Description("Lightbulb (f0eb, idea, inspiration)")] LightbulbRegular,
        [Description("Lightbulb (f0eb, idea, inspiration)")] LightbulbSolid,
        [Description("Line (f3c0)")] LineBrands,
        [Description("LinkedIn (f08c, linkedin-square)")] LinkedinBrands,
        [Description("LinkedIn In (f0e1, linkedin)")] LinkedinInBrands,
        [Description("Link (f0c1, chain)")] LinkSolid,
        [Description("Linode (f2b8)")] LinodeBrands,
        [Description("Linux (f17c, tux)")] LinuxBrands,
        [Description("Turkish Lira Sign (f195, try, try, turkish)")] LiraSignSolid,
        [Description("Alternate List (f022, checklist, completed, done, finished, ol, todo, ul)")] ListAltRegular,
        [Description("Alternate List (f022, checklist, completed, done, finished, ol, todo, ul)")] ListAltSolid,
        [Description("list-ol (f0cb, checklist, list, list, numbers, ol, todo, ul)")] ListOlSolid,
        [Description("List (f03a, checklist, completed, done, finished, ol, todo, ul)")] ListSolid,
        [Description("list-ul (f0ca, checklist, list, ol, todo, ul)")] ListUlSolid,
        [Description("location-arrow (f124, address, coordinates, gps, location, map, place, where)")] LocationArrowSolid,
        [Description("Lock Open (f3c1, admin, lock, open, password, protect)")] LockOpenSolid,
        [Description("lock (f023, admin, protect, security)")] LockSolid,
        [Description("Alternate Long Arrow Down (f309, long-arrow-down)")] LongArrowAltDownSolid,
        [Description("Alternate Long Arrow Left (f30a, back, long-arrow-left, previous)")] LongArrowAltLeftSolid,
        [Description("Alternate Long Arrow Right (f30b, long-arrow-right)")] LongArrowAltRightSolid,
        [Description("Alternate Long Arrow Up (f30c, long-arrow-up)")] LongArrowAltUpSolid,
        [Description("Low Vision (f2a8)")] LowVisionSolid,
        [Description("Luggage Cart (f59d)")] LuggageCartSolid,
        [Description("lyft (f3c3)")] LyftBrands,
        [Description("Magento (f3c4)")] MagentoBrands,
        [Description("magic (f0d0, autocomplete, automatic, wizard)")] MagicSolid,
        [Description("magnet (f076)")] MagnetSolid,
        [Description("Mailchimp (f59e)")] MailchimpBrands,
        [Description("Male (f183, human, man, person, profile, user)")] MaleSolid,
        [Description("Mandalorian (f50f)")] MandalorianBrands,
        [Description("Map Marked-alt (f5a0, address, coordinates, destination, gps, localize, location, map, paper, pin, place, point of interest, position, route, travel, where)")] MapMarkedAltSolid,
        [Description("Map Marked (f59f, address, coordinates, destination, gps, localize, location, map, paper, pin, place, point of interest, position, route, travel, where)")] MapMarkedSolid,
        [Description("Alternate Map Marker (f3c5, address, coordinates, gps, localize, location, map, pin, place, position, travel, where)")] MapMarkerAltSolid,
        [Description("map-marker (f041, address, coordinates, gps, localize, location, map, pin, place, position, travel, where)")] MapMarkerSolid,
        [Description("Map Pin (f276, address, coordinates, gps, localize, location, map, marker, place, position, travel, where)")] MapPinSolid,
        [Description("Map (f279, coordinates, location, paper, place, travel)")] MapRegular,
        [Description("Map Signs (f277)")] MapSignsSolid,
        [Description("Map (f279, coordinates, location, paper, place, travel)")] MapSolid,
        [Description("Marker (f5a1, edit, sharpie, update, write)")] MarkerSolid,
        [Description("Mars Double (f227)")] MarsDoubleSolid,
        [Description("Mars (f222, male)")] MarsSolid,
        [Description("Mars Stroke Horizontal (f22b)")] MarsStrokeHSolid,
        [Description("Mars Stroke (f229)")] MarsStrokeSolid,
        [Description("Mars Stroke Vertical (f22a)")] MarsStrokeVSolid,
        [Description("Mastodon (f4f6)")] MastodonBrands,
        [Description("MaxCDN (f136)")] MaxcdnBrands,
        [Description("Medal (f5a2)")] MedalSolid,
        [Description("MedApps (f3c6)")] MedappsBrands,
        [Description("Medium (f23a)")] MediumBrands,
        [Description("Medium M (f3c7)")] MediumMBrands,
        [Description("medkit (f0fa, first aid, firstaid, health, help, support)")] MedkitSolid,
        [Description("MRT (f3c8)")] MedrtBrands,
        [Description("Meetup (f2e0)")] MeetupBrands,
        [Description("Megaport (f5a3)")] MegaportBrands,
        [Description("Face Without Mouth (f5a4)")] MehBlankRegular,
        [Description("Face Without Mouth (f5a4)")] MehBlankSolid,
        [Description("Neutral Face (f11a, emoticon, face, neutral, rating)")] MehRegular,
        [Description("Face With Rolling Eyes (f5a5)")] MehRollingEyesRegular,
        [Description("Face With Rolling Eyes (f5a5)")] MehRollingEyesSolid,
        [Description("Neutral Face (f11a, emoticon, face, neutral, rating)")] MehSolid,
        [Description("Memory (f538, DIMM, RAM)")] MemorySolid,
        [Description("Mercury (f223, transgender)")] MercurySolid,
        [Description("Microchip (f2db, cpu, processor)")] MicrochipSolid,
        [Description("Alternate Microphone Slash (f539, disable, mute, record, sound, voice)")] MicrophoneAltSlashSolid,
        [Description("Alternate Microphone (f3c9, record, sound, voice)")] MicrophoneAltSolid,
        [Description("Microphone Slash (f131, disable, mute, record, sound, voice)")] MicrophoneSlashSolid,
        [Description("microphone (f130, record, sound, voice)")] MicrophoneSolid,
        [Description("Microsoft (f3ca)")] MicrosoftBrands,
        [Description("Minus Circle (f056, delete, hide, remove, trash)")] MinusCircleSolid,
        [Description("minus (f068, collapse, delete, hide, hide, minify, remove, trash)")] MinusSolid,
        [Description("Minus Square (f146, collapse, delete, hide, hide, minify, remove, trash)")] MinusSquareRegular,
        [Description("Minus Square (f146, collapse, delete, hide, hide, minify, remove, trash)")] MinusSquareSolid,
        [Description("Mix (f3cb)")] MixBrands,
        [Description("Mixcloud (f289)")] MixcloudBrands,
        [Description("Mizuni (f3cc)")] MizuniBrands,
        [Description("Alternate Mobile (f3cd, apple, call, cell phone, cellphone, device, iphone, number, screen, telephone, text)")] MobileAltSolid,
        [Description("Mobile Phone (f10b, apple, call, cell phone, cellphone, device, iphone, number, screen, telephone, text)")] MobileSolid,
        [Description("MODX (f285)")] ModxBrands,
        [Description("Monero (f3d0)")] MoneroBrands,
        [Description("Alternate Money Bill (f3d1, buy, cash, checkout, money, payment, price, purchase)")] MoneyBillAltRegular,
        [Description("Alternate Money Bill (f3d1, buy, cash, checkout, money, payment, price, purchase)")] MoneyBillAltSolid,
        [Description("Money Bill (f0d6, buy, cash, checkout, money, payment, price, purchase)")] MoneyBillSolid,
        [Description("Alternate Wavy Money Bill (f53b)")] MoneyBillWaveAltSolid,
        [Description("Wavy Money Bill (f53a)")] MoneyBillWaveSolid,
        [Description("Alternate Money Check (f53d, bank check, cheque)")] MoneyCheckAltSolid,
        [Description("Money Check (f53c, bank check, cheque)")] MoneyCheckSolid,
        [Description("Monument (f5a6, building, historic, memoroable)")] MonumentSolid,
        [Description("Moon (f186, contrast, darker, night)")] MoonRegular,
        [Description("Moon (f186, contrast, darker, night)")] MoonSolid,
        [Description("Mortar Pestle (f5a7, crush, culinary, grind, medical, mix, spices)")] MortarPestleSolid,
        [Description("Motorcycle (f21c, bike, machine, transportation, vehicle)")] MotorcycleSolid,
        [Description("Mouse Pointer (f245, select)")] MousePointerSolid,
        [Description("Music (f001, note, sound)")] MusicSolid,
        [Description("Napster (f3d2)")] NapsterBrands,
        [Description("Neuter (f22c)")] NeuterSolid,
        [Description("Newspaper (f1ea, article, press)")] NewspaperRegular,
        [Description("Newspaper (f1ea, article, press)")] NewspaperSolid,
        [Description("Nimblr (f5a8)")] NimblrBrands,
        [Description("Nintendo Switch (f418)")] NintendoSwitchBrands,
        [Description("Node.js (f419)")] NodeBrands,
        [Description("Node.js JS (f3d3)")] NodeJsBrands,
        [Description("Not Equal (f53e)")] NotEqualSolid,
        [Description("Medical Notes (f481)")] NotesMedicalSolid,
        [Description("npm (f3d4)")] NpmBrands,
        [Description("NS8 (f3d5)")] Ns8Brands,
        [Description("Nutritionix (f3d6)")] NutritionixBrands,
        [Description("Object Group (f247, design)")] ObjectGroupRegular,
        [Description("Object Group (f247, design)")] ObjectGroupSolid,
        [Description("Object Ungroup (f248, design)")] ObjectUngroupRegular,
        [Description("Object Ungroup (f248, design)")] ObjectUngroupSolid,
        [Description("Odnoklassniki (f263)")] OdnoklassnikiBrands,
        [Description("Odnoklassniki Square (f264)")] OdnoklassnikiSquareBrands,
        [Description("Old Republic (f510)")] OldRepublicBrands,
        [Description("OpenCart (f23d)")] OpencartBrands,
        [Description("OpenID (f19b)")] OpenidBrands,
        [Description("Opera (f26a)")] OperaBrands,
        [Description("Optin Monster (f23c)")] OptinMonsterBrands,
        [Description("Open Source Initiative (f41a)")] OsiBrands,
        [Description("Outdent (f03b)")] OutdentSolid,
        [Description("page4 Corporation (f3d7)")] Page4Brands,
        [Description("Pagelines (f18c, eco, leaf, leaves, nature, plant, tree)")] PagelinesBrands,
        [Description("Paint Brush (f1fc)")] PaintBrushSolid,
        [Description("Paint Roller (f5aa, brush, painting, tool)")] PaintRollerSolid,
        [Description("Palette (f53f, colors, painting)")] PaletteSolid,
        [Description("Palfed (f3d8)")] PalfedBrands,
        [Description("Pallet (f482)")] PalletSolid,
        [Description("Paperclip (f0c6, attachment)")] PaperclipSolid,
        [Description("Paper Plane (f1d8)")] PaperPlaneRegular,
        [Description("Paper Plane (f1d8)")] PaperPlaneSolid,
        [Description("Parachute Box (f4cd, aid, assistance, rescue, supplies)")] ParachuteBoxSolid,
        [Description("paragraph (f1dd)")] ParagraphSolid,
        [Description("Parking (f540)")] ParkingSolid,
        [Description("Passport (f5ab, document, identification, issued)")] PassportSolid,
        [Description("Paste (f0ea, clipboard, copy)")] PasteSolid,
        [Description("Patreon (f3d9)")] PatreonBrands,
        [Description("Pause Circle (f28b)")] PauseCircleRegular,
        [Description("Pause Circle (f28b)")] PauseCircleSolid,
        [Description("pause (f04c, wait)")] PauseSolid,
        [Description("Paw (f1b0, pet)")] PawSolid,
        [Description("Paypal (f1ed)")] PaypalBrands,
        [Description("Alternate Pen (f305, design, edit, update, write)")] PenAltSolid,
        [Description("Alternate Pencil (f303, design, edit, pencil, update, write)")] PencilAltSolid,
        [Description("Pencil Ruler (f5ae)")] PencilRulerSolid,
        [Description("Pen Fancy (f5ac, design, edit, fountain pen, update, write)")] PenFancySolid,
        [Description("Pen Nib (f5ad, design, edit, fountain pen, update, write)")] PenNibSolid,
        [Description("Pen (f304, design, edit, update, write)")] PenSolid,
        [Description("Pen Square (f14b, edit, pencil-square, update, write)")] PenSquareSolid,
        [Description("People Carry (f4ce, movers)")] PeopleCarrySolid,
        [Description("Percentage (f541)")] PercentageSolid,
        [Description("Percent (f295)")] PercentSolid,
        [Description("Periscope (f3da)")] PeriscopeBrands,
        [Description("Phabricator (f3db)")] PhabricatorBrands,
        [Description("Phoenix Framework (f3dc)")] PhoenixFrameworkBrands,
        [Description("Phoenix Squadron (f511)")] PhoenixSquadronBrands,
        [Description("Phone Slash (f3dd)")] PhoneSlashSolid,
        [Description("Phone (f095, call, earphone, number, support, telephone, voice)")] PhoneSolid,
        [Description("Phone Square (f098, call, number, support, telephone, voice)")] PhoneSquareSolid,
        [Description("Phone Volume (f2a0, telephone, volume-control-phone)")] PhoneVolumeSolid,
        [Description("PHP (f457)")] PhpBrands,
        [Description("Alternate Pied Piper Logo (f1a8)")] PiedPiperAltBrands,
        [Description("Pied Piper Logo (f2ae)")] PiedPiperBrands,
        [Description("Pied Piper-hat (f4e5, clothing)")] PiedPiperHatBrands,
        [Description("Pied Piper PP Logo (Old) (f1a7)")] PiedPiperPpBrands,
        [Description("Piggy Bank (f4d3, save, savings)")] PiggyBankSolid,
        [Description("Pills (f484, drugs, medicine)")] PillsSolid,
        [Description("Pinterest (f0d2)")] PinterestBrands,
        [Description("Pinterest P (f231)")] PinterestPBrands,
        [Description("Pinterest Square (f0d3)")] PinterestSquareBrands,
        [Description("Plane Arrival (f5af, airplane, arriving, destination, fly, land, landing, location, mode, travel, trip)")] PlaneArrivalSolid,
        [Description("Plane Departure (f5b0, airplane, departing, destination, fly, location, mode, take off, taking off, travel, trip)")] PlaneDepartureSolid,
        [Description("plane (f072, airplane, destination, fly, location, mode, travel, trip)")] PlaneSolid,
        [Description("Play Circle (f144, playing, start)")] PlayCircleRegular,
        [Description("Play Circle (f144, playing, start)")] PlayCircleSolid,
        [Description("play (f04b, music, playing, sound, start)")] PlaySolid,
        [Description("PlayStation (f3df)")] PlaystationBrands,
        [Description("Plug (f1e6, connect, online, power)")] PlugSolid,
        [Description("Plus Circle (f055, add, create, expand, new)")] PlusCircleSolid,
        [Description("plus (f067, add, create, expand, new)")] PlusSolid,
        [Description("Plus Square (f0fe, add, create, expand, new)")] PlusSquareRegular,
        [Description("Plus Square (f0fe, add, create, expand, new)")] PlusSquareSolid,
        [Description("Podcast (f2ce)")] PodcastSolid,
        [Description("Poo (f2fe)")] PooSolid,
        [Description("Portrait (f3e0)")] PortraitSolid,
        [Description("Pound Sign (f154, gbp, gbp)")] PoundSignSolid,
        [Description("Power Off (f011, on, reboot, restart)")] PowerOffSolid,
        [Description("Alternate Prescription Bottle (f486, drugs, medical, medicine, rx)")] PrescriptionBottleAltSolid,
        [Description("Prescription Bottle (f485, drugs, medical, medicine, rx)")] PrescriptionBottleSolid,
        [Description("Prescription (f5b1, drugs, medical, medicine, rx)")] PrescriptionSolid,
        [Description("print (f02f)")] PrintSolid,
        [Description("Procedures (f487)")] ProceduresSolid,
        [Description("Product Hunt (f288)")] ProductHuntBrands,
        [Description("Project Diagram (f542)")] ProjectDiagramSolid,
        [Description("Pushed (f3e1)")] PushedBrands,
        [Description("Puzzle Piece (f12e, add-on, addon, section)")] PuzzlePieceSolid,
        [Description("Python (f3e2)")] PythonBrands,
        [Description("QQ (f1d6)")] QqBrands,
        [Description("qrcode (f029, scan)")] QrcodeSolid,
        [Description("Question Circle (f059, help, information, support, unknown)")] QuestionCircleRegular,
        [Description("Question Circle (f059, help, information, support, unknown)")] QuestionCircleSolid,
        [Description("Question (f128, help, information, support, unknown)")] QuestionSolid,
        [Description("Quidditch (f458)")] QuidditchSolid,
        [Description("QuinScape (f459)")] QuinscapeBrands,
        [Description("Quora (f2c4)")] QuoraBrands,
        [Description("quote-left (f10d)")] QuoteLeftSolid,
        [Description("quote-right (f10e)")] QuoteRightSolid,
        [Description("random (f074, shuffle, sort)")] RandomSolid,
        [Description("Ravelry (f2d9)")] RavelryBrands,
        [Description("React (f41b)")] ReactBrands,
        [Description("ReadMe (f4d5)")] ReadmeBrands,
        [Description("Rebel Alliance (f1d0)")] RebelBrands,
        [Description("Receipt (f543, check, invoice, table)")] ReceiptSolid,
        [Description("Recycle (f1b8)")] RecycleSolid,
        [Description("reddit Alien (f281)")] RedditAlienBrands,
        [Description("reddit Logo (f1a1)")] RedditBrands,
        [Description("reddit Square (f1a2)")] RedditSquareBrands,
        [Description("Alternate Redo (f2f9, forward, repeat)")] RedoAltSolid,
        [Description("Redo (f01e, forward, repeat, repeat)")] RedoSolid,
        [Description("red river (f3e3)")] RedRiverBrands,
        [Description("Registered Trademark (f25d)")] RegisteredRegular,
        [Description("Registered Trademark (f25d)")] RegisteredSolid,
        [Description("Rendact (f3e4)")] RendactBrands,
        [Description("Renren (f18b)")] RenrenBrands,
        [Description("reply-all (f122)")] ReplyAllSolid,
        [Description("replyd (f3e6)")] ReplydBrands,
        [Description("Reply (f3e5)")] ReplySolid,
        [Description("Researchgate (f4f8)")] ResearchgateBrands,
        [Description("Resolving (f3e7)")] ResolvingBrands,
        [Description("Retweet (f079, refresh, reload, share, swap)")] RetweetSolid,
        [Description("Ribbon (f4d6, badge, cause, lapel, pin)")] RibbonSolid,
        [Description("road (f018, street)")] RoadSolid,
        [Description("Robot (f544)")] RobotSolid,
        [Description("Rocket.Chat (f3e8)")] RocketchatBrands,
        [Description("rocket (f135, app)")] RocketSolid,
        [Description("Rockrms (f3e9)")] RockrmsBrands,
        [Description("R Project (f4f7)")] RProjectBrands,
        [Description("rss (f09e, blog)")] RssSolid,
        [Description("RSS Square (f143, blog, feed)")] RssSquareSolid,
        [Description("Ruble Sign (f158, rub, rub)")] RubleSignSolid,
        [Description("Ruler Combined (f546)")] RulerCombinedSolid,
        [Description("Ruler Horizontal (f547)")] RulerHorizontalSolid,
        [Description("Ruler (f545)")] RulerSolid,
        [Description("Ruler Vertical (f548)")] RulerVerticalSolid,
        [Description("Indian Rupee Sign (f156, indian, inr)")] RupeeSignSolid,
        [Description("Crying Face (f5b3)")] SadCryRegular,
        [Description("Crying Face (f5b3)")] SadCrySolid,
        [Description("Loudly Crying Face (f5b4)")] SadTearRegular,
        [Description("Loudly Crying Face (f5b4)")] SadTearSolid,
        [Description("Safari (f267, browser)")] SafariBrands,
        [Description("Sass (f41e)")] SassBrands,
        [Description("Save (f0c7, floppy, floppy-o)")] SaveRegular,
        [Description("Save (f0c7, floppy, floppy-o)")] SaveSolid,
        [Description("SCHLIX (f3ea)")] SchlixBrands,
        [Description("School (f549)")] SchoolSolid,
        [Description("Screwdriver (f54a, admin, container, fix, repair, settings, tool)")] ScrewdriverSolid,
        [Description("Scribd (f28a)")] ScribdBrands,
        [Description("Searchengin (f3eb)")] SearchenginBrands,
        [Description("Search Minus (f010, magnify, minify, smaller, zoom, zoom out)")] SearchMinusSolid,
        [Description("Search Plus (f00e, bigger, enlarge, magnify, zoom, zoom in)")] SearchPlusSolid,
        [Description("Search (f002, bigger, enlarge, magnify, preview, zoom)")] SearchSolid,
        [Description("Seedling (f4d8)")] SeedlingSolid,
        [Description("Sellcast (f2da, eercast)")] SellcastBrands,
        [Description("Sellsy (f213)")] SellsyBrands,
        [Description("Server (f233, cpu)")] ServerSolid,
        [Description("Servicestack (f3ec)")] ServicestackBrands,
        [Description("Alternate Share (f1e0)")] ShareAltSolid,
        [Description("Alternate Share Square (f1e1)")] ShareAltSquareSolid,
        [Description("Share (f064)")] ShareSolid,
        [Description("Share Square (f14d, send, social)")] ShareSquareRegular,
        [Description("Share Square (f14d, send, social)")] ShareSquareSolid,
        [Description("Shekel Sign (f20b, ils, ils)")] ShekelSignSolid,
        [Description("Alternate Shield (f3ed, shield)")] ShieldAltSolid,
        [Description("Shipping Fast (f48b)")] ShippingFastSolid,
        [Description("Ship (f21a, boat, sea)")] ShipSolid,
        [Description("Shirts in Bulk (f214)")] ShirtsinbulkBrands,
        [Description("Shoe Prints (f54b, feet, footprints, steps)")] ShoePrintsSolid,
        [Description("Shopping Bag (f290)")] ShoppingBagSolid,
        [Description("Shopping Basket (f291)")] ShoppingBasketSolid,
        [Description("shopping-cart (f07a, buy, checkout, payment, purchase)")] ShoppingCartSolid,
        [Description("Shopware (f5b5)")] ShopwareBrands,
        [Description("Shower (f2cc)")] ShowerSolid,
        [Description("Shuttle Van (f5b6, machine, public-transportation, transportation, vehicle)")] ShuttleVanSolid,
        [Description("signal (f012, bars, graph, online, status)")] SignalSolid,
        [Description("Signature (f5b7, John Hancock, cursive, name, writing)")] SignatureSolid,
        [Description("Alternate Sign In (f2f6, arrow, enter, join, log in, login, sign in, sign up, sign-in, signin, signup)")] SignInAltSolid,
        [Description("Sign Language (f2a7)")] SignLanguageSolid,
        [Description("Alternate Sign Out (f2f5, arrow, exit, leave, log out, logout, sign-out)")] SignOutAltSolid,
        [Description("Sign (f4d9)")] SignSolid,
        [Description("SimplyBuilt (f215)")] SimplybuiltBrands,
        [Description("SISTRIX (f3ee)")] SistrixBrands,
        [Description("Sitemap (f0e8, directory, hierarchy, ia, information architecture, organization)")] SitemapSolid,
        [Description("Sith (f512)")] SithBrands,
        [Description("Skull (f54c, bones, skeleton, yorick)")] SkullSolid,
        [Description("skyatlas (f216)")] SkyatlasBrands,
        [Description("Skype (f17e)")] SkypeBrands,
        [Description("Slack Logo (f198, anchor, hash, hashtag)")] SlackBrands,
        [Description("Slack Hashtag (f3ef, anchor, hash, hashtag)")] SlackHashBrands,
        [Description("Horizontal Sliders (f1de, settings, sliders)")] SlidersHSolid,
        [Description("Slideshare (f1e7)")] SlideshareBrands,
        [Description("Beaming Face With Smiling Eyes (f5b8)")] SmileBeamRegular,
        [Description("Beaming Face With Smiling Eyes (f5b8)")] SmileBeamSolid,
        [Description("Smiling Face (f118, approve, emoticon, face, happy, rating, satisfied)")] SmileRegular,
        [Description("Smiling Face (f118, approve, emoticon, face, happy, rating, satisfied)")] SmileSolid,
        [Description("Winking Face (f4da)")] SmileWinkRegular,
        [Description("Winking Face (f4da)")] SmileWinkSolid,
        [Description("Smoking Ban (f54d, no smoking, non-smoking)")] SmokingBanSolid,
        [Description("Smoking (f48d, cigarette, nicotine, smoking status)")] SmokingSolid,
        [Description("Snapchat (f2ab)")] SnapchatBrands,
        [Description("Snapchat Ghost (f2ac)")] SnapchatGhostBrands,
        [Description("Snapchat Square (f2ad)")] SnapchatSquareBrands,
        [Description("Snowflake (f2dc)")] SnowflakeRegular,
        [Description("Snowflake (f2dc)")] SnowflakeSolid,
        [Description("Solar Panel (f5ba, clean, eco-friendly, energy, green, sun)")] SolarPanelSolid,
        [Description("Sort Alpha Down (f15d, sort-alpha-asc)")] SortAlphaDownSolid,
        [Description("Sort Alpha Up (f15e, sort-alpha-desc)")] SortAlphaUpSolid,
        [Description("Sort Amount Down (f160, sort-amount-asc)")] SortAmountDownSolid,
        [Description("Sort Amount Up (f161, sort-amount-desc)")] SortAmountUpSolid,
        [Description("Sort Down (Descending) (f0dd, arrow, descending, sort-desc)")] SortDownSolid,
        [Description("Sort Numeric Down (f162, numbers, sort-numeric-asc)")] SortNumericDownSolid,
        [Description("Sort Numeric Up (f163, numbers, sort-numeric-desc)")] SortNumericUpSolid,
        [Description("Sort (f0dc, order)")] SortSolid,
        [Description("Sort Up (Ascending) (f0de, arrow, ascending, sort-asc)")] SortUpSolid,
        [Description("SoundCloud (f1be)")] SoundcloudBrands,
        [Description("Space Shuttle (f197, astronaut, machine, nasa, rocket, transportation)")] SpaceShuttleSolid,
        [Description("Spa (f5bb, mindfullness, plant, wellness)")] SpaSolid,
        [Description("Speakap (f3f3)")] SpeakapBrands,
        [Description("Spinner (f110, loading, progress)")] SpinnerSolid,
        [Description("Splotch (f5bc)")] SplotchSolid,
        [Description("Spotify (f1bc)")] SpotifyBrands,
        [Description("Spray Can (f5bd)")] SprayCanSolid,
        [Description("Square Full (f45c)")] SquareFullSolid,
        [Description("Square (f0c8, block, box)")] SquareRegular,
        [Description("Square (f0c8, block, box)")] SquareSolid,
        [Description("Squarespace (f5be)")] SquarespaceBrands,
        [Description("Stack Exchange (f18d)")] StackExchangeBrands,
        [Description("Stack Overflow (f16c)")] StackOverflowBrands,
        [Description("Stamp (f5bf)")] StampSolid,
        [Description("Alternate Star Half (f5c0, achievement, award, rating, score, star-half-empty, star-half-full)")] StarHalfAltSolid,
        [Description("star-half (f089, achievement, award, rating, score, star-half-empty, star-half-full)")] StarHalfRegular,
        [Description("star-half (f089, achievement, award, rating, score, star-half-empty, star-half-full)")] StarHalfSolid,
        [Description("Star (f005, achievement, award, favorite, important, night, rating, score)")] StarRegular,
        [Description("Star (f005, achievement, award, favorite, important, night, rating, score)")] StarSolid,
        [Description("StayLinked (f3f5)")] StaylinkedBrands,
        [Description("Steam (f1b6)")] SteamBrands,
        [Description("Steam Square (f1b7)")] SteamSquareBrands,
        [Description("Steam Symbol (f3f6)")] SteamSymbolBrands,
        [Description("step-backward (f048, beginning, first, previous, rewind, start)")] StepBackwardSolid,
        [Description("step-forward (f051, end, last, next)")] StepForwardSolid,
        [Description("Stethoscope (f0f1)")] StethoscopeSolid,
        [Description("Sticker Mule (f3f7)")] StickerMuleBrands,
        [Description("Sticky Note (f249)")] StickyNoteRegular,
        [Description("Sticky Note (f249)")] StickyNoteSolid,
        [Description("Stop Circle (f28d)")] StopCircleRegular,
        [Description("Stop Circle (f28d)")] StopCircleSolid,
        [Description("stop (f04d, block, box, square)")] StopSolid,
        [Description("Stopwatch (f2f2, time)")] StopwatchSolid,
        [Description("Alternate Store (f54f)")] StoreAltSolid,
        [Description("Store (f54e)")] StoreSolid,
        [Description("Strava (f428)")] StravaBrands,
        [Description("Stream (f550)")] StreamSolid,
        [Description("Street View (f21d, map)")] StreetViewSolid,
        [Description("Strikethrough (f0cc)")] StrikethroughSolid,
        [Description("Stripe (f429)")] StripeBrands,
        [Description("Stripe S (f42a)")] StripeSBrands,
        [Description("Stroopwafel (f551, dessert, food, sweets, waffle)")] StroopwafelSolid,
        [Description("Studio Vinari (f3f8)")] StudiovinariBrands,
        [Description("StumbleUpon Logo (f1a4)")] StumbleuponBrands,
        [Description("StumbleUpon Circle (f1a3)")] StumbleuponCircleBrands,
        [Description("subscript (f12c)")] SubscriptSolid,
        [Description("Subway (f239, machine, railway, train, transportation, vehicle)")] SubwaySolid,
        [Description("Suitcase Rolling (f5c1)")] SuitcaseRollingSolid,
        [Description("Suitcase (f0f2, baggage, luggage, move, suitcase, travel, trip)")] SuitcaseSolid,
        [Description("Sun (f185, brighten, contrast, day, lighter, weather)")] SunRegular,
        [Description("Sun (f185, brighten, contrast, day, lighter, weather)")] SunSolid,
        [Description("Superpowers (f2dd)")] SuperpowersBrands,
        [Description("superscript (f12b, exponential)")] SuperscriptSolid,
        [Description("Supple (f3f9)")] SuppleBrands,
        [Description("Hushed Face (f5c2)")] SurpriseRegular,
        [Description("Hushed Face (f5c2)")] SurpriseSolid,
        [Description("Swatchbook (f5c3)")] SwatchbookSolid,
        [Description("Swimmer (f5c4, athlete, head, man, person, water)")] SwimmerSolid,
        [Description("Swimming Pool (f5c5, ladder, recreation, water)")] SwimmingPoolSolid,
        [Description("Alternate Sync (f2f1, refresh, reload, rotate)")] SyncAltSolid,
        [Description("Sync (f021, exchange, refresh, reload, rotate, swap)")] SyncSolid,
        [Description("Syringe (f48e, immunizations, needle)")] SyringeSolid,
        [Description("table (f0ce, data, excel, spreadsheet)")] TableSolid,
        [Description("Alternate Tablet (f3fa, apple, device, ipad, kindle, screen)")] TabletAltSolid,
        [Description("Table Tennis (f45d)")] TableTennisSolid,
        [Description("tablet (f10a, apple, device, ipad, kindle, screen)")] TabletSolid,
        [Description("Tablets (f490, drugs, medicine)")] TabletsSolid,
        [Description("Alternate Tachometer (f3fd, dashboard, tachometer)")] TachometerAltSolid,
        [Description("tag (f02b, label)")] TagSolid,
        [Description("tags (f02c, labels)")] TagsSolid,
        [Description("Tape (f4db)")] TapeSolid,
        [Description("Tasks (f0ae, downloading, downloads, loading, progress, settings)")] TasksSolid,
        [Description("Taxi (f1ba, cab, cabbie, car, car service, lyft, machine, transportation, uber, vehicle)")] TaxiSolid,
        [Description("TeamSpeak (f4f9)")] TeamspeakBrands,
        [Description("Telegram (f2c6)")] TelegramBrands,
        [Description("Telegram Plane (f3fe)")] TelegramPlaneBrands,
        [Description("Tencent Weibo (f1d5)")] TencentWeiboBrands,
        [Description("Terminal (f120, code, command, console, prompt)")] TerminalSolid,
        [Description("text-height (f034)")] TextHeightSolid,
        [Description("text-width (f035)")] TextWidthSolid,
        [Description("Themeco (f5c6)")] ThemecoBrands,
        [Description("ThemeIsle (f2b2)")] ThemeisleBrands,
        [Description("Thermometer Empty (f2cb, status)")] ThermometerEmptySolid,
        [Description("Thermometer Full (f2c7, status)")] ThermometerFullSolid,
        [Description("Thermometer 1/2 Full (f2c9, status)")] ThermometerHalfSolid,
        [Description("Thermometer 1/4 Full (f2ca, status)")] ThermometerQuarterSolid,
        [Description("Thermometer (f491, fever, temperature)")] ThermometerSolid,
        [Description("Thermometer 3/4 Full (f2c8, status)")] ThermometerThreeQuartersSolid,
        [Description("th-large (f009, blocks, boxes, grid, squares)")] ThLargeSolid,
        [Description("th-list (f00b, checklist, completed, done, finished, ol, todo, ul)")] ThListSolid,
        [Description("th (f00a, blocks, boxes, grid, squares)")] ThSolid,
        [Description("thumbs-down (f165, disagree, disapprove, dislike, hand, thumbs-o-down)")] ThumbsDownRegular,
        [Description("thumbs-down (f165, disagree, disapprove, dislike, hand, thumbs-o-down)")] ThumbsDownSolid,
        [Description("thumbs-up (f164, agree, approve, favorite, hand, like, ok, okay, success, thumbs-o-up, yes, you got it dude)")] ThumbsUpRegular,
        [Description("thumbs-up (f164, agree, approve, favorite, hand, like, ok, okay, success, thumbs-o-up, yes, you got it dude)")] ThumbsUpSolid,
        [Description("Thumbtack (f08d, coordinates, location, marker, pin, thumb-tack)")] ThumbtackSolid,
        [Description("Alternate Ticket (f3ff, ticket)")] TicketAltSolid,
        [Description("Times Circle (f057, close, cross, exit, incorrect, notice, notification, notify, problem, wrong, x)")] TimesCircleRegular,
        [Description("Times Circle (f057, close, cross, exit, incorrect, notice, notification, notify, problem, wrong, x)")] TimesCircleSolid,
        [Description("Times (f00d, close, cross, error, exit, incorrect, notice, notification, notify, problem, wrong, x)")] TimesSolid,
        [Description("Tint Slash (f5c7)")] TintSlashSolid,
        [Description("tint (f043, drop, droplet, raindrop, waterdrop)")] TintSolid,
        [Description("Tired Face (f5c8)")] TiredRegular,
        [Description("Tired Face (f5c8)")] TiredSolid,
        [Description("Toggle Off (f204, switch)")] ToggleOffSolid,
        [Description("Toggle On (f205, switch)")] ToggleOnSolid,
        [Description("Toolbox (f552, admin, container, fix, repair, settings, tools)")] ToolboxSolid,
        [Description("Tooth (f5c9)")] ToothSolid,
        [Description("Trade Federation (f513)")] TradeFederationBrands,
        [Description("Trademark (f25c)")] TrademarkSolid,
        [Description("Train (f238, bullet, locomotive, railway)")] TrainSolid,
        [Description("Alternate Transgender (f225)")] TransgenderAltSolid,
        [Description("Transgender (f224, intersex)")] TransgenderSolid,
        [Description("Alternate Trash (f2ed, delete, garbage, hide, remove, trash, trash-o)")] TrashAltRegular,
        [Description("Alternate Trash (f2ed, delete, garbage, hide, remove, trash, trash-o)")] TrashAltSolid,
        [Description("Trash (f1f8, delete, garbage, hide, remove)")] TrashSolid,
        [Description("Tree (f1bb)")] TreeSolid,
        [Description("Trello (f181)")] TrelloBrands,
        [Description("TripAdvisor (f262)")] TripadvisorBrands,
        [Description("trophy (f091, achievement, award, cup, game, winner)")] TrophySolid,
        [Description("Truck Loading (f4de)")] TruckLoadingSolid,
        [Description("Truck Moving (f4df)")] TruckMovingSolid,
        [Description("truck (f0d1, delivery, shipping)")] TruckSolid,
        [Description("T-Shirt (f553, cloth, clothing)")] TshirtSolid,
        [Description("TTY (f1e4)")] TtySolid,
        [Description("Tumblr (f173)")] TumblrBrands,
        [Description("Tumblr Square (f174)")] TumblrSquareBrands,
        [Description("Television (f26c, computer, display, monitor, television)")] TvSolid,
        [Description("Twitch (f1e8)")] TwitchBrands,
        [Description("Twitter (f099, social network, tweet)")] TwitterBrands,
        [Description("Twitter Square (f081, social network, tweet)")] TwitterSquareBrands,
        [Description("Typo3 (f42b)")] Typo3Brands,
        [Description("Uber (f402)")] UberBrands,
        [Description("UIkit (f403)")] UikitBrands,
        [Description("Umbrella Beach (f5ca, protection, recreation, sun)")] UmbrellaBeachSolid,
        [Description("Umbrella (f0e9, protection, rain)")] UmbrellaSolid,
        [Description("Underline (f0cd)")] UnderlineSolid,
        [Description("Alternate Undo (f2ea, back, control z, exchange, oops, return, swap)")] UndoAltSolid,
        [Description("Undo (f0e2, back, control z, exchange, oops, return, rotate, swap)")] UndoSolid,
        [Description("Uniregistry (f404)")] UniregistryBrands,
        [Description("Universal Access (f29a)")] UniversalAccessSolid,
        [Description("University (f19c, bank, institution)")] UniversitySolid,
        [Description("unlink (f127, chain, chain-broken, remove)")] UnlinkSolid,
        [Description("Alternate Unlock (f13e, admin, lock, password, protect)")] UnlockAltSolid,
        [Description("unlock (f09c, admin, lock, password, protect)")] UnlockSolid,
        [Description("Untappd (f405)")] UntappdBrands,
        [Description("Upload (f093, export, publish)")] UploadSolid,
        [Description("USB (f287)")] UsbBrands,
        [Description("Alternate User Slash (f4fa)")] UserAltSlashSolid,
        [Description("Alternate User (f406, account, avatar, head, man, person, profile)")] UserAltSolid,
        [Description("User Astronaut (f4fb, avatar, clothing, cosmonaut, space, suit)")] UserAstronautSolid,
        [Description("User Check (f4fc)")] UserCheckSolid,
        [Description("User Circle (f2bd, account, avatar, head, man, person, profile)")] UserCircleRegular,
        [Description("User Circle (f2bd, account, avatar, head, man, person, profile)")] UserCircleSolid,
        [Description("User Clock (f4fd)")] UserClockSolid,
        [Description("User Cog (f4fe)")] UserCogSolid,
        [Description("User Edit (f4ff)")] UserEditSolid,
        [Description("User Friends (f500)")] UserFriendsSolid,
        [Description("User Graduate (f501, cap, clothing, commencement, gown, graduation, student)")] UserGraduateSolid,
        [Description("User Lock (f502)")] UserLockSolid,
        [Description("user-md (f0f0, doctor, job, medical, nurse, occupation, profile)")] UserMdSolid,
        [Description("User Minus (f503)")] UserMinusSolid,
        [Description("User Ninja (f504, assassin, avatar, dangerous, sneaky)")] UserNinjaSolid,
        [Description("Add User (f234, sign up, signup)")] UserPlusSolid,
        [Description("User (f007, account, avatar, head, man, person, profile)")] UserRegular,
        [Description("Users Cog (f509)")] UsersCogSolid,
        [Description("User Secret (f21b, clothing, coat, hat, incognito, privacy, spy, whisper)")] UserSecretSolid,
        [Description("User Shield (f505)")] UserShieldSolid,
        [Description("User Slash (f506)")] UserSlashSolid,
        [Description("User (f007, account, avatar, head, man, person, profile)")] UserSolid,
        [Description("Users (f0c0, people, persons, profiles)")] UsersSolid,
        [Description("User Tag (f507)")] UserTagSolid,
        [Description("User Tie (f508, avatar, business, clothing, formal)")] UserTieSolid,
        [Description("Remove User (f235)")] UserTimesSolid,
        [Description("us-Sunnah Foundation (f407)")] UssunnahBrands,
        [Description("Utensil Spoon (f2e5, spoon)")] UtensilSpoonSolid,
        [Description("Utensils (f2e7, cutlery, dinner, eat, food, knife, restaurant, spoon)")] UtensilsSolid,
        [Description("Vaadin (f408)")] VaadinBrands,
        [Description("Vector Square (f5cb)")] VectorSquareSolid,
        [Description("Venus Double (f226)")] VenusDoubleSolid,
        [Description("Venus Mars (f228)")] VenusMarsSolid,
        [Description("Venus (f221, female)")] VenusSolid,
        [Description("Viacoin (f237)")] ViacoinBrands,
        [Description("Viadeo (f2a9)")] ViadeoBrands,
        [Description("Viadeo Square (f2aa)")] ViadeoSquareBrands,
        [Description("Vial (f492, test tube)")] VialSolid,
        [Description("Vials (f493, lab results, test tubes)")] VialsSolid,
        [Description("Viber (f409)")] ViberBrands,
        [Description("Video Slash (f4e2)")] VideoSlashSolid,
        [Description("Video (f03d, camera, film, movie, record, video-camera)")] VideoSolid,
        [Description("Vimeo (f40a)")] VimeoBrands,
        [Description("Vimeo Square (f194)")] VimeoSquareBrands,
        [Description("Vimeo (f27d, vimeo)")] VimeoVBrands,
        [Description("Vine (f1ca)")] VineBrands,
        [Description("VK (f189)")] VkBrands,
        [Description("VNV (f40b)")] VnvBrands,
        [Description("Volleyball Ball (f45f)")] VolleyballBallSolid,
        [Description("volume-down (f027, audio, lower, music, quieter, sound, speaker)")] VolumeDownSolid,
        [Description("volume-off (f026, audio, music, mute, sound)")] VolumeOffSolid,
        [Description("volume-up (f028, audio, higher, louder, music, sound, speaker)")] VolumeUpSolid,
        [Description("Vue.js (f41f)")] VuejsBrands,
        [Description("Walking (f554)")] WalkingSolid,
        [Description("Wallet (f555)")] WalletSolid,
        [Description("Warehouse (f494)")] WarehouseSolid,
        [Description("Weebly (f5cc)")] WeeblyBrands,
        [Description("Weibo (f18a)")] WeiboBrands,
        [Description("Hanging Weight (f5cd, anvil, heavy, measurement)")] WeightHangingSolid,
        [Description("Weight (f496, measurement, scale, weight)")] WeightSolid,
        [Description("Weixin (WeChat) (f1d7)")] WeixinBrands,
        [Description("What's App (f232)")] WhatsappBrands,
        [Description("What's App Square (f40c)")] WhatsappSquareBrands,
        [Description("Wheelchair (f193, handicap, person)")] WheelchairSolid,
        [Description("WHMCS (f40d)")] WhmcsBrands,
        [Description("WiFi (f1eb)")] WifiSolid,
        [Description("Wikipedia W (f266)")] WikipediaWBrands,
        [Description("Window Close (f410)")] WindowCloseRegular,
        [Description("Window Close (f410)")] WindowCloseSolid,
        [Description("Window Maximize (f2d0)")] WindowMaximizeRegular,
        [Description("Window Maximize (f2d0)")] WindowMaximizeSolid,
        [Description("Window Minimize (f2d1)")] WindowMinimizeRegular,
        [Description("Window Minimize (f2d1)")] WindowMinimizeSolid,
        [Description("Window Restore (f2d2)")] WindowRestoreRegular,
        [Description("Window Restore (f2d2)")] WindowRestoreSolid,
        [Description("Windows (f17a, microsoft)")] WindowsBrands,
        [Description("Wine Glass-alt (f5ce)")] WineGlassAltSolid,
        [Description("Wine Glass (f4e3)")] WineGlassSolid,
        [Description("Wix (f5cf)")] WixBrands,
        [Description("Wolf Pack-battalion (f514)")] WolfPackBattalionBrands,
        [Description("Won Sign (f159, krw, krw)")] WonSignSolid,
        [Description("WordPress Logo (f19a)")] WordpressBrands,
        [Description("Wordpress Simple (f411)")] WordpressSimpleBrands,
        [Description("WPBeginner (f297)")] WpbeginnerBrands,
        [Description("WPExplorer (f2de)")] WpexplorerBrands,
        [Description("WPForms (f298)")] WpformsBrands,
        [Description("Wrench (f0ad, fix, settings, spanner, tool, update)")] WrenchSolid,
        [Description("Xbox (f412)")] XboxBrands,
        [Description("Xing (f168)")] XingBrands,
        [Description("Xing Square (f169)")] XingSquareBrands,
        [Description("X-Ray (f497, radiological images, radiology)")] XRaySolid,
        [Description("Yahoo Logo (f19e)")] YahooBrands,
        [Description("Yandex (f413)")] YandexBrands,
        [Description("Yandex International (f414)")] YandexInternationalBrands,
        [Description("Y Combinator (f23b)")] YCombinatorBrands,
        [Description("Yelp (f1e9)")] YelpBrands,
        [Description("Yen Sign (f157, jpy, jpy)")] YenSignSolid,
        [Description("Yoast (f2b1)")] YoastBrands,
        [Description("YouTube (f167, film, video, youtube-play, youtube-square)")] YoutubeBrands,
        [Description("YouTube Square (f431)")] YoutubeSquareBrands,
    }
}