namespace MahApps.Metro.IconPacks
{
#if !(NETFX_CORE || WINDOWS_UWP)
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconFeatherIcons" />.
    /// </summary>
    /// <remarks>
    /// Feather is licensed under the MIT License <see><cref>https://github.com/feathericons/feather/blob/master/LICENSE</cref></see>
    /// Contributions, corrections and requests can be made on GitHub <see><cref>https://github.com/feathericons/feather</cref></see>.
    /// </remarks>
    public enum PackIconFeatherIconsKind
    {
        [Description("Empty placeholder")] None,
        [Description("activity (Pulse, Health, Action, Motion)")] Activity,
        [Description("airplay (Stream, Cast, Mirroring)")] Airplay,
        [Description("alert-circle (Warning, Alert, Danger)")] AlertCircle,
        [Description("alert-octagon (Warning, Alert, Danger)")] AlertOctagon,
        [Description("alert-triangle (Warning, Alert, Danger)")] AlertTriangle,
        [Description("align-center")] AlignCenter,
        [Description("align-justify")] AlignJustify,
        [Description("align-left")] AlignLeft,
        [Description("align-right")] AlignRight,
        [Description("anchor")] Anchor,
        [Description("aperture (Camera, Photo)")] Aperture,
        [Description("archive")] Archive,
        [Description("arrow-down")] ArrowDown,
        [Description("arrow-down-circle")] ArrowDownCircle,
        [Description("arrow-down-left")] ArrowDownLeft,
        [Description("arrow-down-right")] ArrowDownRight,
        [Description("arrow-left")] ArrowLeft,
        [Description("arrow-left-circle")] ArrowLeftCircle,
        [Description("arrow-right")] ArrowRight,
        [Description("arrow-right-circle")] ArrowRightCircle,
        [Description("arrow-up")] ArrowUp,
        [Description("arrow-up-circle")] ArrowUpCircle,
        [Description("arrow-up-left")] ArrowUpLeft,
        [Description("arrow-up-right")] ArrowUpRight,
        [Description("at-sign (Mention, At, Email, Message)")] AtSign,
        [Description("award (Achievement, Badge)")] Award,
        [Description("bar-chart")] BarChart,
        [Description("bar-chart-2")] BarChart2,
        [Description("battery")] Battery,
        [Description("battery-charging")] BatteryCharging,
        [Description("bell (Alarm, Notification, Sound)")] Bell,
        [Description("bell-off (Alarm, Notification, Silent)")] BellOff,
        [Description("bluetooth (Wireless)")] Bluetooth,
        [Description("bold")] Bold,
        [Description("book (Read, Dictionary, Booklet, Magazine, Library)")] Book,
        [Description("bookmark (Read, Clip, Marker, Tag)")] Bookmark,
        [Description("book-open (Read, Library)")] BookOpen,
        [Description("box")] Box,
        [Description("briefcase (Work, Bag, Baggage, Folder)")] Briefcase,
        [Description("calendar")] Calendar,
        [Description("camera")] Camera,
        [Description("camera-off")] CameraOff,
        [Description("cast")] Cast,
        [Description("check")] Check,
        [Description("check-circle")] CheckCircle,
        [Description("check-square")] CheckSquare,
        [Description("chevron-down")] ChevronDown,
        [Description("chevron-left")] ChevronLeft,
        [Description("chevron-right")] ChevronRight,
        [Description("chevrons-down")] ChevronsDown,
        [Description("chevrons-left")] ChevronsLeft,
        [Description("chevrons-right")] ChevronsRight,
        [Description("chevrons-up")] ChevronsUp,
        [Description("chevron-up")] ChevronUp,
        [Description("chrome")] Chrome,
        [Description("circle")] Circle,
        [Description("clipboard (Copy)")] Clipboard,
        [Description("clock (Time, Watch, Alarm)")] Clock,
        [Description("cloud (Weather)")] Cloud,
        [Description("cloud-drizzle (Weather, Shower)")] CloudDrizzle,
        [Description("cloud-lightning (Weather, Bolt)")] CloudLightning,
        [Description("cloud-off")] CloudOff,
        [Description("cloud-rain (Weather)")] CloudRain,
        [Description("cloud-snow (Weather, Blizzard)")] CloudSnow,
        [Description("code")] Code,
        [Description("codepen (Logo)")] Codepen,
        [Description("codesandbox (Logo)")] Codesandbox,
        [Description("coffee (Drink, Cup, Mug, Tea, Cafe, Hot, Beverage)")] Coffee,
        [Description("columns")] Columns,
        [Description("command (Keyboard, Cmd, Terminal, Prompt)")] Command,
        [Description("compass (Navigation, Safari, Travel, Direction)")] Compass,
        [Description("copy (Clone, Duplicate)")] Copy,
        [Description("corner-down-left (Arrow)")] CornerDownLeft,
        [Description("corner-down-right (Arrow)")] CornerDownRight,
        [Description("corner-left-down (Arrow)")] CornerLeftDown,
        [Description("corner-left-up (Arrow)")] CornerLeftUp,
        [Description("corner-right-down (Arrow)")] CornerRightDown,
        [Description("corner-right-up (Arrow)")] CornerRightUp,
        [Description("corner-up-left (Arrow)")] CornerUpLeft,
        [Description("corner-up-right (Arrow)")] CornerUpRight,
        [Description("cpu")] Cpu,
        [Description("credit-card (Purchase, Payment, Cc)")] CreditCard,
        [Description("crop (Photo, Image)")] Crop,
        [Description("crosshair (Aim, Target)")] Crosshair,
        [Description("database (Storage, Memory)")] Database,
        [Description("delete (Remove)")] Delete,
        [Description("disc (Album, Cd, Dvd, Music)")] Disc,
        [Description("dollar-sign (Currency, Money, Payment)")] DollarSign,
        [Description("download")] Download,
        [Description("download-cloud")] DownloadCloud,
        [Description("droplet (Water)")] Droplet,
        [Description("edit (Pencil, Change)")] Edit,
        [Description("edit-2 (Pencil, Change)")] Edit2,
        [Description("edit-3 (Pencil, Change)")] Edit3,
        [Description("external-link (Outbound)")] ExternalLink,
        [Description("eye (View, Watch)")] Eye,
        [Description("eye-off (View, Watch, Hide, Hidden)")] EyeOff,
        [Description("facebook (Logo, Social)")] Facebook,
        [Description("fast-forward (Music)")] FastForward,
        [Description("feather")] Feather,
        [Description("figma (Logo, Design, Tool)")] Figma,
        [Description("file")] File,
        [Description("file-minus")] FileMinus,
        [Description("file-plus")] FilePlus,
        [Description("file-text")] FileText,
        [Description("film (Movie, Video)")] Film,
        [Description("filter")] Filter,
        [Description("flag")] Flag,
        [Description("folder (Directory)")] Folder,
        [Description("folder-minus (Directory)")] FolderMinus,
        [Description("folder-plus (Directory)")] FolderPlus,
        [Description("framer (Logo, Design, Tool)")] Framer,
        [Description("frown (Emoji, Face, Bad, Sad, Emotion)")] Frown,
        [Description("gift (Present, Box, Birthday, Party)")] Gift,
        [Description("git-branch (Code, VersionControl)")] GitBranch,
        [Description("git-commit (Code, VersionControl)")] GitCommit,
        [Description("github (Logo, VersionControl)")] Github,
        [Description("gitlab (Logo, VersionControl)")] Gitlab,
        [Description("git-merge (Code, VersionControl)")] GitMerge,
        [Description("git-pull-request (Code, VersionControl)")] GitPullRequest,
        [Description("globe")] Globe,
        [Description("grid")] Grid,
        [Description("hard-drive (Computer, Server, Memory, Data)")] HardDrive,
        [Description("hash (Hashtag, Number, Pound)")] Hash,
        [Description("headphones (Music, Audio, Sound)")] Headphones,
        [Description("heart (Like, Love, Emotion)")] Heart,
        [Description("help-circle (QuestionMark)")] HelpCircle,
        [Description("hexagon (Shape, NodeJs, Logo)")] Hexagon,
        [Description("home (House, Living)")] Home,
        [Description("image (Picture)")] Image,
        [Description("inbox (Email)")] Inbox,
        [Description("info")] Info,
        [Description("instagram (Logo, Camera)")] Instagram,
        [Description("italic")] Italic,
        [Description("key (Password, Login, Authentication, Secure)")] Key,
        [Description("layers")] Layers,
        [Description("layout")] Layout,
        [Description("life-buoy")] LifeBuoy,
        [Description("link")] Link,
        [Description("link-2")] Link2,
        [Description("linkedin (Logo, SocialMedia)")] Linkedin,
        [Description("list")] List,
        [Description("loader")] Loader,
        [Description("lock (Security, Password, Secure)")] Lock,
        [Description("log-in (SignIn, Arrow, Enter)")] LogIn,
        [Description("log-out (SignOut, Arrow, Exit)")] LogOut,
        [Description("mail (Email, Message)")] Mail,
        [Description("map (Location, Navigation, Travel)")] Map,
        [Description("map-pin (Location, Navigation, Travel, Marker)")] MapPin,
        [Description("maximize (Fullscreen)")] Maximize,
        [Description("maximize-2 (Fullscreen, Arrows, Expand)")] Maximize2,
        [Description("meh (Emoji, Face, Neutral, Emotion)")] Meh,
        [Description("menu (Bars, Navigation, Hamburger)")] Menu,
        [Description("message-circle (Comment, Chat)")] MessageCircle,
        [Description("message-square (Comment, Chat)")] MessageSquare,
        [Description("mic (Record, Sound, Listen)")] Mic,
        [Description("mic-off (Record, Sound, Mute)")] MicOff,
        [Description("minimize (ExitFullscreen, Close)")] Minimize,
        [Description("minimize-2 (ExitFullscreen, Arrows, Close)")] Minimize2,
        [Description("minus")] Minus,
        [Description("minus-circle")] MinusCircle,
        [Description("minus-square")] MinusSquare,
        [Description("monitor (Tv, Screen, Display)")] Monitor,
        [Description("moon (Dark, Night)")] Moon,
        [Description("more-horizontal (Ellipsis)")] MoreHorizontal,
        [Description("more-vertical (Ellipsis)")] MoreVertical,
        [Description("mouse-pointer (Arrow, Cursor)")] MousePointer,
        [Description("move (Arrows)")] Move,
        [Description("music")] Music,
        [Description("navigation (Location, Travel)")] Navigation,
        [Description("navigation-2 (Location, Travel)")] Navigation2,
        [Description("octagon (Stop)")] Octagon,
        [Description("package (Box, Container)")] Package,
        [Description("paperclip (Attachment)")] Paperclip,
        [Description("pause (Music, Stop)")] Pause,
        [Description("pause-circle (Music, Audio, Stop)")] PauseCircle,
        [Description("pen-tool (Vector, Drawing)")] PenTool,
        [Description("percent")] Percent,
        [Description("phone")] Phone,
        [Description("phone-call")] PhoneCall,
        [Description("phone-forwarded")] PhoneForwarded,
        [Description("phone-incoming")] PhoneIncoming,
        [Description("phone-missed")] PhoneMissed,
        [Description("phone-off")] PhoneOff,
        [Description("phone-outgoing")] PhoneOutgoing,
        [Description("pie-chart")] PieChart,
        [Description("play (Music, Start)")] Play,
        [Description("play-circle (Music, Start)")] PlayCircle,
        [Description("plus (Add, New)")] Plus,
        [Description("plus-circle (Add, New)")] PlusCircle,
        [Description("plus-square (Add, New)")] PlusSquare,
        [Description("pocket (Logo, Save)")] Pocket,
        [Description("power (On, Off)")] Power,
        [Description("printer")] Printer,
        [Description("radio (Signal)")] Radio,
        [Description("refresh-ccw")] RefreshCcw,
        [Description("refresh-cw")] RefreshCw,
        [Description("repeat")] Repeat,
        [Description("rewind (Music)")] Rewind,
        [Description("rotate-ccw")] RotateCcw,
        [Description("rotate-cw")] RotateCw,
        [Description("rss (Feed, Subscribe)")] Rss,
        [Description("save (FloppyDisk)")] Save,
        [Description("scissors")] Scissors,
        [Description("search (Find, Magnifier, MagnifyingGlass)")] Search,
        [Description("send (Message, Mail, Email, PaperAirplane, PaperAeroplane)")] Send,
        [Description("server")] Server,
        [Description("settings (Cog, Edit, Gear, Preferences)")] Settings,
        [Description("share")] Share,
        [Description("share-2")] Share2,
        [Description("shield (Security, Secure)")] Shield,
        [Description("shield-off (Security, Insecure)")] ShieldOff,
        [Description("shopping-bag (Ecommerce, Cart, Purchase, Store)")] ShoppingBag,
        [Description("shopping-cart (Ecommerce, Cart, Purchase, Store)")] ShoppingCart,
        [Description("shuffle (Music)")] Shuffle,
        [Description("sidebar")] Sidebar,
        [Description("skip-back (Music)")] SkipBack,
        [Description("skip-forward (Music)")] SkipForward,
        [Description("slack")] Slack,
        [Description("slash (Ban, No)")] Slash,
        [Description("sliders (Settings, Controls)")] Sliders,
        [Description("smartphone")] Smartphone,
        [Description("smile (Emoji, Face, Happy, Good, Emotion)")] Smile,
        [Description("speaker (Music)")] Speaker,
        [Description("square")] Square,
        [Description("star (Bookmark, Favorite, Like)")] Star,
        [Description("stop-circle")] StopCircle,
        [Description("sun (Brightness, Weather, Light)")] Sun,
        [Description("sunrise (Weather, Time, Morning, Day)")] Sunrise,
        [Description("sunset (Weather, Time, Evening, Night)")] Sunset,
        [Description("tablet")] Tablet,
        [Description("tag (Label)")] Tag,
        [Description("target (Bullseye)")] Target,
        [Description("terminal (Code, CommandLine, Prompt)")] Terminal,
        [Description("thermometer")] Thermometer,
        [Description("thumbs-down (Dislike, Bad, Emotion)")] ThumbsDown,
        [Description("thumbs-up (Like, Good, Emotion)")] ThumbsUp,
        [Description("toggle-left (On, Off, Switch)")] ToggleLeft,
        [Description("toggle-right (On, Off, Switch)")] ToggleRight,
        [Description("tool")] Tool,
        [Description("trash (Garbage, Delete, Remove, Bin)")] Trash,
        [Description("trash-2 (Garbage, Delete, Remove, Bin)")] Trash2,
        [Description("trello")] Trello,
        [Description("trending-down")] TrendingDown,
        [Description("trending-up")] TrendingUp,
        [Description("triangle (Delta)")] Triangle,
        [Description("truck (Delivery, Van, Shipping, Transport, Lorry)")] Truck,
        [Description("tv")] Tv,
        [Description("twitch")] Twitch,
        [Description("twitter (Logo, Social)")] Twitter,
        [Description("type")] Type,
        [Description("umbrella (Rain, Weather)")] Umbrella,
        [Description("underline")] Underline,
        [Description("unlock")] Unlock,
        [Description("upload")] Upload,
        [Description("upload-cloud")] UploadCloud,
        [Description("user")] User,
        [Description("user-check")] UserCheck,
        [Description("user-minus")] UserMinus,
        [Description("user-plus")] UserPlus,
        [Description("users")] Users,
        [Description("user-x")] UserX,
        [Description("video (Camera, Movie, Film)")] Video,
        [Description("video-off (Camera, Movie, Film)")] VideoOff,
        [Description("voicemail (Phone)")] Voicemail,
        [Description("volume (Music, Sound, Mute)")] Volume,
        [Description("volume-1 (Music, Sound)")] Volume1,
        [Description("volume-2 (Music, Sound)")] Volume2,
        [Description("volume-x (Music, Sound, Mute)")] VolumeX,
        [Description("watch (Clock, Time)")] Watch,
        [Description("wifi")] Wifi,
        [Description("wifi-off")] WifiOff,
        [Description("wind (Weather, Air)")] Wind,
        [Description("x (Cancel, Close, Delete, Remove, Times, Clear)")] X,
        [Description("x-circle (Cancel, Close, Delete, Remove, Times, Clear)")] XCircle,
        [Description("x-octagon (Delete, Stop, Alert, Warning, Times, Clear)")] XOctagon,
        [Description("x-square (Cancel, Close, Delete, Remove, Times, Clear)")] XSquare,
        [Description("youtube (Logo, Video, Play)")] Youtube,
        [Description("zap (Flash, Camera, Lightning)")] Zap,
        [Description("zap-off (Flash, Camera, Lightning)")] ZapOff,
        [Description("zoom-in")] ZoomIn,
        [Description("zoom-out")] ZoomOut,
    }
}