namespace MahApps.Metro.IconPacks
{
#if !NETFX_CORE
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconTypicons" />.
    /// </summary>
    /// <remarks>
    /// Typicons Icons/Artwork distributed under [CC BY-SA](<see><cref>https://creativecommons.org/licenses/by-sa/3.0/</cref></see>) licence.
    /// Typicons Font distributed under 'SIL Open Font License' licence.
    /// </remarks>
    public enum PackIconTypiconsKind
    {
        [Description("Empty placeholder")] None,
        [Description("adjust-brightness (Sun)")] AdjustBrightness,
        [Description("adjust-contrast (Half)")] AdjustContrast,
        [Description("anchor")] Anchor,
        [Description("anchor-outline")] AnchorOutline,
        [Description("archive")] Archive,
        [Description("arrow-back")] ArrowBack,
        [Description("arrow-back-outline")] ArrowBackOutline,
        [Description("arrow-down")] ArrowDown,
        [Description("arrow-down-outline")] ArrowDownOutline,
        [Description("arrow-down-thick")] ArrowDownThick,
        [Description("arrow-forward")] ArrowForward,
        [Description("arrow-forward-outline")] ArrowForwardOutline,
        [Description("arrow-left")] ArrowLeft,
        [Description("arrow-left-outline")] ArrowLeftOutline,
        [Description("arrow-left-thick")] ArrowLeftThick,
        [Description("arrow-loop")] ArrowLoop,
        [Description("arrow-loop-outline")] ArrowLoopOutline,
        [Description("arrow-maximise")] ArrowMaximise,
        [Description("arrow-maximise-outline")] ArrowMaximiseOutline,
        [Description("arrow-minimise")] ArrowMinimise,
        [Description("arrow-minimise-outline")] ArrowMinimiseOutline,
        [Description("arrow-move")] ArrowMove,
        [Description("arrow-move-outline")] ArrowMoveOutline,
        [Description("arrow-repeat")] ArrowRepeat,
        [Description("arrow-repeat-outline")] ArrowRepeatOutline,
        [Description("arrow-right")] ArrowRight,
        [Description("arrow-right-outline")] ArrowRightOutline,
        [Description("arrow-right-thick")] ArrowRightThick,
        [Description("arrow-shuffle")] ArrowShuffle,
        [Description("arrow-sorted-down")] ArrowSortedDown,
        [Description("arrow-sorted-up")] ArrowSortedUp,
        [Description("arrow-sync")] ArrowSync,
        [Description("arrow-sync-outline")] ArrowSyncOutline,
        [Description("arrow-unsorted")] ArrowUnsorted,
        [Description("arrow-up")] ArrowUp,
        [Description("arrow-up-outline")] ArrowUpOutline,
        [Description("arrow-up-thick")] ArrowUpThick,
        [Description("at")] At,
        [Description("attachment")] Attachment,
        [Description("attachment-outline")] AttachmentOutline,
        [Description("backspace (Delete)")] Backspace,
        [Description("backspace-outline (Delete)")] BackspaceOutline,
        [Description("battery-charge (Power)")] BatteryCharge,
        [Description("battery-full (Power)")] BatteryFull,
        [Description("battery-high (Power)")] BatteryHigh,
        [Description("battery-low (Power)")] BatteryLow,
        [Description("battery-mid (Power)")] BatteryMid,
        [Description("beaker (Lab, Beta, Experiment)")] Beaker,
        [Description("beer (Ale, Lager)")] Beer,
        [Description("bell (Tone, Alarm)")] Bell,
        [Description("book")] Book,
        [Description("bookmark (Banner, Flag)")] Bookmark,
        [Description("briefcase")] Briefcase,
        [Description("brush")] Brush,
        [Description("business-card (Id)")] BusinessCard,
        [Description("calculator")] Calculator,
        [Description("calendar")] Calendar,
        [Description("calendar-outline")] CalendarOutline,
        [Description("camera (Photo)")] Camera,
        [Description("camera-outline")] CameraOutline,
        [Description("cancel")] Cancel,
        [Description("cancel-outline (Photo)")] CancelOutline,
        [Description("chart-area (Graph)")] ChartArea,
        [Description("chart-area-outline (Graph)")] ChartAreaOutline,
        [Description("chart-bar (Graph)")] ChartBar,
        [Description("chart-bar-outline (Graph)")] ChartBarOutline,
        [Description("chart-line (Graph)")] ChartLine,
        [Description("chart-line-outline (Graph)")] ChartLineOutline,
        [Description("chart-pie (Graph)")] ChartPie,
        [Description("chart-pie-outline (Graph)")] ChartPieOutline,
        [Description("chevron-left (LessThan)")] ChevronLeft,
        [Description("chevron-left-outline (LessThan)")] ChevronLeftOutline,
        [Description("chevron-right (GreaterThan)")] ChevronRight,
        [Description("chevron-right-outline (GreaterThan)")] ChevronRightOutline,
        [Description("clipboard (Copy)")] Clipboard,
        [Description("cloud-storage (Data, Upload)")] CloudStorage,
        [Description("cloud-storage-outline (Data, Upload)")] CloudStorageOutline,
        [Description("code (Tag)")] Code,
        [Description("code-outline (Tag)")] CodeOutline,
        [Description("coffee (Beverage)")] Coffee,
        [Description("cog (Settings)")] Cog,
        [Description("cog-outline (Settings)")] CogOutline,
        [Description("compass (Safari)")] Compass,
        [Description("contacts (Address, Book)")] Contacts,
        [Description("credit-card (Payment)")] CreditCard,
        [Description("css3")] Css3,
        [Description("database (Db)")] Database,
        [Description("delete (Cross, Close)")] Delete,
        [Description("delete-outline (Cross, Close)")] DeleteOutline,
        [Description("device-desktop (Pc, Mac)")] DeviceDesktop,
        [Description("device-laptop (Notebook, Macbook)")] DeviceLaptop,
        [Description("device-phone (Iphone)")] DevicePhone,
        [Description("device-tablet (Ipad)")] DeviceTablet,
        [Description("directions")] Directions,
        [Description("divide (Division)")] Divide,
        [Description("divide-outline (Division)")] DivideOutline,
        [Description("document (File)")] Document,
        [Description("document-add (File)")] DocumentAdd,
        [Description("document-delete (File)")] DocumentDelete,
        [Description("document-text (File)")] DocumentText,
        [Description("download")] Download,
        [Description("download-outline")] DownloadOutline,
        [Description("dropbox")] Dropbox,
        [Description("edit (Pencil)")] Edit,
        [Description("eject (Export, Log, Off, Out)")] Eject,
        [Description("eject-outline (Export, Log, Off, Out)")] EjectOutline,
        [Description("equals")] Equals,
        [Description("equals-outline")] EqualsOutline,
        [Description("export (Share)")] Export,
        [Description("export-outline (Share)")] ExportOutline,
        [Description("eye (View)")] Eye,
        [Description("eye-outline (View)")] EyeOutline,
        [Description("feather")] Feather,
        [Description("film (Strip)")] Film,
        [Description("filter (Funnel, Refine)")] Filter,
        [Description("flag")] Flag,
        [Description("flag-outline")] FlagOutline,
        [Description("flash (Power, Lightning)")] Flash,
        [Description("flash-outline (Power, Lightning)")] FlashOutline,
        [Description("flow-children")] FlowChildren,
        [Description("flow-merge")] FlowMerge,
        [Description("flow-parallel")] FlowParallel,
        [Description("flow-switch")] FlowSwitch,
        [Description("folder (Directory)")] Folder,
        [Description("folder-add (Directory)")] FolderAdd,
        [Description("folder-delete (Directory)")] FolderDelete,
        [Description("folder-open (Directory)")] FolderOpen,
        [Description("gift (Present)")] Gift,
        [Description("globe")] Globe,
        [Description("globe-outline")] GlobeOutline,
        [Description("group (Users)")] Group,
        [Description("group-outline (Users)")] GroupOutline,
        [Description("headphones")] Headphones,
        [Description("heart (Like, Favourite, Love)")] Heart,
        [Description("heart-full-outline (Like, Favourite, Love)")] HeartFullOutline,
        [Description("heart-half-outline (Like, Favourite, Love)")] HeartHalfOutline,
        [Description("heart-outline (Like, Favourite, Love)")] HeartOutline,
        [Description("home")] Home,
        [Description("home-outline")] HomeOutline,
        [Description("html5")] Html5,
        [Description("image (Picture, Photo)")] Image,
        [Description("image-outline (Picture, Photo)")] ImageOutline,
        [Description("infinity")] Infinity,
        [Description("infinity-outline")] InfinityOutline,
        [Description("info")] Info,
        [Description("info-large")] InfoLarge,
        [Description("info-large-outline")] InfoLargeOutline,
        [Description("info-outline")] InfoOutline,
        [Description("input-checked (Tick, Correct)")] InputChecked,
        [Description("input-checked-outline (Tick, Correct)")] InputCheckedOutline,
        [Description("key (Password, Login)")] Key,
        [Description("keyboard")] Keyboard,
        [Description("key-outline (Password, Login)")] KeyOutline,
        [Description("leaf")] Leaf,
        [Description("lightbulb (Idea)")] Lightbulb,
        [Description("link (Chain)")] Link,
        [Description("link-outline (Chain)")] LinkOutline,
        [Description("location (Map, Pin)")] Location,
        [Description("location-arrow (Direction)")] LocationArrow,
        [Description("location-arrow-outline (Direction)")] LocationArrowOutline,
        [Description("location-outline (Map, Pin)")] LocationOutline,
        [Description("lock-closed (Locked)")] LockClosed,
        [Description("lock-closed-outline (Locked)")] LockClosedOutline,
        [Description("lock-open")] LockOpen,
        [Description("lock-open-outline")] LockOpenOutline,
        [Description("mail (Email)")] Mail,
        [Description("map (Brochure, Pamphlet)")] Map,
        [Description("media-eject")] MediaEject,
        [Description("media-eject-outline")] MediaEjectOutline,
        [Description("media-fast-forward")] MediaFastForward,
        [Description("media-fast-forward-outline")] MediaFastForwardOutline,
        [Description("media-pause")] MediaPause,
        [Description("media-pause-outline")] MediaPauseOutline,
        [Description("media-play")] MediaPlay,
        [Description("media-play-outline")] MediaPlayOutline,
        [Description("media-play-reverse")] MediaPlayReverse,
        [Description("media-play-reverse-outline")] MediaPlayReverseOutline,
        [Description("media-record")] MediaRecord,
        [Description("media-record-outline")] MediaRecordOutline,
        [Description("media-rewind")] MediaRewind,
        [Description("media-rewind-outline")] MediaRewindOutline,
        [Description("media-stop")] MediaStop,
        [Description("media-stop-outline")] MediaStopOutline,
        [Description("message (Msg, Chat)")] Message,
        [Description("messages (Msg, Chat)")] Messages,
        [Description("message-typing (Msg, Chat)")] MessageTyping,
        [Description("microphone (Record)")] Microphone,
        [Description("microphone-outline (Record)")] MicrophoneOutline,
        [Description("minus (Subtract)")] Minus,
        [Description("minus-outline (Subtract)")] MinusOutline,
        [Description("mortar-board")] MortarBoard,
        [Description("news (Article)")] News,
        [Description("notes (Music)")] Notes,
        [Description("notes-outline (Music)")] NotesOutline,
        [Description("pen (Write, Compose)")] Pen,
        [Description("pencil (Write, Compose)")] Pencil,
        [Description("phone (Call, Ring)")] Phone,
        [Description("phone-outline (Call, Ring)")] PhoneOutline,
        [Description("pi")] Pi,
        [Description("pin")] Pin,
        [Description("pin-outline")] PinOutline,
        [Description("pi-outline")] PiOutline,
        [Description("pipette (Picker)")] Pipette,
        [Description("plane (Flight)")] Plane,
        [Description("plane-outline (Flight)")] PlaneOutline,
        [Description("plug (Connect)")] Plug,
        [Description("plus (Add)")] Plus,
        [Description("plus-outline (Add)")] PlusOutline,
        [Description("point-of-interest (Command)")] PointOfInterest,
        [Description("point-of-interest-outline (Command)")] PointOfInterestOutline,
        [Description("power (On, Off)")] Power,
        [Description("power-outline (On, Off)")] PowerOutline,
        [Description("printer (Fax)")] Printer,
        [Description("puzzle (Jigsaw)")] Puzzle,
        [Description("puzzle-outline (Jigsaw)")] PuzzleOutline,
        [Description("radar (Position)")] Radar,
        [Description("radar-outline (Position)")] RadarOutline,
        [Description("refresh (Arrow)")] Refresh,
        [Description("refresh-outline (Arrow)")] RefreshOutline,
        [Description("rss (Feed)")] Rss,
        [Description("rss-outline (Feed)")] RssOutline,
        [Description("scissors (Cut)")] Scissors,
        [Description("scissors-outline (Cut)")] ScissorsOutline,
        [Description("shopping-bag")] ShoppingBag,
        [Description("shopping-cart")] ShoppingCart,
        [Description("social-at-circular (@, Mail)")] SocialAtCircular,
        [Description("social-dribbble")] SocialDribbble,
        [Description("social-dribbble-circular")] SocialDribbbleCircular,
        [Description("social-facebook")] SocialFacebook,
        [Description("social-facebook-circular")] SocialFacebookCircular,
        [Description("social-flickr")] SocialFlickr,
        [Description("social-flickr-circular")] SocialFlickrCircular,
        [Description("social-github")] SocialGithub,
        [Description("social-github-circular")] SocialGithubCircular,
        [Description("social-google-plus")] SocialGooglePlus,
        [Description("social-google-plus-circular")] SocialGooglePlusCircular,
        [Description("social-instagram")] SocialInstagram,
        [Description("social-instagram-circular")] SocialInstagramCircular,
        [Description("social-last-fm")] SocialLastFm,
        [Description("social-last-fm-circular")] SocialLastFmCircular,
        [Description("social-linkedin")] SocialLinkedin,
        [Description("social-linkedin-circular")] SocialLinkedinCircular,
        [Description("social-pinterest")] SocialPinterest,
        [Description("social-pinterest-circular")] SocialPinterestCircular,
        [Description("social-skype")] SocialSkype,
        [Description("social-skype-outline")] SocialSkypeOutline,
        [Description("social-tumbler")] SocialTumbler,
        [Description("social-tumbler-circular")] SocialTumblerCircular,
        [Description("social-twitter")] SocialTwitter,
        [Description("social-twitter-circular")] SocialTwitterCircular,
        [Description("social-vimeo")] SocialVimeo,
        [Description("social-vimeo-circular")] SocialVimeoCircular,
        [Description("social-youtube")] SocialYoutube,
        [Description("social-youtube-circular")] SocialYoutubeCircular,
        [Description("sort-alphabetically (AZ)")] SortAlphabetically,
        [Description("sort-alphabetically-outline (AZ)")] SortAlphabeticallyOutline,
        [Description("sort-numerically (_123)")] SortNumerically,
        [Description("sort-numerically-outline (_123)")] SortNumericallyOutline,
        [Description("spanner (Settings)")] Spanner,
        [Description("spanner-outline (Settings)")] SpannerOutline,
        [Description("spiral (Curve)")] Spiral,
        [Description("star (Like, Favourite, Love, Rate)")] Star,
        [Description("starburst (Banner, Ribbon)")] Starburst,
        [Description("starburst-outline (Banner, Ribbon)")] StarburstOutline,
        [Description("star-full-outline (Like, Favourite, Love, Rate)")] StarFullOutline,
        [Description("star-half (Like, Favourite, Love, Rate)")] StarHalf,
        [Description("star-half-outline (Like, Favourite, Love, Rate)")] StarHalfOutline,
        [Description("star-outline (Like, Favourite, Love, Rate)")] StarOutline,
        [Description("stopwatch (Time)")] Stopwatch,
        [Description("support (Life, Ring)")] Support,
        [Description("tabs-outline (Expand, Merge)")] TabsOutline,
        [Description("tag")] Tag,
        [Description("tags")] Tags,
        [Description("thermometer (Temperature)")] Thermometer,
        [Description("th-large (Square, Grid)")] ThLarge,
        [Description("th-large-outline (Square, Grid)")] ThLargeOutline,
        [Description("th-list (Thumbnail)")] ThList,
        [Description("th-list-outline (Thumbnail)")] ThListOutline,
        [Description("th-menu")] ThMenu,
        [Description("th-menu-outline")] ThMenuOutline,
        [Description("th-small (Square, Grid)")] ThSmall,
        [Description("th-small-outline (Square, Grid)")] ThSmallOutline,
        [Description("thumbs-down (Dislike)")] ThumbsDown,
        [Description("thumbs-ok (Average)")] ThumbsOk,
        [Description("thumbs-up (Like)")] ThumbsUp,
        [Description("tick (Ok, Done, Correct)")] Tick,
        [Description("ticket (Pass)")] Ticket,
        [Description("tick-outline (Ok, Done, Correct)")] TickOutline,
        [Description("time (Watch, Clock)")] Time,
        [Description("times (Cross, X)")] Times,
        [Description("times-outline (Cross, X)")] TimesOutline,
        [Description("trash (Garbage, Rubbish, Delete)")] Trash,
        [Description("tree")] Tree,
        [Description("upload")] Upload,
        [Description("upload-outline")] UploadOutline,
        [Description("user (Person)")] User,
        [Description("user-add (Person)")] UserAdd,
        [Description("user-add-outline (Person)")] UserAddOutline,
        [Description("user-delete (Person)")] UserDelete,
        [Description("user-delete-outline (Person)")] UserDeleteOutline,
        [Description("user-outline (Person)")] UserOutline,
        [Description("vendor-android")] VendorAndroid,
        [Description("vendor-apple")] VendorApple,
        [Description("vendor-microsoft")] VendorMicrosoft,
        [Description("video")] Video,
        [Description("video-outline")] VideoOutline,
        [Description("volume (Sound)")] Volume,
        [Description("volume-down (Sound)")] VolumeDown,
        [Description("volume-mute (Sound)")] VolumeMute,
        [Description("volume-up (Sound)")] VolumeUp,
        [Description("warning (Error, Alert)")] Warning,
        [Description("warning-outline (Error, Alert)")] WarningOutline,
        [Description("watch (Time)")] Watch,
        [Description("waves")] Waves,
        [Description("waves-outline")] WavesOutline,
        [Description("weather-cloudy")] WeatherCloudy,
        [Description("weather-downpour")] WeatherDownpour,
        [Description("weather-night")] WeatherNight,
        [Description("weather-partly-sunny")] WeatherPartlySunny,
        [Description("weather-shower")] WeatherShower,
        [Description("weather-snow")] WeatherSnow,
        [Description("weather-stormy")] WeatherStormy,
        [Description("weather-sunny")] WeatherSunny,
        [Description("weather-windy")] WeatherWindy,
        [Description("weather-windy-cloudy")] WeatherWindyCloudy,
        [Description("wi-fi (Internet, Connection)")] WiFi,
        [Description("wi-fi-outline (Internet, Connection)")] WiFiOutline,
        [Description("wine (Drink, Beverage)")] Wine,
        [Description("world")] World,
        [Description("world-outline")] WorldOutline,
        [Description("zoom")] Zoom,
        [Description("zoom-in")] ZoomIn,
        [Description("zoom-in-outline")] ZoomInOutline,
        [Description("zoom-out")] ZoomOut,
        [Description("zoom-outline")] ZoomOutline,
        [Description("zoom-out-outline")] ZoomOutOutline,
    }
}