namespace MahApps.Metro.IconPacks
{
#if NETFX_CORE
    using MahApps.Metro.IconPacks.Core;
#else
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconOcticons" />.
    /// </summary>
    /// <remarks>
    /// All icons sourced from GitHub Octicons - <see><cref>https://octicons.github.com</cref></see> - 
    /// <see><cref>https://github.com/primer/octicons/blob/master/LICENSE</cref></see>.
    /// </remarks>
    public enum PackIconOcticonsKind
    {
        [Description("Empty placeholder")] None,
        [Description("Alert (Warning, Triangle, Exclamation, Point)")] Alert,
        [Description("ArrowDown (Point, Direction)")] ArrowDown,
        [Description("ArrowLeft (Point, Direction)")] ArrowLeft,
        [Description("ArrowRight (Point, Direction)")] ArrowRight,
        [Description("ArrowSmallDown (Point, Direction)")] ArrowSmallDown,
        [Description("ArrowSmallLeft (Point, Direction, Little, Tiny)")] ArrowSmallLeft,
        [Description("ArrowSmallRight (Point, Direction, Little, Tiny)")] ArrowSmallRight,
        [Description("ArrowSmallUp (Point, Direction, Little, Tiny)")] ArrowSmallUp,
        [Description("ArrowUp (Point, Direction)")] ArrowUp,
        [Description("Beaker (Experiment, Labs, Experimental, Feature, Test, Science, Education, Study, Development, Testing)")] Beaker,
        [Description("Bell (Notification)")] Bell,
        [Description("Bold (Bold)")] Bold,
        [Description("Book (Book, Journal, Wiki, Readme)")] Book,
        [Description("Bookmark (Tabbard)")] Bookmark,
        [Description("Briefcase (Suitcase, Business)")] Briefcase,
        [Description("Broadcast (Rss, Radio, Signal)")] Broadcast,
        [Description("Browser (Window, Web)")] Browser,
        [Description("Bug (Insect)")] Bug,
        [Description("Calendar (Time, Day, Month, Year)")] Calendar,
        [Description("Check (Mark, Yes, Confirm, Accept, Ok, Success)")] Check,
        [Description("Checklist (Todo)")] Checklist,
        [Description("ChevronDown (Triangle, Arrow)")] ChevronDown,
        [Description("ChevronLeft (Triangle, Arrow)")] ChevronLeft,
        [Description("ChevronRight (Triangle, Arrow)")] ChevronRight,
        [Description("ChevronUp (Triangle, Arrow)")] ChevronUp,
        [Description("CircleSlash (No, Deny, Fail, Failure, Error, Bad)")] CircleSlash,
        [Description("CircuitBoard (Developer, Hardware, Electricity)")] CircuitBoard,
        [Description("Clippy (Copy, Paste, Save, Capture)")] Clippy,
        [Description("Clock (Time, Hour, Minute, Second)")] Clock,
        [Description("CloudDownload (Save, Install, Get)")] CloudDownload,
        [Description("CloudUpload (Put, Export)")] CloudUpload,
        [Description("Code (Brackets)")] Code,
        [Description("Comment (Speak, Bubble)")] Comment,
        [Description("CommentDiscussion (Converse, Talk)")] CommentDiscussion,
        [Description("CreditCard (Money, Billing, Payments, Transactions)")] CreditCard,
        [Description("Dash (Hyphen, Range)")] Dash,
        [Description("Dashboard (Speed, Dial)")] Dashboard,
        [Description("Database (Disks, Data)")] Database,
        [Description("DesktopDownload (Clone, Download)")] DesktopDownload,
        [Description("DeviceCamera (Photo, Picture, Image, Snapshot)")] DeviceCamera,
        [Description("DeviceCameraVideo (Watch, View, Media, Stream)")] DeviceCameraVideo,
        [Description("DeviceDesktop (Computer, Monitor)")] DeviceDesktop,
        [Description("DeviceMobile (Phone, Iphone, Cellphone)")] DeviceMobile,
        [Description("Diff (Difference, Changes, Compare)")] Diff,
        [Description("DiffAdded (New, Addition)")] DiffAdded,
        [Description("DiffIgnored (Slash)")] DiffIgnored,
        [Description("DiffModified (Dot, Changed, Updated)")] DiffModified,
        [Description("DiffRemoved (Deleted, Subtracted, Dash)")] DiffRemoved,
        [Description("DiffRenamed (Moved, Arrow)")] DiffRenamed,
        [Description("Ellipses (Dot, More)")] Ellipses,
        [Description("Ellipsis (Read, More, Hidden, Expand)")] Ellipsis,
        [Description("Eye (Look, Watch, See)")] Eye,
        [Description("File (File)")] File,
        [Description("FileBinary (Image, Video, Word, Powerpoint, Excel)")] FileBinary,
        [Description("FileCode (Text, Javascript, Html, Css, Php, Ruby, Coffeescript, Sass, Scss)")] FileCode,
        [Description("FileDirectory (Folder)")] FileDirectory,
        [Description("FileMedia (Image, Video, Audio)")] FileMedia,
        [Description("FilePdf (Adobe)")] FilePdf,
        [Description("FileSubmodule (Folder)")] FileSubmodule,
        [Description("FileSymlinkDirectory (Folder, Subfolder, Link, Alias)")] FileSymlinkDirectory,
        [Description("FileSymlinkFile (Link, Alias)")] FileSymlinkFile,
        [Description("FileText (Document)")] FileText,
        [Description("FileZip (Compress, Archive)")] FileZip,
        [Description("Flame (Fire, Hot, Burn, Trending)")] Flame,
        [Description("Fold (Unfold, Hide, Collapse)")] Fold,
        [Description("Gear (Settings)")] Gear,
        [Description("Gift (Package, Present, Skill, Craft, Freebie)")] Gift,
        [Description("Gist (Gist, Github)")] Gist,
        [Description("GistSecret (Gist, Secret, Private)")] GistSecret,
        [Description("GitBranch (Branch, Git)")] GitBranch,
        [Description("GitCommit (Save)")] GitCommit,
        [Description("GitCompare (Difference, Changes)")] GitCompare,
        [Description("GitMerge (Join)")] GitMerge,
        [Description("GitPullRequest (Review)")] GitPullRequest,
        [Description("Globe (World)")] Globe,
        [Description("Grabber (Mover, Drap, Drop)")] Grabber,
        [Description("Graph (Trend, Stats, Statistics)")] Graph,
        [Description("Heart (Love)")] Heart,
        [Description("History (Time, Past, Revert, Back)")] History,
        [Description("Home (Welcome, Index, House, Building)")] Home,
        [Description("HorizontalRule (Hr)")] HorizontalRule,
        [Description("Hubot (Robot)")] Hubot,
        [Description("Inbox (Mail, Todo, New, Messages)")] Inbox,
        [Description("Info (Help)")] Info,
        [Description("IssueClosed (Done, Complete)")] IssueClosed,
        [Description("IssueOpened (New)")] IssueOpened,
        [Description("IssueReopened (Regression)")] IssueReopened,
        [Description("Italic (Font, Italic, Style)")] Italic,
        [Description("Jersey (Team, Game, Basketball)")] Jersey,
        [Description("Key (Key, Lock, Secure, Safe)")] Key,
        [Description("Keyboard (Type, Keys, Write, Shortcuts)")] Keyboard,
        [Description("Law (Legal, Bill)")] Law,
        [Description("LightBulb (Idea)")] LightBulb,
        [Description("Link (Connect, Hyperlink)")] Link,
        [Description("LinkExternal (Out, See, More, Go, To)")] LinkExternal,
        [Description("ListOrdered (Numbers, Tasks, Todo, Items)")] ListOrdered,
        [Description("ListUnordered (Bullet, Point, Tasks, Todo, Items)")] ListUnordered,
        [Description("Location (Here, Marker)")] Location,
        [Description("Lock (Secure, Safe, Protected)")] Lock,
        [Description("LogoGist (Logo, Gist)")] LogoGist,
        [Description("LogoGithub (Brand)")] LogoGithub,
        [Description("Mail (Email, Unread)")] Mail,
        [Description("MailRead (Email, Open)")] MailRead,
        [Description("MailReply (Email)")] MailReply,
        [Description("Markdown (Markup, Style)")] Markdown,
        [Description("MarkGithub (Octocat)")] MarkGithub,
        [Description("Megaphone (Bullhorn, Loud, Shout, Broadcast)")] Megaphone,
        [Description("Mention (At, Ping)")] Mention,
        [Description("Milestone (Marker)")] Milestone,
        [Description("Mirror (Reflect)")] Mirror,
        [Description("MortarBoard (Education, Learn, Teach)")] MortarBoard,
        [Description("Mute (Quiet, Sound, Audio, Turn, Off)")] Mute,
        [Description("NoNewline (Return)")] NoNewline,
        [Description("Note (Card, Paper, Ticket)")] Note,
        [Description("Octoface (Octocat)")] Octoface,
        [Description("Organization (People, Group, Team)")] Organization,
        [Description("Package (Box, Ship)")] Package,
        [Description("Paintcan (Style, Theme, Art, Color)")] Paintcan,
        [Description("Pencil (Edit, Change, Update, Write)")] Pencil,
        [Description("Person (People, Man, Woman, Human)")] Person,
        [Description("Pin (People, Save, Star, Bookmark)")] Pin,
        [Description("Plug (Hook, Webhook)")] Plug,
        [Description("Plus (Add, New, More)")] Plus,
        [Description("PlusSmall (Add, New, More, Small)")] PlusSmall,
        [Description("PrimitiveDot (Circle)")] PrimitiveDot,
        [Description("PrimitiveSquare (Box)")] PrimitiveSquare,
        [Description("Project (Board, Kanban, Columns, Scrum)")] Project,
        [Description("Pulse (Graph, Trend, Line)")] Pulse,
        [Description("Question (Help, Explain)")] Question,
        [Description("Quote (Quotation)")] Quote,
        [Description("RadioTower (Broadcast)")] RadioTower,
        [Description("Reply (ReplyAll, Back)")] Reply,
        [Description("Repo (Book, Journal)")] Repo,
        [Description("RepoClone (Book, Journal)")] RepoClone,
        [Description("RepoForcePush (Book, Journal, Put)")] RepoForcePush,
        [Description("RepoForked (Book, Journal, Copy)")] RepoForked,
        [Description("RepoPull (Book, Journal, Get)")] RepoPull,
        [Description("RepoPush (Book, Journal, Put)")] RepoPush,
        [Description("Rocket (Staff, Stafftools, Blast, Off, Space)")] Rocket,
        [Description("Rss (Broadcast, Feed)")] Rss,
        [Description("Ruby (Code)")] Ruby,
        [Description("ScreenFull (Fullscreen, Expand)")] ScreenFull,
        [Description("ScreenNormal (Fullscreen, Expand, Exit)")] ScreenNormal,
        [Description("Search (Magnifying, Glass)")] Search,
        [Description("Server (Computers, Racks, Ops)")] Server,
        [Description("Settings (Sliders, Filters)")] Settings,
        [Description("Shield (Protect, Shield, Lock)")] Shield,
        [Description("SignIn (Door, Arrow, Direction, Enter)")] SignIn,
        [Description("SignOut (Door, Arrow, Direction, Leave)")] SignOut,
        [Description("Smiley (Emoji, Smile, Mood, Emotion)")] Smiley,
        [Description("Squirrel (Ship, Shipit)")] Squirrel,
        [Description("Star (Save, Remember, Like)")] Star,
        [Description("Stop (Block, Spam)")] Stop,
        [Description("Sync (Cycle, Refresh, Loop)")] Sync,
        [Description("Tag (Release)")] Tag,
        [Description("Tasklist (Todo)")] Tasklist,
        [Description("Telescope (Science, Space, Look, View, Explore)")] Telescope,
        [Description("Terminal (Code, Ops, Shell)")] Terminal,
        [Description("TextSize (Font, Size, Text)")] TextSize,
        [Description("ThreeBars (Hamburger)")] ThreeBars,
        [Description("Thumbsdown (Thumb, Thumbsdown, Rejected)")] Thumbsdown,
        [Description("Thumbsup (Thumb, Thumbsup, Prop, Ship)")] Thumbsup,
        [Description("Tools (Screwdriver, Wrench, Settings)")] Tools,
        [Description("Trashcan (Garbage, Rubbish, Recycle, Delete)")] Trashcan,
        [Description("TriangleDown (Arrow, Point, Direction)")] TriangleDown,
        [Description("TriangleLeft (Arrow, Point, Direction)")] TriangleLeft,
        [Description("TriangleRight (Arrow, Point, Direction)")] TriangleRight,
        [Description("TriangleUp (Arrow, Point, Direction)")] TriangleUp,
        [Description("Unfold (Expand, Open, Reveal)")] Unfold,
        [Description("Unmute (Loud, Volume, Audio, Sound, Play)")] Unmute,
        [Description("Unverified (Insecure, Untrusted)")] Unverified,
        [Description("Verified (Trusted, Secure, Trustworthy)")] Verified,
        [Description("Versions (History)")] Versions,
        [Description("Watch (Wait, Hourglass)")] Watch,
        [Description("X (Remove, Close, Delete)")] X,
        [Description("Zap (Electricity, Lightning, Props, Like, Star, Save)")] Zap,
    }
}