namespace MahApps.Metro.IconPacks
{
#if NETFX_CORE
    using MahApps.Metro.IconPacks.Core;
#else
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconSimpleIcons" />.
    /// </summary>
    /// <remarks>
    /// All SVG icons for popular brands, maintained by Dan Leech <see><cref>https://twitter.com/bathtype</cref></see>.
    /// Contributions, corrections and requests can be made on GitHub <see><cref>https://github.com/danleech/simple-icons</cref></see>.
    /// </remarks>
    public enum PackIconSimpleIconsKind
    {
        [Description("Empty placeholder")] None,
        [Description("500px, https://about.500px.com/press")] _500px,
        [Description("About.me, https://about.me/assets")] AboutMe,
        [Description("ACM, http://identitystandards.acm.org/")] Acm,
        [Description("Air, http://getair.co")] Air,
        [Description("Airbnb, https://www.airbnb.co.uk/press/resources")] Airbnb,
        [Description("Amazon, https://worldvectorlogo.com/logo/amazon-icon")] Amazon,
        [Description("American Express, https://commons.wikimedia.org/wiki/File:American_Express_logo.svg")] AmericanExpress,
        [Description("Android, http://developer.android.com/distribute/tools/promote/brand.html")] Android,
        [Description("Apple, https://worldvectorlogo.com/logo/apple")] Apple,
        [Description("App.net, https://account.app.net/legal/assets")] AppNet,
        [Description("Asana, https://asana.com/styles")] Asana,
        [Description("Auth0, https://styleguide.auth0.com")] Auth0,
        [Description("Automatic, https://www.automatic.com/press")] Automatic,
        [Description("Baidu, https://en.wikipedia.org/wiki/File:Baidu.svg")] Baidu,
        [Description("Bandcamp, https://bandcamp.com/buttons")] Bandcamp,
        [Description("Basecamp, https://worldvectorlogo.com/logo/basecamp")] Basecamp,
        [Description("Bath ASU")] BathAsu,
        [Description("Bebo, http://bebo.com/press")] Bebo,
        [Description("Behance, https://www.behance.net/dev/api/brand")] Behance,
        [Description("Big Cartel, https://www.bigcartel.com")] BigCartel,
        [Description("Bing, https://commons.wikimedia.org/wiki/File:Bing_logo_(2016).svg")] Bing,
        [Description("Bitbucket, https://bitbucket.org")] Bitbucket,
        [Description("Bitcoin, https://bitcoin.org/en")] Bitcoin,
        [Description("Bitly, https://bitly.com/pages/press")] Bitly,
        [Description("Blogger, https://www.blogger.com")] Blogger,
        [Description("Bootstrap, http://getbootstrap.com/about")] Bootstrap,
        [Description("Brand.ai, https://brand.ai/brand-ai/style")] BrandAi,
        [Description("Buffer, https://buffer.com/press")] Buffer,
        [Description("BuzzFeed, http://www.buzzfeed.com/press/downloads")] BuzzFeed,
        [Description("CakePHP, https://cakephp.org/logos")] CakePhp,
        [Description("Campaign Monitor, https://www.campaignmonitor.com/brand")] CampaignMonitor,
        [Description("CircleCI, https://circleci.com/press")] CircleCi,
        [Description("Codecademy")] Codecademy,
        [Description("Codeforces")] Codeforces,
        [Description("CodeIgniter, https://www.codeigniter.com/help/legal")] CodeIgniter,
        [Description("CodePen, http://codepen.io")] CodePen,
        [Description("Coderwall, https://github.com/twolfson/coderwall-svg")] Coderwall,
        [Description("Code School, https://www.codeschool.com/brand-assets")] CodeSchool,
        [Description("Codio, https://codio.com")] Codio,
        [Description("ComproPago, https://compropago.com")] ComproPago,
        [Description("Conekta, https://www.conekta.io")] Conekta,
        [Description("Co-op, http://www.co-operative.coop/corporate/press/logos/")] CoOp,
        [Description("Coursera, https://www.coursera.org")] Coursera,
        [Description("CSS3, http://www.w3.org/html/logo/")] Css3,
        [Description("CSS Wizardry, http://csswizardry.com")] CssWizardry,
        [Description("Dailymotion, http://press.dailymotion.com/?page_id=346")] Dailymotion,
        [Description("Deezer, http://www.deezer.com/company/press")] Deezer,
        [Description("Delicious, https://en.wikipedia.org/wiki/Delicious_(website)")] Delicious,
        [Description("Designer News, https://www.designernews.co")] DesignerNews,
        [Description("DeviantArt, http://help.deviantart.com/21")] DeviantArt,
        [Description("Diaspora, https://wiki.diasporafoundation.org/Branding")] Diaspora,
        [Description("Digg, https://en.wikipedia.org/wiki/Digg")] Digg,
        [Description("DigitalOcean, https://www.digitalocean.com/company/logos-and-badges/")] DigitalOcean,
        [Description("Discord, https://discordapp.com/branding")] Discord,
        [Description("Discover, https://www.discovernetwork.com/en-us/business-resources/free-signage-logos")] Discover,
        [Description("Disqus, https://disqus.com/brand")] Disqus,
        [Description("Docker, https://www.docker.com")] Docker,
        [Description("Draugiem.lv, https://www.frype.com/applications/dev/docs/logos/")] DraugiemLv,
        [Description("Dribbble, https://dribbble.com/branding")] Dribbble,
        [Description("Dropbox, https://www.dropbox.com/branding")] Dropbox,
        [Description("Drupal, https://www.drupal.org/drupalorg/style-guide/colors")] Drupal,
        [Description("eBay, https://go.developer.ebay.com/logos")] EBay,
        [Description("Ello, https://ello.co")] Ello,
        [Description("Empire Kred, http://www.empire.kred")] EmpireKred,
        [Description("Ethereum, https://www.ethereum.org/images/logos/Ethereum_Visual_Identity_1.0.0.pdf")] Ethereum,
        [Description("Etsy, https://www.etsy.com/uk/press")] Etsy,
        [Description("Eventbrite, https://www.eventbrite.com")] Eventbrite,
        [Description("Event Store, https://github.com/eventstore/brand")] EventStore,
        [Description("Evernote, https://evernote.com/brand/color-palette/")] Evernote,
        [Description("Everplaces, https://everplaces.com")] Everplaces,
        [Description("Facebook, https://www.facebookbrand.com")] Facebook,
        [Description("Feedly, https://worldvectorlogo.com/logo/feedly")] Feedly,
        [Description("Fitbit, http://www.fitbit.com/uk/home")] Fitbit,
        [Description("Flickr, https://worldvectorlogo.com/logo/flickr-1")] Flickr,
        [Description("Flipboard, https://about.flipboard.com/brand-guidelines")] Flipboard,
        [Description("Foursquare, https://foursquare.com/about/logos")] Foursquare,
        [Description("freeCodeCamp, https://freecodecamp.com")] FreeCodeCamp,
        [Description("Garmin, https://developer.garmin.com/resources/brand-guidelines/")] Garmin,
        [Description("Gauges")] Gauges,
        [Description("Geeklist, https://geekli.st/press")] Geeklist,
        [Description("Geocaching, https://www.geocaching.com/about/logousage.aspx")] Geocaching,
        [Description("Ghost, https://ghost.org/about/logos")] Ghost,
        [Description("Git, http://git-scm.com/downloads/logos")] Git,
        [Description("GitHub, https://github.com/logos")] GitHub,
        [Description("GitLab, https://about.gitlab.com/press/")] GitLab,
        [Description("Gitter")] Gitter,
        [Description("Glassdoor, http://www.glassdoor.com/press/images")] Glassdoor,
        [Description("Gmail, https://material.io/guidelines/resources/sticker-sheets-icons.html#sticker-sheets-icons-components")] Gmail,
        [Description("GoldenLine, http://www.goldenline.pl")] GoldenLine,
        [Description("Goodreads")] Goodreads,
        [Description("Google, https://developers.google.com/+/branding-guidelines?hl=en")] Google,
        [Description("Google Analytics, https://analytics.google.com")] GoogleAnalytics,
        [Description("Google Drive, https://developers.google.com/drive/web/branding")] GoogleDrive,
        [Description("Google Hangouts, https://material.google.com/resources/sticker-sheets-icons.html#sticker-sheets-icons-components")] GoogleHangouts,
        [Description("Google Play, https://getsello.com")] GooglePlay,
        [Description("Google+, https://developers.google.com/+/branding-guidelines")] GooglePlus,
        [Description("GOV.UK, https://github.com/alphagov/design-assets/tree/master/Icons")] GovUk,
        [Description("Gratipay, https://gratipay.com")] Gratipay,
        [Description("Grav, http://getgrav.org/media")] Grav,
        [Description("Gravatar, https://automattic.com/press")] Gravatar,
        [Description("Gulp, https://github.com/gulpjs/artwork/blob/master/gulp.svg")] Gulp,
        [Description("Gumtree, https://www.gumtree.com")] Gumtree,
        [Description("HackerRank, https://www.hackerrank.com/")] HackerRank,
        [Description("Hackster, https://drive.google.com/file/d/0B3aqzR8LzoqdT1p4ZUlWVnJ1elk/view?usp=sharing")] Hackster,
        [Description("Hatena Bookmark, http://hatenacorp.jp/press/resource")] HatenaBookmark,
        [Description("Heroku, https://www.heroku.com")] Heroku,
        [Description("HipChat, http://hipchat.com")] HipChat,
        [Description("Hootsuite, https://hootsuite.com/en-gb/about/media-kit")] Hootsuite,
        [Description("Houzz, http://www.houzz.co.uk/buttonsAndBadges")] Houzz,
        [Description("HTML5, http://www.w3.org/html/logo/")] Html5,
        [Description("Hulu, http://www.hulu.com/press/assets")] Hulu,
        [Description("iFixit, https://www.ifixit.com/")] IFixit,
        [Description("IMDb, http://www.imdb.com/pressroom/brand_guidelines")] ImDb,
        [Description("Instacart, https://www.instacart.com/press")] Instacart,
        [Description("Instagram, https://www.instagram-brand.com")] Instagram,
        [Description("Instapaper")] Instapaper,
        [Description("Intercom, https://www.intercom.io")] Intercom,
        [Description("InVision, https://projects.invisionapp.com/boards/BX4P1DY5H46R")] InVision,
        [Description("JavaScript, https://github.com/voodootikigod/logo.js")] JavaScript,
        [Description("Jekyll, https://github.com/jekyll/brand")] Jekyll,
        [Description("Jenkins, https://wiki.jenkins-ci.org/display/JENKINS/Logo")] Jenkins,
        [Description("JIRA, https://www.atlassian.com/company/news/press-kit")] Jira,
        [Description("Joomla, https://docs.joomla.org/Joomla:Brand_Identity_Elements")] Joomla,
        [Description("JSFiddle, http://doc.jsfiddle.net/meta/downloads.html")] JsFiddle,
        [Description("JSON, https://commons.wikimedia.org/wiki/File:JSON_vector_logo.svg")] Json,
        [Description("JustGiving, https://justgiving.com")] JustGiving,
        [Description("Kaggle, https://www.kaggle.com/contact")] Kaggle,
        [Description("Khan Academy, https://khanacademy.zendesk.com/hc/en-us/articles/202483630-Press-room")] KhanAcademy,
        [Description("Kickstarter, https://www.kickstarter.com/help/brand_assets")] Kickstarter,
        [Description("Kik, http://www.kik.com/press")] Kik,
        [Description("Kirby, http://getkirby.com/assets/images/logo.svg")] Kirby,
        [Description("Klout, https://klout.com/s/developers/styleguide")] Klout,
        [Description("Koding, https://koding.com/About")] Koding,
        [Description("Lanyrd, http://lanyrd.com/help/faq/#branding")] Lanyrd,
        [Description("Laravel, https://github.com/laravel/art")] Laravel,
        [Description("Last.fm, http://www.last.fm/about/resources")] LastFm,
        [Description("Launchpad, https://help.launchpad.net/logo/submissions")] Launchpad,
        [Description("Line, http://line.me/en/logo")] Line,
        [Description("LinkedIn, https://brand.linkedin.com")] LinkedIn,
        [Description("Linux Foundation, http://www.linuxfoundation.org/about/about-linux")] LinuxFoundation,
        [Description("LiveJournal, http://www.livejournal.com")] LiveJournal,
        [Description("Livestream, https://livestream.com/press")] Livestream,
        [Description("Macy’s, http://macys.com")] MacyS,
        [Description("Magento, http://magento.com")] Magento,
        [Description("MailChimp, http://mailchimp.com/about/brand-assets")] MailChimp,
        [Description("MakerBot, http://www.makerbot.com/makerbot-press-assets")] MakerBot,
        [Description("MasterCard, https://brand.mastercard.com/brandcenter/mastercard-brand-mark/downloads.html")] MasterCard,
        [Description("Matternet, http://mttr.net")] Matternet,
        [Description("MediaTemple, https://mediatemple.net/company/about-us")] MediaTemple,
        [Description("Medium, https://medium.com")] Medium,
        [Description("Meetup")] Meetup,
        [Description("Messenger, https://worldvectorlogo.com/logo/facebook-messenger")] Messenger,
        [Description("Microgenetics")] Microgenetics,
        [Description("Microsoft, https://ratnacahayarina.files.wordpress.com/2014/03/microsoft.pdf")] Microsoft,
        [Description("Microsoft Access, https://www.office.com")] MicrosoftAccess,
        [Description("Microsoft Excel, https://www.office.com")] MicrosoftExcel,
        [Description("Microsoft OneNote, https://www.office.com")] MicrosoftOneNote,
        [Description("Microsoft Outlook, https://www.office.com")] MicrosoftOutlook,
        [Description("Microsoft PowerPoint, https://www.office.com")] MicrosoftPowerPoint,
        [Description("Microsoft Word, https://www.office.com")] MicrosoftWord,
        [Description("Minecraft")] Minecraft,
        [Description("Minutemailer, https://minutemailer.com/press")] Minutemailer,
        [Description("Mixcloud, https://www.mixcloud.com/branding")] Mixcloud,
        [Description("Monero, https://getmonero.org")] Monero,
        [Description("Monkey tie, https://www.monkey-tie.com/presse")] MonkeyTie,
        [Description("Monogram, http://monogram.me")] Monogram,
        [Description("Moo, https://www.moo.com/uk/about/press.html")] Moo,
        [Description("Myspace, https://myspace.com/pressroom/assetslogos")] Myspace,
        [Description("Netflix, https://commons.wikimedia.org/wiki/File:Netflix_2014_logo.svg")] Netflix,
        [Description("Nintendo, https://en.wikipedia.org/wiki/Nintendo#/media/File:Nintendo.svg")] Nintendo,
        [Description("Nintendo Switch, http://www.nintendo.co.uk/")] NintendoSwitch,
        [Description("Oculus, https://www.oculus.com/en-us/press-kit")] Oculus,
        [Description("Odnoklassniki, http://v.ok.ru/logo.html")] Odnoklassniki,
        [Description("OneDrive, https://msdn.microsoft.com/en-us/onedrive/dn673556.aspx")] OneDrive,
        [Description("Opera, https://github.com/operasoftware/logo")] Opera,
        [Description("Origin, https://www.origin.com/gbr/en-us/store")] Origin,
        [Description("Overcast, https://overcast.fm")] Overcast,
        [Description("OVH, https://www.ovh.com/fr/news/logo-ovh.xml")] Ovh,
        [Description("Pagekit, https://pagekit.com/logo-guide")] Pagekit,
        [Description("Patreon, https://worldvectorlogo.com/logo/patreon")] Patreon,
        [Description("PayPal, https://www.paypal-marketing.com/html/partner/na/portal-v2/pdf/PP_Masterbrandguidelines_v21_mm.pdf")] PayPal,
        [Description("Periscope, https://www.periscope.tv/press")] Periscope,
        [Description("Pinboard, https://commons.wikimedia.org/wiki/File:Feedbin-Icon-share-pinboard.svg")] Pinboard,
        [Description("Pingdom, https://tools.pingdom.com")] Pingdom,
        [Description("Pingup, http://pingup.com/resources")] Pingup,
        [Description("Pinterest, https://business.pinterest.com/en/brand-guidelines")] Pinterest,
        [Description("PlanGrid, https://plangrid.com/en/")] PlanGrid,
        [Description("Player.me, https://player.me/p/about-us")] PlayerMe,
        [Description("PlayStation, http://uk.playstation.com/media/DPBjbK0o/CECH-4202_4203%20PS3_QSG_GB_Eastern_3_web_vf1.pdf")] PlayStation,
        [Description("Plurk, https://www.plurk.com/brandInfo")] Plurk,
        [Description("Pocket, https://getpocket.com/blog/press/")] Pocket,
        [Description("Podcasts")] Podcasts,
        [Description("ProcessWire, https://github.com/processwire")] ProcessWire,
        [Description("Product Hunt, https://www.producthunt.com/branding")] ProductHunt,
        [Description("Proto.io, https://proto.io/en/presskit")] ProtoIo,
        [Description("ProtonMail, https://protonmail.com/media-kit")] ProtonMail,
        [Description("Quantopian, https://www.quantopian.com")] Quantopian,
        [Description("Quora, https://www.quora.com")] Quora,
        [Description("Raspberry Pi, https://www.raspberrypi.org/trademark-rules")] RaspberryPi,
        [Description("Rdio, https://commons.wikimedia.org/wiki/File:Rdio.svg")] Rdio,
        [Description("React, https://facebook.github.io/react/")] React,
        [Description("Readability, https://readability.com/about")] Readability,
        [Description("Read the Docs, https://github.com/rtfd/readthedocs.org/blob/master/media/readthedocsbranding.ai")] ReadTheDocs,
        [Description("Reddit, https://worldvectorlogo.com/logo/reddit-2")] Reddit,
        [Description("ReverbNation, https://www.reverbnation.com")] ReverbNation,
        [Description("RSS, https://en.wikipedia.org/wiki/Feed_icon")] Rss,
        [Description("Ruby")] Ruby,
        [Description("Runkeeper, https://runkeeper.com/partnerships")] Runkeeper,
        [Description("Sass, http://sass-lang.com/styleguide/brand")] Sass,
        [Description("Sauce Labs, https://saucelabs.com/press-room/press-coverage")] SauceLabs,
        [Description("Scribd, https://www.scribd.com")] Scribd,
        [Description("Sega, https://en.wikipedia.org/wiki/Sega#/media/File:Sega_logo.svg")] Sega,
        [Description("Sellfy, https://sellfy.com/about/")] Sellfy,
        [Description("Sentia Yoga")] SentiaYoga,
        [Description("Sentry, https://sentry.io/branding/")] Sentry,
        [Description("Server Fault, http://stackoverflow.com/company/logos")] ServerFault,
        [Description("Shopify, https://press.shopify.com/brand")] Shopify,
        [Description("Simple Icons")] SimpleIcons,
        [Description("Sina Weibo, https://en.wikipedia.org/wiki/Sina_Weibo")] SinaWeibo,
        [Description("SitePoint, http://www.sitepoint.com")] SitePoint,
        [Description("Skyliner, https://www.skyliner.io/help")] Skyliner,
        [Description("Skype, http://blogs.skype.com/?attachment_id=56273")] Skype,
        [Description("Slack, https://slack.com/brand-guidelines")] Slack,
        [Description("Slashdot, https://commons.wikimedia.org/wiki/File:Slashdot_wordmark_and_logo.svg")] Slashdot,
        [Description("Slides, https://slides.com/about")] Slides,
        [Description("Smashing Magazine")] SmashingMagazine,
        [Description("Snapchat, https://www.snapchat.com/brand-guidelines")] Snapchat,
        [Description("Songkick, http://blog.songkick.com/media-assets")] Songkick,
        [Description("SoundCloud, https://soundcloud.com/press")] SoundCloud,
        [Description("Speaker Deck")] SpeakerDeck,
        [Description("Spotify, https://developer.spotify.com/design")] Spotify,
        [Description("Spotlight, https://www.spotlight.com/")] Spotlight,
        [Description("Spreaker, http://www.spreaker.com/press")] Spreaker,
        [Description("Squarespace, http://squarespace.com/brand-guidelines")] Squarespace,
        [Description("Stack Exchange, http://stackoverflow.com/company/logos")] StackExchange,
        [Description("Stack Overflow, http://stackoverflow.com")] StackOverflow,
        [Description("Statamic, http://statamic.com/press")] Statamic,
        [Description("Steam, https://partner.steamgames.com/public/marketing/Steam_Guidelines_02102016.pdf")] Steam,
        [Description("Steem, https://steem.io/")] Steem,
        [Description("Stitcher")] Stitcher,
        [Description("Storify, https://storify.com")] Storify,
        [Description("Stripe, https://stripe.com/about/resources")] Stripe,
        [Description("StubHub, http://www.stubhub.com")] StubHub,
        [Description("StumbleUpon, http://corp.stumbleupon.com/press")] StumbleUpon,
        [Description("StyleShare, http://about.stylesha.re/en/press/presskit/")] StyleShare,
        [Description("Subversion, http://subversion.apache.org/logo")] Subversion,
        [Description("Super User, http://stackoverflow.com/company/logos")] SuperUser,
        [Description("Swarm, https://foursquare.com/about/logos")] Swarm,
        [Description("TED, https://www.ted.com/participate/organize-a-local-tedx-event/tedx-organizer-guide/branding-promotions/logo-and-design/your-tedx-logo")] Ted,
        [Description("Teespring, https://teespring.com")] Teespring,
        [Description("Telegram, https://commons.wikimedia.org/wiki/File:Telegram_alternative_logo.svg")] Telegram,
        [Description("Tencent QQ, http://im.qq.com/")] TencentQq,
        [Description("Tesla, http://www.teslamotors.com/en_GB/about")] Tesla,
        [Description("Tinder, http://www.gotinder.com/press")] Tinder,
        [Description("Toggl, https://blog.toggl.com/media-kit/")] Toggl,
        [Description("Topcoder")] Topcoder,
        [Description("Toptal, https://www.toptal.com/branding")] Toptal,
        [Description("Trakt, https://trakt.tv")] Trakt,
        [Description("Travis CI, https://travis-ci.org")] TravisCi,
        [Description("Treehouse, https://teamtreehouse.com/about")] Treehouse,
        [Description("Trello, https://trello.com/about/branding")] Trello,
        [Description("TripAdvisor, http://www.tripadvisor.co.uk/PressCenter")] TripAdvisor,
        [Description("Trulia, http://www.trulia.com")] Trulia,
        [Description("Tumblr, https://www.tumblr.com/logo")] Tumblr,
        [Description("Twilio, https://www.twilio.com/company/brand")] Twilio,
        [Description("Twitch, http://www.twitch.tv/p/brand-assets")] Twitch,
        [Description("Twitter, https://brand.twitter.com")] Twitter,
        [Description("Twoo, http://www.twoo.com/about/press")] Twoo,
        [Description("Uber, https://www.uber.com/media/")] Uber,
        [Description("Ubuntu, https://insights.ubuntu.com/press-centre")] Ubuntu,
        [Description("Udacity, https://www.udacity.com")] Udacity,
        [Description("UIkit, https://getuikit.com")] UIkit,
        [Description("Upwork, https://www.upwork.com/press/")] Upwork,
        [Description("Viadeo, http://corporate.viadeo.com/en/media/resources")] Viadeo,
        [Description("Viber, http://www.viber.com/en/media-kit")] Viber,
        [Description("Vimeo, https://vimeo.com/about/brand_guidelines")] Vimeo,
        [Description("Vine, https://vine.co/logo")] Vine,
        [Description("Virb, http://virb.com/about")] Virb,
        [Description("Visa, https://commons.wikimedia.org/wiki/File:Visa_2014_logo_detail.svg")] Visa,
        [Description("VK, https://vk.com/about")] Vk,
        [Description("Vue.js, https://github.com/vuejs/art")] VueJs,
        [Description("WeChat, https://worldvectorlogo.com/logo/wechat-3")] WeChat,
        [Description("WhatsApp, https://www.whatsappbrand.com")] WhatsApp,
        [Description("Wikipedia, https://en.wikipedia.org/wiki/Logo_of_Wikipedia")] Wikipedia,
        [Description("Windows, https://commons.wikimedia.org/wiki/File:Windows_10_Logo.svg")] Windows,
        [Description("Wire, http://brand.wire.com")] Wire,
        [Description("Wix, http://www.wix.com/about/design-assets")] Wix,
        [Description("WordPress, https://wordpress.org/about/logos")] WordPress,
        [Description("Xbox, http://mspartner-public.sharepoint.com/XBOX%20Games/Xbox%20logo's%20+%20Guidelines/Xbox%20Live/Xbox_Live_Guidelines_10-4-13.pdf")] Xbox,
        [Description("Xero, https://www.xero.com/uk/about/media/downloads")] Xero,
        [Description("Xing, https://worldvectorlogo.com/logo/xing-icon")] Xing,
        [Description("Yahoo!, https://en.wikipedia.org/wiki/Yahoo!")] Yahoo,
        [Description("Yammer, https://developer.yammer.com/docs/branding-guide")] Yammer,
        [Description("Y Combinator, https://www.ycombinator.com/press/")] YCombinator,
        [Description("Yelp, http://www.yelp.com/brand")] Yelp,
        [Description("YouTube, https://www.youtube.com/yt/brand/en-GB/downloads.html")] YouTube,
        [Description("Zapier, https://zapier.com/about/brand")] Zapier,
        [Description("Zendesk, https://www.zendesk.com")] Zendesk,
        [Description("Zerply, https://zerply.com/about/resources")] Zerply,
        [Description("Zillow, http://zillow.mediaroom.com/logos")] Zillow,
    }
}