namespace MahApps.Metro.IconPacks
{
#if NETFX_CORE
    using MahApps.Metro.IconPacks.Core;
#else
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconFontAwesome" />.
    /// </summary>
    /// <remarks>
    /// All icons sourced from FontAwesome Icons Font v4.6.3 - <see><cref>http://fontawesome.io</cref></see> - 
    /// <see><cref>https://github.com/FortAwesome/Font-Awesome</cref></see>.
    /// </remarks>
    public enum PackIconFontAwesomeKind
    {
        [Description("Empty placeholder")] None,
        [Description("500px (f26e)")] _500pxBrands,
        [Description("Accessible Icon (f368, accessibility, wheelchair, handicap, person, wheelchair-alt)")] AccessibleIconBrands,
        [Description("Accusoft (f369)")] AccusoftBrands,
        [Description("Address Book (f2b9)")] AddressBookRegular,
        [Description("Address Book (f2b9)")] AddressBookSolid,
        [Description("Address Card (f2bb)")] AddressCardRegular,
        [Description("Address Card (f2bb)")] AddressCardSolid,
        [Description("adjust (f042, contrast)")] AdjustSolid,
        [Description("App.net (f170)")] AdnBrands,
        [Description("Adversal (f36a)")] AdversalBrands,
        [Description("affiliatetheme (f36b)")] AffiliatethemeBrands,
        [Description("Algolia (f36c)")] AlgoliaBrands,
        [Description("align-center (f037, middle, text)")] AlignCenterSolid,
        [Description("align-justify (f039, text)")] AlignJustifySolid,
        [Description("align-left (f036, text)")] AlignLeftSolid,
        [Description("align-right (f038, text)")] AlignRightSolid,
        [Description("Allergies (f461, intolerances, pox, hand, freckles, spots)")] AllergiesSolid,
        [Description("Amazon (f270)")] AmazonBrands,
        [Description("Amazon Pay (f42c)")] AmazonPayBrands,
        [Description("ambulance (f0f9, vehicle, support, help, machine)")] AmbulanceSolid,
        [Description("American Sign Language Interpreting (f2a3)")] AmericanSignLanguageInterpretingSolid,
        [Description("Amilia (f36d)")] AmiliaBrands,
        [Description("Anchor (f13d, link)")] AnchorSolid,
        [Description("Android (f17b, robot)")] AndroidBrands,
        [Description("AngelList (f209)")] AngellistBrands,
        [Description("Angle Double Down (f103, arrows)")] AngleDoubleDownSolid,
        [Description("Angle Double Left (f100, laquo, quote, previous, back, arrows)")] AngleDoubleLeftSolid,
        [Description("Angle Double Right (f101, raquo, quote, next, forward, arrows)")] AngleDoubleRightSolid,
        [Description("Angle Double Up (f102, arrows)")] AngleDoubleUpSolid,
        [Description("angle-down (f107, arrow)")] AngleDownSolid,
        [Description("angle-left (f104, previous, back, arrow)")] AngleLeftSolid,
        [Description("angle-right (f105, next, forward, arrow)")] AngleRightSolid,
        [Description("angle-up (f106, arrow)")] AngleUpSolid,
        [Description("Angry Creative (f36e)")] AngrycreativeBrands,
        [Description("Angular (f420)")] AngularBrands,
        [Description("Apper Systems AB (f371)")] ApperBrands,
        [Description("Apple (f179, osx, food)")] AppleBrands,
        [Description("Apple Pay (f415)")] ApplePayBrands,
        [Description("App Store (f36f)")] AppStoreBrands,
        [Description("iOS App Store (f370)")] AppStoreIosBrands,
        [Description("Archive (f187, box, storage, package)")] ArchiveSolid,
        [Description("Alternate Arrow Circle Down (f358, download, arrow-circle-o-down)")] ArrowAltCircleDownRegular,
        [Description("Alternate Arrow Circle Down (f358, download, arrow-circle-o-down)")] ArrowAltCircleDownSolid,
        [Description("Alternate Arrow Circle Left (f359, previous, back, arrow-circle-o-left)")] ArrowAltCircleLeftRegular,
        [Description("Alternate Arrow Circle Left (f359, previous, back, arrow-circle-o-left)")] ArrowAltCircleLeftSolid,
        [Description("Alternate Arrow Circle Right (f35a, next, forward, arrow-circle-o-right)")] ArrowAltCircleRightRegular,
        [Description("Alternate Arrow Circle Right (f35a, next, forward, arrow-circle-o-right)")] ArrowAltCircleRightSolid,
        [Description("Alternate Arrow Circle Up (f35b, arrow-circle-o-up)")] ArrowAltCircleUpRegular,
        [Description("Alternate Arrow Circle Up (f35b, arrow-circle-o-up)")] ArrowAltCircleUpSolid,
        [Description("Arrow Circle Down (f0ab, download)")] ArrowCircleDownSolid,
        [Description("Arrow Circle Left (f0a8, previous, back)")] ArrowCircleLeftSolid,
        [Description("Arrow Circle Right (f0a9, next, forward)")] ArrowCircleRightSolid,
        [Description("Arrow Circle Up (f0aa)")] ArrowCircleUpSolid,
        [Description("arrow-down (f063, download)")] ArrowDownSolid,
        [Description("arrow-left (f060, previous, back)")] ArrowLeftSolid,
        [Description("arrow-right (f061, next, forward)")] ArrowRightSolid,
        [Description("Alternate Arrows Horizontal (f337, resize, arrows-h)")] ArrowsAltHSolid,
        [Description("Alternate Arrows (f0b2, expand, enlarge, fullscreen, bigger, move, reorder, resize, arrow, arrows)")] ArrowsAltSolid,
        [Description("Alternate Arrows Vertical (f338, resize, arrows-v)")] ArrowsAltVSolid,
        [Description("arrow-up (f062)")] ArrowUpSolid,
        [Description("Assistive Listening Systems (f2a2)")] AssistiveListeningSystemsSolid,
        [Description("asterisk (f069, details)")] AsteriskSolid,
        [Description("Asymmetrik, Ltd. (f372)")] AsymmetrikBrands,
        [Description("At (f1fa, email, e-mail)")] AtSolid,
        [Description("Audible (f373)")] AudibleBrands,
        [Description("Audio Description (f29e)")] AudioDescriptionSolid,
        [Description("Autoprefixer (f41c)")] AutoprefixerBrands,
        [Description("avianex (f374)")] AvianexBrands,
        [Description("Aviato (f421)")] AviatoBrands,
        [Description("Amazon Web Services (AWS) (f375)")] AwsBrands,
        [Description("backward (f04a, rewind, previous)")] BackwardSolid,
        [Description("Balance Scale (f24e)")] BalanceScaleSolid,
        [Description("Band-Aid (f462, bandage, ouch, boo boo)")] BandAidSolid,
        [Description("Bandcamp (f2d5)")] BandcampBrands,
        [Description("ban (f05e, delete, remove, trash, hide, block, stop, abort, cancel, ban, prohibit)")] BanSolid,
        [Description("barcode (f02a, scan)")] BarcodeSolid,
        [Description("Bars (f0c9, menu, drag, reorder, settings, list, ul, ol, checklist, todo, hamburger, navigation, nav)")] BarsSolid,
        [Description("Baseball Ball (f433)")] BaseballBallSolid,
        [Description("Basketball Ball (f434)")] BasketballBallSolid,
        [Description("Bath (f2cd)")] BathSolid,
        [Description("Battery Empty (f244, power, status)")] BatteryEmptySolid,
        [Description("Battery Full (f240, power, status)")] BatteryFullSolid,
        [Description("Battery 1/2 Full (f242, power, status)")] BatteryHalfSolid,
        [Description("Battery 1/4 Full (f243, power, status)")] BatteryQuarterSolid,
        [Description("Battery 3/4 Full (f241, power, status)")] BatteryThreeQuartersSolid,
        [Description("Bed (f236, travel)")] BedSolid,
        [Description("beer (f0fc, alcohol, stein, drink, mug, bar, liquor)")] BeerSolid,
        [Description("Behance (f1b4)")] BehanceBrands,
        [Description("Behance Square (f1b5)")] BehanceSquareBrands,
        [Description("bell (f0f3, alert, reminder, notification)")] BellRegular,
        [Description("Bell Slash (f1f6)")] BellSlashRegular,
        [Description("Bell Slash (f1f6)")] BellSlashSolid,
        [Description("bell (f0f3, alert, reminder, notification)")] BellSolid,
        [Description("Bicycle (f206, vehicle, transportation, bike, gears)")] BicycleSolid,
        [Description("BIMobject (f378)")] BimobjectBrands,
        [Description("Binoculars (f1e5)")] BinocularsSolid,
        [Description("Birthday Cake (f1fd)")] BirthdayCakeSolid,
        [Description("Bitbucket (f171, git, bitbucket-square)")] BitbucketBrands,
        [Description("Bitcoin (f379)")] BitcoinBrands,
        [Description("Bity (f37a)")] BityBrands,
        [Description("BlackBerry (f37b)")] BlackberryBrands,
        [Description("Font Awesome Black Tie (f27e)")] BlackTieBrands,
        [Description("Blind (f29d)")] BlindSolid,
        [Description("Blogger B (f37d)")] BloggerBBrands,
        [Description("Blogger (f37c)")] BloggerBrands,
        [Description("Bluetooth (f294)")] BluetoothBBrands,
        [Description("Bluetooth (f293)")] BluetoothBrands,
        [Description("bold (f032)")] BoldSolid,
        [Description("Lightning Bolt (f0e7, lightning, weather)")] BoltSolid,
        [Description("Bomb (f1e2)")] BombSolid,
        [Description("bookmark (f02e, save)")] BookmarkRegular,
        [Description("bookmark (f02e, save)")] BookmarkSolid,
        [Description("book (f02d, read, documentation)")] BookSolid,
        [Description("Bowling Ball (f436)")] BowlingBallSolid,
        [Description("Boxes (f468)")] BoxesSolid,
        [Description("Box Open (f49e)")] BoxOpenSolid,
        [Description("Box (f466, package)")] BoxSolid,
        [Description("Braille (f2a1)")] BrailleSolid,
        [Description("Medical Briefcase (f469, health briefcase)")] BriefcaseMedicalSolid,
        [Description("Briefcase (f0b1, work, business, office, luggage, bag)")] BriefcaseSolid,
        [Description("BTC (f15a)")] BtcBrands,
        [Description("Bug (f188, report, insect)")] BugSolid,
        [Description("Building (f1ad, work, business, apartment, office, company)")] BuildingRegular,
        [Description("Building (f1ad, work, business, apartment, office, company)")] BuildingSolid,
        [Description("bullhorn (f0a1, announcement, share, broadcast, louder, megaphone)")] BullhornSolid,
        [Description("Bullseye (f140, target)")] BullseyeSolid,
        [Description("Burn (f46a, energy)")] BurnSolid,
        [Description("Büromöbel-Experte GmbH & Co. KG. (f37f)")] BuromobelexperteBrands,
        [Description("Bus (f207, vehicle, machine, public transportation, transportation)")] BusSolid,
        [Description("BuySellAds (f20d)")] BuyselladsBrands,
        [Description("Calculator (f1ec)")] CalculatorSolid,
        [Description("Alternate Calendar (f073, date, time, when, event, calendar, schedule)")] CalendarAltRegular,
        [Description("Alternate Calendar (f073, date, time, when, event, calendar, schedule)")] CalendarAltSolid,
        [Description("Calendar Check (f274, todo, done, agree, accept, confirm, ok, select, success, appointment, correct)")] CalendarCheckRegular,
        [Description("Calendar Check (f274, todo, done, agree, accept, confirm, ok, select, success, appointment, correct)")] CalendarCheckSolid,
        [Description("Calendar Minus (f272)")] CalendarMinusRegular,
        [Description("Calendar Minus (f272)")] CalendarMinusSolid,
        [Description("Calendar Plus (f271)")] CalendarPlusRegular,
        [Description("Calendar Plus (f271)")] CalendarPlusSolid,
        [Description("Calendar (f133, date, time, when, event, calendar-o, schedule)")] CalendarRegular,
        [Description("Calendar (f133, date, time, when, event, calendar-o, schedule)")] CalendarSolid,
        [Description("Calendar Times (f273)")] CalendarTimesRegular,
        [Description("Calendar Times (f273)")] CalendarTimesSolid,
        [Description("Retro Camera (f083, photo, picture, record)")] CameraRetroSolid,
        [Description("camera (f030, photo, picture, record)")] CameraSolid,
        [Description("Capsules (f46b, medicine, drugs)")] CapsulesSolid,
        [Description("Caret Down (f0d7, more, dropdown, menu, triangle down, arrow)")] CaretDownSolid,
        [Description("Caret Left (f0d9, previous, back, triangle left, arrow)")] CaretLeftSolid,
        [Description("Caret Right (f0da, next, forward, triangle right, arrow)")] CaretRightSolid,
        [Description("Caret Square Down (f150, more, dropdown, menu, caret-square-o-down)")] CaretSquareDownRegular,
        [Description("Caret Square Down (f150, more, dropdown, menu, caret-square-o-down)")] CaretSquareDownSolid,
        [Description("Caret Square Left (f191, previous, back, caret-square-o-left)")] CaretSquareLeftRegular,
        [Description("Caret Square Left (f191, previous, back, caret-square-o-left)")] CaretSquareLeftSolid,
        [Description("Caret Square Right (f152, next, forward, caret-square-o-right)")] CaretSquareRightRegular,
        [Description("Caret Square Right (f152, next, forward, caret-square-o-right)")] CaretSquareRightSolid,
        [Description("Caret Square Up (f151, caret-square-o-up)")] CaretSquareUpRegular,
        [Description("Caret Square Up (f151, caret-square-o-up)")] CaretSquareUpSolid,
        [Description("Caret Up (f0d8, triangle up, arrow)")] CaretUpSolid,
        [Description("Car (f1b9, vehicle, machine, transportation)")] CarSolid,
        [Description("Shopping Cart Arrow Down (f218, shopping)")] CartArrowDownSolid,
        [Description("Add to Shopping Cart (f217, add, shopping)")] CartPlusSolid,
        [Description("Amazon Pay Credit Card (f42d)")] CcAmazonPayBrands,
        [Description("American Express Credit Card (f1f3, amex)")] CcAmexBrands,
        [Description("Apple Pay Credit Card (f416)")] CcApplePayBrands,
        [Description("Diner's Club Credit Card (f24c)")] CcDinersClubBrands,
        [Description("Discover Credit Card (f1f2)")] CcDiscoverBrands,
        [Description("JCB Credit Card (f24b)")] CcJcbBrands,
        [Description("MasterCard Credit Card (f1f1)")] CcMastercardBrands,
        [Description("Paypal Credit Card (f1f4)")] CcPaypalBrands,
        [Description("Stripe Credit Card (f1f5)")] CcStripeBrands,
        [Description("Visa Credit Card (f1f0)")] CcVisaBrands,
        [Description("Centercode (f380)")] CentercodeBrands,
        [Description("certificate (f0a3, badge, star)")] CertificateSolid,
        [Description("Area Chart (f1fe, graph, analytics, area-chart)")] ChartAreaSolid,
        [Description("Bar Chart (f080, graph, analytics, bar-chart)")] ChartBarRegular,
        [Description("Bar Chart (f080, graph, analytics, bar-chart)")] ChartBarSolid,
        [Description("Line Chart (f201, graph, analytics, line-chart, dashboard)")] ChartLineSolid,
        [Description("Pie Chart (f200, graph, analytics, pie-chart)")] ChartPieSolid,
        [Description("Check Circle (f058, todo, done, agree, accept, confirm, ok, select, success, yes, correct)")] CheckCircleRegular,
        [Description("Check Circle (f058, todo, done, agree, accept, confirm, ok, select, success, yes, correct)")] CheckCircleSolid,
        [Description("Check (f00c, checkmark, done, todo, agree, accept, confirm, tick, ok, select, success, notification, notify, notice, yes, correct)")] CheckSolid,
        [Description("Check Square (f14a, checkmark, done, todo, agree, accept, confirm, ok, select, success, yes, correct)")] CheckSquareRegular,
        [Description("Check Square (f14a, checkmark, done, todo, agree, accept, confirm, ok, select, success, yes, correct)")] CheckSquareSolid,
        [Description("Chess Bishop (f43a)")] ChessBishopSolid,
        [Description("Chess Board (f43c)")] ChessBoardSolid,
        [Description("Chess King (f43f)")] ChessKingSolid,
        [Description("Chess Knight (f441)")] ChessKnightSolid,
        [Description("Chess Pawn (f443)")] ChessPawnSolid,
        [Description("Chess Queen (f445)")] ChessQueenSolid,
        [Description("Chess Rook (f447)")] ChessRookSolid,
        [Description("Chess (f439)")] ChessSolid,
        [Description("Chevron Circle Down (f13a, more, dropdown, menu, arrow)")] ChevronCircleDownSolid,
        [Description("Chevron Circle Left (f137, previous, back, arrow)")] ChevronCircleLeftSolid,
        [Description("Chevron Circle Right (f138, next, forward, arrow)")] ChevronCircleRightSolid,
        [Description("Chevron Circle Up (f139, arrow)")] ChevronCircleUpSolid,
        [Description("chevron-down (f078)")] ChevronDownSolid,
        [Description("chevron-left (f053, bracket, previous, back)")] ChevronLeftSolid,
        [Description("chevron-right (f054, bracket, next, forward)")] ChevronRightSolid,
        [Description("chevron-up (f077)")] ChevronUpSolid,
        [Description("Child (f1ae)")] ChildSolid,
        [Description("Chrome (f268, browser)")] ChromeBrands,
        [Description("Circle Notched (f1ce, circle-o-notch)")] CircleNotchSolid,
        [Description("Circle (f111, dot, notification, circle-thin)")] CircleRegular,
        [Description("Circle (f111, dot, notification, circle-thin)")] CircleSolid,
        [Description("Clipboard Check (f46c, todo, done, agree, accept, confirm, ok, select, success, yes)")] ClipboardCheckSolid,
        [Description("Clipboard List (f46d, todo, ul, ol, checklist, finished, completed, done, schedule, intinerary)")] ClipboardListSolid,
        [Description("Clipboard (f328, paste)")] ClipboardRegular,
        [Description("Clipboard (f328, paste)")] ClipboardSolid,
        [Description("Clock (f017, watch, timer, late, timestamp, date, schedule)")] ClockRegular,
        [Description("Clock (f017, watch, timer, late, timestamp, date, schedule)")] ClockSolid,
        [Description("Clone (f24d, copy)")] CloneRegular,
        [Description("Clone (f24d, copy)")] CloneSolid,
        [Description("Closed Captioning (f20a, cc)")] ClosedCaptioningRegular,
        [Description("Closed Captioning (f20a, cc)")] ClosedCaptioningSolid,
        [Description("Cloud Download Alternate (f381, cloud-download)")] CloudDownloadAltSolid,
        [Description("cloudscale.ch (f383)")] CloudscaleBrands,
        [Description("Cloudsmith (f384)")] CloudsmithBrands,
        [Description("Cloud (f0c2, save)")] CloudSolid,
        [Description("Cloud Upload Alternate (f382, cloud-upload)")] CloudUploadAltSolid,
        [Description("cloudversify (f385)")] CloudversifyBrands,
        [Description("Code Branch (f126, git, fork, vcs, svn, github, rebase, version, branch, code-fork)")] CodeBranchSolid,
        [Description("Codepen (f1cb)")] CodepenBrands,
        [Description("Code (f121, html, brackets)")] CodeSolid,
        [Description("Codie Pie (f284)")] CodiepieBrands,
        [Description("Coffee (f0f4, morning, mug, breakfast, tea, drink, cafe)")] CoffeeSolid,
        [Description("cog (f013, settings)")] CogSolid,
        [Description("cogs (f085, settings, gears)")] CogsSolid,
        [Description("Columns (f0db, split, panes, dashboard)")] ColumnsSolid,
        [Description("Alternate Comment (f27a, speech, notification, note, chat, bubble, feedback, message, texting, sms, conversation, commenting, commenting)")] CommentAltRegular,
        [Description("Alternate Comment (f27a, speech, notification, note, chat, bubble, feedback, message, texting, sms, conversation, commenting, commenting)")] CommentAltSolid,
        [Description("Comment Dots (f4ad)")] CommentDotsSolid,
        [Description("comment (f075, speech, notification, note, chat, bubble, feedback, message, texting, sms, conversation)")] CommentRegular,
        [Description("Comment Slash (f4b3)")] CommentSlashSolid,
        [Description("comment (f075, speech, notification, note, chat, bubble, feedback, message, texting, sms, conversation)")] CommentSolid,
        [Description("comments (f086, speech, notification, note, chat, bubble, feedback, message, texting, sms, conversation)")] CommentsRegular,
        [Description("comments (f086, speech, notification, note, chat, bubble, feedback, message, texting, sms, conversation)")] CommentsSolid,
        [Description("Compass (f14e, safari, directory, menu, location)")] CompassRegular,
        [Description("Compass (f14e, safari, directory, menu, location)")] CompassSolid,
        [Description("Compress (f066, collapse, combine, contract, merge, smaller)")] CompressSolid,
        [Description("Connect Develop (f20e)")] ConnectdevelopBrands,
        [Description("Contao (f26d)")] ContaoBrands,
        [Description("Copy (f0c5, duplicate, clone, file, files-o)")] CopyRegular,
        [Description("Copyright (f1f9)")] CopyrightRegular,
        [Description("Copyright (f1f9)")] CopyrightSolid,
        [Description("Copy (f0c5, duplicate, clone, file, files-o)")] CopySolid,
        [Description("Couch (f4b8)")] CouchSolid,
        [Description("cPanel (f388)")] CpanelBrands,
        [Description("Creative Commons (f25e)")] CreativeCommonsBrands,
        [Description("Credit Card (f09d, money, buy, debit, checkout, purchase, payment, credit-card-alt)")] CreditCardRegular,
        [Description("Credit Card (f09d, money, buy, debit, checkout, purchase, payment, credit-card-alt)")] CreditCardSolid,
        [Description("crop (f125, design)")] CropSolid,
        [Description("Crosshairs (f05b, picker, gpd)")] CrosshairsSolid,
        [Description("Alternate CSS3 Logo (f38b)")] Css3AltBrands,
        [Description("CSS 3 Logo (f13c, code)")] Css3Brands,
        [Description("Cube (f1b2, package)")] CubeSolid,
        [Description("Cubes (f1b3, packages)")] CubesSolid,
        [Description("Cut (f0c4, scissors, scissors)")] CutSolid,
        [Description("Cuttlefish (f38c)")] CuttlefishBrands,
        [Description("Dungeons & Dragons (f38d)")] DAndDBrands,
        [Description("DashCube (f210)")] DashcubeBrands,
        [Description("Database (f1c0)")] DatabaseSolid,
        [Description("Deaf (f2a4)")] DeafSolid,
        [Description("Delicious Logo (f1a5)")] DeliciousBrands,
        [Description("deploy.dog (f38e)")] DeploydogBrands,
        [Description("Deskpro (f38f)")] DeskproBrands,
        [Description("Desktop (f108, monitor, screen, desktop, computer, demo, device, pc, machine)")] DesktopSolid,
        [Description("deviantART (f1bd)")] DeviantartBrands,
        [Description("Diagnoses (f470)")] DiagnosesSolid,
        [Description("Digg Logo (f1a6)")] DiggBrands,
        [Description("Digital Ocean (f391)")] DigitalOceanBrands,
        [Description("Discord (f392)")] DiscordBrands,
        [Description("Discourse (f393)")] DiscourseBrands,
        [Description("DNA (f471, double helix, helix)")] DnaSolid,
        [Description("DocHub (f394)")] DochubBrands,
        [Description("Docker (f395)")] DockerBrands,
        [Description("Dollar Sign (f155, usd, price)")] DollarSignSolid,
        [Description("Dolly Flatbed (f474)")] DollyFlatbedSolid,
        [Description("Dolly (f472)")] DollySolid,
        [Description("Donate (f4b9, give, generosity)")] DonateSolid,
        [Description("Dot Circle (f192, target, bullseye, notification)")] DotCircleRegular,
        [Description("Dot Circle (f192, target, bullseye, notification)")] DotCircleSolid,
        [Description("Dove (f4ba)")] DoveSolid,
        [Description("Download (f019, import)")] DownloadSolid,
        [Description("Draft2digital (f396)")] Draft2digitalBrands,
        [Description("Dribbble (f17d)")] DribbbleBrands,
        [Description("Dribbble Square (f397)")] DribbbleSquareBrands,
        [Description("Dropbox (f16b)")] DropboxBrands,
        [Description("Drupal Logo (f1a9)")] DrupalBrands,
        [Description("Dyalog (f399)")] DyalogBrands,
        [Description("Earlybirds (f39a)")] EarlybirdsBrands,
        [Description("Edge Browser (f282, browser, ie)")] EdgeBrands,
        [Description("Edit (f044, write, edit, update, pencil, pen)")] EditRegular,
        [Description("Edit (f044, write, edit, update, pencil, pen)")] EditSolid,
        [Description("eject (f052)")] EjectSolid,
        [Description("Elementor (f430)")] ElementorBrands,
        [Description("Horizontal Ellipsis (f141, dots, menu, drag, reorder, settings, list, ul, ol, kebab, navigation, nav)")] EllipsisHSolid,
        [Description("Vertical Ellipsis (f142, dots, menu, drag, reorder, settings, list, ul, ol, kebab, navigation, nav)")] EllipsisVSolid,
        [Description("Ember (f423)")] EmberBrands,
        [Description("Galactic Empire (f1d1)")] EmpireBrands,
        [Description("Envelope Open (f2b6, email, e-mail, letter, support, mail, message, notification)")] EnvelopeOpenRegular,
        [Description("Envelope Open (f2b6, email, e-mail, letter, support, mail, message, notification)")] EnvelopeOpenSolid,
        [Description("Envelope (f0e0, email, e-mail, letter, support, mail, message, notification)")] EnvelopeRegular,
        [Description("Envelope (f0e0, email, e-mail, letter, support, mail, message, notification)")] EnvelopeSolid,
        [Description("Envelope Square (f199, email, e-mail, letter, support, mail, message, notification)")] EnvelopeSquareSolid,
        [Description("Envira Gallery (f299, leaf)")] EnviraBrands,
        [Description("eraser (f12d, remove, delete)")] EraserSolid,
        [Description("Erlang (f39d)")] ErlangBrands,
        [Description("Ethereum (f42e)")] EthereumBrands,
        [Description("Etsy (f2d7)")] EtsyBrands,
        [Description("Euro Sign (f153, eur, eur)")] EuroSignSolid,
        [Description("Alternate Exchange (f362, transfer, arrows, arrow, exchange, swap, return, reciprocate)")] ExchangeAltSolid,
        [Description("Exclamation Circle (f06a, warning, error, problem, notification, notify, notice, alert, danger)")] ExclamationCircleSolid,
        [Description("exclamation (f12a, warning, error, problem, notification, notify, notice, alert, danger)")] ExclamationSolid,
        [Description("Exclamation Triangle (f071, warning, error, problem, notification, notify, notice, alert, danger)")] ExclamationTriangleSolid,
        [Description("Alternate Expand Arrows (f31e, enlarge, bigger, resize, move, arrows-alt)")] ExpandArrowsAltSolid,
        [Description("Expand (f065, enlarge, bigger, resize)")] ExpandSolid,
        [Description("ExpeditedSSL (f23e)")] ExpeditedsslBrands,
        [Description("Alternate External Link (f35d, open, new, external-link)")] ExternalLinkAltSolid,
        [Description("Alternate External Link Square (f360, open, new, external-link-square)")] ExternalLinkSquareAltSolid,
        [Description("Eye Dropper (f1fb, eyedropper)")] EyeDropperSolid,
        [Description("Eye Slash (f070, toggle, show, hide, visible, visiblity, views, unseen, blind)")] EyeSlashRegular,
        [Description("Eye Slash (f070, toggle, show, hide, visible, visiblity, views, unseen, blind)")] EyeSlashSolid,
        [Description("Eye (f06e, show, visible, views, see, seen, sight, optic)")] EyeSolid,
        [Description("Facebook (f09a, social network, facebook-official)")] FacebookBrands,
        [Description("Facebook F (f39e, facebook)")] FacebookFBrands,
        [Description("Facebook Messenger (f39f)")] FacebookMessengerBrands,
        [Description("Facebook Square (f082, social network)")] FacebookSquareBrands,
        [Description("fast-backward (f049, rewind, previous, beginning, start, first)")] FastBackwardSolid,
        [Description("fast-forward (f050, next, end, last)")] FastForwardSolid,
        [Description("Fax (f1ac)")] FaxSolid,
        [Description("Female (f182, woman, human, user, person, profile)")] FemaleSolid,
        [Description("fighter-jet (f0fb, fly, plane, airplane, quick, fast, travel, transportation, maverick, goose, top gun)")] FighterJetSolid,
        [Description("Alternate File (f15c, new, page, pdf, document, file-text, invoice)")] FileAltRegular,
        [Description("Alternate File (f15c, new, page, pdf, document, file-text, invoice)")] FileAltSolid,
        [Description("Archive File (f1c6, zip, .zip, compress, compression, bundle, download)")] FileArchiveRegular,
        [Description("Archive File (f1c6, zip, .zip, compress, compression, bundle, download)")] FileArchiveSolid,
        [Description("Audio File (f1c7)")] FileAudioRegular,
        [Description("Audio File (f1c7)")] FileAudioSolid,
        [Description("Code File (f1c9)")] FileCodeRegular,
        [Description("Code File (f1c9)")] FileCodeSolid,
        [Description("Excel File (f1c3)")] FileExcelRegular,
        [Description("Excel File (f1c3)")] FileExcelSolid,
        [Description("Image File (f1c5)")] FileImageRegular,
        [Description("Image File (f1c5)")] FileImageSolid,
        [Description("Medical File Alternate (f478)")] FileMedicalAltSolid,
        [Description("Medical File (f477)")] FileMedicalSolid,
        [Description("PDF File (f1c1)")] FilePdfRegular,
        [Description("PDF File (f1c1)")] FilePdfSolid,
        [Description("Powerpoint File (f1c4)")] FilePowerpointRegular,
        [Description("Powerpoint File (f1c4)")] FilePowerpointSolid,
        [Description("File (f15b, new, page, pdf, document)")] FileRegular,
        [Description("File (f15b, new, page, pdf, document)")] FileSolid,
        [Description("Video File (f1c8)")] FileVideoRegular,
        [Description("Video File (f1c8)")] FileVideoSolid,
        [Description("Word File (f1c2)")] FileWordRegular,
        [Description("Word File (f1c2)")] FileWordSolid,
        [Description("Film (f008, movie)")] FilmSolid,
        [Description("Filter (f0b0, funnel, options)")] FilterSolid,
        [Description("fire-extinguisher (f134)")] FireExtinguisherSolid,
        [Description("Firefox (f269, browser)")] FirefoxBrands,
        [Description("fire (f06d, flame, hot, popular)")] FireSolid,
        [Description("First Aid (f479)")] FirstAidSolid,
        [Description("firstdraft (f3a1)")] FirstdraftBrands,
        [Description("First Order (f2b0)")] FirstOrderBrands,
        [Description("flag-checkered (f11e, report, notification, notify, notice)")] FlagCheckeredSolid,
        [Description("flag (f024, report, notification, notify, notice)")] FlagRegular,
        [Description("flag (f024, report, notification, notify, notice)")] FlagSolid,
        [Description("Flask (f0c3, science, beaker, experimental, labs)")] FlaskSolid,
        [Description("Flickr (f16e)")] FlickrBrands,
        [Description("Flipboard (f44d)")] FlipboardBrands,
        [Description("Fly (f417)")] FlyBrands,
        [Description("Folder Open (f07c)")] FolderOpenRegular,
        [Description("Folder Open (f07c)")] FolderOpenSolid,
        [Description("Folder (f07b)")] FolderRegular,
        [Description("Folder (f07b)")] FolderSolid,
        [Description("Alternate Font Awesome (f35c)")] FontAwesomeAltBrands,
        [Description("Font Awesome (f2b4, meanpath)")] FontAwesomeBrands,
        [Description("Font Awesome Flag (f425)")] FontAwesomeFlagBrands,
        [Description("Fonticons (f280)")] FonticonsBrands,
        [Description("Fonticons Fi (f3a2)")] FonticonsFiBrands,
        [Description("font (f031, text)")] FontSolid,
        [Description("Football Ball (f44e)")] FootballBallSolid,
        [Description("Alternate Fort Awesome (f3a3, castle)")] FortAwesomeAltBrands,
        [Description("Fort Awesome (f286, castle)")] FortAwesomeBrands,
        [Description("Forumbee (f211)")] ForumbeeBrands,
        [Description("forward (f04e, forward, next)")] ForwardSolid,
        [Description("Foursquare (f180)")] FoursquareBrands,
        [Description("FreeBSD (f3a4)")] FreebsdBrands,
        [Description("Free Code Camp (f2c5)")] FreeCodeCampBrands,
        [Description("Frown (f119, face, emoticon, sad, disapprove, rating)")] FrownRegular,
        [Description("Frown (f119, face, emoticon, sad, disapprove, rating)")] FrownSolid,
        [Description("Futbol (f1e3, soccer, football, ball)")] FutbolRegular,
        [Description("Futbol (f1e3, soccer, football, ball)")] FutbolSolid,
        [Description("Gamepad (f11b, controller)")] GamepadSolid,
        [Description("Gavel (f0e3, judge, lawyer, opinion, hammer)")] GavelSolid,
        [Description("Gem (f3a5, diamond)")] GemRegular,
        [Description("Gem (f3a5, diamond)")] GemSolid,
        [Description("Genderless (f22d)")] GenderlessSolid,
        [Description("Get Pocket (f265)")] GetPocketBrands,
        [Description("GG Currency (f260)")] GgBrands,
        [Description("GG Currency Circle (f261)")] GgCircleBrands,
        [Description("gift (f06b, present, party, wrapped, giving, generosity)")] GiftSolid,
        [Description("Git (f1d3)")] GitBrands,
        [Description("Alternate GitHub (f113, octocat)")] GithubAltBrands,
        [Description("GitHub (f09b, octocat)")] GithubBrands,
        [Description("GitHub Square (f092, octocat)")] GithubSquareBrands,
        [Description("GitKraken (f3a6)")] GitkrakenBrands,
        [Description("GitLab (f296, Axosoft)")] GitlabBrands,
        [Description("Git Square (f1d2)")] GitSquareBrands,
        [Description("Gitter (f426)")] GitterBrands,
        [Description("Martini Glass (f000, martini, drink, bar, alcohol, liquor, glass)")] GlassMartiniSolid,
        [Description("Glide (f2a5)")] GlideBrands,
        [Description("Glide G (f2a6)")] GlideGBrands,
        [Description("Globe (f0ac, world, planet, map, place, travel, earth, global, translate, all, language, localize, location, coordinates, country, gps, online)")] GlobeSolid,
        [Description("Gofore (f3a7)")] GoforeBrands,
        [Description("Golf Ball (f450)")] GolfBallSolid,
        [Description("Goodreads (f3a8)")] GoodreadsBrands,
        [Description("Goodreads G (f3a9)")] GoodreadsGBrands,
        [Description("Google Logo (f1a0)")] GoogleBrands,
        [Description("Google Drive (f3aa)")] GoogleDriveBrands,
        [Description("Google Play (f3ab)")] GooglePlayBrands,
        [Description("Google Plus (f2b3, google-plus-circle, google-plus-official)")] GooglePlusBrands,
        [Description("Google Plus G (f0d5, social network, google-plus)")] GooglePlusGBrands,
        [Description("Google Plus Square (f0d4, social network)")] GooglePlusSquareBrands,
        [Description("Google Wallet (f1ee)")] GoogleWalletBrands,
        [Description("Graduation Cap (f19d, learning, school, student)")] GraduationCapSolid,
        [Description("Gratipay (Gittip) (f184, heart, like, favorite, love)")] GratipayBrands,
        [Description("Grav (f2d6)")] GravBrands,
        [Description("Gripfire, Inc. (f3ac)")] GripfireBrands,
        [Description("Grunt (f3ad)")] GruntBrands,
        [Description("Gulp (f3ae)")] GulpBrands,
        [Description("Hacker News (f1d4)")] HackerNewsBrands,
        [Description("Hacker News Square (f3af)")] HackerNewsSquareBrands,
        [Description("Hand Holding Heart (f4be)")] HandHoldingHeartSolid,
        [Description("Hand Holding (f4bd)")] HandHoldingSolid,
        [Description("Hand Holding US Dollar (f4c0, dollar sign, price, donation, giving)")] HandHoldingUsdSolid,
        [Description("Lizard (Hand) (f258)")] HandLizardRegular,
        [Description("Lizard (Hand) (f258)")] HandLizardSolid,
        [Description("Paper (Hand) (f256, stop)")] HandPaperRegular,
        [Description("Paper (Hand) (f256, stop)")] HandPaperSolid,
        [Description("Peace (Hand) (f25b)")] HandPeaceRegular,
        [Description("Peace (Hand) (f25b)")] HandPeaceSolid,
        [Description("Hand Pointing Down (f0a7, point, finger, hand-o-down)")] HandPointDownRegular,
        [Description("Hand Pointing Down (f0a7, point, finger, hand-o-down)")] HandPointDownSolid,
        [Description("Pointer (Hand) (f25a, select)")] HandPointerRegular,
        [Description("Pointer (Hand) (f25a, select)")] HandPointerSolid,
        [Description("Hand Pointing Left (f0a5, point, left, previous, back, finger, hand-o-left)")] HandPointLeftRegular,
        [Description("Hand Pointing Left (f0a5, point, left, previous, back, finger, hand-o-left)")] HandPointLeftSolid,
        [Description("Hand Pointing Right (f0a4, point, right, next, forward, finger, hand-o-right)")] HandPointRightRegular,
        [Description("Hand Pointing Right (f0a4, point, right, next, forward, finger, hand-o-right)")] HandPointRightSolid,
        [Description("Hand Pointing Up (f0a6, point, finger, hand-o-up)")] HandPointUpRegular,
        [Description("Hand Pointing Up (f0a6, point, finger, hand-o-up)")] HandPointUpSolid,
        [Description("Rock (Hand) (f255)")] HandRockRegular,
        [Description("Rock (Hand) (f255)")] HandRockSolid,
        [Description("Scissors (Hand) (f257)")] HandScissorsRegular,
        [Description("Scissors (Hand) (f257)")] HandScissorsSolid,
        [Description("Handshake (f2b5, greeting, partnership)")] HandshakeRegular,
        [Description("Handshake (f2b5, greeting, partnership)")] HandshakeSolid,
        [Description("Helping Hands (f4c4, assistance, aid, partnership, volunteering)")] HandsHelpingSolid,
        [Description("Spock (Hand) (f259)")] HandSpockRegular,
        [Description("Spock (Hand) (f259)")] HandSpockSolid,
        [Description("Hands (f4c2)")] HandsSolid,
        [Description("Hashtag (f292)")] HashtagSolid,
        [Description("HDD (f0a0, harddrive, hard drive, storage, save, machine)")] HddRegular,
        [Description("HDD (f0a0, harddrive, hard drive, storage, save, machine)")] HddSolid,
        [Description("heading (f1dc, header, header)")] HeadingSolid,
        [Description("headphones (f025, sound, listen, music, audio, speaker)")] HeadphonesSolid,
        [Description("Heartbeat (f21e, ekg, vital signs, lifeline)")] HeartbeatSolid,
        [Description("Heart (f004, love, like, favorite)")] HeartRegular,
        [Description("Heart (f004, love, like, favorite)")] HeartSolid,
        [Description("Hips (f452)")] HipsBrands,
        [Description("HireAHelper (f3b0)")] HireAHelperBrands,
        [Description("History (f1da)")] HistorySolid,
        [Description("Hockey Puck (f453)")] HockeyPuckSolid,
        [Description("home (f015, main, house)")] HomeSolid,
        [Description("Hooli (f427)")] HooliBrands,
        [Description("Hospital Alternate (f47d, building, medical center, emergency room)")] HospitalAltSolid,
        [Description("hospital (f0f8, building, medical center, emergency room)")] HospitalRegular,
        [Description("hospital (f0f8, building, medical center, emergency room)")] HospitalSolid,
        [Description("Hospital Symbol (f47e)")] HospitalSymbolSolid,
        [Description("Hotjar (f3b1)")] HotjarBrands,
        [Description("Hourglass End (f253)")] HourglassEndSolid,
        [Description("Hourglass Half (f252)")] HourglassHalfSolid,
        [Description("Hourglass (f254)")] HourglassRegular,
        [Description("Hourglass (f254)")] HourglassSolid,
        [Description("Hourglass Start (f251)")] HourglassStartSolid,
        [Description("Houzz (f27c)")] HouzzBrands,
        [Description("H Square (f0fd, hospital, hotel)")] HSquareSolid,
        [Description("HTML 5 Logo (f13b)")] Html5Brands,
        [Description("HubSpot (f3b2)")] HubspotBrands,
        [Description("I Beam Cursor (f246)")] ICursorSolid,
        [Description("Identification Badge (f2c1)")] IdBadgeRegular,
        [Description("Identification Badge (f2c1)")] IdBadgeSolid,
        [Description("Identification Card Alternate (f47f, demographics)")] IdCardAltSolid,
        [Description("Identification Card (f2c2)")] IdCardRegular,
        [Description("Identification Card (f2c2)")] IdCardSolid,
        [Description("Image (f03e, photo, album, picture, picture)")] ImageRegular,
        [Description("Image (f03e, photo, album, picture, picture)")] ImageSolid,
        [Description("Images (f302, photo, album, picture)")] ImagesRegular,
        [Description("Images (f302, photo, album, picture)")] ImagesSolid,
        [Description("IMDB (f2d8)")] ImdbBrands,
        [Description("inbox (f01c)")] InboxSolid,
        [Description("Indent (f03c)")] IndentSolid,
        [Description("Industry (f275, factory, manufacturing)")] IndustrySolid,
        [Description("Info Circle (f05a, help, information, more, details)")] InfoCircleSolid,
        [Description("Info (f129, help, information, more, details)")] InfoSolid,
        [Description("Instagram (f16d)")] InstagramBrands,
        [Description("Internet-explorer (f26b, browser, ie)")] InternetExplorerBrands,
        [Description("ioxhost (f208)")] IoxhostBrands,
        [Description("italic (f033, italics)")] ItalicSolid,
        [Description("iTunes (f3b4)")] ItunesBrands,
        [Description("Itunes Note (f3b5)")] ItunesNoteBrands,
        [Description("Jenkis (f3b6)")] JenkinsBrands,
        [Description("Joget (f3b7)")] JogetBrands,
        [Description("Joomla Logo (f1aa)")] JoomlaBrands,
        [Description("JavaScript (JS) (f3b8)")] JsBrands,
        [Description("jsFiddle (f1cc)")] JsfiddleBrands,
        [Description("JavaScript (JS) Square (f3b9)")] JsSquareBrands,
        [Description("Keyboard (f11c, type, input)")] KeyboardRegular,
        [Description("Keyboard (f11c, type, input)")] KeyboardSolid,
        [Description("KeyCDN (f3ba)")] KeycdnBrands,
        [Description("key (f084, unlock, password)")] KeySolid,
        [Description("Kickstarter (f3bb)")] KickstarterBrands,
        [Description("Kickstarter K (f3bc)")] KickstarterKBrands,
        [Description("KORVUE (f42f)")] KorvueBrands,
        [Description("Language (f1ab)")] LanguageSolid,
        [Description("Laptop (f109, demo, computer, device, pc, mac, pc, macbook, dell, dude you're getting, machine)")] LaptopSolid,
        [Description("Laravel (f3bd)")] LaravelBrands,
        [Description("last.fm (f202)")] LastfmBrands,
        [Description("last.fm Square (f203)")] LastfmSquareBrands,
        [Description("leaf (f06c, eco, nature, plant)")] LeafSolid,
        [Description("Leanpub (f212)")] LeanpubBrands,
        [Description("Lemon (f094, food)")] LemonRegular,
        [Description("Lemon (f094, food)")] LemonSolid,
        [Description("Less (f41d)")] LessBrands,
        [Description("Level Down Alternate (f3be, level-down)")] LevelDownAltSolid,
        [Description("Level Up Alternate (f3bf, level-up)")] LevelUpAltSolid,
        [Description("Life Ring (f1cd, support)")] LifeRingRegular,
        [Description("Life Ring (f1cd, support)")] LifeRingSolid,
        [Description("Lightbulb (f0eb, idea, inspiration)")] LightbulbRegular,
        [Description("Lightbulb (f0eb, idea, inspiration)")] LightbulbSolid,
        [Description("Line (f3c0)")] LineBrands,
        [Description("LinkedIn (f08c, linkedin-square)")] LinkedinBrands,
        [Description("LinkedIn In (f0e1, linkedin)")] LinkedinInBrands,
        [Description("Link (f0c1, chain)")] LinkSolid,
        [Description("Linode (f2b8)")] LinodeBrands,
        [Description("Linux (f17c, tux)")] LinuxBrands,
        [Description("Turkish Lira Sign (f195, try, turkish, try)")] LiraSignSolid,
        [Description("List Alternate (f022, ul, ol, checklist, finished, completed, done, todo)")] ListAltRegular,
        [Description("List Alternate (f022, ul, ol, checklist, finished, completed, done, todo)")] ListAltSolid,
        [Description("list-ol (f0cb, ul, ol, checklist, list, todo, list, numbers)")] ListOlSolid,
        [Description("List (f03a, ul, ol, checklist, finished, completed, done, todo)")] ListSolid,
        [Description("list-ul (f0ca, ul, ol, checklist, todo, list)")] ListUlSolid,
        [Description("location-arrow (f124, map, coordinates, location, address, place, where, gps)")] LocationArrowSolid,
        [Description("Lock Open (f3c1, protect, admin, password, lock, open)")] LockOpenSolid,
        [Description("lock (f023, protect, admin, security)")] LockSolid,
        [Description("Alternate Long Arrow Down (f309, long-arrow-down)")] LongArrowAltDownSolid,
        [Description("Alternate Long Arrow Left (f30a, previous, back, long-arrow-left)")] LongArrowAltLeftSolid,
        [Description("Alternate Long Arrow Right (f30b, long-arrow-right)")] LongArrowAltRightSolid,
        [Description("Alternate Long Arrow Up (f30c, long-arrow-up)")] LongArrowAltUpSolid,
        [Description("Low Vision (f2a8)")] LowVisionSolid,
        [Description("lyft (f3c3)")] LyftBrands,
        [Description("Magento (f3c4)")] MagentoBrands,
        [Description("magic (f0d0, wizard, automatic, autocomplete)")] MagicSolid,
        [Description("magnet (f076)")] MagnetSolid,
        [Description("Male (f183, man, human, user, person, profile)")] MaleSolid,
        [Description("Map Marker Alternate (f3c5, map-marker, gps)")] MapMarkerAltSolid,
        [Description("map-marker (f041, map, pin, location, coordinates, localize, address, travel, where, place, gps)")] MapMarkerSolid,
        [Description("Map Pin (f276)")] MapPinSolid,
        [Description("Map (f279)")] MapRegular,
        [Description("Map Signs (f277)")] MapSignsSolid,
        [Description("Map (f279)")] MapSolid,
        [Description("Mars Double (f227)")] MarsDoubleSolid,
        [Description("Mars (f222, male)")] MarsSolid,
        [Description("Mars Stroke Horizontal (f22b)")] MarsStrokeHSolid,
        [Description("Mars Stroke (f229)")] MarsStrokeSolid,
        [Description("Mars Stroke Vertical (f22a)")] MarsStrokeVSolid,
        [Description("MaxCDN (f136)")] MaxcdnBrands,
        [Description("MedApps (f3c6)")] MedappsBrands,
        [Description("Medium (f23a)")] MediumBrands,
        [Description("Medium M (f3c7)")] MediumMBrands,
        [Description("medkit (f0fa, first aid, firstaid, help, support, health)")] MedkitSolid,
        [Description("MRT (f3c8)")] MedrtBrands,
        [Description("Meetup (f2e0)")] MeetupBrands,
        [Description("Meh (f11a, face, emoticon, rating, neutral)")] MehRegular,
        [Description("Meh (f11a, face, emoticon, rating, neutral)")] MehSolid,
        [Description("Mercury (f223, transgender)")] MercurySolid,
        [Description("Microchip (f2db)")] MicrochipSolid,
        [Description("Microphone Slash (f131, record, voice, sound, mute)")] MicrophoneSlashSolid,
        [Description("microphone (f130, record, voice, sound)")] MicrophoneSolid,
        [Description("Microsoft (f3ca)")] MicrosoftBrands,
        [Description("Minus Circle (f056, delete, remove, trash, hide)")] MinusCircleSolid,
        [Description("minus (f068, hide, minify, delete, remove, trash, hide, collapse)")] MinusSolid,
        [Description("Minus Square (f146, hide, minify, delete, remove, trash, hide, collapse)")] MinusSquareRegular,
        [Description("Minus Square (f146, hide, minify, delete, remove, trash, hide, collapse)")] MinusSquareSolid,
        [Description("Mix (f3cb)")] MixBrands,
        [Description("Mixcloud (f289)")] MixcloudBrands,
        [Description("Mizuni (f3cc)")] MizuniBrands,
        [Description("Alternate Mobile (f3cd, cell phone, cellphone, text, call, number, telephone, device, screen, apple, iphone)")] MobileAltSolid,
        [Description("Mobile Phone (f10b, cell phone, cellphone, text, call, number, telephone, device, screen, apple, iphone)")] MobileSolid,
        [Description("MODX (f285)")] ModxBrands,
        [Description("Monero (f3d0)")] MoneroBrands,
        [Description("Money Bill Alternate (f3d1, cash, money, buy, checkout, purchase, payment, price)")] MoneyBillAltRegular,
        [Description("Money Bill Alternate (f3d1, cash, money, buy, checkout, purchase, payment, price)")] MoneyBillAltSolid,
        [Description("Moon (f186, night, darker, contrast)")] MoonRegular,
        [Description("Moon (f186, night, darker, contrast)")] MoonSolid,
        [Description("Motorcycle (f21c, vehicle, machine, transportation, bike)")] MotorcycleSolid,
        [Description("Mouse Pointer (f245, select)")] MousePointerSolid,
        [Description("Music (f001, note, sound)")] MusicSolid,
        [Description("Napster (f3d2)")] NapsterBrands,
        [Description("Neuter (f22c)")] NeuterSolid,
        [Description("Newspaper (f1ea, press, article)")] NewspaperRegular,
        [Description("Newspaper (f1ea, press, article)")] NewspaperSolid,
        [Description("Nintendo Switch (f418)")] NintendoSwitchBrands,
        [Description("Node.js (f419)")] NodeBrands,
        [Description("Node.js JS (f3d3)")] NodeJsBrands,
        [Description("Medical Notes (f481)")] NotesMedicalSolid,
        [Description("npm (f3d4)")] NpmBrands,
        [Description("NS8 (f3d5)")] Ns8Brands,
        [Description("Nutritionix (f3d6)")] NutritionixBrands,
        [Description("Object Group (f247, design)")] ObjectGroupRegular,
        [Description("Object Group (f247, design)")] ObjectGroupSolid,
        [Description("Object Ungroup (f248, design)")] ObjectUngroupRegular,
        [Description("Object Ungroup (f248, design)")] ObjectUngroupSolid,
        [Description("Odnoklassniki (f263)")] OdnoklassnikiBrands,
        [Description("Odnoklassniki Square (f264)")] OdnoklassnikiSquareBrands,
        [Description("OpenCart (f23d)")] OpencartBrands,
        [Description("OpenID (f19b)")] OpenidBrands,
        [Description("Opera (f26a)")] OperaBrands,
        [Description("Optin Monster (f23c)")] OptinMonsterBrands,
        [Description("Open Source Initiative (f41a)")] OsiBrands,
        [Description("Outdent (f03b)")] OutdentSolid,
        [Description("page4 Corporation (f3d7)")] Page4Brands,
        [Description("Pagelines (f18c, leaf, leaves, tree, plant, eco, nature)")] PagelinesBrands,
        [Description("Paint Brush (f1fc)")] PaintBrushSolid,
        [Description("Palfed (f3d8)")] PalfedBrands,
        [Description("Pallet (f482)")] PalletSolid,
        [Description("Paperclip (f0c6, attachment)")] PaperclipSolid,
        [Description("Paper Plane (f1d8)")] PaperPlaneRegular,
        [Description("Paper Plane (f1d8)")] PaperPlaneSolid,
        [Description("Parachute Box (f4cd, aid, assistance, rescue, supplies)")] ParachuteBoxSolid,
        [Description("paragraph (f1dd)")] ParagraphSolid,
        [Description("Paste (f0ea, copy, clipboard)")] PasteSolid,
        [Description("Patreon (f3d9)")] PatreonBrands,
        [Description("Pause Circle (f28b)")] PauseCircleRegular,
        [Description("Pause Circle (f28b)")] PauseCircleSolid,
        [Description("pause (f04c, wait)")] PauseSolid,
        [Description("Paw (f1b0, pet)")] PawSolid,
        [Description("Paypal (f1ed)")] PaypalBrands,
        [Description("Alternate Pencil (f303, write, edit, update, pencil, design)")] PencilAltSolid,
        [Description("Pen Square (f14b, write, edit, update, pencil-square)")] PenSquareSolid,
        [Description("People Carry (f4ce, movers)")] PeopleCarrySolid,
        [Description("Percent (f295)")] PercentSolid,
        [Description("Periscope (f3da)")] PeriscopeBrands,
        [Description("Phabricator (f3db)")] PhabricatorBrands,
        [Description("Phoenix Framework (f3dc)")] PhoenixFrameworkBrands,
        [Description("Phone Slash (f3dd)")] PhoneSlashSolid,
        [Description("Phone (f095, call, voice, number, support, earphone, telephone)")] PhoneSolid,
        [Description("Phone Square (f098, call, voice, number, support, telephone)")] PhoneSquareSolid,
        [Description("Phone Volume (f2a0, telephone, volume-control-phone)")] PhoneVolumeSolid,
        [Description("PHP (f457)")] PhpBrands,
        [Description("Alternate Pied Piper Logo (f1a8)")] PiedPiperAltBrands,
        [Description("Pied Piper Logo (f2ae)")] PiedPiperBrands,
        [Description("Pied Piper PP Logo (Old) (f1a7)")] PiedPiperPpBrands,
        [Description("Piggy Bank (f4d3, savings, save)")] PiggyBankSolid,
        [Description("Pills (f484, medicine, drugs)")] PillsSolid,
        [Description("Pinterest (f0d2)")] PinterestBrands,
        [Description("Pinterest P (f231)")] PinterestPBrands,
        [Description("Pinterest Square (f0d3)")] PinterestSquareBrands,
        [Description("plane (f072, travel, trip, location, destination, airplane, fly, mode)")] PlaneSolid,
        [Description("Play Circle (f144, start, playing)")] PlayCircleRegular,
        [Description("Play Circle (f144, start, playing)")] PlayCircleSolid,
        [Description("play (f04b, start, playing, music, sound)")] PlaySolid,
        [Description("PlayStation (f3df)")] PlaystationBrands,
        [Description("Plug (f1e6, power, connect, online)")] PlugSolid,
        [Description("Plus Circle (f055, add, new, create, expand)")] PlusCircleSolid,
        [Description("plus (f067, add, new, create, expand)")] PlusSolid,
        [Description("Plus Square (f0fe, add, new, create, expand)")] PlusSquareRegular,
        [Description("Plus Square (f0fe, add, new, create, expand)")] PlusSquareSolid,
        [Description("Podcast (f2ce)")] PodcastSolid,
        [Description("Poo (f2fe)")] PooSolid,
        [Description("Pound Sign (f154, gbp, gbp)")] PoundSignSolid,
        [Description("Power Off (f011, on)")] PowerOffSolid,
        [Description("Alternate Prescription Bottle (f486, prescription, rx)")] PrescriptionBottleAltSolid,
        [Description("Prescription Bottle (f485, prescription, rx)")] PrescriptionBottleSolid,
        [Description("print (f02f)")] PrintSolid,
        [Description("Procedures (f487)")] ProceduresSolid,
        [Description("Product Hunt (f288)")] ProductHuntBrands,
        [Description("Pushed (f3e1)")] PushedBrands,
        [Description("Puzzle Piece (f12e, addon, add-on, section)")] PuzzlePieceSolid,
        [Description("Python (f3e2)")] PythonBrands,
        [Description("QQ (f1d6)")] QqBrands,
        [Description("qrcode (f029, scan)")] QrcodeSolid,
        [Description("Question Circle (f059, help, information, unknown, support)")] QuestionCircleRegular,
        [Description("Question Circle (f059, help, information, unknown, support)")] QuestionCircleSolid,
        [Description("Question (f128, help, information, unknown, support)")] QuestionSolid,
        [Description("Quidditch (f458)")] QuidditchSolid,
        [Description("QuinScape (f459)")] QuinscapeBrands,
        [Description("Quora (f2c4)")] QuoraBrands,
        [Description("quote-left (f10d)")] QuoteLeftSolid,
        [Description("quote-right (f10e)")] QuoteRightSolid,
        [Description("random (f074, sort, shuffle)")] RandomSolid,
        [Description("Ravelry (f2d9)")] RavelryBrands,
        [Description("React (f41b)")] ReactBrands,
        [Description("ReadMe (f4d5)")] ReadmeBrands,
        [Description("Rebel Alliance (f1d0)")] RebelBrands,
        [Description("Recycle (f1b8)")] RecycleSolid,
        [Description("reddit Alien (f281)")] RedditAlienBrands,
        [Description("reddit Logo (f1a1)")] RedditBrands,
        [Description("reddit Square (f1a2)")] RedditSquareBrands,
        [Description("Alternate Redo (f2f9, forward, repeat)")] RedoAltSolid,
        [Description("Redo (f01e, forward, repeat, repeat)")] RedoSolid,
        [Description("red river (f3e3)")] RedRiverBrands,
        [Description("Registered Trademark (f25d)")] RegisteredRegular,
        [Description("Registered Trademark (f25d)")] RegisteredSolid,
        [Description("Rendact (f3e4)")] RendactBrands,
        [Description("Renren (f18b)")] RenrenBrands,
        [Description("reply-all (f122)")] ReplyAllSolid,
        [Description("replyd (f3e6)")] ReplydBrands,
        [Description("Reply (f3e5)")] ReplySolid,
        [Description("Resolving (f3e7)")] ResolvingBrands,
        [Description("Retweet (f079, refresh, reload, share, swap)")] RetweetSolid,
        [Description("Ribbon (f4d6, cause, badge, pin, lapel)")] RibbonSolid,
        [Description("road (f018, street)")] RoadSolid,
        [Description("Rocket.Chat (f3e8)")] RocketchatBrands,
        [Description("rocket (f135, app)")] RocketSolid,
        [Description("Rockrms (f3e9)")] RockrmsBrands,
        [Description("rss (f09e, blog)")] RssSolid,
        [Description("RSS Square (f143, feed, blog)")] RssSquareSolid,
        [Description("Ruble Sign (f158, rub, rub)")] RubleSignSolid,
        [Description("Indian Rupee Sign (f156, indian, inr)")] RupeeSignSolid,
        [Description("Safari (f267, browser)")] SafariBrands,
        [Description("Sass (f41e)")] SassBrands,
        [Description("Save (f0c7, floppy, floppy-o)")] SaveRegular,
        [Description("Save (f0c7, floppy, floppy-o)")] SaveSolid,
        [Description("SCHLIX (f3ea)")] SchlixBrands,
        [Description("Scribd (f28a)")] ScribdBrands,
        [Description("Searchengin (f3eb)")] SearchenginBrands,
        [Description("Search Minus (f010, magnify, minify, zoom, smaller, zoom out)")] SearchMinusSolid,
        [Description("Search Plus (f00e, magnify, zoom, enlarge, bigger, zoom in)")] SearchPlusSolid,
        [Description("Search (f002, magnify, zoom, enlarge, bigger, preview)")] SearchSolid,
        [Description("Seedling (f4d8)")] SeedlingSolid,
        [Description("Sellcast (f2da, eercast)")] SellcastBrands,
        [Description("Sellsy (f213)")] SellsyBrands,
        [Description("Server (f233)")] ServerSolid,
        [Description("Servicestack (f3ec)")] ServicestackBrands,
        [Description("Alternate Share (f1e0)")] ShareAltSolid,
        [Description("Alternate Share Square (f1e1)")] ShareAltSquareSolid,
        [Description("Share (f064)")] ShareSolid,
        [Description("Share Square (f14d, social, send)")] ShareSquareRegular,
        [Description("Share Square (f14d, social, send)")] ShareSquareSolid,
        [Description("Shekel Sign (f20b, ils, ils)")] ShekelSignSolid,
        [Description("Alternate Shield (f3ed, shield)")] ShieldAltSolid,
        [Description("Shipping Fast (f48b)")] ShippingFastSolid,
        [Description("Ship (f21a, boat, sea)")] ShipSolid,
        [Description("Shirts in Bulk (f214)")] ShirtsinbulkBrands,
        [Description("Shopping Bag (f290)")] ShoppingBagSolid,
        [Description("Shopping Basket (f291)")] ShoppingBasketSolid,
        [Description("shopping-cart (f07a, checkout, buy, purchase, payment)")] ShoppingCartSolid,
        [Description("Shower (f2cc)")] ShowerSolid,
        [Description("signal (f012, graph, bars, status, online)")] SignalSolid,
        [Description("Alternate Sign In (f2f6, enter, join, log in, login, sign up, sign in, signin, signup, arrow, sign-in)")] SignInAltSolid,
        [Description("Sign Language (f2a7)")] SignLanguageSolid,
        [Description("Alternate Sign Out (f2f5, log out, logout, leave, exit, arrow, sign-out)")] SignOutAltSolid,
        [Description("Sign (f4d9)")] SignSolid,
        [Description("SimplyBuilt (f215)")] SimplybuiltBrands,
        [Description("SISTRIX (f3ee)")] SistrixBrands,
        [Description("Sitemap (f0e8, directory, hierarchy, organization)")] SitemapSolid,
        [Description("skyatlas (f216)")] SkyatlasBrands,
        [Description("Skype (f17e)")] SkypeBrands,
        [Description("Slack Logo (f198, hashtag, anchor, hash)")] SlackBrands,
        [Description("Slack Hashtag (f3ef, hashtag, anchor, hash)")] SlackHashBrands,
        [Description("Horizontal Sliders (f1de, settings, sliders)")] SlidersHSolid,
        [Description("Slideshare (f1e7)")] SlideshareBrands,
        [Description("Smile (f118, face, emoticon, happy, approve, satisfied, rating)")] SmileRegular,
        [Description("Smile (f118, face, emoticon, happy, approve, satisfied, rating)")] SmileSolid,
        [Description("Smoking (f48d, smoking status, cigarette, nicotine)")] SmokingSolid,
        [Description("Snapchat (f2ab)")] SnapchatBrands,
        [Description("Snapchat Ghost (f2ac)")] SnapchatGhostBrands,
        [Description("Snapchat Square (f2ad)")] SnapchatSquareBrands,
        [Description("Snowflake (f2dc)")] SnowflakeRegular,
        [Description("Snowflake (f2dc)")] SnowflakeSolid,
        [Description("Sort Alpha Down (f15d, sort-alpha-asc)")] SortAlphaDownSolid,
        [Description("Sort Alpha Up (f15e, sort-alpha-desc)")] SortAlphaUpSolid,
        [Description("Sort Amount Down (f160, sort-amount-asc)")] SortAmountDownSolid,
        [Description("Sort Amount Up (f161, sort-amount-desc)")] SortAmountUpSolid,
        [Description("Sort Down (Descending) (f0dd, arrow, descending, sort-desc)")] SortDownSolid,
        [Description("Sort Numeric Down (f162, numbers, sort-numeric-asc)")] SortNumericDownSolid,
        [Description("Sort Numeric Up (f163, numbers, sort-numeric-desc)")] SortNumericUpSolid,
        [Description("Sort (f0dc, order)")] SortSolid,
        [Description("Sort Up (Ascending) (f0de, arrow, ascending, sort-asc)")] SortUpSolid,
        [Description("SoundCloud (f1be)")] SoundcloudBrands,
        [Description("Space Shuttle (f197, nasa, astronaut, rocket, machine, transportation)")] SpaceShuttleSolid,
        [Description("Speakap (f3f3)")] SpeakapBrands,
        [Description("Spinner (f110, loading, progress)")] SpinnerSolid,
        [Description("Spotify (f1bc)")] SpotifyBrands,
        [Description("Square Full (f45c)")] SquareFullSolid,
        [Description("Square (f0c8, block, box)")] SquareRegular,
        [Description("Square (f0c8, block, box)")] SquareSolid,
        [Description("Stack Exchange (f18d)")] StackExchangeBrands,
        [Description("Stack Overflow (f16c)")] StackOverflowBrands,
        [Description("star-half (f089, award, achievement, rating, score, star-half-empty, star-half-full)")] StarHalfRegular,
        [Description("star-half (f089, award, achievement, rating, score, star-half-empty, star-half-full)")] StarHalfSolid,
        [Description("Star (f005, award, achievement, night, rating, score, favorite)")] StarRegular,
        [Description("Star (f005, award, achievement, night, rating, score, favorite)")] StarSolid,
        [Description("StayLinked (f3f5)")] StaylinkedBrands,
        [Description("Steam (f1b6)")] SteamBrands,
        [Description("Steam Square (f1b7)")] SteamSquareBrands,
        [Description("Steam Symbol (f3f6)")] SteamSymbolBrands,
        [Description("step-backward (f048, rewind, previous, beginning, start, first)")] StepBackwardSolid,
        [Description("step-forward (f051, next, end, last)")] StepForwardSolid,
        [Description("Stethoscope (f0f1)")] StethoscopeSolid,
        [Description("Sticker Mule (f3f7)")] StickerMuleBrands,
        [Description("Sticky Note (f249)")] StickyNoteRegular,
        [Description("Sticky Note (f249)")] StickyNoteSolid,
        [Description("Stop Circle (f28d)")] StopCircleRegular,
        [Description("Stop Circle (f28d)")] StopCircleSolid,
        [Description("stop (f04d, block, box, square)")] StopSolid,
        [Description("Stopwatch (f2f2, time)")] StopwatchSolid,
        [Description("Strava (f428)")] StravaBrands,
        [Description("Street View (f21d, map)")] StreetViewSolid,
        [Description("Strikethrough (f0cc)")] StrikethroughSolid,
        [Description("Stripe (f429)")] StripeBrands,
        [Description("Stripe S (f42a)")] StripeSBrands,
        [Description("Studio Vinari (f3f8)")] StudiovinariBrands,
        [Description("StumbleUpon Logo (f1a4)")] StumbleuponBrands,
        [Description("StumbleUpon Circle (f1a3)")] StumbleuponCircleBrands,
        [Description("subscript (f12c)")] SubscriptSolid,
        [Description("Subway (f239, vehicle, train, railway, machine, transportation)")] SubwaySolid,
        [Description("Suitcase (f0f2, trip, luggage, travel, move, baggage)")] SuitcaseSolid,
        [Description("Sun (f185, weather, contrast, lighter, brighten, day)")] SunRegular,
        [Description("Sun (f185, weather, contrast, lighter, brighten, day)")] SunSolid,
        [Description("Superpowers (f2dd)")] SuperpowersBrands,
        [Description("superscript (f12b, exponential)")] SuperscriptSolid,
        [Description("Supple (f3f9)")] SuppleBrands,
        [Description("Alternate Sync (f2f1, reload, refresh)")] SyncAltSolid,
        [Description("Sync (f021, reload, refresh, exchange, swap)")] SyncSolid,
        [Description("Syringe (f48e, immunizations, needle)")] SyringeSolid,
        [Description("table (f0ce, data, excel, spreadsheet)")] TableSolid,
        [Description("Alternate Tablet (f3fa, device, screen, apple, ipad, kindle)")] TabletAltSolid,
        [Description("Table Tennis (f45d)")] TableTennisSolid,
        [Description("tablet (f10a, device, screen, apple, ipad, kindle)")] TabletSolid,
        [Description("Tablets (f490, medicine, drugs)")] TabletsSolid,
        [Description("Alternate Tachometer (f3fd, tachometer, dashboard)")] TachometerAltSolid,
        [Description("tag (f02b, label)")] TagSolid,
        [Description("tags (f02c, labels)")] TagsSolid,
        [Description("Tape (f4db)")] TapeSolid,
        [Description("Tasks (f0ae, progress, loading, downloading, downloads, settings)")] TasksSolid,
        [Description("Taxi (f1ba, vehicle, machine, transportation, cab, cabbie, car, uber, lyft, car service)")] TaxiSolid,
        [Description("Telegram (f2c6)")] TelegramBrands,
        [Description("Telegram Plane (f3fe)")] TelegramPlaneBrands,
        [Description("Tencent Weibo (f1d5)")] TencentWeiboBrands,
        [Description("Terminal (f120, command, prompt, code, console)")] TerminalSolid,
        [Description("text-height (f034)")] TextHeightSolid,
        [Description("text-width (f035)")] TextWidthSolid,
        [Description("ThemeIsle (f2b2)")] ThemeisleBrands,
        [Description("Thermometer Empty (f2cb, status)")] ThermometerEmptySolid,
        [Description("Thermometer Full (f2c7, status)")] ThermometerFullSolid,
        [Description("Thermometer 1/2 Full (f2c9, status)")] ThermometerHalfSolid,
        [Description("Thermometer 1/4 Full (f2ca, status)")] ThermometerQuarterSolid,
        [Description("Thermometer (f491, temperature, fever)")] ThermometerSolid,
        [Description("Thermometer 3/4 Full (f2c8, status)")] ThermometerThreeQuartersSolid,
        [Description("th-large (f009, blocks, squares, boxes, grid)")] ThLargeSolid,
        [Description("th-list (f00b, ul, ol, checklist, finished, completed, done, todo)")] ThListSolid,
        [Description("th (f00a, blocks, squares, boxes, grid)")] ThSolid,
        [Description("thumbs-down (f165, dislike, disapprove, disagree, hand, thumbs-o-down)")] ThumbsDownRegular,
        [Description("thumbs-down (f165, dislike, disapprove, disagree, hand, thumbs-o-down)")] ThumbsDownSolid,
        [Description("thumbs-up (f164, like, favorite, approve, agree, hand, thumbs-o-up, success, yes, ok, okay, you got it dude)")] ThumbsUpRegular,
        [Description("thumbs-up (f164, like, favorite, approve, agree, hand, thumbs-o-up, success, yes, ok, okay, you got it dude)")] ThumbsUpSolid,
        [Description("Thumbtack (f08d, marker, pin, location, coordinates, thumb-tack)")] ThumbtackSolid,
        [Description("Alternate Ticket (f3ff, ticket)")] TicketAltSolid,
        [Description("Times Circle (f057, close, exit, x, cross, problem, notification, notify, notice, wrong, incorrect)")] TimesCircleRegular,
        [Description("Times Circle (f057, close, exit, x, cross, problem, notification, notify, notice, wrong, incorrect)")] TimesCircleSolid,
        [Description("Times (f00d, close, exit, x, cross, error, problem, notification, notify, notice, wrong, incorrect)")] TimesSolid,
        [Description("tint (f043, raindrop, waterdrop, drop, droplet)")] TintSolid,
        [Description("Toggle Off (f204, switch)")] ToggleOffSolid,
        [Description("Toggle On (f205, switch)")] ToggleOnSolid,
        [Description("Trademark (f25c)")] TrademarkSolid,
        [Description("Train (f238, bullet, locomotive, railway)")] TrainSolid,
        [Description("Alternate Transgender (f225)")] TransgenderAltSolid,
        [Description("Transgender (f224, intersex)")] TransgenderSolid,
        [Description("Alternate Trash (f2ed, garbage, delete, remove, hide, trash, trash-o)")] TrashAltRegular,
        [Description("Alternate Trash (f2ed, garbage, delete, remove, hide, trash, trash-o)")] TrashAltSolid,
        [Description("Trash (f1f8, garbage, delete, remove, hide)")] TrashSolid,
        [Description("Tree (f1bb)")] TreeSolid,
        [Description("Trello (f181)")] TrelloBrands,
        [Description("TripAdvisor (f262)")] TripadvisorBrands,
        [Description("trophy (f091, award, achievement, cup, winner, game)")] TrophySolid,
        [Description("Truck Loading (f4de)")] TruckLoadingSolid,
        [Description("Truck Moving (f4df)")] TruckMovingSolid,
        [Description("truck (f0d1, shipping, delivery)")] TruckSolid,
        [Description("TTY (f1e4)")] TtySolid,
        [Description("Tumblr (f173)")] TumblrBrands,
        [Description("Tumblr Square (f174)")] TumblrSquareBrands,
        [Description("Television (f26c, display, computer, monitor, television)")] TvSolid,
        [Description("Twitch (f1e8)")] TwitchBrands,
        [Description("Twitter (f099, tweet, social network)")] TwitterBrands,
        [Description("Twitter Square (f081, tweet, social network)")] TwitterSquareBrands,
        [Description("Typo3 (f42b)")] Typo3Brands,
        [Description("Uber (f402)")] UberBrands,
        [Description("UIkit (f403)")] UikitBrands,
        [Description("Umbrella (f0e9)")] UmbrellaSolid,
        [Description("Underline (f0cd)")] UnderlineSolid,
        [Description("Alternate Undo (f2ea, back, exchange, swap, return, control z, oops)")] UndoAltSolid,
        [Description("Undo (f0e2, back, exchange, swap, return, control z, oops)")] UndoSolid,
        [Description("Uniregistry (f404)")] UniregistryBrands,
        [Description("Universal Access (f29a)")] UniversalAccessSolid,
        [Description("University (f19c, bank, institution)")] UniversitySolid,
        [Description("unlink (f127, remove, chain, chain-broken)")] UnlinkSolid,
        [Description("Alternate Unlock (f13e, protect, admin, password, lock)")] UnlockAltSolid,
        [Description("unlock (f09c, protect, admin, password, lock)")] UnlockSolid,
        [Description("Untappd (f405)")] UntappdBrands,
        [Description("Upload (f093, import)")] UploadSolid,
        [Description("USB (f287)")] UsbBrands,
        [Description("User Circle (f2bd, person, man, head, profile, account)")] UserCircleRegular,
        [Description("User Circle (f2bd, person, man, head, profile, account)")] UserCircleSolid,
        [Description("user-md (f0f0, doctor, profile, medical, nurse, job, occupation)")] UserMdSolid,
        [Description("Add User (f234, sign up, signup)")] UserPlusSolid,
        [Description("User (f007, person, man, head, profile, account)")] UserRegular,
        [Description("User Secret (f21b, whisper, spy, incognito, privacy)")] UserSecretSolid,
        [Description("User (f007, person, man, head, profile, account)")] UserSolid,
        [Description("Users (f0c0, people, profiles, persons)")] UsersSolid,
        [Description("Remove User (f235)")] UserTimesSolid,
        [Description("us-Sunnah Foundation (f407)")] UssunnahBrands,
        [Description("Utensil Spoon (f2e5, spoon)")] UtensilSpoonSolid,
        [Description("Utensils (f2e7, food, restaurant, spoon, knife, dinner, eat, cutlery)")] UtensilsSolid,
        [Description("Vaadin (f408)")] VaadinBrands,
        [Description("Venus Double (f226)")] VenusDoubleSolid,
        [Description("Venus Mars (f228)")] VenusMarsSolid,
        [Description("Venus (f221, female)")] VenusSolid,
        [Description("Viacoin (f237)")] ViacoinBrands,
        [Description("Viadeo (f2a9)")] ViadeoBrands,
        [Description("Viadeo Square (f2aa)")] ViadeoSquareBrands,
        [Description("Vial (f492, test tube)")] VialSolid,
        [Description("Vials (f493, lab results, test tubes)")] VialsSolid,
        [Description("Viber (f409)")] ViberBrands,
        [Description("Video Slash (f4e2)")] VideoSlashSolid,
        [Description("Video (f03d, film, movie, record, camera, video-camera)")] VideoSolid,
        [Description("Vimeo (f40a)")] VimeoBrands,
        [Description("Vimeo Square (f194)")] VimeoSquareBrands,
        [Description("Vimeo (f27d, vimeo)")] VimeoVBrands,
        [Description("Vine (f1ca)")] VineBrands,
        [Description("VK (f189)")] VkBrands,
        [Description("VNV (f40b)")] VnvBrands,
        [Description("Volleyball Ball (f45f)")] VolleyballBallSolid,
        [Description("volume-down (f027, audio, lower, quieter, sound, music, speaker)")] VolumeDownSolid,
        [Description("volume-off (f026, audio, mute, sound, music)")] VolumeOffSolid,
        [Description("volume-up (f028, audio, higher, louder, sound, music, speaker)")] VolumeUpSolid,
        [Description("Vue.js (f41f)")] VuejsBrands,
        [Description("Warehouse (f494)")] WarehouseSolid,
        [Description("Weibo (f18a)")] WeiboBrands,
        [Description("Weight (f496, scale)")] WeightSolid,
        [Description("Weixin (WeChat) (f1d7)")] WeixinBrands,
        [Description("What's App (f232)")] WhatsappBrands,
        [Description("What's App Square (f40c)")] WhatsappSquareBrands,
        [Description("Wheelchair (f193, handicap, person)")] WheelchairSolid,
        [Description("WHMCS (f40d)")] WhmcsBrands,
        [Description("WiFi (f1eb)")] WifiSolid,
        [Description("Wikipedia W (f266)")] WikipediaWBrands,
        [Description("Window Close (f410)")] WindowCloseRegular,
        [Description("Window Close (f410)")] WindowCloseSolid,
        [Description("Window Maximize (f2d0)")] WindowMaximizeRegular,
        [Description("Window Maximize (f2d0)")] WindowMaximizeSolid,
        [Description("Window Minimize (f2d1)")] WindowMinimizeRegular,
        [Description("Window Minimize (f2d1)")] WindowMinimizeSolid,
        [Description("Window Restore (f2d2)")] WindowRestoreRegular,
        [Description("Window Restore (f2d2)")] WindowRestoreSolid,
        [Description("Windows (f17a, microsoft)")] WindowsBrands,
        [Description("Wine Glass (f4e3)")] WineGlassSolid,
        [Description("Won Sign (f159, krw, krw)")] WonSignSolid,
        [Description("WordPress Logo (f19a)")] WordpressBrands,
        [Description("Wordpress Simple (f411)")] WordpressSimpleBrands,
        [Description("WPBeginner (f297)")] WpbeginnerBrands,
        [Description("WPExplorer (f2de)")] WpexplorerBrands,
        [Description("WPForms (f298)")] WpformsBrands,
        [Description("Wrench (f0ad, settings, fix, update, spanner, tool)")] WrenchSolid,
        [Description("Xbox (f412)")] XboxBrands,
        [Description("Xing (f168)")] XingBrands,
        [Description("Xing Square (f169)")] XingSquareBrands,
        [Description("X-Ray (f497, radiological images, radiology)")] XRaySolid,
        [Description("Yahoo Logo (f19e)")] YahooBrands,
        [Description("Yandex (f413)")] YandexBrands,
        [Description("Yandex International (f414)")] YandexInternationalBrands,
        [Description("Y Combinator (f23b)")] YCombinatorBrands,
        [Description("Yelp (f1e9)")] YelpBrands,
        [Description("Yen Sign (f157, jpy, jpy)")] YenSignSolid,
        [Description("Yoast (f2b1)")] YoastBrands,
        [Description("YouTube (f167, video, film, youtube-play, youtube-square)")] YoutubeBrands,
        [Description("YouTube Square (f431)")] YoutubeSquareBrands,
    }
}