namespace MahApps.Metro.IconPacks
{
#if !NETFX_CORE
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconSimpleIcons" />.
    /// </summary>
    /// <remarks>
    /// All SVG icons for popular brands, maintained by Dan Leech <see><cref>https://twitter.com/bathtype</cref></see>.
    /// Contributions, corrections and requests can be made on GitHub <see><cref>https://github.com/danleech/simple-icons</cref></see>.
    /// </remarks>
    public enum PackIconSimpleIconsKind
    {
        [Description("Empty placeholder")] None,
        [Description("500px, https://about.500px.com/press")] _500px,
        [Description("About.me, https://about.me/assets")] AboutMe,
        [Description("ACM, http://identitystandards.acm.org/")] Acm,
        [Description("AddThis, http://www.addthis.com/")] AddThis,
        [Description("Adobe, https://www.adobe.com/")] Adobe,
        [Description("Adobe Acrobat Reader, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobeAcrobatReader,
        [Description("Adobe After Effects, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobeAfterEffects,
        [Description("Adobe Creative Cloud, https://www.adobe.io/apis/creativecloud/creativesdk/docs/websdk/adobe-creative-sdk-for-web_master/branding-guidelines.html")] AdobeCreativeCloud,
        [Description("Adobe Dreamweaver, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobeDreamweaver,
        [Description("Adobe Illustrator, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobeIllustrator,
        [Description("Adobe InDesign, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobeInDesign,
        [Description("Adobe Lightroom, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobeLightroom,
        [Description("Adobe Photoshop, https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg")] AdobePhotoshop,
        [Description("Adobe Typekit, https://helpx.adobe.com/content/dam/help/mnemonics/tk_appicon_RGB.svg")] AdobeTypekit,
        [Description("Airbnb, https://www.airbnb.com")] Airbnb,
        [Description("Amazon, https://worldvectorlogo.com/logo/amazon-icon")] Amazon,
        [Description("AMD, https://subscriptions.amd.com/greatpower/img/amd-logo-black.svg")] Amd,
        [Description("American Express, https://commons.wikimedia.org/wiki/File:American_Express_logo.svg")] AmericanExpress,
        [Description("Android, http://developer.android.com/distribute/tools/promote/brand.html")] Android,
        [Description("AngelList, https://angel.co/logo")] AngelList,
        [Description("Angular, https://angular.io/assets/images/logos/angular/angular_solidBlack.svg")] Angular,
        [Description("Apple, https://worldvectorlogo.com/logo/apple")] Apple,
        [Description("Apple Music, https://www.apple.com/itunes/marketing-on-music/identity-guidelines.html#apple-music-icon")] AppleMusic,
        [Description("Apple Pay, https://developer.apple.com/apple-pay/marketing/")] ApplePay,
        [Description("Archive of Our Own, https://archiveofourown.org/")] ArchiveOfOurOwn,
        [Description("Arch Linux, https://www.archlinux.org/art/")] ArchLinux,
        [Description("ArtStation, https://www.artstation.com/about/logo")] ArtStation,
        [Description("Asana, https://asana.com/styles")] Asana,
        [Description("AT&T, https://commons.wikimedia.org/wiki/File:AT%26T_logo_2016.svg")] AtAndT,
        [Description("Atlassian, https://atlassian.design/guidelines/brand/logos-1")] Atlassian,
        [Description("Atom, https://commons.wikimedia.org/wiki/File:Atom_editor_logo.svg")] Atom,
        [Description("Aurelia, https://aurelia.io/")] Aurelia,
        [Description("Auth0, https://styleguide.auth0.com")] Auth0,
        [Description("Automatic, https://www.automatic.com/press")] Automatic,
        [Description("Aventrix, https://www.aventrix.com/press")] Aventrix,
        [Description("Baidu, https://en.wikipedia.org/wiki/File:Baidu.svg")] Baidu,
        [Description("Bandcamp, https://bandcamp.com/buttons")] Bandcamp,
        [Description("Basecamp, https://basecamp.com/about/press")] Basecamp,
        [Description("Bath ASU, https://bathasu.com/press/")] BathAsu,
        [Description("Beats, https://www.elastic.co/brand")] Beats,
        [Description("Behance, https://www.behance.net/dev/api/brand")] Behance,
        [Description("Big Cartel, https://www.bigcartel.com")] BigCartel,
        [Description("Bing, https://commons.wikimedia.org/wiki/File:Bing_logo_(2016).svg")] Bing,
        [Description("Bitbucket, https://www.atlassian.com/company/news/press-kit")] Bitbucket,
        [Description("Bitcoin, https://bitcoin.org/en")] Bitcoin,
        [Description("Bitly, https://bitly.com/pages/press")] Bitly,
        [Description("Blender, https://www.blender.org/about/logo/")] Blender,
        [Description("Blogger, https://www.blogger.com")] Blogger,
        [Description("Boost, https://www.boostmobile.com/")] Boost,
        [Description("Bootstrap, http://getbootstrap.com/about")] Bootstrap,
        [Description("Bower, https://bower.io/docs/about/#brand")] Bower,
        [Description("Brand.ai, https://brand.ai/brand-ai/style")] BrandAi,
        [Description("Buffer, https://buffer.com/press")] Buffer,
        [Description("BuzzFeed, http://www.buzzfeed.com/press/downloads")] BuzzFeed,
        [Description("CakePHP, https://cakephp.org/logos")] CakePhp,
        [Description("Campaign Monitor, https://www.campaignmonitor.com/brand")] CampaignMonitor,
        [Description("Cash App, https://cash.app/press")] CashApp,
        [Description("Castorama, https://www.castorama.fr/")] Castorama,
        [Description("Castro, http://supertop.co/castro/press/")] Castro,
        [Description("Circle, https://www.circle.com/")] Circle,
        [Description("CircleCI, https://circleci.com/press")] CircleCi,
        [Description("Clockify, https://clockify.me/")] Clockify,
        [Description("Clojure, https://commons.wikimedia.org/wiki/File:Clojure_logo.svg")] Clojure,
        [Description("Cloudflare, https://www.cloudflare.com/logo/")] Cloudflare,
        [Description("Codecademy, https://www.codecademy.com/")] Codecademy,
        [Description("Codeforces, http://codeforces.com/")] Codeforces,
        [Description("CodeIgniter, https://www.codeigniter.com/help/legal")] CodeIgniter,
        [Description("CodePen, http://codepen.io")] CodePen,
        [Description("Coderwall, https://github.com/twolfson/coderwall-svg")] Coderwall,
        [Description("Codewars, https://www.codewars.com")] Codewars,
        [Description("Codio, https://codio.com")] Codio,
        [Description("CoffeeScript, https://coffeescript.org/")] CoffeeScript,
        [Description("ComproPago, https://compropago.com")] ComproPago,
        [Description("Conekta, https://www.conekta.io")] Conekta,
        [Description("Co-op, http://www.co-operative.coop/corporate/press/logos/")] CoOp,
        [Description("Coursera, https://about.coursera.org/press")] Coursera,
        [Description("CSS3, http://www.w3.org/html/logo/")] Css3,
        [Description("CSS Wizardry, http://csswizardry.com")] CssWizardry,
        [Description("D3.js, https://github.com/d3/d3-logo")] D3Js,
        [Description("Dailymotion, http://press.dailymotion.com/?page_id=346")] Dailymotion,
        [Description("Debian, https://www.debian.org/logos")] Debian,
        [Description("Deezer, http://www.deezer.com/company/press")] Deezer,
        [Description("Delicious, https://en.wikipedia.org/wiki/Delicious_(website)")] Delicious,
        [Description("Dell, https://datasecurity.dell.com/wp-content/themes/dell/images/logo-dell.svg")] Dell,
        [Description("Designer News, https://www.designernews.co")] DesignerNews,
        [Description("DeviantArt, http://help.deviantart.com/21")] DeviantArt,
        [Description("devRant, https://devrant.com")] DevRant,
        [Description("dev.to, https://dev.to/")] DevTo,
        [Description("Diaspora, https://wiki.diasporafoundation.org/Branding")] Diaspora,
        [Description("Digg, https://en.wikipedia.org/wiki/Digg")] Digg,
        [Description("DigitalOcean, https://www.digitalocean.com/company/logos-and-badges/")] DigitalOcean,
        [Description("Discord, https://discordapp.com/branding")] Discord,
        [Description("Discourse, https://www.discourse.org/")] Discourse,
        [Description("Discover, https://www.discovernetwork.com/en-us/business-resources/free-signage-logos")] Discover,
        [Description("Disqus, https://disqus.com/brand")] Disqus,
        [Description("Disroot, https://git.fosscommunity.in/disroot/assests/blob/master/d.svg")] Disroot,
        [Description("Django, https://www.djangoproject.com/community/logos/")] Django,
        [Description("Docker, https://www.docker.com")] Docker,
        [Description(".NET, https://docs.microsoft.com/en-us/dotnet/images/hub/net.svg")] DotNet,
        [Description("Draugiem.lv, https://www.frype.com/applications/dev/docs/logos/")] DraugiemLv,
        [Description("Dribbble, https://dribbble.com/branding")] Dribbble,
        [Description("Dropbox, https://www.dropbox.com/branding")] Dropbox,
        [Description("Drupal, https://www.drupal.org/drupalorg/style-guide/colors")] Drupal,
        [Description("DTube, https://about.d.tube/mediakit.html")] DTube,
        [Description("eBay, https://go.developer.ebay.com/logos")] EBay,
        [Description("Elastic, https://www.elastic.co/brand")] Elastic,
        [Description("Elastic Cloud, https://www.elastic.co/brand")] ElasticCloud,
        [Description("Elasticsearch, https://www.elastic.co/brand")] Elasticsearch,
        [Description("Elastic Stack, https://www.elastic.co/brand")] ElasticStack,
        [Description("Ello, https://ello.co")] Ello,
        [Description("Empire Kred, http://www.empire.kred")] EmpireKred,
        [Description("Envato, https://envato.com/")] Envato,
        [Description("ESLint, https://eslint.org/img/logo.svg")] EsLint,
        [Description("Ethereum, https://www.ethereum.org/images/logos/Ethereum_Visual_Identity_1.0.0.pdf")] Ethereum,
        [Description("Etsy, https://www.etsy.com/uk/press")] Etsy,
        [Description("Eventbrite, https://www.eventbrite.com")] Eventbrite,
        [Description("Event Store, https://github.com/eventstore/brand")] EventStore,
        [Description("Evernote, https://evernote.com/press")] Evernote,
        [Description("Everplaces, https://everplaces.com")] Everplaces,
        [Description("Facebook, https://www.facebookbrand.com")] Facebook,
        [Description("Fandango, https://www.fandango.com")] Fandango,
        [Description("FeatHub, http://feathub.com/")] FeatHub,
        [Description("Feedly, https://blog.feedly.com/wp-content/themes/feedly-2017-v1.19.3/assets/images/logos/logo.svg")] Feedly,
        [Description("Figma, https://figma.com/")] Figma,
        [Description("Firebase, https://firebase.google.com/brand-guidelines/")] Firebase,
        [Description("Fitbit, http://www.fitbit.com/uk/home")] Fitbit,
        [Description("Flickr, https://worldvectorlogo.com/logo/flickr-1")] Flickr,
        [Description("Flipboard, https://about.flipboard.com/brand-guidelines")] Flipboard,
        [Description("Fnac, http://www.fnac.com/")] Fnac,
        [Description("Foursquare, https://foursquare.com/about/logos")] Foursquare,
        [Description("Framer, https://framer.com")] Framer,
        [Description("freeCodeCamp, https://freecodecamp.com")] FreeCodeCamp,
        [Description("Fur Affinity, https://www.furaffinity.net/")] FurAffinity,
        [Description("Furry Network, https://furrynetwork.com")] FurryNetwork,
        [Description("Garmin, https://developer.garmin.com/resources/brand-guidelines/")] Garmin,
        [Description("Gatsby, https://www.gatsbyjs.org/")] Gatsby,
        [Description("Gauges, http://get.gaug.es/")] Gauges,
        [Description("Geocaching, https://www.geocaching.com/about/logousage.aspx")] Geocaching,
        [Description("Gerrit, https://gerrit-review.googlesource.com/c/75842/")] Gerrit,
        [Description("Ghost, https://ghost.org/design")] Ghost,
        [Description("Git, http://git-scm.com/downloads/logos")] Git,
        [Description("GitHub, https://github.com/logos")] GitHub,
        [Description("GitLab, https://about.gitlab.com/press/")] GitLab,
        [Description("Gitter, https://gitter.im/")] Gitter,
        [Description("Glassdoor, https://www.glassdoor.com/press/images/")] Glassdoor,
        [Description("Gmail, https://material.io/guidelines/resources/sticker-sheets-icons.html#sticker-sheets-icons-components")] Gmail,
        [Description("GNU, https://gnu.org")] Gnu,
        [Description("GNU social, https://www.gnu.org/graphics/social.html")] GnuSocial,
        [Description("Go, https://golang.org/doc/gopher/")] Go,
        [Description("GoldenLine, http://www.goldenline.pl")] GoldenLine,
        [Description("Goodreads, https://www.goodreads.com/about/press")] Goodreads,
        [Description("Google, https://developers.google.com/+/branding-guidelines?hl=en")] Google,
        [Description("Google Allo, https://allo.google.com/web")] GoogleAllo,
        [Description("Google Analytics, https://analytics.google.com")] GoogleAnalytics,
        [Description("Google Chrome, https://blog.google/press/?product_tag=chrome")] GoogleChrome,
        [Description("Google Drive, https://developers.google.com/drive/web/branding")] GoogleDrive,
        [Description("Google Hangouts, https://material.google.com/resources/sticker-sheets-icons.html#sticker-sheets-icons-components")] GoogleHangouts,
        [Description("Google Keep, https://play.google.com/store/apps/details?id=com.google.android.keep")] GoogleKeep,
        [Description("Google Play, https://getsello.com")] GooglePlay,
        [Description("Google+, https://developers.google.com/+/branding-guidelines")] GooglePlus,
        [Description("GOV.UK, https://github.com/alphagov/design-assets/tree/master/Icons")] GovUk,
        [Description("Graphcool, https://www.graph.cool")] Graphcool,
        [Description("GraphQL, http://graphql.org/")] GraphQl,
        [Description("Grav, http://getgrav.org/media")] Grav,
        [Description("Gravatar, https://automattic.com/press")] Gravatar,
        [Description("Groupon, https://brandplaybook.groupon.com/guidelines/logo/")] Groupon,
        [Description("Gulp, https://github.com/gulpjs/artwork/blob/master/gulp.svg")] Gulp,
        [Description("Gumroad, https://gumroad.com/press")] Gumroad,
        [Description("Gumtree, https://www.gumtree.com")] Gumtree,
        [Description("HackerRank, https://www.hackerrank.com/")] HackerRank,
        [Description("Hackster, https://drive.google.com/file/d/0B3aqzR8LzoqdT1p4ZUlWVnJ1elk/view?usp=sharing")] Hackster,
        [Description("Haskell, https://commons.wikimedia.org/wiki/File:Haskell-Logo.svg")] Haskell,
        [Description("Hatena Bookmark, http://hatenacorp.jp/press/resource")] HatenaBookmark,
        [Description("Heroku, https://www.heroku.com")] Heroku,
        [Description("Hexo, https://hexo.io/")] Hexo,
        [Description("Highly, https://highly.co/")] Highly,
        [Description("HipChat, https://www.atlassian.com/company/news/press-kit")] HipChat,
        [Description("HockeyApp, https://hockeyapp.net/brand-guidelines/")] HockeyApp,
        [Description("homify, http://lsg.homify.com/")] Homify,
        [Description("Hootsuite, https://hootsuite.com/en-gb/about/media-kit")] Hootsuite,
        [Description("Houzz, http://www.houzz.co.uk/buttonsAndBadges")] Houzz,
        [Description("HTML5, http://www.w3.org/html/logo/")] Html5,
        [Description("Hulu, https://www.hulu.com/press/brand-assets/")] Hulu,
        [Description("Humble Bundle, https://support.humblebundle.com/hc/en-us/articles/202742060-Bundle-Logos")] HumbleBundle,
        [Description("IconJar, https://geticonjar.com/press-kit/")] IconJar,
        [Description("ICQ, https://en.wikipedia.org/wiki/File:ICQ.svg")] Icq,
        [Description("iFixit, https://www.ifixit.com/")] IFixit,
        [Description("IMDb, http://www.imdb.com/pressroom/brand_guidelines")] ImDb,
        [Description("Inkscape, https://commons.wikimedia.org/wiki/File:Inkscape_Logo.svg")] Inkscape,
        [Description("Instacart, https://www.instacart.com/press")] Instacart,
        [Description("Instagram, https://www.instagram-brand.com")] Instagram,
        [Description("Instapaper, https://www.instapaper.com/")] Instapaper,
        [Description("Intel, https://www.intel.com")] Intel,
        [Description("Intercom, https://www.intercom.io")] Intercom,
        [Description("Internet Explorer, https://compass-ssl.microsoft.com/assets/c8/67/c867db4c-f328-45b8-817c-33834c70aae6.svg?n=IE.svg")] InternetExplorer,
        [Description("InVision, https://projects.invisionapp.com/boards/BX4P1DY5H46R")] InVision,
        [Description("Java, https://www.oracle.com/legal/logos.html")] Java,
        [Description("JavaScript, https://github.com/voodootikigod/logo.js")] JavaScript,
        [Description("Jekyll, https://github.com/jekyll/brand")] Jekyll,
        [Description("Jenkins, https://wiki.jenkins-ci.org/display/JENKINS/Logo")] Jenkins,
        [Description("Jira, https://www.atlassian.com/company/news/press-kit")] Jira,
        [Description("Joomla, https://docs.joomla.org/Joomla:Brand_Identity_Elements")] Joomla,
        [Description("jQuery, https://brand.jquery.org/logos/")] JQuery,
        [Description("JSFiddle, http://doc.jsfiddle.net/meta/downloads.html")] JsFiddle,
        [Description("JSON, https://commons.wikimedia.org/wiki/File:JSON_vector_logo.svg")] Json,
        [Description("JustGiving, https://justgiving.com")] JustGiving,
        [Description("Kaggle, https://www.kaggle.com/contact")] Kaggle,
        [Description("KaiOS, https://www.dropbox.com/sh/2qihtgrzllws8ki/AABmo9X1KMT6lHnvh4Em7dpWa?dl=0")] KaiOs,
        [Description("Keybase, https://github.com/keybase/client/tree/master/media/logos")] Keybase,
        [Description("KeyCDN, https://www.keycdn.com/logos")] KeyCdn,
        [Description("Khan Academy, https://khanacademy.zendesk.com/hc/en-us/articles/202483630-Press-room")] KhanAcademy,
        [Description("Kibana, https://www.elastic.co/brand")] Kibana,
        [Description("Kickstarter, https://www.kickstarter.com/help/brand_assets")] Kickstarter,
        [Description("Kik, http://www.kik.com/press")] Kik,
        [Description("Kirby, http://getkirby.com/assets/images/logo.svg")] Kirby,
        [Description("Klout, https://klout.com/s/developers/styleguide")] Klout,
        [Description("Known, https://withknown.com/img/logo_k.png")] Known,
        [Description("Koding, https://koding.com/About")] Koding,
        [Description("Ko-fi, https://ko-fi.com/home/about")] KoFi,
        [Description("Kotlin, https://resources.jetbrains.com/storage/products/kotlin/docs/kotlin_logos.zip")] Kotlin,
        [Description("Lanyrd, http://lanyrd.com/help/faq/#branding")] Lanyrd,
        [Description("Laravel, https://github.com/laravel/art")] Laravel,
        [Description("Last.fm, http://www.last.fm/about/resources")] LastFm,
        [Description("Launchpad, https://help.launchpad.net/logo/submissions")] Launchpad,
        [Description("LeetCode, https://leetcode.com")] LeetCode,
        [Description("Letterboxd, https://letterboxd.com/about/logos/")] Letterboxd,
        [Description("Line, http://line.me/en/logo")] Line,
        [Description("LINE WEBTOON, http://webtoons.com/")] LineWebtoon,
        [Description("LinkedIn, https://brand.linkedin.com")] LinkedIn,
        [Description("Linux, http://www.linuxfoundation.org/about/about-linux")] Linux,
        [Description("Linux Foundation, http://www.linuxfoundation.org/about/about-linux")] LinuxFoundation,
        [Description("LiveJournal, http://www.livejournal.com")] LiveJournal,
        [Description("Livestream, https://livestream.com/press")] Livestream,
        [Description("Logstash, https://www.elastic.co/brand")] Logstash,
        [Description("Lua, https://www.lua.org/docs.html")] Lua,
        [Description("Macy’s, http://www.macysinc.com/press-room/logo-photo-gallery/logos-macys-inc/default.aspx")] MacyS,
        [Description("Magento, http://magento.com")] Magento,
        [Description("MailChimp, http://mailchimp.com/about/brand-assets")] MailChimp,
        [Description("Mail.Ru, https://corp.mail.ru/en/press/identity/")] MailRu,
        [Description("MakerBot, http://www.makerbot.com/makerbot-press-assets")] MakerBot,
        [Description("MasterCard, https://brand.mastercard.com/brandcenter/mastercard-brand-mark/downloads.html")] MasterCard,
        [Description("Mastodon, https://source.joinmastodon.org/mastodon/joinmastodon/blob/master/public/press-kit.zip")] Mastodon,
        [Description("Matternet, http://mttr.net")] Matternet,
        [Description("MediaTemple, https://mediatemple.net/company/about-us")] MediaTemple,
        [Description("Medium, https://medium.design/logos-and-brand-guidelines-f1a01a733592")] Medium,
        [Description("Meetup, https://www.meetup.com/help/customer/portal/articles/1802998-promotional-materials-for-your-meetup/")] Meetup,
        [Description("Messenger, https://worldvectorlogo.com/logo/facebook-messenger")] Messenger,
        [Description("Meteor, http://logo.meteorapp.com/")] Meteor,
        [Description("Micro.blog, https://twitter.com/BradEllis/status/943956921886715904")] MicroBlog,
        [Description("Microgenetics, http://microgenetics.co.uk/")] Microgenetics,
        [Description("Microsoft, https://ratnacahayarina.files.wordpress.com/2014/03/microsoft.pdf")] Microsoft,
        [Description("Microsoft Access, https://www.office.com")] MicrosoftAccess,
        [Description("Microsoft Edge, https://compass-ssl.microsoft.com/assets/86/b5/86b52157-162f-4130-ab00-3db03397c46d.svg?n=edge.svg")] MicrosoftEdge,
        [Description("Microsoft Excel, https://www.office.com")] MicrosoftExcel,
        [Description("Microsoft OneDrive, https://msdn.microsoft.com/en-us/onedrive/dn673556.aspx")] MicrosoftOneDrive,
        [Description("Microsoft OneNote, https://www.office.com")] MicrosoftOneNote,
        [Description("Microsoft Outlook, https://www.office.com")] MicrosoftOutlook,
        [Description("Microsoft PowerPoint, https://www.office.com")] MicrosoftPowerPoint,
        [Description("Microsoft Word, https://www.office.com")] MicrosoftWord,
        [Description("Minutemailer, https://minutemailer.com/press")] Minutemailer,
        [Description("Mix, https://mix.com")] Mix,
        [Description("Mixcloud, https://www.mixcloud.com/branding")] Mixcloud,
        [Description("Mixer, https://github.com/mixer/branding-kit/")] Mixer,
        [Description("Monero, https://getmonero.org")] Monero,
        [Description("MongoDB, https://www.mongodb.com/pressroom")] MongoDb,
        [Description("Monkey tie, https://www.monkey-tie.com/presse")] MonkeyTie,
        [Description("Monogram, http://monogram.me")] Monogram,
        [Description("Moo, https://www.moo.com/uk/about/press.html")] Moo,
        [Description("Mozilla, https://mozilla.ninja/our-logo")] Mozilla,
        [Description("Mozilla Firefox, http://design.firefox.com/photon/visuals/product-identity-assets.html")] MozillaFirefox,
        [Description("Myspace, https://myspace.com/pressroom/assetslogos")] Myspace,
        [Description("MySQL, https://www.mysql.com/about/legal/logos.html")] MySql,
        [Description("Neo4j, https://neo4j.com/style-guide/")] Neo4j,
        [Description("Netflix, https://commons.wikimedia.org/wiki/File:Netflix_2014_logo.svg")] Netflix,
        [Description("Netlify, https://www.netlify.com/press/")] Netlify,
        [Description("Nextcloud, https://nextcloud.com/press/")] Nextcloud,
        [Description("Nextdoor, https://nextdoor.com/newsroom/")] Nextdoor,
        [Description("NGINX, https://www.nginx.com/")] Nginx,
        [Description("Nintendo, https://en.wikipedia.org/wiki/Nintendo#/media/File:Nintendo.svg")] Nintendo,
        [Description("Nintendo GameCube, https://www.nintendo.com/consumer/systems/nintendogamecube/index.jsp")] NintendoGameCube,
        [Description("Nintendo Switch, http://www.nintendo.co.uk/")] NintendoSwitch,
        [Description("Node.js, https://nodejs.org/en/about/resources/")] NodeJs,
        [Description("Nodemon, https://nodemon.io/")] Nodemon,
        [Description("NPM, https://github.com/npm/logos")] Npm,
        [Description("Nucleo, https://nucleoapp.com/wp-content/themes/nucleo-webapp-12/img/logo.svg")] Nucleo,
        [Description("NuGet, https://github.com/NuGet/Media")] NuGet,
        [Description("NVIDIA, https://www.nvidia.com/etc/designs/nvidiaGDC/clientlibs_base/images/NVIDIA-Logo.svg")] Nvidia,
        [Description("Oculus, https://www.oculus.com/en-us/press-kit")] Oculus,
        [Description("Odnoklassniki, http://v.ok.ru/logo.html")] Odnoklassniki,
        [Description("Opera, https://github.com/operasoftware/logo")] Opera,
        [Description("Origin, https://www.origin.com/gbr/en-us/store")] Origin,
        [Description("Overcast, https://overcast.fm")] Overcast,
        [Description("OVH, https://www.ovh.com/fr/news/logo-ovh.xml")] Ovh,
        [Description("Pagekit, https://pagekit.com/logo-guide")] Pagekit,
        [Description("Pandora, http://blog.pandora.com/us/the-color-of-music-unveiling-a-new-pandora-look-that-reflects-your-music-experience/")] Pandora,
        [Description("Patreon, https://www.patreon.com/brand/downloads")] Patreon,
        [Description("PayPal, https://www.paypal-marketing.com/html/partner/na/portal-v2/pdf/PP_Masterbrandguidelines_v21_mm.pdf")] PayPal,
        [Description("Periscope, https://www.periscope.tv/press")] Periscope,
        [Description("PHP, http://php.net/download-logos.php")] Php,
        [Description("Picarto.TV, https://picarto.tv/site/press")] PicartoTv,
        [Description("Pinboard, https://commons.wikimedia.org/wiki/File:Feedbin-Icon-share-pinboard.svg")] Pinboard,
        [Description("Pingdom, https://tools.pingdom.com")] Pingdom,
        [Description("Pingup, http://pingup.com/resources")] Pingup,
        [Description("Pinterest, https://business.pinterest.com/en/brand-guidelines")] Pinterest,
        [Description("PlanGrid, https://plangrid.com/en/")] PlanGrid,
        [Description("Player.me, https://player.me/p/about-us")] PlayerMe,
        [Description("PlayStation, http://uk.playstation.com/media/DPBjbK0o/CECH-4202_4203%20PS3_QSG_GB_Eastern_3_web_vf1.pdf")] PlayStation,
        [Description("PlayStation 3, https://commons.wikimedia.org/wiki/File:PlayStation_3_Logo_neu.svg#/media/File:PS3.svg")] PlayStation3,
        [Description("PlayStation 4, https://commons.wikimedia.org/wiki/File:PlayStation_4_logo_and_wordmark.svg")] PlayStation4,
        [Description("Plex, http://brand.plex.tv/d/qxmJ3odkK0fj/plex-style-guide")] Plex,
        [Description("Pluralsight, https://www.pluralsight.com/newsroom/brand-assets")] Pluralsight,
        [Description("Plurk, https://www.plurk.com/brandInfo")] Plurk,
        [Description("Pocket, https://getpocket.com/blog/press/")] Pocket,
        [Description("Podcasts, https://www.apple.com/itunes/marketing-on-podcasts/identity-guidelines.html#apple-podcasts-icon")] Podcasts,
        [Description("Prismic, https://prismic.io/")] Prismic,
        [Description("ProcessWire, https://github.com/processwire")] ProcessWire,
        [Description("Product Hunt, https://www.producthunt.com/branding")] ProductHunt,
        [Description("Proto.io, https://proto.io/en/presskit")] ProtoIo,
        [Description("ProtonMail, https://protonmail.com/media-kit")] ProtonMail,
        [Description("Python, https://www.python.org/community/logos/")] Python,
        [Description("Qiita, https://www.qiita.com")] Qiita,
        [Description("Qualcomm, https://www.qualcomm.com")] Qualcomm,
        [Description("Quantcast, http://branding.quantcast.com/logouse/")] Quantcast,
        [Description("Quantopian, https://www.quantopian.com")] Quantopian,
        [Description("Quora, https://www.quora.com")] Quora,
        [Description("Qzone, https://qzone.qq.com/")] Qzone,
        [Description("Rails, http://rubyonrails.org/images/rails-logo.svg")] Rails,
        [Description("Raspberry Pi, https://www.raspberrypi.org/trademark-rules")] RaspberryPi,
        [Description("React, https://facebook.github.io/react/")] React,
        [Description("Read the Docs, https://github.com/rtfd/readthedocs.org/blob/master/media/readthedocsbranding.ai")] ReadTheDocs,
        [Description("Redbubble, https://www.redbubble.com/explore/client/4196122a442ab3f429ec802f71717465.svg")] Redbubble,
        [Description("Reddit, https://worldvectorlogo.com/logo/reddit-2")] Reddit,
        [Description("Redis, https://redis.io/images/redis-logo.svg")] Redis,
        [Description("Redux, https://github.com/reactjs/redux/tree/master/logo")] Redux,
        [Description("Renren, https://seeklogo.com/vector-logo/184137/renren-inc")] Renren,
        [Description("ReverbNation, https://www.reverbnation.com")] ReverbNation,
        [Description("Riseup, https://riseup.net/en/about-us/images")] Riseup,
        [Description("rollup.js, https://rollupjs.org/")] RollupJs,
        [Description("Roots, https://roots.io/")] Roots,
        [Description("RSS, https://en.wikipedia.org/wiki/Feed_icon")] Rss,
        [Description("Ruby, https://www.ruby-lang.org/en/about/logo/")] Ruby,
        [Description("Runkeeper, https://runkeeper.com/partnerships")] Runkeeper,
        [Description("Rust, https://www.rust-lang.org/")] Rust,
        [Description("Safari, https://images.techhive.com/images/article/2014/11/safari-favorites-100530680-large.jpg")] Safari,
        [Description("Salesforce, https://www.salesforce.com/")] Salesforce,
        [Description("Samsung, https://www.samsung.com/us")] Samsung,
        [Description("Samsung Pay, https://pay.samsung.com/developers/resource/brand")] SamsungPay,
        [Description("SAP, https://support.sap.com/content/dam/support/sap-logo.svg")] Sap,
        [Description("Sass, http://sass-lang.com/styleguide/brand")] Sass,
        [Description("Sauce Labs, https://saucelabs.com/")] SauceLabs,
        [Description("Scala, https://www.scala-lang.org/")] Scala,
        [Description("Scribd, https://www.scribd.com")] Scribd,
        [Description("Sega, https://en.wikipedia.org/wiki/Sega#/media/File:Sega_logo.svg")] Sega,
        [Description("Sellfy, https://sellfy.com/about/")] Sellfy,
        [Description("Sentry, https://sentry.io/branding/")] Sentry,
        [Description("Server Fault, http://stackoverflow.com/company/logos")] ServerFault,
        [Description("Shazam, https://brandfolder.com/shazam")] Shazam,
        [Description("Shopify, https://press.shopify.com/brand")] Shopify,
        [Description("Signal, https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms")] Signal,
        [Description("Simple Icons, https://simpleicons.org/")] SimpleIcons,
        [Description("Sina Weibo, https://en.wikipedia.org/wiki/Sina_Weibo")] SinaWeibo,
        [Description("SitePoint, http://www.sitepoint.com")] SitePoint,
        [Description("Skyliner, https://www.skyliner.io/help")] Skyliner,
        [Description("Skype, http://blogs.skype.com/?attachment_id=56273")] Skype,
        [Description("Slack, https://slack.com/brand-guidelines")] Slack,
        [Description("Slashdot, https://commons.wikimedia.org/wiki/File:Slashdot_wordmark_and_logo.svg")] Slashdot,
        [Description("SlickPic, https://www.slickpic.com/")] SlickPic,
        [Description("Slides, https://slides.com/about")] Slides,
        [Description("Smashing Magazine, https://www.smashingmagazine.com/")] SmashingMagazine,
        [Description("Snapchat, https://www.snapchat.com/brand-guidelines")] Snapchat,
        [Description("Sogou, https://www.sogou.com/")] Sogou,
        [Description("Songkick, http://blog.songkick.com/media-assets")] Songkick,
        [Description("SoundCloud, https://soundcloud.com/press")] SoundCloud,
        [Description("SourceForge, https://sourceforge.net/")] SourceForge,
        [Description("SparkPost, https://www.sparkpost.com/")] SparkPost,
        [Description("Speaker Deck, https://speakerdeck.com/")] SpeakerDeck,
        [Description("Spotify, https://developer.spotify.com/design")] Spotify,
        [Description("Spotlight, https://www.spotlight.com/")] Spotlight,
        [Description("Spreaker, http://www.spreaker.com/press")] Spreaker,
        [Description("Sprint, https://www.sprint.com/")] Sprint,
        [Description("Squarespace, http://squarespace.com/brand-guidelines")] Squarespace,
        [Description("Stack Exchange, http://stackoverflow.com/company/logos")] StackExchange,
        [Description("Stack Overflow, http://stackoverflow.com")] StackOverflow,
        [Description("Statamic, http://statamic.com/press")] Statamic,
        [Description("Staticman, https://staticman.net/")] Staticman,
        [Description("Steam, https://partner.steamgames.com/public/marketing/Steam_Guidelines_02102016.pdf")] Steam,
        [Description("Steem, https://steem.io/")] Steem,
        [Description("Stitcher, https://www.stitcher.com/")] Stitcher,
        [Description("Storify, https://storify.com")] Storify,
        [Description("Strava, https://itunes.apple.com/us/app/strava-running-and-cycling-gps/id426826309")] Strava,
        [Description("Stripe, https://stripe.com/about/resources")] Stripe,
        [Description("StubHub, http://www.stubhub.com")] StubHub,
        [Description("StyleShare, https://www.stylesha.re/")] StyleShare,
        [Description("Stylus, http://stylus-lang.com/img/stylus-logo.svg")] Stylus,
        [Description("Sublime Text, https://en.wikipedia.org/wiki/File:Sublime_Text_Logo.png")] SublimeText,
        [Description("Subversion, http://subversion.apache.org/logo")] Subversion,
        [Description("Super User, http://stackoverflow.com/company/logos")] SuperUser,
        [Description("Swarm, https://foursquare.com/about/logos")] Swarm,
        [Description("Swift, https://developer.apple.com/develop/")] Swift,
        [Description("Symfony, https://symfony.com/logo")] Symfony,
        [Description("Tails, https://tails.boum.org/contribute/how/promote/material/logo/")] Tails,
        [Description("Tapas, https://tapas.io/site/about#media")] Tapas,
        [Description("TED, https://www.ted.com/participate/organize-a-local-tedx-event/tedx-organizer-guide/branding-promotions/logo-and-design/your-tedx-logo")] Ted,
        [Description("Teespring, https://teespring.com")] Teespring,
        [Description("Telegram, https://commons.wikimedia.org/wiki/File:Telegram_alternative_logo.svg")] Telegram,
        [Description("Tencent QQ, http://im.qq.com/")] TencentQq,
        [Description("Tesla, http://www.teslamotors.com/en_GB/about")] Tesla,
        [Description("The Mighty, https://themighty.com/")] TheMighty,
        [Description("The Movie Database, https://www.themoviedb.org/about/logos-attribution")] TheMovieDatabase,
        [Description("Tinder, http://www.gotinder.com/press")] Tinder,
        [Description("T-Mobile, https://www.t-mobile.com/news/media-library?fulltext=logo")] TMobile,
        [Description("Toggl, https://toggl.com/media-toolkit")] Toggl,
        [Description("Topcoder, http://topcoder.com/")] Topcoder,
        [Description("Toptal, https://www.toptal.com/branding")] Toptal,
        [Description("Trakt, https://trakt.tv")] Trakt,
        [Description("Travis CI, https://travis-ci.org")] TravisCi,
        [Description("Treehouse, https://teamtreehouse.com/about")] Treehouse,
        [Description("Trello, https://trello.com/about/branding")] Trello,
        [Description("TripAdvisor, https://tripadvisor.mediaroom.com/download/TripAdvisor_Logo_Guidelines_5_15_17.pdf")] TripAdvisor,
        [Description("Trulia, http://www.trulia.com")] Trulia,
        [Description("Tumblr, https://www.tumblr.com/logo")] Tumblr,
        [Description("Twilio, https://www.twilio.com/company/brand")] Twilio,
        [Description("Twitch, http://www.twitch.tv/p/brand-assets")] Twitch,
        [Description("Twitter, https://brand.twitter.com")] Twitter,
        [Description("Twoo, http://www.twoo.com/about/press")] Twoo,
        [Description("TYPO3, https://typo3.com/fileadmin/assets/typo3logos/typo3_bullet_01.svg")] Typo3,
        [Description("Uber, https://www.uber.com/media/")] Uber,
        [Description("Ubuntu, https://design.ubuntu.com/brand/ubuntu-logo/")] Ubuntu,
        [Description("Udacity, https://www.udacity.com")] Udacity,
        [Description("UIkit, https://getuikit.com")] UIkit,
        [Description("Umbraco, https://umbraco.com/")] Umbraco,
        [Description("Unsplash, https://unsplash.com/")] Unsplash,
        [Description("Untappd, https://untappd.com/")] Untappd,
        [Description("Upwork, https://www.upwork.com/press/")] Upwork,
        [Description("Vagrant, https://www.hashicorp.com/brand#vagrant")] Vagrant,
        [Description("Venmo, https://venmo.com/about/brand/")] Venmo,
        [Description("Verizon, https://www.verizondigitalmedia.com/about/logo-usage/")] Verizon,
        [Description("Viadeo, http://corporate.viadeo.com/en/media/resources")] Viadeo,
        [Description("Viber, https://www.viber.com/brand-center/")] Viber,
        [Description("Vim, https://commons.wikimedia.org/wiki/File:Vimlogo.svg")] Vim,
        [Description("Vimeo, https://vimeo.com/about/brand_guidelines")] Vimeo,
        [Description("Vine, https://vine.co/logo")] Vine,
        [Description("Virb, http://virb.com/about")] Virb,
        [Description("Visa, https://commons.wikimedia.org/wiki/File:Visa_2014_logo_detail.svg")] Visa,
        [Description("Visual Studio Code, https://code.visualstudio.com")] VisualStudioCode,
        [Description("VK, https://vk.com/about")] Vk,
        [Description("VSCO, https://vsco.co/about/press/vsco-releases-redesigned-mobile-app")] Vsco,
        [Description("Vue.js, https://github.com/vuejs/art")] VueJs,
        [Description("Wattpad, https://www.wattpad.com/press/#assets")] Wattpad,
        [Description("Weasyl, https://www.weasyl.com/")] Weasyl,
        [Description("Webpack, https://webpack.js.org/branding/")] Webpack,
        [Description("WebStorm, https://www.jetbrains.com/company/brand/#section=images-logos")] WebStorm,
        [Description("WeChat, https://worldvectorlogo.com/logo/wechat-3")] WeChat,
        [Description("WhatsApp, https://www.whatsappbrand.com")] WhatsApp,
        [Description("When I Work, https://wheniwork.com/")] WhenIWork,
        [Description("Wii, https://de.wikipedia.org/wiki/Datei:WiiU.svg")] Wii,
        [Description("Wii U, https://de.wikipedia.org/wiki/Datei:WiiU.svg")] WiiU,
        [Description("Wikipedia, https://en.wikipedia.org/wiki/Logo_of_Wikipedia")] Wikipedia,
        [Description("Windows, https://commons.wikimedia.org/wiki/File:Windows_10_Logo.svg")] Windows,
        [Description("Wire, http://brand.wire.com")] Wire,
        [Description("Wix, http://www.wix.com/about/design-assets")] Wix,
        [Description("Wolfram, http://company.wolfram.com/press-center/wolfram-corporate/")] Wolfram,
        [Description("Wolfram Language, http://company.wolfram.com/press-center/language/")] WolframLanguage,
        [Description("Wolfram Mathematica, http://company.wolfram.com/press-center/mathematica/")] WolframMathematica,
        [Description("WordPress, https://wordpress.org/about/logos")] WordPress,
        [Description("WP Engine, https://wpengine.com/")] WpEngine,
        [Description("Xbox, http://mspartner-public.sharepoint.com/XBOX%20Games/Xbox%20logo's%20+%20Guidelines/Xbox%20Live/Xbox_Live_Guidelines_10-4-13.pdf")] Xbox,
        [Description("Xcode, https://developer.apple.com/develop/")] Xcode,
        [Description("Xero, https://www.xero.com/uk/about/media/downloads")] Xero,
        [Description("Xing, https://dev.xing.com/logo_rules")] Xing,
        [Description("X-Pack, https://www.elastic.co/brand")] XPack,
        [Description("XSplit, https://www.xsplit.com/presskit")] XSplit,
        [Description("Yahoo!, https://en.wikipedia.org/wiki/Yahoo!")] Yahoo,
        [Description("Yammer, https://developer.yammer.com/docs/branding-guide")] Yammer,
        [Description("Yandex, https://yandex.com/company/general_info/logotype_rules")] Yandex,
        [Description("Y Combinator, https://www.ycombinator.com/press/")] YCombinator,
        [Description("Yelp, http://www.yelp.com/brand")] Yelp,
        [Description("YouTube, https://www.youtube.com/yt/about/brand-resources/#logos-icons-colors")] YouTube,
        [Description("Zapier, https://zapier.com/about/brand")] Zapier,
        [Description("Zendesk, https://www.zendesk.com/company/brand-assets/#logo")] Zendesk,
        [Description("Zerply, https://zerply.com/about/resources")] Zerply,
        [Description("Zillow, http://zillow.mediaroom.com/logos")] Zillow,
    }
}