namespace MahApps.Metro.IconPacks
{
#if !(NETFX_CORE || WINDOWS_UWP)
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconVaadinIcons" />.
    /// </summary>
    /// <remarks>
    /// Vaadin Icons are licensed under the [Apache License 2.0](<see><cref>https://github.com/vaadin/vaadin-icons/blob/master/LICENSE</cref></see>).
    /// Contributions, corrections and requests can be made on GitHub <see><cref>https://github.com/vaadin/vaadin-icons</cref></see>.
    /// </remarks>
    public enum PackIconVaadinIconsKind
    {
        [Description("Empty placeholder")] None,
        [Description("abacus (e682, Ledger, Item, calc, calculator, math)")] Abacus,
        [Description("absolute-position (e61e, Web application, css, layout)")] AbsolutePosition,
        [Description("academy-cap (e902, Education, degree, college, school)")] AcademyCap,
        [Description("accessibility (e683, Sign, wheelchair, healthcare)")] Accessibility,
        [Description("accordion-menu (e61f, Web application, layout, html, component, navigation)")] AccordionMenu,
        [Description("add-dock (e620, Web application, layout, navigation)")] AddDock,
        [Description("adjust (e74a, Web application, Edit, contrast, brightness, settings)")] Adjust,
        [Description("adobe-flash (e648, Brand)")] AdobeFlash,
        [Description("airplane (e684, Transportation, plane, travel, vacation, fly, flight)")] Airplane,
        [Description("alarm (e903, Scheduling, Item, clock, woke up, wake up, time)")] Alarm,
        [Description("align-center (e74b, Text editor, paragraph, column)")] AlignCenter,
        [Description("align-justify (e7ae, Text editor, paragraph, column)")] AlignJustify,
        [Description("align-left (e74c, Text editor, paragraph, column)")] AlignLeft,
        [Description("align-right (e74d, Text editor, paragraph, column)")] AlignRight,
        [Description("alt (e905, Keyboard, key, option, shortcut, type)")] Alt,
        [Description("alt-a (e904, Keyboard, key, option, shortcut, type)")] AltA,
        [Description("ambulance (e906, Medical, Transportation, emergency, rescue, vehicle, patient)")] Ambulance,
        [Description("anchor (e685, Web application, hold, link)")] Anchor,
        [Description("angle-double-down (e6e6, Directions, chevron-down)")] AngleDoubleDown,
        [Description("angle-double-left (e6e7, Directions, previous, chevron-left)")] AngleDoubleLeft,
        [Description("angle-double-right (e6e8, Directions, next, chevron-right)")] AngleDoubleRight,
        [Description("angle-double-up (e6e9, Directions, chevron-up)")] AngleDoubleUp,
        [Description("angle-down (e6ea, Directions, chevron-down, caret-down)")] AngleDown,
        [Description("angle-left (e6eb, Directions, previous, chevron-left, caret-left)")] AngleLeft,
        [Description("angle-right (e6ec, Directions, next, chevron-right, caret-right)")] AngleRight,
        [Description("angle-up (e6ed, Directions, chevron-up, caret-up)")] AngleUp,
        [Description("archive (e6ee, Office, box, document, documents, documentation, file, files, filing)")] Archive,
        [Description("archives (e621, Office, document, documents, documentation, file, files, filing, drawers)")] Archives,
        [Description("area-select (e806, Web application, Edit, html, pointer)")] AreaSelect,
        [Description("arrow-backward (e622, Directions, reply, back, previous, left)")] ArrowBackward,
        [Description("arrow-circle-down (e6f0, Directions)")] ArrowCircleDown,
        [Description("arrow-circle-down-o (e6ef, Directions)")] ArrowCircleDownOutline,
        [Description("arrow-circle-left (e6f2, Directions, previous)")] ArrowCircleLeft,
        [Description("arrow-circle-left-o (e6f1, Directions, previous)")] ArrowCircleLeftOutline,
        [Description("arrow-circle-right (e6f4, Directions, next)")] ArrowCircleRight,
        [Description("arrow-circle-right-o (e6f3, Directions, next)")] ArrowCircleRightOutline,
        [Description("arrow-circle-up (e6f6, Directions)")] ArrowCircleUp,
        [Description("arrow-circle-up-o (e6f5, Directions)")] ArrowCircleUpOutline,
        [Description("arrow-down (e7af, Directions)")] ArrowDown,
        [Description("arrow-forward (e623, Directions, send, next, right)")] ArrowForward,
        [Description("arrow-left (e7b0, Directions, previous)")] ArrowLeft,
        [Description("arrow-long-down (e74e, Directions)")] ArrowLongDown,
        [Description("arrow-long-left (e74f, Directions, previous)")] ArrowLongLeft,
        [Description("arrow-right (e7b1, Directions, next)")] ArrowRight,
        [Description("arrows (e755, Directions, move)")] Arrows,
        [Description("arrows-cross (e750, Directions, expand)")] ArrowsCross,
        [Description("arrows-long-h (e751, Directions, scroll, horizontal)")] ArrowsLongH,
        [Description("arrows-long-right (e752, Directions, next)")] ArrowsLongRight,
        [Description("arrows-long-up (e753, Directions)")] ArrowsLongUp,
        [Description("arrows-long-v (e754, Directions, scroll, vertical)")] ArrowsLongV,
        [Description("arrow-up (e7b2, Directions)")] ArrowUp,
        [Description("asterisk (e686, Medical, healthcare, star)")] Asterisk,
        [Description("at (e624, Web application, email)")] At,
        [Description("automation (e687, Web application, machine, process)")] Automation,
        [Description("backspace (e908, Keyboard, key, delete, back, shortcut, type)")] Backspace,
        [Description("backspace-a (e907, Keyboard, key, delete, back, shortcut, type)")] BackspaceA,
        [Description("backwards (e756, Media, Player, rewind)")] Backwards,
        [Description("ban (e6f7, Notification, Sign, forbid, refuse, reject, no)")] Ban,
        [Description("bar-chart (e757, Charts, graph, diagram, column-chart)")] BarChart,
        [Description("bar-chart-h (e909, Charts, graph, diagram, column-chart, horizontal)")] BarChartH,
        [Description("bar-chart-v (e90a, Charts, graph, diagram, column-chart, vertical)")] BarChartV,
        [Description("barcode (e688, Media, ean, code)")] Barcode,
        [Description("bed (e90b, Item, sleep, pillow)")] Bed,
        [Description("bell (e7b4, Notification, Item, alert, reminder, ring)")] Bell,
        [Description("bell-o (e758, Notification, Item, alert, reminder, ring)")] BellOutline,
        [Description("bell-slash (e626, Notification, Item, alert, reminder, ring, mute, do not disturb, off, disable)")] BellSlash,
        [Description("bell-slash-o (e625, Notification, Item, alert, reminder, ring, mute, do not disturb, off, disable)")] BellSlashOutline,
        [Description("boat (e627, Transportation, travel, ship, cruising, sailing)")] Boat,
        [Description("bold (e6f8, Text editor, font, character, text-decoration)")] Bold,
        [Description("bolt (e759, Sign, lightning, electricity)")] Bolt,
        [Description("bomb (e689, Item, explosive)")] Bomb,
        [Description("book (e6f9, Media, Item, cover)")] Book,
        [Description("book-dollar (e600, Ledger, Item, accounting, bookkeeping)")] BookDollar,
        [Description("bookmark (e7b6, Sign)")] Bookmark,
        [Description("bookmark-o (e7b5, Sign)")] BookmarkOutline,
        [Description("book-percent (e601, Ledger, Item, accounting, bookkeeping)")] BookPercent,
        [Description("briefcase (e602, Item, suitcase, work)")] Briefcase,
        [Description("browser (e628, Web application, layout, html, internet, web page, site)")] Browser,
        [Description("bug (e68b, Web application, insect)")] Bug,
        [Description("bug-o (e68a, Web application, insect)")] BugOutline,
        [Description("building (e7b8, Location, structure, headquarters, office)")] Building,
        [Description("building-o (e7b7, Location, structure, headquarters, office)")] BuildingOutline,
        [Description("bullets (e629, Text editor, list, order)")] Bullets,
        [Description("bullseye (e6fa, Sign, target, hit, rings)")] Bullseye,
        [Description("buss (e90c, Transportation, vehicle, car, charter, coach)")] Buss,
        [Description("button (e62a, Web application, layout, html, component, navigation)")] Button,
        [Description("calc (e68c, Ledger, calculator, math)")] Calc,
        [Description("calc-book (e62b, Ledger, accounting, bookkeeping, calculator)")] CalcBook,
        [Description("calendar (e7ba, Scheduling, Office, appointment, meeting, time)")] Calendar,
        [Description("calendar-briefcase (e604, Scheduling, Office, suitcase, appointment, meeting, time, work)")] CalendarBriefcase,
        [Description("calendar-clock (e605, Scheduling, Office, appointment, meeting, time)")] CalendarClock,
        [Description("calendar-envelope (e62c, Scheduling, Office, letter, mail, appointment, meeting, time, work)")] CalendarEnvelope,
        [Description("calendar-o (e7b9, Scheduling, Office, appointment, meeting, time)")] CalendarOutline,
        [Description("calendar-user (e606, Scheduling, Office, appointment, meeting, time)")] CalendarUser,
        [Description("camera (e7bb, Devices, Item, photo, photography , shoot)")] Camera,
        [Description("car (e62d, Transportation, vehicle, auto, travel, drive, driving)")] Car,
        [Description("caret-down (e7bc, Directions, triangle)")] CaretDown,
        [Description("caret-left (e7bd, Directions, triangle, previous)")] CaretLeft,
        [Description("caret-right (e7be, Directions, triangle, play, start, next)")] CaretRight,
        [Description("caret-square-down-o (e7bf, Directions, triangle)")] CaretSquareDownOutline,
        [Description("caret-square-left-o (e7c0, Directions, triangle, previous)")] CaretSquareLeftOutline,
        [Description("caret-square-right-o (e7c1, Directions, triangle, play, start, next)")] CaretSquareRightOutline,
        [Description("caret-square-up-o (e7c2, Directions, triangle)")] CaretSquareUpOutline,
        [Description("caret-up (e7c3, Directions, triangle)")] CaretUp,
        [Description("cart (e6fc, Shopping, shopping, buy)")] Cart,
        [Description("cart-o (e6fb, Shopping, shopping, buy)")] CartOutline,
        [Description("cash (e901, Shopping, Ledger, dollar, money, bills, currency)")] Cash,
        [Description("chart (e68e, Charts, graph, diagram)")] Chart,
        [Description("chart-3d (e90d, Charts, graph, diagram, column-chart)")] Chart3d,
        [Description("chart-grid (e90e, Charts, graph, diagram, table)")] ChartGrid,
        [Description("chart-line (e68d, Charts, graph, diagram)")] ChartLine,
        [Description("chart-timeline (e90f, Charts, graph, diagram, column-chart, linear)")] ChartTimeline,
        [Description("chat (e75a, Social, dialog, talk)")] Chat,
        [Description("check (e75b, Form, confirm, assign, agreed, ok)")] Check,
        [Description("check-circle (e7c5, Form, confirm, assign, agreed, ok)")] CheckCircle,
        [Description("check-circle-o (e7c4, Form, confirm, assign, agreed, ok)")] CheckCircleOutline,
        [Description("check-square (e62e, Form, confirm, assign, agreed, ok)")] CheckSquare,
        [Description("check-square-o (e6fd, Form, confirm, assign, agreed, ok)")] CheckSquareOutline,
        [Description("chevron-circle-down (e7c7, Directions)")] ChevronCircleDown,
        [Description("chevron-circle-down-o (e7c6, Directions)")] ChevronCircleDownOutline,
        [Description("chevron-circle-left (e7c9, Directions, previous)")] ChevronCircleLeft,
        [Description("chevron-circle-left-o (e7c8, Directions, previous)")] ChevronCircleLeftOutline,
        [Description("chevron-circle-right (e7cb, Directions, next)")] ChevronCircleRight,
        [Description("chevron-circle-right-o (e7ca, Directions, next)")] ChevronCircleRightOutline,
        [Description("chevron-circle-up (e7cd, Directions)")] ChevronCircleUp,
        [Description("chevron-circle-up-o (e7cc, Directions)")] ChevronCircleUpOutline,
        [Description("chevron-down (e7ce, Directions, caret)")] ChevronDown,
        [Description("chevron-down-small (e965, Directions, caret)")] ChevronDownSmall,
        [Description("chevron-left (e7cf, Directions, previous, caret)")] ChevronLeft,
        [Description("chevron-left-small (e966, Directions, caret, previous)")] ChevronLeftSmall,
        [Description("chevron-right (e7d0, Directions, next, caret)")] ChevronRight,
        [Description("chevron-right-small (e967, Directions, caret, next)")] ChevronRightSmall,
        [Description("chevron-up (e7d1, Directions, caret)")] ChevronUp,
        [Description("chevron-up-small (e968, Directions, caret)")] ChevronUpSmall,
        [Description("child (e62f, People, kid, hobbit)")] Child,
        [Description("circle (e75d, Shape, ball, disc)")] Circle,
        [Description("circle-thin (e75c, Shape, Form, ball, disc)")] CircleThin,
        [Description("clipboard (e635, Office, document, file, copy)")] Clipboard,
        [Description("clipboard-check (e910, Office, document, file, confirm, assign, agreed, ok)")] ClipboardCheck,
        [Description("clipboard-cross (e630, Office, Medical, healtcare, patient)")] ClipboardCross,
        [Description("clipboard-heart (e631, Office, Medical, healtcare, patient)")] ClipboardHeart,
        [Description("clipboard-pulse (e632, Office, Medical, healtcare, patient, status)")] ClipboardPulse,
        [Description("clipboard-text (e633, Office, document, file)")] ClipboardText,
        [Description("clipboard-user (e634, Office, People, document, file, profile)")] ClipboardUser,
        [Description("clock (e7d2, Scheduling, Item, appointment, meeting, time)")] Clock,
        [Description("close (e7ad, Web application, delete, remove, x)")] Close,
        [Description("close-big (e916, Web application, closed, disabled)")] CloseBig,
        [Description("close-circle (e811, Web application, x, delete, remove)")] CloseCircle,
        [Description("close-circle-o (e810, Web application, x, delete, remove)")] CloseCircleOutline,
        [Description("close-small (e911, Web application, Form, delete, remove, x)")] CloseSmall,
        [Description("cloud (e763, Web application, Weather)")] Cloud,
        [Description("cloud-download (e75f, Web application)")] CloudDownload,
        [Description("cloud-download-o (e75e, Web application)")] CloudDownloadOutline,
        [Description("cloud-o (e760, Web application, Weather)")] CloudOutline,
        [Description("cloud-upload (e762, Web application)")] CloudUpload,
        [Description("cloud-upload-o (e761, Web application)")] CloudUploadOutline,
        [Description("cluster (e912, Social, Item, share, network, web, structure)")] Cluster,
        [Description("code (e68f, Web application, Edit, html, system, tags)")] Code,
        [Description("coffee (e690, Food, Web application, java, cup)")] Coffee,
        [Description("cog (e7d3, Web application, Edit, settings, gear)")] Cog,
        [Description("cog-o (e764, Web application, Edit, settings, gear)")] CogOutline,
        [Description("cogs (e691, Web application, Edit, settings, gears)")] Cogs,
        [Description("coin-piles (e913, Ledger, Shopping, money, currency, dollar, bills, cash)")] CoinPiles,
        [Description("coins (e914, Ledger, Shopping, money, currency, dollar, bills, cash)")] Coins,
        [Description("combobox (e636, Web application, layout, html, component, navigation, dropdown)")] Combobox,
        [Description("comment (e768, Social, speech bubble, chat, dialog, talk)")] Comment,
        [Description("comment-ellipsis (e766, Social, chat, dialog, talk)")] CommentEllipsis,
        [Description("comment-ellipsis-o (e765, Social, chat, dialog, talk)")] CommentEllipsisOutline,
        [Description("comment-o (e767, Social, speech bubble, chat, dialog, talk)")] CommentOutline,
        [Description("comments (e76a, Social, chat, dialog, talk)")] Comments,
        [Description("comments-o (e769, Social, chat, dialog, talk)")] CommentsOutline,
        [Description("compile (e915, Web application, Media, compress, compose)")] Compile,
        [Description("compress (e76b, Web application, minimize)")] Compress,
        [Description("compress-square (e637, Web application, minimize, fit)")] CompressSquare,
        [Description("connect (e76d, Social, share, network)")] Connect,
        [Description("connect-o (e76c, Social, share, network)")] ConnectOutline,
        [Description("controller (e692, Edit, settings, adjust, dial)")] Controller,
        [Description("copy (e7d5, Web application, duplicate, documents, files)")] Copy,
        [Description("copy-o (e7d4, Web application, duplicate, documents, files)")] CopyOutline,
        [Description("copyright (e638, Sign)")] Copyright,
        [Description("corner-lower-left (e693, Shape, triangle)")] CornerLowerLeft,
        [Description("corner-lower-right (e694, Shape, triangle)")] CornerLowerRight,
        [Description("corner-upper-left (e695, Shape, triangle)")] CornerUpperLeft,
        [Description("corner-upper-right (e696, Shape, triangle)")] CornerUpperRight,
        [Description("credit-card (e76e, Shopping, Item, payment)")] CreditCard,
        [Description("crop (e76f, Edit, resize)")] Crop,
        [Description("cross-cutlery (e6fe, Food, fork, knife, food, eat)")] CrossCutlery,
        [Description("crosshairs (e7d6, Edit, scope, target)")] Crosshairs,
        [Description("css (e639, Web application, html)")] Css,
        [Description("ctrl (e918, Keyboard, key, shortcut, type, control)")] Ctrl,
        [Description("ctrl-a (e917, Keyboard, key, shortcut, type, control)")] CtrlA,
        [Description("cube (e697, Item, box, package)")] Cube,
        [Description("cubes (e698, Item, boxes, packages)")] Cubes,
        [Description("curly-brackets (e63a, Web application, css, code, braces)")] CurlyBrackets,
        [Description("cursor (e91a, Web application, pointer, click, mouse)")] Cursor,
        [Description("cursor-o (e919, Web application, pointer, click, mouse)")] CursorOutline,
        [Description("cutlery (e6ff, Food, fork, knife, eat, food)")] Cutlery,
        [Description("dashboard (e700, Web application, speed meter, measure, fast, dial)")] Dashboard,
        [Description("database (e737, Devices, Media, server, storage, hdd, hard disk)")] Database,
        [Description("date-input (e63b, Scheduling, layout, html, component)")] DateInput,
        [Description("deindent (e770, Text editor, paragraph, column, unindent, outdent)")] Deindent,
        [Description("del (e91c, Keyboard, key, shortcut, type, delete, remove)")] Del,
        [Description("del-a (e91b, Keyboard, key, shortcut, type, delete, remove)")] DelA,
        [Description("dental-chair (e607, Medical, dentist, healthcare)")] DentalChair,
        [Description("desktop (e7d7, Devices, Media, Item, computer, imac, screen, monitor)")] Desktop,
        [Description("diamond (e91e, Item, luxury, gem, ruby, jewelry)")] Diamond,
        [Description("diamond-o (e91d, Item, luxury, gem, ruby, jewelry)")] DiamondOutline,
        [Description("diploma (e964, Education, degree, school, certificate)")] Diploma,
        [Description("diploma-scroll (e969, Education, degree, school, certificate)")] DiplomaScroll,
        [Description("disc (e701, Media, Item, cd, blue-ray, dvd)")] Disc,
        [Description("doctor (e609, Medical, People, stethoscope, healthcare)")] Doctor,
        [Description("doctor-briefcase (e608, Medical, Tools, Item, suitcase, healthcare)")] DoctorBriefcase,
        [Description("dollar (e60a, Ledger, Shopping, money, currency)")] Dollar,
        [Description("dot-circle (e702, Form, radio button)")] DotCircle,
        [Description("download (e703, Web application, save)")] Download,
        [Description("download-alt (e699, Web application, save)")] DownloadAlt,
        [Description("drop (e704, Shape, Edit, Weather, blur, water, rain, liquid)")] Drop,
        [Description("edit (e771, Form, Edit, note, write, pen)")] Edit,
        [Description("eject (e772, Media, Player)")] Eject,
        [Description("elastic (e63c, Item, rubber-band)")] Elastic,
        [Description("ellipsis-circle (e7da, Shape, Form, dots)")] EllipsisCircle,
        [Description("ellipsis-circle-o (e7d9, Shape, Form, dots)")] EllipsisCircleOutline,
        [Description("ellipsis-dots-h (e91f, Web application, navigation, horizontal, more, additional)")] EllipsisDotsH,
        [Description("ellipsis-dots-v (e920, Web application, navigation, vertical, more, additional)")] EllipsisDotsV,
        [Description("ellipsis-h (e773, Shape, Form, dots)")] EllipsisH,
        [Description("ellipsis-v (e774, Shape, Form, dots)")] EllipsisV,
        [Description("enter (e922, Keyboard, key, shortcut, type, return, ok)")] Enter,
        [Description("enter-arrow (e921, Keyboard, key, shortcut, type, return, ok)")] EnterArrow,
        [Description("envelope (e7dc, Office, Item, mail, letter, email)")] Envelope,
        [Description("envelope-open (e63e, Office, mail, letter, email)")] EnvelopeOpen,
        [Description("envelope-o (e7db, Office, Item, mail, letter, email)")] EnvelopeOutline,
        [Description("envelope-open-o (e63d, Office, mail, letter, email)")] EnvelopeOutlinepenOutline,
        [Description("envelopes (e924, Office, Item, mail, letter, email)")] Envelopes,
        [Description("envelopes-o (e923, Office, Item, mail, letter, email)")] EnvelopesOutline,
        [Description("eraser (e69a, Office, Item, Edit, erase, delete, remove)")] Eraser,
        [Description("esc (e926, Keyboard, key, shortcut, type, escape, stop, close, cancel)")] Esc,
        [Description("esc-a (e925, Keyboard, key, shortcut, type, escape, stop, close, cancel)")] EscA,
        [Description("euro (e927, Ledger, Shopping, money, currency, payment)")] Euro,
        [Description("exchange (e705, Directions, Web application, swap, arrows, bidirectional)")] Exchange,
        [Description("exclamation (e708, Notification, Sign, warning)")] Exclamation,
        [Description("exclamation-circle (e707, Notification, Sign, warning)")] ExclamationCircle,
        [Description("exclamation-circle-o (e706, Notification, Sign, warning)")] ExclamationCircleOutline,
        [Description("exit (e60c, Sign, run, sign out, log out)")] Exit,
        [Description("exit-o (e60b, Sign, sign out, log out)")] ExitOutline,
        [Description("expand (e776, Directions, Web application, maximize, full screen, arrows)")] Expand,
        [Description("expand-full (e775, Directions, Web application, maximize, full screen, arrows)")] ExpandFull,
        [Description("expand-square (e7dd, Directions, Web application, maximize, full screen, arrows)")] ExpandSquare,
        [Description("external-browser (e63f, Web application)")] ExternalBrowser,
        [Description("external-link (e7de, Web application, extract)")] ExternalLink,
        [Description("eye (e7df, Sign, visible, show, view)")] Eye,
        [Description("eyedropper (e640, Tools, Item, color picker)")] Eyedropper,
        [Description("eye-slash (e709, Sign, hide, unseen, disable, hidden)")] EyeSlash,
        [Description("facebook (e69c, Brand, Social)")] Facebook,
        [Description("facebook-square (e69b, Brand, Social)")] FacebookSquare,
        [Description("factory (e641, Location, production, work)")] Factory,
        [Description("family (e928, People, users, child, human, person, group)")] Family,
        [Description("fast-backward (e777, Media, Player, previous, first)")] FastBackward,
        [Description("fast-forward (e778, Media, Player, next, last)")] FastForward,
        [Description("female (e69d, People, human, person, woman, girl)")] Female,
        [Description("file (e7e3, File types, document)")] File,
        [Description("file-add (e929, File types, document, attachment, new, plus, page)")] FileAdd,
        [Description("file-code (e70a, File types, html, document)")] FileCode,
        [Description("file-font (e69e, File types, text, document)")] FileFont,
        [Description("file-movie (e70b, File types, video, media, document)")] FileMovie,
        [Description("file-o (e7e0, File types, document)")] FileOutline,
        [Description("file-picture (e70c, File types, image, photo, document)")] FilePicture,
        [Description("file-presentation (e69f, File types, multimedia, powerpoint, keynote, document)")] FilePresentation,
        [Description("file-process (e642, File types, document, cog, settings, gear)")] FileProcess,
        [Description("file-refresh (e643, File types, document, reload)")] FileRefresh,
        [Description("file-remove (e92a, File types, document, attachment, destroy, delete, x, page)")] FileRemove,
        [Description("file-search (e92b, File types, document, attachment, find, inspect, looking glass, page)")] FileSearch,
        [Description("file-sound (e70d, File types, music, voice, sound, audio, document)")] FileSound,
        [Description("file-start (e644, File types, media, video, movie, document)")] FileStart,
        [Description("file-table (e6a0, File types, table, sheet, document)")] FileTable,
        [Description("file-text (e7e2, File types, text, document)")] FileText,
        [Description("file-text-o (e7e1, File types, text, document)")] FileTextOutline,
        [Description("file-tree (e647, Web application, nodes, mindmap)")] FileTree,
        [Description("file-tree-small (e645, Web application, nodes, mindmap)")] FileTreeSmall,
        [Description("file-tree-sub (e646, Web application, nodes, mindmap)")] FileTreeSub,
        [Description("file-zip (e70e, File types, compress, rar, document, archive)")] FileZip,
        [Description("fill (e6a1, Tools, paint bucket)")] Fill,
        [Description("film (e779, Media, movie, video, clip)")] Film,
        [Description("filter (e6a2, Item)")] Filter,
        [Description("fire (e6a3, Sign, hot, burn)")] Fire,
        [Description("flag (e711, Sign)")] Flag,
        [Description("flag-checkered (e70f, Sign, goal, finish)")] FlagCheckered,
        [Description("flag-o (e710, Sign)")] FlagOutline,
        [Description("flash (e712, Sign, Shape)")] Flash,
        [Description("flask (e7e4, Medical, Item, test, lab, laboratory, science)")] Flask,
        [Description("flight-landing (e92c, Transportation, travel, airplane, fly, arrive, arrival, vacation)")] FlightLanding,
        [Description("flight-takeoff (e92d, Transportation, travel, airplane, fly, departure, vacation)")] FlightTakeoff,
        [Description("flip-h (e649, Edit, mirror)")] FlipH,
        [Description("flip-v (e64a, Edit, mirror)")] FlipV,
        [Description("folder (e7e6, File types, document, file, container)")] Folder,
        [Description("folder-add (e92e, File types, document, file, container, new, plus)")] FolderAdd,
        [Description("folder-open (e77b, File types, document, file, container)")] FolderOpen,
        [Description("folder-o (e7e5, File types, document, file, container)")] FolderOutline,
        [Description("folder-open-o (e77a, File types, document, file, container)")] FolderOutlinepenOutline,
        [Description("folder-remove (e92f, File types, document, file, container, delete, destroy, x)")] FolderRemove,
        [Description("folder-search (e930, File types, document, file, container, find, inspect, looking glass)")] FolderSearch,
        [Description("font (e713, Text editor, text, character, text-decoration, letter)")] Font,
        [Description("form (e64b, Web application, layout, html, component)")] Form,
        [Description("forward (e77c, Media, Player, next)")] Forward,
        [Description("frown-o (e6a4, Social, Sign, unhappy, sad, emoji)")] FrownOutline,
        [Description("funcion (e64c, Web application, math, code)")] Funcion,
        [Description("funnel (e931, Charts, graph, diagram, filter, limit, define)")] Funnel,
        [Description("gamepad (e714, Media, Item, game, pad, joystick)")] Gamepad,
        [Description("gavel (e6a5, Tools, Item, auction, justice, hammer)")] Gavel,
        [Description("gift (e715, Item, present, birthday)")] Gift,
        [Description("glass (e77d, Food, cocktail, drink, party)")] Glass,
        [Description("glasses (e7e7, Item, goggles, nerd)")] Glasses,
        [Description("globe (e77e, Web application, earth, internet, global, world)")] Globe,
        [Description("globe-wire (e932, Web application, earth, internet, web, global, world)")] GlobeWire,
        [Description("golf (e60d, People, leisure, play, free time, sport)")] Golf,
        [Description("google-plus (e6a7, Brand, Social)")] GooglePlus,
        [Description("google-plus-square (e6a6, Brand, Social)")] GooglePlusSquare,
        [Description("grab (e64d, Web application, hold, hand)")] Grab,
        [Description("grid (e651, Web application, layout, html, component, table)")] Grid,
        [Description("grid-bevel (e64e, Web application, layout, html, component, table)")] GridBevel,
        [Description("grid-big (e7e9, Web application, menu, window)")] GridBig,
        [Description("grid-big-o (e7e8, Web application, menu, window)")] GridBigOutline,
        [Description("grid-h (e64f, Web application, layout, html, component, columns)")] GridH,
        [Description("grid-small (e7eb, Web application, layout, html, component, table)")] GridSmall,
        [Description("grid-small-o (e7ea, Web application, layout, html, component, table)")] GridSmallOutline,
        [Description("grid-v (e650, Web application, layout, html, component, rows)")] GridV,
        [Description("group (e60e, People, users, staff)")] Group,
        [Description("hammer (e933, Tools, Item, nail, knock, building, construction)")] Hammer,
        [Description("hand (e652, Web application, pan)")] Hand,
        [Description("handle-corner (e716, Web application, resize)")] HandleCorner,
        [Description("handshake (e934, People, agreement, deal, partnership, business)")] Handshake,
        [Description("hands-up (e6a8, People, human, person, happy, joy)")] HandsUp,
        [Description("harddrive (e718, Devices, Media, Item, disk, harddisk, HD, storage)")] Harddrive,
        [Description("harddrive-o (e717, Devices, Media, Item, disk, harddisk, HD, storage)")] HarddriveOutline,
        [Description("hash (e6a9, Web application, number, pound)")] Hash,
        [Description("header (e719, Text editor, font, character, text-decoration, letter)")] Header,
        [Description("headphones (e71a, Devices, Media, Item, sound, audio, voice, music, listening)")] Headphones,
        [Description("headset (e935, Devices, Media, headphones, microphone, skype, sound, audio, voice)")] Headset,
        [Description("health-card (e60f, Medical, insurance, heart, healthcare)")] HealthCard,
        [Description("heart (e780, Medical, Shape, life, love, health, healthcare)")] Heart,
        [Description("heart-o (e77f, Medical, life, love, health, healthcare)")] HeartOutline,
        [Description("home (e7ed, Location, house)")] Home,
        [Description("home-o (e7ec, Location, house)")] HomeOutline,
        [Description("hospital (e936, Location, Medical, doctor, emergency, healthcare, structure, building)")] Hospital,
        [Description("hourglass (e93a, Scheduling, Item, timer, measurement, stopwatch)")] Hourglass,
        [Description("hourglass-empty (e937, Scheduling, Item, timer, measurement, stopwatch)")] HourglassEmpty,
        [Description("hourglass-end (e938, Scheduling, Item, timer, measurement, stopwatch)")] HourglassEnd,
        [Description("hourglass-start (e939, Scheduling, Item, timer, measurement, stopwatch)")] HourglassStart,
        [Description("inbox (e71b, Office, email)")] Inbox,
        [Description("indent (e781, Text editor, paragraph, column)")] Indent,
        [Description("info (e71e, Notification, Sign, information)")] Info,
        [Description("info-circle (e71d, Notification, Sign, information)")] InfoCircle,
        [Description("info-circle-o (e71c, Notification, Sign, information)")] InfoCircleOutline,
        [Description("input (e653, Web application, text, layout, html, component, field)")] Input,
        [Description("insert (e7d8, Web application, internal, link, put)")] Insert,
        [Description("institution (e6aa, Location, academy, school, justice, court, museum)")] Institution,
        [Description("invoice (e610, Ledger, Shopping, bill, billing, payment)")] Invoice,
        [Description("italic (e720, Text editor, font, character, text-decoration)")] Italic,
        [Description("key (e6ac, Item, sign in, log in, login, access)")] Key,
        [Description("keyboard (e722, Devices, Item, input, type)")] Keyboard,
        [Description("keyboard-o (e721, Devices, Item, input, type)")] KeyboardOutline,
        [Description("key-o (e6ab, Item, sign in, log in, login, access)")] KeyOutline,
        [Description("laptop (e782, Devices, Item, macbook, computer)")] Laptop,
        [Description("layout (e654, Web application, layout, html, web page, site)")] Layout,
        [Description("level-down (e783, Directions, arrow, angle)")] LevelDown,
        [Description("level-down-bold (e611, Directions, arrow, angle)")] LevelDownBold,
        [Description("level-left (e784, Directions, arrow, angle, back, reply, previous)")] LevelLeft,
        [Description("level-left-bold (e612, Directions, arrow, angle, back, reply, previous)")] LevelLeftBold,
        [Description("level-right (e785, Directions, Office, forward, arrow, angle, next)")] LevelRight,
        [Description("level-right-bold (e655, Directions, Office, forward, arrow, angle, next)")] LevelRightBold,
        [Description("level-up (e786, Directions, arrow, angle)")] LevelUp,
        [Description("level-up-bold (e613, Directions, arrow, angle)")] LevelUpBold,
        [Description("lifebuoy (e6ad, Item, lifesaver, life ring, help, insurance)")] Lifebuoy,
        [Description("lightbulb (e6ae, Notification, Item, idea, smart)")] Lightbulb,
        [Description("line-bar-chart (e93b, Charts, graph, diagram, column-chart, dashboard)")] LineBarChart,
        [Description("line-chart (e93c, Charts, graph, diagram)")] LineChart,
        [Description("line-h (e723, Shape)")] LineH,
        [Description("lines (e7ef, Text editor, Shape, justify, text, align, paragraph)")] Lines,
        [Description("lines-list (e7ee, Text editor, bullets, text)")] LinesList,
        [Description("line-v (e724, Shape)")] LineV,
        [Description("link (e725, Web application)")] Link,
        [Description("list (e7f1, Text editor, bullets, text)")] List,
        [Description("list-ol (e71f, Text editor, order, sort, checklist)")] ListOl,
        [Description("list-select (e656, Web application, layout, html, component, navigation)")] ListSelect,
        [Description("list-ul (e7f0, Text editor, Web application, bullets, text)")] ListUl,
        [Description("location-arrow (e728, Location, map, direction, compass)")] LocationArrow,
        [Description("location-arrow-circle (e727, Location, map, direction, compass)")] LocationArrowCircle,
        [Description("location-arrow-circle-o (e726, Location, map, direction, compass)")] LocationArrowCircleOutline,
        [Description("lock (e7f2, Item, secure, safe, protect)")] Lock,
        [Description("magic (e6b1, Tools, Item, wand, staff)")] Magic,
        [Description("magnet (e787, Item, Sign)")] Magnet,
        [Description("mailbox (e729, Office, email, archive)")] Mailbox,
        [Description("male (e6b2, People, human, person, man, boy)")] Male,
        [Description("map-marker (e788, Location, location)")] MapMarker,
        [Description("margin (e65b, Web application, css, layout, html)")] Margin,
        [Description("margin-bottom (e657, Web application, css, layout, html)")] MarginBottom,
        [Description("margin-left (e658, Web application, css, layout, html)")] MarginLeft,
        [Description("margin-right (e659, Web application, css, layout, html)")] MarginRight,
        [Description("margin-top (e65a, Web application, css, layout, html)")] MarginTop,
        [Description("medal (e6b3, Item, achievement, award)")] Medal,
        [Description("megafone (e6b4, Social, Item, campaign, marketing)")] Megafone,
        [Description("meh-o (e6b5, Social, Sign, blah, whatever, bored, emoji)")] MehOutline,
        [Description("menu (e7b3, Web application, hamburger, bars)")] Menu,
        [Description("microphone (e72a, Media, Player, Item, record, voice)")] Microphone,
        [Description("minus (e7f6, Form, line, bar, minimize, collapse, remove)")] Minus,
        [Description("minus-circle (e7f4, Form, minimize, collapse, remove, no-entry)")] MinusCircle,
        [Description("minus-circle-o (e7f3, Form, minimize, collapse, remove, no-entry)")] MinusCircleOutline,
        [Description("minus-square-o (e7f5, Form, minimize, collapse, remove)")] MinusSquareOutline,
        [Description("mobile (e7f7, Devices, Item, phone, iphone, smartphone)")] Mobile,
        [Description("mobile-browser (e93d, Web application, Devices, layout, html, internet, smartphone, responsive, web, page, site)")] MobileBrowser,
        [Description("mobile-retro (e93e, Devices, Item, cellphone, old)")] MobileRetro,
        [Description("modal (e7f8, Web application, layout, html, internet, web page, site, pop-up)")] Modal,
        [Description("modal-list (e72b, Web application, layout, html, internet, web page, site, pop-up)")] ModalList,
        [Description("money (e6b6, Shopping, dollar, bill, payment)")] Money,
        [Description("money-deposit (e93f, Ledger, Shopping, dollar, finance, banking, atm)")] MoneyDeposit,
        [Description("money-exchange (e940, Ledger, Shopping, dollar, finance, banking, buy, purchase)")] MoneyExchange,
        [Description("money-withdraw (e941, Ledger, Shopping, dollar, finance, banking, atm)")] MoneyWithdraw,
        [Description("moon (e78a, Sign, night, evening)")] Moon,
        [Description("moon-o (e789, Sign, night, evening)")] MoonOutline,
        [Description("morning (e942, Weather, Sign, sunrise, sunset, horizon, summer, time)")] Morning,
        [Description("movie (e78b, Media, Player, video, clip)")] Movie,
        [Description("music (e78c, Media, Player, melody, voice, sound, song, audio, note)")] Music,
        [Description("mute (e72c, Media, Player, microphone, voice)")] Mute,
        [Description("native-button (e65c, Web application, layout, html, component, navigation)")] NativeButton,
        [Description("newspaper (e943, Items, journal, press, magazine)")] Newspaper,
        [Description("notebook (e65d, Office, Item, cover, exercise, school)")] Notebook,
        [Description("nurse (e944, Medical, People, healthcare, medic)")] Nurse,
        [Description("office (e945, Location, Office, structure, headquarters, building, work)")] Office,
        [Description("open-book (e7f9, Media, media, read, learn)")] OpenBook,
        [Description("option (e947, Keyboard, key, shortcut, type, command, modifier, Mac, OS X)")] Option,
        [Description("option-a (e946, Keyboard, key, shortcut, type, command, modifier, Mac, OS X)")] OptionA,
        [Description("options (e65e, Web application, Form, list, order, form, select, radiobuttons)")] Options,
        [Description("orientation (e65f, Web application, landscape, portrait, viewport, rotate)")] Orientation,
        [Description("out (e614, Notification, Sign, vacation, out of office)")] Out,
        [Description("outbox (e660, Office, email, send, sent)")] Outbox,
        [Description("package (e6b7, Transportation, Item, box, delivery, logistics, shipping, pickup)")] Package,
        [Description("padding (e665, Web application, css, layout, html)")] Padding,
        [Description("padding-bottom (e661, Web application, css, layout, html)")] PaddingBottom,
        [Description("padding-left (e662, Web application, css, layout, html)")] PaddingLeft,
        [Description("padding-right (e663, Web application, css, layout, html)")] PaddingRight,
        [Description("padding-top (e664, Web application, css, layout, html)")] PaddingTop,
        [Description("paintbrush (e6b8, Tools, Item, paint)")] Paintbrush,
        [Description("paint-roll (e666, Tools, Item, paint)")] PaintRoll,
        [Description("palete (e667, Tools, Item, color, paint)")] Palete,
        [Description("panel (e668, Web application, layout, html, component)")] Panel,
        [Description("paperclip (e72d, Office, Item, attachment)")] Paperclip,
        [Description("paperplane (e6b9, Office, email, send)")] Paperplane,
        [Description("paperplane-o (e6ba, Office, email, send)")] PaperplaneOutline,
        [Description("paragraph (e6bb, Text editor, text, character, text-decoration, pilcrow)")] Paragraph,
        [Description("password (e669, Web application, layout, html, component, login, log in, sign in)")] Password,
        [Description("paste (e6bc, Web application, clipboard, file, document)")] Paste,
        [Description("pause (e78d, Media, Player, hold)")] Pause,
        [Description("pencil (e7fa, Text editor, Item, Edit, draw, edit, write, pen)")] Pencil,
        [Description("phone (e7fb, Devices, call)")] Phone,
        [Description("phone-landline (e948, Devices, telephone, call, dial, contact)")] PhoneLandline,
        [Description("picture (e7fc, Media, Item, image, photo)")] Picture,
        [Description("pie-bar-chart (e949, Charts, graph, diagram, column-chart, dashboard)")] PieBarChart,
        [Description("pie-chart (e6bd, Charts, graph, diagram)")] PieChart,
        [Description("piggy-bank (e94b, Ledger, Shopping, money, currency, banking, finance)")] PiggyBank,
        [Description("piggy-bank-coin (e94a, Ledger, Shopping, money, currency, banking, finance)")] PiggyBankCoin,
        [Description("pill (e615, Medical, medicine, cure, healthcare)")] Pill,
        [Description("pills (e616, Medical, medicine, cure, healthcare)")] Pills,
        [Description("pin (e7fd, Office, Item, attach, location, mark)")] Pin,
        [Description("pin-post (e6be, Office, note, remind)")] PinPost,
        [Description("play (e78e, Media, Player, Shape, start, triangle)")] Play,
        [Description("play-circle (e731, Media, Player, start)")] PlayCircle,
        [Description("play-circle-o (e72e, Media, Player, start)")] PlayCircleOutline,
        [Description("plug (e66a, Sign, attach, electricy)")] Plug,
        [Description("plus (e801, Form, add, expand)")] Plus,
        [Description("plus-circle (e7ff, Form, add, expand)")] PlusCircle,
        [Description("plus-circle-o (e7fe, Form, add, expand)")] PlusCircleOutline,
        [Description("plus-minus (e603, Ledger, Shopping, calculator)")] PlusMinus,
        [Description("plus-square-o (e800, Form, add, expand)")] PlusSquareOutline,
        [Description("pointer (e66b, Web application, tap, hand)")] Pointer,
        [Description("power-off (e78f, Web application, end, logout, log out, sign out, shut down, start, power-on)")] PowerOff,
        [Description("presentation (e6bf, Office, multimedia, powerpoint, keynote)")] Presentation,
        [Description("print (e802, Devices, Item, printer)")] Print,
        [Description("progressbar (e66c, Web application, loading)")] Progressbar,
        [Description("puzzle-piece (e6c0, Item, component, piece, part, add-on)")] PuzzlePiece,
        [Description("pyramid-chart (e94c, Charts, graph, diagram, growing, levels)")] PyramidChart,
        [Description("qrcode (e6c1, File types, Media)")] Qrcode,
        [Description("question (e732, Notification, help, puzzle)")] Question,
        [Description("question-circle (e730, Notification, help, puzzle)")] QuestionCircle,
        [Description("question-circle-o (e72f, Notification, help, puzzle)")] QuestionCircleOutline,
        [Description("quote-left (e6c2, Text editor)")] QuoteLeft,
        [Description("quote-right (e6c3, Text editor)")] QuoteRight,
        [Description("random (e733, Directions, Web application, crossing, shuffle)")] Random,
        [Description("raster (e6c5, Shape, texture)")] Raster,
        [Description("raster-lower-left (e6c4, Shape, texture)")] RasterLowerLeft,
        [Description("records (e94d, Office, documents, archive, files, filing, scoresheets)")] Records,
        [Description("recycle (e6c6, Sign, ecology)")] Recycle,
        [Description("refresh (e790, Directions, Web application, update, reload, spin, recycle)")] Refresh,
        [Description("reply (e792, Directions, Office, arrow, back, previous)")] Reply,
        [Description("reply-all (e791, Directions, Office, arrow, back, previous)")] ReplyAll,
        [Description("resize-h (e66d, Web application, move)")] ResizeH,
        [Description("resize-v (e66e, Web application, move)")] ResizeV,
        [Description("retweet (e793, Directions)")] Retweet,
        [Description("rhombus (e66f, Shape, square, diamond)")] Rhombus,
        [Description("road (e6c7, Sign, route, path, highway, street)")] Road,
        [Description("road-branch (e670, Sign, Directions, Web application, route, path, intersection)")] RoadBranch,
        [Description("road-branches (e671, Sign, Directions, Web application, route, path, intersection)")] RoadBranches,
        [Description("road-split (e672, Directions, Web application, route, path, divine, fork)")] RoadSplit,
        [Description("rocket (e6c8, Transportation, space, ship, craft, launch)")] Rocket,
        [Description("rotate-left (e794, Directions, backward, history, earlier, previous)")] RotateLeft,
        [Description("rotate-right (e795, Directions, forward, future, upcoming)")] RotateRight,
        [Description("rss (e6ca, Social, Notification, news, subscribe)")] Rss,
        [Description("rss-square (e6c9, Social, Notification, news, subscribe)")] RssSquare,
        [Description("safe (e6cc, Item, security, protection, safe keeping, support, cover, vault, encrypt)")] Safe,
        [Description("safe-lock (e6cb, Item, security, protection, safe keeping, support, cover, vault, encrypt)")] SafeLock,
        [Description("scale (e94f, Item, measure, weight, evaluate)")] Scale,
        [Description("scale-unbalance (e94e, Item, measure, weight, evaluate)")] ScaleUnbalance,
        [Description("scatter-chart (e950, Charts, graph, diagram, points, measurements)")] ScatterChart,
        [Description("scissors (e734, Tools, Item, Edit, cut, clippers)")] Scissors,
        [Description("screwdriver (e735, Tools, Item, Edit, settings, adjust)")] Screwdriver,
        [Description("search (e805, Tools, Item, looking glass, inspect)")] Search,
        [Description("search-minus (e804, Tools, Item, looking glass, zoom in, enlarge)")] SearchMinus,
        [Description("search-plus (e803, Tools, Item, looking glass, zoom out, shrink)")] SearchPlus,
        [Description("select (e673, Web application, layout, html, component, navigation, dropdown)")] Select,
        [Description("server (e736, Devices, Media, storage, hard drive, hard disk, cloud, hdd)")] Server,
        [Description("share (e796, Directions, send, next, right)")] Share,
        [Description("share-square (e6cd, Directions, arrow, send)")] ShareSquare,
        [Description("shield (e6ce, Item, security, protection, safe keeping, support, cover, antivirus)")] Shield,
        [Description("shift (e952, Keyboard, key, shortcut, type, modifier)")] Shift,
        [Description("shift-arrow (e951, Keyboard, key, shortcut, type, modifier)")] ShiftArrow,
        [Description("shop (e953, Location, Shopping, buy, commerce, store, supermarket)")] Shop,
        [Description("signal (e738, Notification, Sign, wlan, wireless, Wi-Fi, cellular, radio, waves)")] Signal,
        [Description("sign-in (e797, Directions, Web application, log in, login, enter)")] SignIn,
        [Description("sign-in-alt (e6b0, Web application, log in, login, enter)")] SignInAlt,
        [Description("sign-out (e798, Directions, Web application, logout, log out, leave, exit)")] SignOut,
        [Description("sign-out-alt (e6af, Web application, logout, log out, leave, exit)")] SignOutAlt,
        [Description("sitemap (e739, Web application, hierarchy, mindmap)")] Sitemap,
        [Description("slider (e674, Media, Player, Edit, adjust)")] Slider,
        [Description("sliders (e6cf, Media, Player, Edit, settings, adjust, mixer)")] Sliders,
        [Description("smiley-o (e6d0, Social, happy, smile, emoji)")] SmileyOutline,
        [Description("sort (e799, Directions, arrange)")] Sort,
        [Description("sound-disable (e79a, Media, Player, mute, sound, voice, audio, speaker)")] SoundDisable,
        [Description("spark-line (e954, Charts, graph, diagram, stock market)")] SparkLine,
        [Description("specialist (e617, Medical, People, doctor, healthcare, surgeon)")] Specialist,
        [Description("spinner (e6d3, Shape, loader, loading)")] Spinner,
        [Description("spinner-arc (e6d1, Shape, loader, loading)")] SpinnerArc,
        [Description("spinner-third (e6d2, Shape, loader, loading)")] SpinnerThird,
        [Description("spline-area-chart (e955, Charts, graph, diagram, line)")] SplineAreaChart,
        [Description("spline-chart (e956, Charts, graph, diagram, line)")] SplineChart,
        [Description("split (e675, Web application, Edit, duplicate, division)")] Split,
        [Description("split-h (e807, Web application, layout, html, component)")] SplitH,
        [Description("split-v (e808, Web application, layout, html, component)")] SplitV,
        [Description("spoon (e73a, Food, Item, soup)")] Spoon,
        [Description("square-shadow (e79b, Form, Shape, box, check)")] SquareShadow,
        [Description("star (e7a1, Social, Shape)")] Star,
        [Description("star-half-left (e79d, Social)")] StarHalfLeft,
        [Description("star-half-left-o (e79c, Social)")] StarHalfLeftOutline,
        [Description("star-half-right (e79f, Social)")] StarHalfRight,
        [Description("star-half-right-o (e79e, Social)")] StarHalfRightOutline,
        [Description("star-o (e7a0, Social, Shape)")] StarOutline,
        [Description("start-cog (e676, Web application, play, process, gear)")] StartCog,
        [Description("step-backward (e7a2, Media, Player, previous)")] StepBackward,
        [Description("step-forward (e7a3, Media, Player, next)")] StepForward,
        [Description("stethoscope (e618, Medical, Tools, Item, doctor, healthcare, diagnose)")] Stethoscope,
        [Description("stock (e957, Item, boxes, packages, warehouse, storing, pallet)")] Stock,
        [Description("stop (e7a4, Media, Player, Shape, box, square)")] Stop,
        [Description("stop-cog (e677, Web application, end, process, gear)")] StopCog,
        [Description("stopwatch (e958, Scheduling, Item, time, tracking, measurement, hours)")] Stopwatch,
        [Description("storage (e959, Location, boxes, packages, warehouse, storing, stock)")] Storage,
        [Description("strikethrough (e73b, Text editor, font, character, text-decoration)")] Strikethrough,
        [Description("subscript (e6d4, Text editor, calc, calculator, math)")] Subscript,
        [Description("suitcase (e809, Item, briefcase, travel)")] Suitcase,
        [Description("sun-down (e95a, Weather, Sign, evening, time, daytime)")] SunDown,
        [Description("sun-o (e73c, Sign, Weather, summer, warm)")] SunOutline,
        [Description("sun-rise (e95b, Weather, Sign, morning, time, daytime)")] SunRise,
        [Description("superscript (e6d5, Text editor, calc, calculator, math)")] Superscript,
        [Description("sword (e678, Item, sharp, blade, weapon)")] Sword,
        [Description("tab (e95d, Keyboard, key, shortcut, type, tabulator, indent)")] Tab,
        [Description("tab-a (e95c, Keyboard, key, shortcut, type, tabulator, indent)")] TabA,
        [Description("table (e7a5, Web application, layout, html, component)")] Table,
        [Description("tablet (e80a, Devices, Media, Item, pad, ipad)")] Tablet,
        [Description("tabs (e679, Web application, layout, html, component, navigation, tabsheet)")] Tabs,
        [Description("tag (e6d6, Notification, Sign, label, price)")] Tag,
        [Description("tags (e6d7, Notification, Sign, label, price)")] Tags,
        [Description("tasks (e73d, Form, check, list, todo)")] Tasks,
        [Description("taxi (e67a, Transportation, vehicle, travel, auto)")] Taxi,
        [Description("teeth (e619, Medical, dental, dentist, healthcare, mouth)")] Teeth,
        [Description("terminal (e6d8, Web application, code, system, prompt)")] Terminal,
        [Description("text-height (e73e, Text editor, font, character, text-decoration)")] TextHeight,
        [Description("text-input (e67b, Text editor, Web application, layout, html, component)")] TextInput,
        [Description("text-label (e67c, Text editor, Web application, header, font, character, text-decoration)")] TextLabel,
        [Description("text-width (e73f, Text editor, font, character, text-decoration)")] TextWidth,
        [Description("thin-square (e7a6, Shape, Form, check box, stop)")] ThinSquare,
        [Description("thumbs-down (e6da, Social, dislike, facebook)")] ThumbsDown,
        [Description("thumbs-down-o (e6d9, Social, dislike, facebook)")] ThumbsDownOutline,
        [Description("thumbs-up (e6dc, Social, like, facebook)")] ThumbsUp,
        [Description("thumbs-up-o (e6db, Social, like, facebook)")] ThumbsUpOutline,
        [Description("ticket (e740, Item, pass, licence, permit)")] Ticket,
        [Description("time-backward (e7a7, Scheduling, history, clock, earlier, previous)")] TimeBackward,
        [Description("time-forward (e7a8, Scheduling, future, clock, upcoming, postpone, snooze)")] TimeForward,
        [Description("timer (e95e, Scheduling, Item, time, tracking, measurement, hours, stopwatch)")] Timer,
        [Description("toolbox (e741, Tools, Item, settings)")] Toolbox,
        [Description("tools (e742, Tools, Item, Edit, wrench, screwdriver, settings)")] Tools,
        [Description("tooth (e67d, Media, dental, dentist, healthcare)")] Tooth,
        [Description("touch (e95f, Web application, tap, click, pointer, finger)")] Touch,
        [Description("train (e67e, Transportation, railroad)")] Train,
        [Description("trash (e80b, Web application, delete, remove, garbage, bin)")] Trash,
        [Description("tree-table (e67f, Web application, layout, html, component, navigation)")] TreeTable,
        [Description("trendind-down (e960, Charts, graph, diagram, line-chart, table, lower)")] TrendindDown,
        [Description("trending-up (e961, Charts, graph, diagram, line-chart, table, rise)")] TrendingUp,
        [Description("trophy (e743, Item, prize, champion, award)")] Trophy,
        [Description("truck (e6dd, Transportation, vehicle, delivery, logistics, shipping, pickup)")] Truck,
        [Description("twin-col-select (e680, Web application, layout, html, component, navigation)")] TwinColSelect,
        [Description("twitter (e6df, Brand, Social)")] Twitter,
        [Description("twitter-square (e6de, Brand, Social)")] TwitterSquare,
        [Description("umbrella (e6e0, Item, security, protection, safe keeping, support, cover, antivirus)")] Umbrella,
        [Description("underline (e744, Text editor, font, character, text-decoration)")] Underline,
        [Description("unlink (e745, Web application, broken)")] Unlink,
        [Description("unlock (e80c, Item, open, acccess)")] Unlock,
        [Description("upload (e746, Web application, cloud, storage)")] Upload,
        [Description("upload-alt (e6e1, Web application, cloud, storage)")] UploadAlt,
        [Description("user (e80d, People, person)")] User,
        [Description("user-card (e61a, People, ID, identification)")] UserCard,
        [Description("user-check (e61b, People, verify)")] UserCheck,
        [Description("user-clock (e61c, People, Scheduling, time, appointment)")] UserClock,
        [Description("user-heart (e61d, Medical, People, healtcare, patient)")] UserHeart,
        [Description("users (e747, People, group)")] Users,
        [Description("user-star (e962, People, favorite, save)")] UserStar,
        [Description("vaadin-h (e80e, Brand)")] VaadinH,
        [Description("vaadin-v (e80f, Brand)")] VaadinV,
        [Description("viewport (e681, Web application, screen, canvas)")] Viewport,
        [Description("vimeo (e6e3, Brand, Social, Media, video, clip, movie)")] Vimeo,
        [Description("vimeo-square (e6e2, Brand, Social, Media, video, clip, movie)")] VimeoSquare,
        [Description("volume (e7ac, Media, Player, sound, voice, audio, speaker)")] Volume,
        [Description("volume-down (e7a9, Media, Player, sound, voice, audio, speaker)")] VolumeDown,
        [Description("volume-off (e7aa, Media, Player, mute, sound, voice, audio, speaker)")] VolumeOff,
        [Description("volume-up (e7ab, Media, Player, sound, voice, audio, speaker, loud, louder)")] VolumeUp,
        [Description("wallet (e963, Item, money, currency, cash, coins)")] Wallet,
        [Description("warning (e748, Notification, Sign, explanation mark, triangle)")] Warning,
        [Description("workplace (e900, Location, Office, structure, headquarters, office, work, building)")] Workplace,
        [Description("wrench (e749, Tools, Item, Edit, wrench, settings)")] Wrench,
        [Description("youtube (e6e5, Brand, Social, Media, video, clip, movie)")] Youtube,
        [Description("youtube-square (e6e4, Brand, Social, Media, video, clip, movie)")] YoutubeSquare
    }
}