namespace MahApps.Metro.IconPacks
{
#if !(NETFX_CORE || WINDOWS_UWP)
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconMicrons" />.
    /// </summary>
    /// <remarks>
    /// The Microns icons are licensed under [CC BY-SA](<see><cref>https://creativecommons.org/licenses/by-sa/3.0/</cref></see>) license.
    /// Contributions, corrections and requests can be made on GitHub <see><cref>https://github.com/stephenhutchings/microns</cref></see>.
    /// </remarks>
    public enum PackIconMicronsKind
    {
        [Description("Empty placeholder")] None,
        [Description("mu-align-center (E765, align, middle)")] AlignCenter,
        [Description("mu-align-left (E764, align, start)")] AlignLeft,
        [Description("mu-align-right (E766, align, end)")] AlignRight,
        [Description("mu-i-asterisk (E71B, check, correct)")] AsteriskInline,
        [Description("mu-audio (E73D, headphones)")] Audio,
        [Description("mu-audio-description (E725, media,accessibility)")] AudioDescription,
        [Description("mu-chart-bar (E727, graph, data)")] BarChart,
        [Description("mu-bars (E740, hamburger, menu, vertical)")] Bars,
        [Description("mu-bold (E75E, font, strong)")] Bold,
        [Description("mu-bookmark (E72F, save, for, later)")] Bookmark,
        [Description("mu-box (E750, box, checkbox)")] Box,
        [Description("mu-box-cross (E755, box, checkbox, ballot)")] BoxCross,
        [Description("mu-box-minus (E753, box, checkbox, partial, indeterminate)")] BoxMinus,
        [Description("mu-box-plus (E752, box, checkbox, add)")] BoxPlus,
        [Description("mu-box-tick (E754, box, checkbox, selected, on)")] BoxTick,
        [Description("mu-i-bullet (E71A, circle, dot, spot)")] BulletInline,
        [Description("mu-calendar (E72A, date, schedule, year, month)")] Calendar,
        [Description("mu-cancel (E741, undo, close, exit, cross, x)")] Cancel,
        [Description("mu-captions (E723, media,closed)")] Captions,
        [Description("mu-caret (E70F, sort, select)")] Caret,
        [Description("mu-chapters (E74B, list)")] Chapters,
        [Description("mu-chat (E730, comment, conversation)")] Chat,
        [Description("mu-text-unstyle (E763, font, clear)")] ClearStyles,
        [Description("mu-clock (E72B, time, schedule, hour, second, minute)")] Clock,
        [Description("mu-cloud (E769, server)")] Cloud,
        [Description("mu-code (E74F, embed)")] Code,
        [Description("mu-cog (E736, settings, preferences)")] Cog,
        [Description("mu-contract (E747, minimise, minimize)")] Contract,
        [Description("mu-i-cross (E719, cancel, undo, clear, wrong, incorrect)")] CrossInline,
        [Description("mu-delete (E732, trash, remove, archive)")] Delete,
        [Description("mu-down (E707, chevron, angle, south)")] Down,
        [Description("mu-arrow-down (E703, direction, south)")] DownArrow,
        [Description("mu-caret-down (E711, sort, select, descending, drop, down)")] DownCaret,
        [Description("mu-i-down (E715, chevron, angle, south)")] DownInline,
        [Description("mu-download (E709, align, bottom, pull)")] Download,
        [Description("mu-edit (E731, create)")] Edit,
        [Description("mu-expand (E748, maximise, maximize)")] Expand,
        [Description("mu-fail (E75C, clear, error)")] Fail,
        [Description("mu-file (E73A, document)")] File,
        [Description("mu-flag (E72E, remember, alert)")] Flag,
        [Description("mu-grid (E749, square)")] Grid,
        [Description("mu-group (E739, user, collection, team)")] Group,
        [Description("mu-heart (E72D, favourite, favorite, love, like)")] Heart,
        [Description("mu-hide (E734, hidden, unpublished, eye, closed)")] Hide,
        [Description("mu-hd (E724, media,high, definition)")] HighDefinition,
        [Description("mu-vol-high (E721, media,sound, listen, loud)")] HighVolume,
        [Description("mu-image (E73B, picture, photo)")] Image,
        [Description("mu-indent (E767, align, middle)")] Indent,
        [Description("mu-info (E759, notification, warning)")] Info,
        [Description("mu-italic (E75F, font, emphasis)")] Italic,
        [Description("mu-left (E704, chevron, angle, west)")] Left,
        [Description("mu-arrow-left (E700, direction, west)")] LeftArrow,
        [Description("mu-i-left (E712, chevron, angle, west)")] LeftInline,
        [Description("mu-chart-line (E726, graph, data)")] LineChart,
        [Description("mu-link (E737, anchor, chain)")] Link,
        [Description("mu-lock (E735, hidden)")] Lock,
        [Description("mu-vol-low (E71F, media,sound, listen, mute, quiet)")] LowVolume,
        [Description("mu-mail (E74E, email, post, send)")] Mail,
        [Description("mu-matrix (E74A, square, grid)")] Matrix,
        [Description("mu-menu (E73F, hamburger, bars, horizontal)")] Menu,
        [Description("mu-vol-mid (E720, media,sound, listen, medium)")] MidVolume,
        [Description("mu-minus (E70E, delete, remove, minimise, minimize)")] Minus,
        [Description("mu-i-minus (E717, delete, remove, minimise, minimize)")] MinusInline,
        [Description("mu-vol-mute (E722, media,sound, listen, silent)")] MuteVolume,
        [Description("mu-opts-h (E742, dots, three, more, horizontal)")] OptionsHorizontal,
        [Description("mu-opts-v (E743, dots, three, more, vertical)")] OptionsVertical,
        [Description("mu-outdent (E768, align, end)")] Outdent,
        [Description("mu-pass (E75B, confirm)")] Pass,
        [Description("mu-pause (E71D, media,stop)")] Pause,
        [Description("mu-chart-pie (E729, graph, data)")] PieChart,
        [Description("mu-play (E71C, media,watch, go)")] Play,
        [Description("mu-plus (E70D, add, new, create, maximise, maximize)")] Plus,
        [Description("mu-i-plus (E716, add, new, create, maximise, maximize)")] PlusInline,
        [Description("mu-print (E73E, printer)")] Print,
        [Description("mu-radio-full (E758, ring, circle, filled, on)")] RadioFilled,
        [Description("mu-radio-off (E756, ring, circle, off)")] RadioOff,
        [Description("mu-radio-on (E757, fisheye, selected, radio, on, record)")] RadioOn,
        [Description("mu-redo (E70B, forward, history, navigate, right)")] Redo,
        [Description("mu-replay (E70C, rewind,restart)")] Replay,
        [Description("mu-right (E705, chevron, angle, east)")] Right,
        [Description("mu-arrow-right (E701, direction, east)")] RightArrow,
        [Description("mu-i-right (E713, chevron, angle, east)")] RightInline,
        [Description("mu-rss (E74C, feed)")] Rss,
        [Description("mu-chart-scatter (E728, graph, data)")] ScatterPlot,
        [Description("mu-search (E744, find, magnify)")] Search,
        [Description("mu-share (E74D, connect)")] Share,
        [Description("mu-show (E733, visible, published, eye, open)")] Show,
        [Description("mu-box-full (E751, box, checkbox, filled)")] SolidBox,
        [Description("mu-star (E72C, favourite, favorite, review, like)")] Star,
        [Description("mu-strikeout (E761, font, strikethrough, strike-out)")] Strikeout,
        [Description("mu-subtitles (E71E, media)")] Subtitles,
        [Description("mu-text (E75D, font, letter, A)")] Text,
        [Description("mu-text-size (E762, font)")] TextSize,
        [Description("mu-i-tick (E718, check, correct)")] TickInline,
        [Description("mu-underline (E760, )")] Underline,
        [Description("mu-undo (E70A, back, history, navigate, left)")] Undo,
        [Description("mu-up (E706, chevron, angle, north)")] Up,
        [Description("mu-arrow-up (E702, direction, north)")] UpArrow,
        [Description("mu-caret-up (E710, sort, select, ascending, drop, up)")] UpCaret,
        [Description("mu-i-up (E714, chevron, angle, north)")] UpInline,
        [Description("mu-upload (E708, align, top, push)")] Upload,
        [Description("mu-user (E738, person, individual)")] User,
        [Description("mu-video (E73C, play, circle)")] Video,
        [Description("mu-warn (E75A, notification, danger, warning, error)")] Warn,
        [Description("mu-web (E76A, world, map)")] Web,
        [Description("mu-wifi (E76B, online)")] Wifi,
        [Description("mu-zoom-in (E745, magnify)")] ZoomIn,
        [Description("mu-zoom-out (E746, magnify)")] ZoomOut
    }
}