namespace MahApps.Metro.IconPacks
{
#if !(NETFX_CORE || WINDOWS_UWP)
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconIonicons" />.
    /// </summary>
    /// <remarks>
    /// Ionicons are licensed under the [MIT license](<see><cref>https://github.com/ionic-team/ionicons/blob/master/LICENSE</cref></see>).
    /// Contributions, corrections and requests can be made on GitHub <see><cref>https://github.com/ionic-team/ionicons</cref></see>.
    /// </remarks>
    public enum PackIconIoniconsKind
    {
        [Description("Empty placeholder")] None,
        [Description("ios-add-circle-outline (add, circle)")] AddCircleOutlineiOS,
        [Description("md-add-circle-outline (add, circle)")] AddCircleOutlineMD,
        [Description("ios-add-circle (add, circle)")] AddCircleiOS,
        [Description("md-add-circle (add, circle)")] AddCircleMD,
        [Description("ios-add (add, include, invite, plus)")] AddiOS,
        [Description("md-add (add, include, invite, plus)")] AddMD,
        [Description("ios-airplane (airplane, plane)")] AirplaneiOS,
        [Description("md-airplane (airplane, plane)")] AirplaneMD,
        [Description("ios-alarm (alarm, clock, time)")] AlarmiOS,
        [Description("md-alarm (alarm, clock, time)")] AlarmMD,
        [Description("ios-albums (albums, boxes, slides, square)")] AlbumsiOS,
        [Description("md-albums (albums, boxes, slides, square)")] AlbumsMD,
        [Description("ios-alert (!, alert, attention, exclamation, notice, warning)")] AlertiOS,
        [Description("md-alert (!, alert, attention, exclamation, notice, warning)")] AlertMD,
        [Description("ios-american-football (american, football)")] AmericanFootballiOS,
        [Description("md-american-football (american, football)")] AmericanFootballMD,
        [Description("ios-analytics (analytics, data, metrics, track)")] AnalyticsiOS,
        [Description("md-analytics (analytics, data, metrics, track)")] AnalyticsMD,
        [Description("ios-aperture (aperture, dark, images, levels, light, settings)")] ApertureiOS,
        [Description("md-aperture (aperture, dark, images, levels, light, settings)")] ApertureMD,
        [Description("ios-apps (apps, applications)")] AppsiOS,
        [Description("md-apps (apps, applications)")] AppsMD,
        [Description("ios-appstore (appstore, store)")] AppstoreiOS,
        [Description("md-appstore (appstore, store)")] AppstoreMD,
        [Description("ios-archive (archive, email)")] ArchiveiOS,
        [Description("md-archive (archive, email)")] ArchiveMD,
        [Description("ios-arrow-back (arrow, back, chevron, navigation)")] ArrowBackiOS,
        [Description("md-arrow-back (arrow, back, chevron, navigation)")] ArrowBackMD,
        [Description("ios-arrow-down (arrow, chevron, down)")] ArrowDowniOS,
        [Description("md-arrow-down (arrow, chevron, down)")] ArrowDownMD,
        [Description("ios-arrow-dropdown-circle (arrow, circle, dropdown)")] ArrowDropdownCircleiOS,
        [Description("md-arrow-dropdown-circle (arrow, circle, dropdown)")] ArrowDropdownCircleMD,
        [Description("ios-arrow-dropdown (arrow, dropdown)")] ArrowDropdowniOS,
        [Description("md-arrow-dropdown (arrow, dropdown)")] ArrowDropdownMD,
        [Description("ios-arrow-dropleft-circle (arrow, circle, dropleft)")] ArrowDropleftCircleiOS,
        [Description("md-arrow-dropleft-circle (arrow, circle, dropleft)")] ArrowDropleftCircleMD,
        [Description("ios-arrow-dropleft (arrow, dropleft)")] ArrowDropleftiOS,
        [Description("md-arrow-dropleft (arrow, dropleft)")] ArrowDropleftMD,
        [Description("ios-arrow-dropright-circle (arrow, circle, dropright)")] ArrowDroprightCircleiOS,
        [Description("md-arrow-dropright-circle (arrow, circle, dropright)")] ArrowDroprightCircleMD,
        [Description("ios-arrow-dropright (arrow, dropright)")] ArrowDroprightiOS,
        [Description("md-arrow-dropright (arrow, dropright)")] ArrowDroprightMD,
        [Description("ios-arrow-dropup-circle (arrow, circle, dropup)")] ArrowDropupCircleiOS,
        [Description("md-arrow-dropup-circle (arrow, circle, dropup)")] ArrowDropupCircleMD,
        [Description("ios-arrow-dropup (arrow, dropup)")] ArrowDropupiOS,
        [Description("md-arrow-dropup (arrow, dropup)")] ArrowDropupMD,
        [Description("ios-arrow-forward (arrow, chevron, forward, navigation)")] ArrowForwardiOS,
        [Description("md-arrow-forward (arrow, chevron, forward, navigation)")] ArrowForwardMD,
        [Description("ios-arrow-round-back (arrow, back, round)")] ArrowRoundBackiOS,
        [Description("md-arrow-round-back (arrow, back, round)")] ArrowRoundBackMD,
        [Description("ios-arrow-round-down (arrow, down, round)")] ArrowRoundDowniOS,
        [Description("md-arrow-round-down (arrow, down, round)")] ArrowRoundDownMD,
        [Description("ios-arrow-round-forward (arrow, forward, round)")] ArrowRoundForwardiOS,
        [Description("md-arrow-round-forward (arrow, forward, round)")] ArrowRoundForwardMD,
        [Description("ios-arrow-round-up (arrow, round, up)")] ArrowRoundUpiOS,
        [Description("md-arrow-round-up (arrow, round, up)")] ArrowRoundUpMD,
        [Description("ios-arrow-up (arrow, chevron, up)")] ArrowUpiOS,
        [Description("md-arrow-up (arrow, chevron, up)")] ArrowUpMD,
        [Description("ios-at (@, at)")] AtiOS,
        [Description("md-at (@, at)")] AtMD,
        [Description("ios-attach (attach)")] AttachiOS,
        [Description("md-attach (attach)")] AttachMD,
        [Description("ios-backspace (backspace)")] BackspaceiOS,
        [Description("md-backspace (backspace)")] BackspaceMD,
        [Description("ios-barcode (barcode, camera, reader)")] BarcodeiOS,
        [Description("md-barcode (barcode, camera, reader)")] BarcodeMD,
        [Description("ios-baseball (baseball)")] BaseballiOS,
        [Description("md-baseball (baseball)")] BaseballMD,
        [Description("ios-basket (basket)")] BasketiOS,
        [Description("md-basket (basket)")] BasketMD,
        [Description("ios-basketball (basketball)")] BasketballiOS,
        [Description("md-basketball (basketball)")] BasketballMD,
        [Description("ios-battery-charging (battery, charging)")] BatteryChargingiOS,
        [Description("md-battery-charging (battery, charging)")] BatteryChargingMD,
        [Description("ios-battery-dead (battery, dead)")] BatteryDeadiOS,
        [Description("md-battery-dead (battery, dead)")] BatteryDeadMD,
        [Description("ios-battery-full (battery, full)")] BatteryFulliOS,
        [Description("md-battery-full (battery, full)")] BatteryFullMD,
        [Description("ios-beaker (beaker, flask, mixture, potion)")] BeakeriOS,
        [Description("md-beaker (beaker, flask, mixture, potion)")] BeakerMD,
        [Description("ios-bed (bed, hotel, sleep)")] BediOS,
        [Description("md-bed (bed, hotel, sleep)")] BedMD,
        [Description("ios-beer (beer, drink, eat, food)")] BeeriOS,
        [Description("md-beer (beer, drink, eat, food)")] BeerMD,
        [Description("ios-bicycle (bicycle)")] BicycleiOS,
        [Description("md-bicycle (bicycle)")] BicycleMD,
        [Description("ios-bluetooth (bluetooth, cloud, connection)")] BluetoothiOS,
        [Description("md-bluetooth (bluetooth, cloud, connection)")] BluetoothMD,
        [Description("ios-boat (boat)")] BoatiOS,
        [Description("md-boat (boat)")] BoatMD,
        [Description("ios-body (body)")] BodyiOS,
        [Description("md-body (body)")] BodyMD,
        [Description("ios-bonfire (bonfire, heat, hot)")] BonfireiOS,
        [Description("md-bonfire (bonfire, heat, hot)")] BonfireMD,
        [Description("ios-book (book, read)")] BookiOS,
        [Description("md-book (book, read)")] BookMD,
        [Description("ios-bookmark (bookmark, favorite, save, tag)")] BookmarkiOS,
        [Description("md-bookmark (bookmark, favorite, save, tag)")] BookmarkMD,
        [Description("ios-bookmarks (bookmarks, favorite)")] BookmarksiOS,
        [Description("md-bookmarks (bookmarks, favorite)")] BookmarksMD,
        [Description("ios-bowtie (bowtie)")] BowtieiOS,
        [Description("md-bowtie (bowtie)")] BowtieMD,
        [Description("ios-briefcase (briefcase, folder, organize)")] BriefcaseiOS,
        [Description("md-briefcase (briefcase, folder, organize)")] BriefcaseMD,
        [Description("ios-browsers (browsers, square)")] BrowsersiOS,
        [Description("md-browsers (browsers, square)")] BrowsersMD,
        [Description("ios-brush (brush)")] BrushiOS,
        [Description("md-brush (brush)")] BrushMD,
        [Description("ios-bug (bug, develop, error, hacker, program)")] BugiOS,
        [Description("md-bug (bug, develop, error, hacker, program)")] BugMD,
        [Description("ios-build (build)")] BuildiOS,
        [Description("md-build (build)")] BuildMD,
        [Description("ios-bulb (bulb)")] BulbiOS,
        [Description("md-bulb (bulb)")] BulbMD,
        [Description("ios-bus (bus)")] BusiOS,
        [Description("md-bus (bus)")] BusMD,
        [Description("ios-business (business)")] BusinessiOS,
        [Description("md-business (business)")] BusinessMD,
        [Description("ios-cafe (cafe, coffee, cup)")] CafeiOS,
        [Description("md-cafe (cafe, coffee, cup)")] CafeMD,
        [Description("ios-calculator (arithmetic, calculator, math)")] CalculatoriOS,
        [Description("md-calculator (arithmetic, calculator, math)")] CalculatorMD,
        [Description("ios-calendar (calendar, date, month, week)")] CalendariOS,
        [Description("md-calendar (calendar, date, month, week)")] CalendarMD,
        [Description("ios-call (call, telephone)")] CalliOS,
        [Description("md-call (call, telephone)")] CallMD,
        [Description("ios-camera (camera, image, photo)")] CameraiOS,
        [Description("md-camera (camera, image, photo)")] CameraMD,
        [Description("ios-car (car)")] CariOS,
        [Description("md-car (car)")] CarMD,
        [Description("ios-card ($, card, cash, credit, debit, dollars, money, price, shopping)")] CardiOS,
        [Description("md-card ($, card, cash, credit, debit, dollars, money, price, shopping)")] CardMD,
        [Description("ios-cart (cart)")] CartiOS,
        [Description("md-cart (cart)")] CartMD,
        [Description("ios-cash ($, cash, credit, debit, dollars, money, price, shopping)")] CashiOS,
        [Description("md-cash ($, cash, credit, debit, dollars, money, price, shopping)")] CashMD,
        [Description("ios-cellular (cellular)")] CellulariOS,
        [Description("md-cellular (cellular)")] CellularMD,
        [Description("ios-chatboxes (chatboxes, talk)")] ChatboxesiOS,
        [Description("md-chatboxes (chatboxes, talk)")] ChatboxesMD,
        [Description("ios-chatbubbles (chatbubbles, talk)")] ChatbubblesiOS,
        [Description("md-chatbubbles (chatbubbles, talk)")] ChatbubblesMD,
        [Description("ios-checkbox-outline (checkbox)")] CheckboxOutlineiOS,
        [Description("md-checkbox-outline (checkbox)")] CheckboxOutlineMD,
        [Description("ios-checkbox (checkbox)")] CheckboxiOS,
        [Description("md-checkbox (checkbox)")] CheckboxMD,
        [Description("ios-checkmark-circle-outline (checkmark)")] CheckmarkCircleOutlineiOS,
        [Description("md-checkmark-circle-outline (checkmark)")] CheckmarkCircleOutlineMD,
        [Description("ios-checkmark-circle (checkmark, circle)")] CheckmarkCircleiOS,
        [Description("md-checkmark-circle (checkmark, circle)")] CheckmarkCircleMD,
        [Description("ios-checkmark (checkmark)")] CheckmarkiOS,
        [Description("md-checkmark (checkmark)")] CheckmarkMD,
        [Description("ios-clipboard (clipboard, write)")] ClipboardiOS,
        [Description("md-clipboard (clipboard, write)")] ClipboardMD,
        [Description("ios-clock (clock, time)")] ClockiOS,
        [Description("md-clock (clock, time)")] ClockMD,
        [Description("ios-close-circle-outline (close, circle)")] CloseCircleOutlineiOS,
        [Description("md-close-circle-outline (close, circle)")] CloseCircleOutlineMD,
        [Description("ios-close-circle (circle, close)")] CloseCircleiOS,
        [Description("md-close-circle (circle, close)")] CloseCircleMD,
        [Description("ios-close (close, delete, remove)")] CloseiOS,
        [Description("md-close (close, delete, remove)")] CloseMD,
        [Description("ios-cloud-circle (circle, cloud)")] CloudCircleiOS,
        [Description("md-cloud-circle (circle, cloud)")] CloudCircleMD,
        [Description("ios-cloud-done (cloud, done)")] CloudDoneiOS,
        [Description("md-cloud-done (cloud, done)")] CloudDoneMD,
        [Description("ios-cloud-download (cloud, download, storage)")] CloudDownloadiOS,
        [Description("md-cloud-download (cloud, download, storage)")] CloudDownloadMD,
        [Description("ios-cloud-outline (cloud)")] CloudOutlineiOS,
        [Description("md-cloud-outline (cloud)")] CloudOutlineMD,
        [Description("ios-cloud-upload (cloud, storage, upload)")] CloudUploadiOS,
        [Description("md-cloud-upload (cloud, storage, upload)")] CloudUploadMD,
        [Description("ios-cloud (cloud, storage, weather, whether)")] CloudiOS,
        [Description("md-cloud (cloud, storage, weather, whether)")] CloudMD,
        [Description("ios-cloudy-night (cloudy, night, overcast, weather, whether)")] CloudyNightiOS,
        [Description("md-cloudy-night (cloudy, night, overcast, weather, whether)")] CloudyNightMD,
        [Description("ios-cloudy (cloudy, overcast, weather, whether)")] CloudyiOS,
        [Description("md-cloudy (cloudy, overcast, weather, whether)")] CloudyMD,
        [Description("ios-code-download (code, develop, download, hacker, program)")] CodeDownloadiOS,
        [Description("md-code-download (code, develop, download, hacker, program)")] CodeDownloadMD,
        [Description("ios-code-working (code, develop, hacker, program, working)")] CodeWorkingiOS,
        [Description("md-code-working (code, develop, hacker, program, working)")] CodeWorkingMD,
        [Description("ios-code (code, develop, hacker, program)")] CodeiOS,
        [Description("md-code (code, develop, hacker, program)")] CodeMD,
        [Description("ios-cog (cog, gear, options, settings)")] CogiOS,
        [Description("md-cog (cog, gear, options, settings)")] CogMD,
        [Description("ios-color-fill (color, fill)")] ColorFilliOS,
        [Description("md-color-fill (color, fill)")] ColorFillMD,
        [Description("ios-color-filter (color, filter)")] ColorFilteriOS,
        [Description("md-color-filter (color, filter)")] ColorFilterMD,
        [Description("ios-color-palette (color, palette)")] ColorPaletteiOS,
        [Description("md-color-palette (color, palette)")] ColorPaletteMD,
        [Description("ios-color-wand (color, wand)")] ColorWandiOS,
        [Description("md-color-wand (color, wand)")] ColorWandMD,
        [Description("ios-compass (compass, directions, location, navigation)")] CompassiOS,
        [Description("md-compass (compass, directions, location, navigation)")] CompassMD,
        [Description("ios-construct (construct)")] ConstructiOS,
        [Description("md-construct (construct)")] ConstructMD,
        [Description("ios-contact (contact, people, users)")] ContactiOS,
        [Description("md-contact (contact, people, users)")] ContactMD,
        [Description("ios-contacts (contacts, people, users)")] ContactsiOS,
        [Description("md-contacts (contacts, people, users)")] ContactsMD,
        [Description("ios-contract (contract)")] ContractiOS,
        [Description("md-contract (contract)")] ContractMD,
        [Description("ios-contrast (contrast, dark, images, levels, light, settings)")] ContrastiOS,
        [Description("md-contrast (contrast, dark, images, levels, light, settings)")] ContrastMD,
        [Description("ios-copy (copy, duplicate, paper)")] CopyiOS,
        [Description("md-copy (copy, duplicate, paper)")] CopyMD,
        [Description("ios-create (create, edit)")] CreateiOS,
        [Description("md-create (create, edit)")] CreateMD,
        [Description("ios-crop (crop)")] CropiOS,
        [Description("md-crop (crop)")] CropMD,
        [Description("ios-cube (box, container, cube, square)")] CubeiOS,
        [Description("md-cube (box, container, cube, square)")] CubeMD,
        [Description("ios-cut (cut)")] CutiOS,
        [Description("md-cut (cut)")] CutMD,
        [Description("ios-desktop (desktop)")] DesktopiOS,
        [Description("md-desktop (desktop)")] DesktopMD,
        [Description("ios-disc (cd, disc, vinyl)")] DisciOS,
        [Description("md-disc (cd, disc, vinyl)")] DiscMD,
        [Description("ios-document (document, file, paper)")] DocumentiOS,
        [Description("md-document (document, file, paper)")] DocumentMD,
        [Description("ios-done-all (all, done)")] DoneAlliOS,
        [Description("md-done-all (all, done)")] DoneAllMD,
        [Description("ios-download (download, export)")] DownloadiOS,
        [Description("md-download (download, export)")] DownloadMD,
        [Description("ios-easel (easel)")] EaseliOS,
        [Description("md-easel (easel)")] EaselMD,
        [Description("ios-egg (baby, bird, birth, egg, twitter)")] EggiOS,
        [Description("md-egg (baby, bird, birth, egg, twitter)")] EggMD,
        [Description("ios-exit (exit)")] ExitiOS,
        [Description("md-exit (exit)")] ExitMD,
        [Description("ios-expand (expand, resize)")] ExpandiOS,
        [Description("md-expand (expand, resize)")] ExpandMD,
        [Description("ios-eye-off (eye, off)")] EyeOffiOS,
        [Description("md-eye-off (eye, off)")] EyeOffMD,
        [Description("ios-eye (exposed, eye, look, see, view)")] EyeiOS,
        [Description("md-eye (exposed, eye, look, see, view)")] EyeMD,
        [Description("ios-fastforward (fastforward, jump, next, skip)")] FastforwardiOS,
        [Description("md-fastforward (fastforward, jump, next, skip)")] FastforwardMD,
        [Description("ios-female (dudette, female, girl, lady)")] FemaleiOS,
        [Description("md-female (dudette, female, girl, lady)")] FemaleMD,
        [Description("ios-filing (archive, filing)")] FilingiOS,
        [Description("md-filing (archive, filing)")] FilingMD,
        [Description("ios-film (film)")] FilmiOS,
        [Description("md-film (film)")] FilmMD,
        [Description("ios-finger-print (finger, print)")] FingerPrintiOS,
        [Description("md-finger-print (finger, print)")] FingerPrintMD,
        [Description("ios-fitness (fitness)")] FitnessiOS,
        [Description("md-fitness (fitness)")] FitnessMD,
        [Description("ios-flag (favorite, flag, marker)")] FlagiOS,
        [Description("md-flag (favorite, flag, marker)")] FlagMD,
        [Description("ios-flame (fire, flame, heat, hot)")] FlameiOS,
        [Description("md-flame (fire, flame, heat, hot)")] FlameMD,
        [Description("ios-flash-off (flash)")] FlashOffiOS,
        [Description("md-flash-off (flash)")] FlashOffMD,
        [Description("ios-flash (flash, lightning, weather, whether)")] FlashiOS,
        [Description("md-flash (flash, lightning, weather, whether)")] FlashMD,
        [Description("ios-flashlight (flashlight)")] FlashlightiOS,
        [Description("md-flashlight (flashlight)")] FlashlightMD,
        [Description("ios-flask (bubbles, flask, mixture, potion)")] FlaskiOS,
        [Description("md-flask (bubbles, flask, mixture, potion)")] FlaskMD,
        [Description("ios-flower (flower)")] FloweriOS,
        [Description("md-flower (flower)")] FlowerMD,
        [Description("ios-folder-open (folder, open)")] FolderOpeniOS,
        [Description("md-folder-open (folder, open)")] FolderOpenMD,
        [Description("ios-folder (file, folder)")] FolderiOS,
        [Description("md-folder (file, folder)")] FolderMD,
        [Description("ios-football (football, soccer)")] FootballiOS,
        [Description("md-football (football, soccer)")] FootballMD,
        [Description("ios-funnel (funnel, sort)")] FunneliOS,
        [Description("md-funnel (funnel, sort)")] FunnelMD,
        [Description("ios-gift (gift)")] GiftiOS,
        [Description("md-gift (gift)")] GiftMD,
        [Description("ios-git-branch (branch, git)")] GitBranchiOS,
        [Description("md-git-branch (branch, git)")] GitBranchMD,
        [Description("ios-git-commit (commit, git)")] GitCommitiOS,
        [Description("md-git-commit (commit, git)")] GitCommitMD,
        [Description("ios-git-compare (compare, git)")] GitCompareiOS,
        [Description("md-git-compare (compare, git)")] GitCompareMD,
        [Description("ios-git-merge (git, merge)")] GitMergeiOS,
        [Description("md-git-merge (git, merge)")] GitMergeMD,
        [Description("ios-git-network (git, network)")] GitNetworkiOS,
        [Description("md-git-network (git, network)")] GitNetworkMD,
        [Description("ios-git-pull-request (git, pull, request)")] GitPullRequestiOS,
        [Description("md-git-pull-request (git, pull, request)")] GitPullRequestMD,
        [Description("ios-glasses (glasses, look, reading, see, steve)")] GlassesiOS,
        [Description("md-glasses (glasses, look, reading, see, steve)")] GlassesMD,
        [Description("ios-globe (globe, internet, world)")] GlobeiOS,
        [Description("md-globe (globe, internet, world)")] GlobeMD,
        [Description("ios-grid (grid, menu)")] GridiOS,
        [Description("md-grid (grid, menu)")] GridMD,
        [Description("ios-hammer (hammer, options, settings, tools)")] HammeriOS,
        [Description("md-hammer (hammer, options, settings, tools)")] HammerMD,
        [Description("ios-hand (hand, stop)")] HandiOS,
        [Description("md-hand (hand, stop)")] HandMD,
        [Description("ios-happy (fun, good, happy, like, smile, yes)")] HappyiOS,
        [Description("md-happy (fun, good, happy, like, smile, yes)")] HappyMD,
        [Description("ios-headset (headset)")] HeadsetiOS,
        [Description("md-headset (headset)")] HeadsetMD,
        [Description("ios-heart (heart, love)")] HeartiOS,
        [Description("md-heart (heart, love)")] HeartMD,
        [Description("ios-heart-dislike (dislike, heart, love)")] HeartDislikeiOS,
        [Description("md-heart-dislike (dislike, heart, love)")] HeartDislikeMD,
        [Description("ios-heart-empty (empty, heart, love)")] HeartEmptyiOS,
        [Description("md-heart-empty (empty, heart, love)")] HeartEmptyMD,
        [Description("ios-heart-half (half, heart, love)")] HeartHalfiOS,
        [Description("md-heart-half (half, heart, love)")] HeartHalfMD,
        [Description("ios-help-buoy (?, buoy, help, question)")] HelpBuoyiOS,
        [Description("md-help-buoy (?, buoy, help, question)")] HelpBuoyMD,
        [Description("ios-help-circle-outline (help)")] HelpCircleOutlineiOS,
        [Description("md-help-circle-outline (help)")] HelpCircleOutlineMD,
        [Description("ios-help-circle (circle, help)")] HelpCircleiOS,
        [Description("md-help-circle (circle, help)")] HelpCircleMD,
        [Description("ios-help (?, help, information, question)")] HelpiOS,
        [Description("md-help (?, help, information, question)")] HelpMD,
        [Description("ios-home (home, house)")] HomeiOS,
        [Description("md-home (home, house)")] HomeMD,
        [Description("ios-hourglass (hourglass, time)")] HourglassiOS,
        [Description("md-hourglass (hourglass, time)")] HourglassMD,
        [Description("ios-ice-cream (cream, ice)")] IceCreamiOS,
        [Description("md-ice-cream (cream, ice)")] IceCreamMD,
        [Description("ios-image (camera, image, photo)")] ImageiOS,
        [Description("md-image (camera, image, photo)")] ImageMD,
        [Description("ios-images (images, photo)")] ImagesiOS,
        [Description("md-images (images, photo)")] ImagesMD,
        [Description("ios-infinite (forever, infinite, loop)")] InfiniteiOS,
        [Description("md-infinite (forever, infinite, loop)")] InfiniteMD,
        [Description("ios-information-circle-outline (information)")] InformationCircleOutlineiOS,
        [Description("md-information-circle-outline (information)")] InformationCircleOutlineMD,
        [Description("ios-information-circle (circle, information)")] InformationCircleiOS,
        [Description("md-information-circle (circle, information)")] InformationCircleMD,
        [Description("ios-information (help, information, knowledge)")] InformationiOS,
        [Description("md-information (help, information, knowledge)")] InformationMD,
        [Description("ios-jet (fly, jet, plane)")] JetiOS,
        [Description("md-jet (fly, jet, plane)")] JetMD,
        [Description("ios-journal (journal)")] JournaliOS,
        [Description("md-journal (journal)")] JournalMD,
        [Description("ios-key (access, key)")] KeyiOS,
        [Description("md-key (access, key)")] KeyMD,
        [Description("ios-keypad (keypad, type)")] KeypadiOS,
        [Description("md-keypad (keypad, type)")] KeypadMD,
        [Description("ios-laptop (apple, laptop, macbook, osx)")] LaptopiOS,
        [Description("md-laptop (apple, laptop, macbook, osx)")] LaptopMD,
        [Description("ios-leaf (green, leaf, nature, plant, recycle)")] LeafiOS,
        [Description("md-leaf (green, leaf, nature, plant, recycle)")] LeafMD,
        [Description("ios-link (anchor, attach, chain, href, link)")] LinkiOS,
        [Description("md-link (anchor, attach, chain, href, link)")] LinkMD,
        [Description("ios-list-box (box, list)")] ListBoxiOS,
        [Description("md-list-box (box, list)")] ListBoxMD,
        [Description("ios-list (list)")] ListiOS,
        [Description("md-list (list)")] ListMD,
        [Description("ios-locate (gps, locate, maps, navigate)")] LocateiOS,
        [Description("md-locate (gps, locate, maps, navigate)")] LocateMD,
        [Description("ios-lock (lock)")] LockiOS,
        [Description("md-lock (lock)")] LockMD,
        [Description("ios-log-in (in, log, signin)")] LogIniOS,
        [Description("md-log-in (in, log, signin)")] LogInMD,
        [Description("ios-log-out (log, out, signout)")] LogOutiOS,
        [Description("md-log-out (log, out, signout)")] LogOutMD,
        [Description("ios-magnet (attraction, magnet, sticky)")] MagnetiOS,
        [Description("md-magnet (attraction, magnet, sticky)")] MagnetMD,
        [Description("ios-mail-open (mail, open)")] MailOpeniOS,
        [Description("md-mail-open (mail, open)")] MailOpenMD,
        [Description("ios-mail-unread (mail, unread)")] MailUnreadiOS,
        [Description("md-mail-unread (mail, unread)")] MailUnreadMD,
        [Description("ios-mail (email, mail)")] MailiOS,
        [Description("md-mail (email, mail)")] MailMD,
        [Description("ios-male (boy, dude, guy, male, male)")] MaleiOS,
        [Description("md-male (boy, dude, guy, male, male)")] MaleMD,
        [Description("ios-man (boy, dude, guy, male, man)")] ManiOS,
        [Description("md-man (boy, dude, guy, male, man)")] ManMD,
        [Description("ios-map (gps, map, navigation, pin)")] MapiOS,
        [Description("md-map (gps, map, navigation, pin)")] MapMD,
        [Description("ios-medal (medal)")] MedaliOS,
        [Description("md-medal (medal)")] MedalMD,
        [Description("ios-medical (medical)")] MedicaliOS,
        [Description("md-medical (medical)")] MedicalMD,
        [Description("ios-medkit (case, disease, firstaid, health, medkit, sick)")] MedkitiOS,
        [Description("md-medkit (case, disease, firstaid, health, medkit, sick)")] MedkitMD,
        [Description("ios-megaphone (megaphone)")] MegaphoneiOS,
        [Description("md-megaphone (megaphone)")] MegaphoneMD,
        [Description("ios-menu (menu)")] MenuiOS,
        [Description("md-menu (menu)")] MenuMD,
        [Description("ios-mic-off (mic, noise, off, sound, speaker, talk)")] MicOffiOS,
        [Description("md-mic-off (mic, noise, off, sound, speaker, talk)")] MicOffMD,
        [Description("ios-mic (mic, noise, sound, speaker, talk)")] MiciOS,
        [Description("md-mic (mic, noise, sound, speaker, talk)")] MicMD,
        [Description("ios-microphone (microphone, music, noise, record, sound, speak)")] MicrophoneiOS,
        [Description("md-microphone (microphone, music, noise, record, sound, speak)")] MicrophoneMD,
        [Description("ios-moon (dark, moon, night, sky)")] MooniOS,
        [Description("md-moon (dark, moon, night, sky)")] MoonMD,
        [Description("ios-more (more, options)")] MoreiOS,
        [Description("md-more (more, options)")] MoreMD,
        [Description("ios-move (move)")] MoveiOS,
        [Description("md-move (move)")] MoveMD,
        [Description("ios-musical-note (listening, musical, noise, note, play, sound)")] MusicalNoteiOS,
        [Description("md-musical-note (listening, musical, noise, note, play, sound)")] MusicalNoteMD,
        [Description("ios-musical-notes (listening, musical, noise, notes, play, sound)")] MusicalNotesiOS,
        [Description("md-musical-notes (listening, musical, noise, notes, play, sound)")] MusicalNotesMD,
        [Description("ios-navigate (gps, location, map, navigate, pin)")] NavigateiOS,
        [Description("md-navigate (gps, location, map, navigate, pin)")] NavigateMD,
        [Description("ios-notifications-off (notifications, off)")] NotificationsOffiOS,
        [Description("md-notifications-off (notifications, off)")] NotificationsOffMD,
        [Description("ios-notifications-outline (notifications)")] NotificationsOutlineiOS,
        [Description("md-notifications-outline (notifications)")] NotificationsOutlineMD,
        [Description("ios-notifications (notifications)")] NotificationsiOS,
        [Description("md-notifications (notifications)")] NotificationsMD,
        [Description("ios-nuclear (danger, hazard, nuclear, warning)")] NucleariOS,
        [Description("md-nuclear (danger, hazard, nuclear, warning)")] NuclearMD,
        [Description("ios-nutrition (nutrition)")] NutritioniOS,
        [Description("md-nutrition (nutrition)")] NutritionMD,
        [Description("ios-open (open)")] OpeniOS,
        [Description("md-open (open)")] OpenMD,
        [Description("ios-options (options)")] OptionsiOS,
        [Description("md-options (options)")] OptionsMD,
        [Description("ios-outlet (computer, digital, electricity, outlet)")] OutletiOS,
        [Description("md-outlet (computer, digital, electricity, outlet)")] OutletMD,
        [Description("ios-paper-plane (paper, plane)")] PaperPlaneiOS,
        [Description("md-paper-plane (paper, plane)")] PaperPlaneMD,
        [Description("ios-paper (feed, paper, paper)")] PaperiOS,
        [Description("md-paper (feed, paper, paper)")] PaperMD,
        [Description("ios-partly-sunny (partly, sunny)")] PartlySunnyiOS,
        [Description("md-partly-sunny (partly, sunny)")] PartlySunnyMD,
        [Description("ios-pause (break, freeze, hold, music, pause)")] PauseiOS,
        [Description("md-pause (break, freeze, hold, music, pause)")] PauseMD,
        [Description("ios-paw (paw)")] PawiOS,
        [Description("md-paw (paw)")] PawMD,
        [Description("ios-people (head, human, people, person, stalker, users)")] PeopleiOS,
        [Description("md-people (head, human, people, person, stalker, users)")] PeopleMD,
        [Description("ios-person-add (add, head, human, member, new, person, staff, users)")] PersonAddiOS,
        [Description("md-person-add (add, head, human, member, new, person, staff, users)")] PersonAddMD,
        [Description("ios-person (head, human, person, staff, users)")] PersoniOS,
        [Description("md-person (head, human, person, staff, users)")] PersonMD,
        [Description("ios-phone-landscape (landscape, phone)")] PhoneLandscapeiOS,
        [Description("md-phone-landscape (landscape, phone)")] PhoneLandscapeMD,
        [Description("ios-phone-portrait (phone, portrait)")] PhonePortraitiOS,
        [Description("md-phone-portrait (phone, portrait)")] PhonePortraitMD,
        [Description("ios-photos (images, photos, square, stills)")] PhotosiOS,
        [Description("md-photos (images, photos, square, stills)")] PhotosMD,
        [Description("ios-pie (cog, options, pie, settings)")] PieiOS,
        [Description("md-pie (cog, options, pie, settings)")] PieMD,
        [Description("ios-pin (gps, location, navigation, pin)")] PiniOS,
        [Description("md-pin (gps, location, navigation, pin)")] PinMD,
        [Description("ios-pint (pint)")] PintiOS,
        [Description("md-pint (pint)")] PintMD,
        [Description("ios-pizza (drink, eat, food, pizza)")] PizzaiOS,
        [Description("md-pizza (drink, eat, food, pizza)")] PizzaMD,
        [Description("ios-planet (globe, home, nature, planet, space, world)")] PlanetiOS,
        [Description("md-planet (globe, home, nature, planet, space, world)")] PlanetMD,
        [Description("ios-play-circle (play)")] PlayCircleiOS,
        [Description("md-play-circle (play)")] PlayCircleMD,
        [Description("ios-play (arrow, music, play, right, watch)")] PlayiOS,
        [Description("md-play (arrow, music, play, right, watch)")] PlayMD,
        [Description("ios-podium (award, compete, competition, lose, podium, win)")] PodiumiOS,
        [Description("md-podium (award, compete, competition, lose, podium, win)")] PodiumMD,
        [Description("ios-power (off, on, power)")] PoweriOS,
        [Description("md-power (off, on, power)")] PowerMD,
        [Description("ios-pricetag ($, commerce, items, money, pricetag, shopping)")] PricetagiOS,
        [Description("md-pricetag ($, commerce, items, money, pricetag, shopping)")] PricetagMD,
        [Description("ios-pricetags ($, commerce, items, money, pricetags, shopping)")] PricetagsiOS,
        [Description("md-pricetags ($, commerce, items, money, pricetags, shopping)")] PricetagsMD,
        [Description("ios-print (print)")] PrintiOS,
        [Description("md-print (print)")] PrintMD,
        [Description("ios-pulse (hot, live, pulse, rate)")] PulseiOS,
        [Description("md-pulse (hot, live, pulse, rate)")] PulseMD,
        [Description("ios-qr-scanner (qr, reader, scanner)")] QrScanneriOS,
        [Description("md-qr-scanner (qr, reader, scanner)")] QrScannerMD,
        [Description("ios-quote (chat, quotation, quote)")] QuoteiOS,
        [Description("md-quote (chat, quotation, quote)")] QuoteMD,
        [Description("ios-radio-button-off (button, circle, off, radio)")] RadioButtonOffiOS,
        [Description("md-radio-button-off (button, circle, off, radio)")] RadioButtonOffMD,
        [Description("ios-radio-button-on (button, circle, on, radio)")] RadioButtonOniOS,
        [Description("md-radio-button-on (button, circle, on, radio)")] RadioButtonOnMD,
        [Description("ios-radio (music, radio)")] RadioiOS,
        [Description("md-radio (music, radio)")] RadioMD,
        [Description("ios-rainy (cloud, rainy, water, weather, whether)")] RainyiOS,
        [Description("md-rainy (cloud, rainy, water, weather, whether)")] RainyMD,
        [Description("ios-recording (film, recording, tape, voicemail)")] RecordingiOS,
        [Description("md-recording (film, recording, tape, voicemail)")] RecordingMD,
        [Description("ios-redo (forward, redo)")] RedoiOS,
        [Description("md-redo (forward, redo)")] RedoMD,
        [Description("ios-refresh-circle (circle, refresh)")] RefreshCircleiOS,
        [Description("md-refresh-circle (circle, refresh)")] RefreshCircleMD,
        [Description("ios-refresh (refresh, reload, renew, reset)")] RefreshiOS,
        [Description("md-refresh (refresh, reload, renew, reset)")] RefreshMD,
        [Description("ios-remove-circle-outline (circle, minus, remove)")] RemoveCircleOutlineiOS,
        [Description("md-remove-circle-outline (circle, minus, remove)")] RemoveCircleOutlineMD,
        [Description("ios-remove-circle (circle, minus, remove)")] RemoveCircleiOS,
        [Description("md-remove-circle (circle, minus, remove)")] RemoveCircleMD,
        [Description("ios-remove (minus, remove, subtract)")] RemoveiOS,
        [Description("md-remove (minus, remove, subtract)")] RemoveMD,
        [Description("ios-reorder (reorder)")] ReorderiOS,
        [Description("md-reorder (reorder)")] ReorderMD,
        [Description("ios-repeat (repeat)")] RepeatiOS,
        [Description("md-repeat (repeat)")] RepeatMD,
        [Description("ios-resize (resize)")] ResizeiOS,
        [Description("md-resize (resize)")] ResizeMD,
        [Description("ios-restaurant (eat, restaurant)")] RestaurantiOS,
        [Description("md-restaurant (eat, restaurant)")] RestaurantMD,
        [Description("ios-return-left (left, return)")] ReturnLeftiOS,
        [Description("md-return-left (left, return)")] ReturnLeftMD,
        [Description("ios-return-right (return, right)")] ReturnRightiOS,
        [Description("md-return-right (return, right)")] ReturnRightMD,
        [Description("ios-reverse-camera (camera, picture, reverse)")] ReverseCameraiOS,
        [Description("md-reverse-camera (camera, picture, reverse)")] ReverseCameraMD,
        [Description("ios-rewind (back, music, previous, rewind)")] RewindiOS,
        [Description("md-rewind (back, music, previous, rewind)")] RewindMD,
        [Description("ios-ribbon (ribbon)")] RibboniOS,
        [Description("md-ribbon (ribbon)")] RibbonMD,
        [Description("ios-rocket (rocket)")] RocketiOS,
        [Description("md-rocket (rocket)")] RocketMD,
        [Description("ios-rose (flower, rose)")] RoseiOS,
        [Description("md-rose (flower, rose)")] RoseMD,
        [Description("ios-sad (bad, cry, no, sad)")] SadiOS,
        [Description("md-sad (bad, cry, no, sad)")] SadMD,
        [Description("ios-save (save)")] SaveiOS,
        [Description("md-save (save)")] SaveMD,
        [Description("ios-school (school)")] SchooliOS,
        [Description("md-school (school)")] SchoolMD,
        [Description("ios-search (glass, magnifying, search)")] SearchiOS,
        [Description("md-search (glass, magnifying, search)")] SearchMD,
        [Description("ios-send (email, paper, send)")] SendiOS,
        [Description("md-send (email, paper, send)")] SendMD,
        [Description("ios-settings (options, settings)")] SettingsiOS,
        [Description("md-settings (options, settings)")] SettingsMD,
        [Description("ios-share-alt (alt, share)")] ShareAltiOS,
        [Description("md-share-alt (alt, share)")] ShareAltMD,
        [Description("ios-share (share)")] ShareiOS,
        [Description("md-share (share)")] ShareMD,
        [Description("ios-shirt (shirt)")] ShirtiOS,
        [Description("md-shirt (shirt)")] ShirtMD,
        [Description("ios-shuffle (random, shuffle)")] ShuffleiOS,
        [Description("md-shuffle (random, shuffle)")] ShuffleMD,
        [Description("ios-skip-backward (backward, music, previous, skip)")] SkipBackwardiOS,
        [Description("md-skip-backward (backward, music, previous, skip)")] SkipBackwardMD,
        [Description("ios-skip-forward (forward, music, next, skip)")] SkipForwardiOS,
        [Description("md-skip-forward (forward, music, next, skip)")] SkipForwardMD,
        [Description("ios-snow (cold, snow)")] SnowiOS,
        [Description("md-snow (cold, snow)")] SnowMD,
        [Description("ios-speedometer (drive, level, speed, speedometer)")] SpeedometeriOS,
        [Description("md-speedometer (drive, level, speed, speedometer)")] SpeedometerMD,
        [Description("ios-square-outline (square)")] SquareOutlineiOS,
        [Description("md-square-outline (square)")] SquareOutlineMD,
        [Description("ios-square (square)")] SquareiOS,
        [Description("md-square (square)")] SquareMD,
        [Description("ios-star-half (favorite, half, rate, star)")] StarHalfiOS,
        [Description("md-star-half (favorite, half, rate, star)")] StarHalfMD,
        [Description("ios-star-outline (star)")] StarOutlineiOS,
        [Description("md-star-outline (star)")] StarOutlineMD,
        [Description("ios-star (favorite, star)")] StariOS,
        [Description("md-star (favorite, star)")] StarMD,
        [Description("ios-stats (stats)")] StatsiOS,
        [Description("md-stats (stats)")] StatsMD,
        [Description("ios-stopwatch (stopwatch, time)")] StopwatchiOS,
        [Description("md-stopwatch (stopwatch, time)")] StopwatchMD,
        [Description("ios-subway (subway)")] SubwayiOS,
        [Description("md-subway (subway)")] SubwayMD,
        [Description("ios-sunny (light, sky, sunny, weather, whether)")] SunnyiOS,
        [Description("md-sunny (light, sky, sunny, weather, whether)")] SunnyMD,
        [Description("ios-swap (swap)")] SwapiOS,
        [Description("md-swap (swap)")] SwapMD,
        [Description("ios-switch (switch)")] SwitchiOS,
        [Description("md-switch (switch)")] SwitchMD,
        [Description("ios-sync (sync)")] SynciOS,
        [Description("md-sync (sync)")] SyncMD,
        [Description("ios-tablet-landscape (landscape, tablet)")] TabletLandscapeiOS,
        [Description("md-tablet-landscape (landscape, tablet)")] TabletLandscapeMD,
        [Description("ios-tablet-portrait (portrait, tablet)")] TabletPortraitiOS,
        [Description("md-tablet-portrait (portrait, tablet)")] TabletPortraitMD,
        [Description("ios-tennisball (tennisball)")] TennisballiOS,
        [Description("md-tennisball (tennisball)")] TennisballMD,
        [Description("ios-text (text)")] TextiOS,
        [Description("md-text (text)")] TextMD,
        [Description("ios-thermometer (cold, heat, hot, mercury, temperature, thermometer)")] ThermometeriOS,
        [Description("md-thermometer (cold, heat, hot, mercury, temperature, thermometer)")] ThermometerMD,
        [Description("ios-thumbs-down (down, thumbs)")] ThumbsDowniOS,
        [Description("md-thumbs-down (down, thumbs)")] ThumbsDownMD,
        [Description("ios-thumbs-up (thumbs, up)")] ThumbsUpiOS,
        [Description("md-thumbs-up (thumbs, up)")] ThumbsUpMD,
        [Description("ios-thunderstorm (cloudy, lightning, overcast, rain, sky, storm, thunderstorm, weather, whether)")] ThunderstormiOS,
        [Description("md-thunderstorm (cloudy, lightning, overcast, rain, sky, storm, thunderstorm, weather, whether)")] ThunderstormMD,
        [Description("ios-time (clock, hour, minute, second, time, watch)")] TimeiOS,
        [Description("md-time (clock, hour, minute, second, time, watch)")] TimeMD,
        [Description("ios-timer (clock, timer)")] TimeriOS,
        [Description("md-timer (clock, timer)")] TimerMD,
        [Description("ios-today (today)")] TodayiOS,
        [Description("md-today (today)")] TodayMD,
        [Description("ios-train (train)")] TrainiOS,
        [Description("md-train (train)")] TrainMD,
        [Description("ios-transgender (transgender)")] TransgenderiOS,
        [Description("md-transgender (transgender)")] TransgenderMD,
        [Description("ios-trash (close, delete, remove, trash)")] TrashiOS,
        [Description("md-trash (close, delete, remove, trash)")] TrashMD,
        [Description("ios-trending-down (down, trending)")] TrendingDowniOS,
        [Description("md-trending-down (down, trending)")] TrendingDownMD,
        [Description("ios-trending-up (trending, up)")] TrendingUpiOS,
        [Description("md-trending-up (trending, up)")] TrendingUpMD,
        [Description("ios-trophy (award, compete, competition, lose, trophy, win)")] TrophyiOS,
        [Description("md-trophy (award, compete, competition, lose, trophy, win)")] TrophyMD,
        [Description("ios-tv (television, tv)")] TviOS,
        [Description("md-tv (television, tv)")] TvMD,
        [Description("ios-umbrella (dry, rain, shelter, umbrella, wet)")] UmbrellaiOS,
        [Description("md-umbrella (dry, rain, shelter, umbrella, wet)")] UmbrellaMD,
        [Description("ios-undo (reply, undo)")] UndoiOS,
        [Description("md-undo (reply, undo)")] UndoMD,
        [Description("ios-unlock (unlock)")] UnlockiOS,
        [Description("md-unlock (unlock)")] UnlockMD,
        [Description("ios-videocam (camera, film, movie, videocam)")] VideocamiOS,
        [Description("md-videocam (camera, film, movie, videocam)")] VideocamMD,
        [Description("ios-volume-high (volume)")] VolumeHighiOS,
        [Description("md-volume-high (volume)")] VolumeHighMD,
        [Description("ios-volume-low (volume)")] VolumeLowiOS,
        [Description("md-volume-low (volume)")] VolumeLowMD,
        [Description("ios-volume-mute (mute, sound, volume)")] VolumeMuteiOS,
        [Description("md-volume-mute (mute, sound, volume)")] VolumeMuteMD,
        [Description("ios-volume-off (off, volume)")] VolumeOffiOS,
        [Description("md-volume-off (off, volume)")] VolumeOffMD,
        [Description("ios-wallet (cash, money, wallet)")] WalletiOS,
        [Description("md-wallet (cash, money, wallet)")] WalletMD,
        [Description("ios-walk (walk)")] WalkiOS,
        [Description("md-walk (walk)")] WalkMD,
        [Description("ios-warning (warning)")] WarningiOS,
        [Description("md-warning (warning)")] WarningMD,
        [Description("ios-watch (watch)")] WatchiOS,
        [Description("md-watch (watch)")] WatchMD,
        [Description("ios-water (water)")] WateriOS,
        [Description("md-water (water)")] WaterMD,
        [Description("ios-wifi (bars, connection, internet, wifi)")] WifiiOS,
        [Description("md-wifi (bars, connection, internet, wifi)")] WifiMD,
        [Description("ios-wine (glass, wine)")] WineiOS,
        [Description("md-wine (glass, wine)")] WineMD,
        [Description("ios-woman (dudette, female, girl, lady, woman)")] WomaniOS,
        [Description("md-woman (dudette, female, girl, lady, woman)")] WomanMD,
        [Description("logo-android (android)")] LogoAndroid,
        [Description("logo-angular (angular)")] LogoAngular,
        [Description("logo-apple (apple)")] LogoApple,
        [Description("logo-bitbucket (bitbucket)")] LogoBitbucket,
        [Description("logo-bitcoin (bitcoin)")] LogoBitcoin,
        [Description("logo-buffer (buffer)")] LogoBuffer,
        [Description("logo-chrome (chrome)")] LogoChrome,
        [Description("logo-closed-captioning (closed-captioning)")] LogoClosedCaptioning,
        [Description("logo-codepen (codepen)")] LogoCodepen,
        [Description("logo-css3 (css3)")] LogoCss3,
        [Description("logo-designernews (designernews)")] LogoDesignernews,
        [Description("logo-dribbble (dribbble)")] LogoDribbble,
        [Description("logo-dropbox (dropbox)")] LogoDropbox,
        [Description("logo-euro (euro)")] LogoEuro,
        [Description("logo-facebook (facebook)")] LogoFacebook,
        [Description("logo-flickr (flickr)")] LogoFlickr,
        [Description("logo-foursquare (foursquare)")] LogoFoursquare,
        [Description("logo-freebsd-devil (freebsd-devil)")] LogoFreebsdDevil,
        [Description("logo-game-controller-a (controller, game)")] LogoGameControllerA,
        [Description("logo-game-controller-b (controller, game)")] LogoGameControllerB,
        [Description("logo-github (github)")] LogoGithub,
        [Description("logo-google (google)")] LogoGoogle,
        [Description("logo-googleplus (googleplus)")] LogoGoogleplus,
        [Description("logo-hackernews (hackernews)")] LogoHackernews,
        [Description("logo-html5 (html5)")] LogoHtml5,
        [Description("logo-instagram (instagram)")] LogoInstagram,
        [Description("logo-ionic (ionic)")] LogoIonic,
        [Description("logo-ionitron (ionitron)")] LogoIonitron,
        [Description("logo-javascript (javascript)")] LogoJavascript,
        [Description("logo-linkedin (linkedin)")] LogoLinkedin,
        [Description("logo-markdown (markdown)")] LogoMarkdown,
        [Description("logo-model-s (car, model-s, tesla)")] LogoModelS,
        [Description("logo-no-smoking (no-smoking)")] LogoNoSmoking,
        [Description("logo-nodejs (nodejs)")] LogoNodejs,
        [Description("logo-npm (npm)")] LogoNpm,
        [Description("logo-octocat (octocat)")] LogoOctocat,
        [Description("logo-pinterest (pinterest)")] LogoPinterest,
        [Description("logo-playstation (playstation)")] LogoPlaystation,
        [Description("logo-polymer (polymer)")] LogoPolymer,
        [Description("logo-python (python)")] LogoPython,
        [Description("logo-reddit (reddit)")] LogoReddit,
        [Description("logo-rss (rss)")] LogoRss,
        [Description("logo-sass (sass)")] LogoSass,
        [Description("logo-skype (skype)")] LogoSkype,
        [Description("logo-slack (slack)")] LogoSlack,
        [Description("logo-snapchat (snapchat)")] LogoSnapchat,
        [Description("logo-steam (steam)")] LogoSteam,
        [Description("logo-tumblr (tumblr)")] LogoTumblr,
        [Description("logo-tux (tux)")] LogoTux,
        [Description("logo-twitch (twitch)")] LogoTwitch,
        [Description("logo-twitter (twitter)")] LogoTwitter,
        [Description("logo-usd ($, usd)")] LogoUsd,
        [Description("logo-vimeo (vimeo)")] LogoVimeo,
        [Description("logo-vk (vk)")] LogoVk,
        [Description("logo-whatsapp (whatsapp)")] LogoWhatsapp,
        [Description("logo-windows (microsoft, windows)")] LogoWindows,
        [Description("logo-wordpress (wordpress)")] LogoWordpress,
        [Description("logo-xbox (xbox)")] LogoXbox,
        [Description("logo-xing (xing)")] LogoXing,
        [Description("logo-yahoo (yahoo)")] LogoYahoo,
        [Description("logo-yen (yen)")] LogoYen,
        [Description("logo-youtube (youtube)")] LogoYoutube
    }
}