namespace MahApps.Metro.IconPacks
{
#if !(NETFX_CORE || WINDOWS_UWP)
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconForkAwesome" />.
    /// </summary>
    /// <remarks>
    /// The Fork Awesome font is licensed under the SIL OFL 1.1 (<see><cref>http://scripts.sil.org/OFL</cref></see>). Fork Awesome is a fork based of off Font Awesome 4.7.0 by Dave Gandy.
    /// More info on licenses at <see><cref>https://forkawesome.github.io</cref></see>. Contributions, corrections and requests can be made on GitHub <see><cref>https://github.com/ForkAwesome/Fork-Awesome</cref></see>.
    /// </remarks>
    public enum PackIconForkAwesomeKind
    {
        [Description("Empty placeholder")] None,
        [Description("500px (f26e, Brand Icons)")] _500px,
        [Description("activitypub (f2f2, Brand Icons)")] Activitypub,
        [Description("address-book (f2b9, Web Application Icons)")] AddressBook,
        [Description("address-book-o (f2ba, Web Application Icons)")] AddressBookOutline,
        [Description("address-card (f2bb, Web Application Icons, vcard)")] AddressCard,
        [Description("address-card-o (f2bc, Web Application Icons, vcard-o)")] AddressCardOutline,
        [Description("adjust (f042, Web Application Icons, contrast)")] Adjust,
        [Description("adn (f170, Brand Icons)")] Adn,
        [Description("align-center (f037, Text Editor Icons, middle, text)")] AlignCenter,
        [Description("align-justify (f039, Text Editor Icons, text)")] AlignJustify,
        [Description("align-left (f036, Text Editor Icons, text)")] AlignLeft,
        [Description("align-right (f038, Text Editor Icons, text)")] AlignRight,
        [Description("amazon (f270, Brand Icons)")] Amazon,
        [Description("ambulance (f0f9, Medical Icons, Transportation Icons, help, support, vehicle)")] Ambulance,
        [Description("american-sign-language-interpreting (f2a3, Web Application Icons, Accessibility Icons, asl-interpreting)")] AmericanSignLanguageInterpreting,
        [Description("anchor (f13d, Web Application Icons, link)")] Anchor,
        [Description("android (f17b, Brand Icons, robot)")] Android,
        [Description("angellist (f209, Brand Icons)")] Angellist,
        [Description("angle-double-down (f103, Directional Icons, arrows)")] AngleDoubleDown,
        [Description("angle-double-left (f100, Directional Icons, arrows, back, laquo, previous, quote)")] AngleDoubleLeft,
        [Description("angle-double-right (f101, Directional Icons, arrows, forward, next, quote, raquo)")] AngleDoubleRight,
        [Description("angle-double-up (f102, Directional Icons, arrows)")] AngleDoubleUp,
        [Description("angle-down (f107, Directional Icons, arrow)")] AngleDown,
        [Description("angle-left (f104, Directional Icons, arrow, back, previous)")] AngleLeft,
        [Description("angle-right (f105, Directional Icons, arrow, forward, next)")] AngleRight,
        [Description("angle-up (f106, Directional Icons, arrow)")] AngleUp,
        [Description("apple (f179, Brand Icons, food, osx)")] Apple,
        [Description("archive (f187, Web Application Icons, box, storage)")] Archive,
        [Description("archive-org (f2fc, Brand Icons, link)")] ArchiveOrg,
        [Description("archlinux (f323, Brand Icons)")] Archlinux,
        [Description("area-chart (f1fe, Web Application Icons, Chart Icons, analytics, graph, statistics)")] AreaChart,
        [Description("arrow-circle-down (f0ab, Directional Icons, download)")] ArrowCircleDown,
        [Description("arrow-circle-left (f0a8, Directional Icons, back, previous)")] ArrowCircleLeft,
        [Description("arrow-circle-o-down (f01a, Directional Icons, download)")] ArrowCircleOutlineDown,
        [Description("arrow-circle-o-left (f190, Directional Icons, back, previous)")] ArrowCircleOutlineLeft,
        [Description("arrow-circle-o-right (f18e, Directional Icons, forward, next)")] ArrowCircleOutlineRight,
        [Description("arrow-circle-o-up (f01b, Directional Icons)")] ArrowCircleOutlineUp,
        [Description("arrow-circle-right (f0a9, Directional Icons, forward, next)")] ArrowCircleRight,
        [Description("arrow-circle-up (f0aa, Directional Icons)")] ArrowCircleUp,
        [Description("arrow-down (f063, Directional Icons, download)")] ArrowDown,
        [Description("arrow-left (f060, Directional Icons, back, previous)")] ArrowLeft,
        [Description("arrow-right (f061, Directional Icons, forward, next)")] ArrowRight,
        [Description("arrows (f047, Web Application Icons, Directional Icons, move, reorder, resize)")] Arrows,
        [Description("arrows-alt (f0b2, Video Player Icons, Directional Icons, arrow, bigger, enlarge, expand, fullscreen, move, reorder, resize)")] ArrowsAlt,
        [Description("arrows-h (f07e, Web Application Icons, Directional Icons, resize)")] ArrowsH,
        [Description("arrows-v (f07d, Web Application Icons, Directional Icons, resize)")] ArrowsV,
        [Description("arrow-up (f062, Directional Icons)")] ArrowUp,
        [Description("artstation (f2ed, Web Application Icons, Brand Icons, art, social-network)")] Artstation,
        [Description("askfm (f33a, Brand Icon)")] Askfm,
        [Description("assistive-listening-systems (f2a2, Web Application Icons, Accessibility Icons)")] AssistiveListeningSystems,
        [Description("asterisk (f069, Web Application Icons, details)")] Asterisk,
        [Description("at (f1fa, Web Application Icons, e-mail, email)")] At,
        [Description("att (f31e, Brand Icons)")] Att,
        [Description("audio-description (f29e, Web Application Icons, Accessibility Icons)")] AudioDescription,
        [Description("backward (f04a, Video Player Icons, previous, rewind)")] Backward,
        [Description("balance-scale (f24e, Web Application Icons)")] BalanceScale,
        [Description("ban (f05e, Web Application Icons, abort, block, cancel, delete, hide, remove, stop, trash)")] Ban,
        [Description("bandcamp (f2d5, Brand Icons)")] Bandcamp,
        [Description("bar-chart (f080, Web Application Icons, Chart Icons, analytics, bar-chart-o, graph, statistics)")] BarChart,
        [Description("barcode (f02a, Web Application Icons, scan)")] Barcode,
        [Description("bars (f0c9, Web Application Icons, checklist, drag, hamburger, list, menu, navicon, ol, reorder, settings, todo, ul)")] Bars,
        [Description("bath (f2cd, Web Application Icons, bathtub, s15)")] Bath,
        [Description("battery-empty (f244, Web Application Icons, battery-0, power)")] BatteryEmpty,
        [Description("battery-full (f240, Web Application Icons, battery, battery-4, power)")] BatteryFull,
        [Description("battery-half (f242, Web Application Icons, battery-2, power)")] BatteryHalf,
        [Description("battery-quarter (f243, Web Application Icons, battery-1, power)")] BatteryQuarter,
        [Description("battery-three-quarters (f241, Web Application Icons, battery-3, power)")] BatteryThreeQuarters,
        [Description("bed (f236, Web Application Icons, hotel, travel)")] Bed,
        [Description("beer (f0fc, Web Application Icons, alcohol, bar, drink, liquor, mug, stein)")] Beer,
        [Description("behance (f1b4, Brand Icons)")] Behance,
        [Description("behance-square (f1b5, Brand Icons)")] BehanceSquare,
        [Description("bell (f0f3, Web Application Icons, alert, notification, reminder)")] Bell,
        [Description("bell-o (f0a2, Web Application Icons, alert, notification, reminder)")] BellOutline,
        [Description("bell-ringing (f32d, Web Application Icons, alert, notification, reminder, ringing)")] BellRinging,
        [Description("bell-slash (f1f6, Web Application Icons)")] BellSlash,
        [Description("bell-slash-o (f1f7, Web Application Icons)")] BellSlashOutline,
        [Description("bicycle (f206, Web Application Icons, Transportation Icons, bike, vehicle)")] Bicycle,
        [Description("binoculars (f1e5, Web Application Icons)")] Binoculars,
        [Description("biometric (f32b, Web Application Icons, biometric, passport)")] Biometric,
        [Description("birthday-cake (f1fd, Web Application Icons)")] BirthdayCake,
        [Description("bitbucket (f171, Brand Icons, git)")] Bitbucket,
        [Description("bitbucket-square (f172, Brand Icons, git)")] BitbucketSquare,
        [Description("black-tie (f27e, Brand Icons)")] BlackTie,
        [Description("blind (f29d, Web Application Icons, Accessibility Icons)")] Blind,
        [Description("blockstack (f33b, Brand Icon)")] Blockstack,
        [Description("bluetooth (f293, Web Application Icons, Brand Icons)")] Bluetooth,
        [Description("bluetooth-b (f294, Web Application Icons, Brand Icons)")] BluetoothB,
        [Description("boardgamegeek (f33c, Brand Icons)")] Boardgamegeek,
        [Description("bold (f032, Text Editor Icons)")] Bold,
        [Description("bolt (f0e7, Web Application Icons, flash, lightning, weather)")] Bolt,
        [Description("bomb (f1e2, Web Application Icons)")] Bomb,
        [Description("book (f02d, Web Application Icons, documentation, read)")] Book,
        [Description("bookmark (f02e, Web Application Icons, save)")] Bookmark,
        [Description("bookmark-o (f097, Web Application Icons, save)")] BookmarkOutline,
        [Description("bootstrap (f315, Brand Icons)")] Bootstrap,
        [Description("braille (f2a1, Web Application Icons, Accessibility Icons)")] Braille,
        [Description("briefcase (f0b1, Web Application Icons, bag, business, luggage, office, work)")] Briefcase,
        [Description("btc (f15a, Payment Icons, Currency Icons, Brand Icons, bitcoin)")] Btc,
        [Description("bug (f188, Web Application Icons, insect, report)")] Bug,
        [Description("building (f1ad, Web Application Icons, apartment, business, company, office, work)")] Building,
        [Description("building-o (f0f7, Web Application Icons, apartment, business, company, office, work)")] BuildingOutline,
        [Description("bullhorn (f0a1, Web Application Icons, announcement, broadcast, louder, megaphone, share)")] Bullhorn,
        [Description("bullseye (f140, Web Application Icons, target)")] Bullseye,
        [Description("bunny (f35f, Web Application Icons)")] Bunny,
        [Description("bus (f207, Web Application Icons, Transportation Icons, vehicle)")] Bus,
        [Description("buymeacoffee (f33d, Brand Icons)")] Buymeacoffee,
        [Description("buysellads (f20d, Brand Icons)")] Buysellads,
        [Description("c (f31c, Brand Icons)")] C,
        [Description("calculator (f1ec, Web Application Icons)")] Calculator,
        [Description("calendar (f073, Web Application Icons, date, event, time, when)")] Calendar,
        [Description("calendar-check-o (f274, Web Application Icons, ok)")] CalendarCheckOutline,
        [Description("calendar-minus-o (f272, Web Application Icons)")] CalendarMinusOutline,
        [Description("calendar-o (f133, Web Application Icons, date, event, time, when)")] CalendarOutline,
        [Description("calendar-plus-o (f271, Web Application Icons)")] CalendarPlusOutline,
        [Description("calendar-times-o (f273, Web Application Icons)")] CalendarTimesOutline,
        [Description("camera (f030, Web Application Icons, photo, picture, record)")] Camera,
        [Description("camera-retro (f083, Web Application Icons, photo, picture, record)")] CameraRetro,
        [Description("car (f1b9, Web Application Icons, Transportation Icons, automobile, vehicle)")] Car,
        [Description("caret-down (f0d7, Directional Icons, arrow, dropdown, menu, more, triangle down)")] CaretDown,
        [Description("caret-left (f0d9, Directional Icons, arrow, back, previous, triangle left)")] CaretLeft,
        [Description("caret-right (f0da, Directional Icons, arrow, forward, next, triangle right)")] CaretRight,
        [Description("caret-square-o-down (f150, Web Application Icons, Directional Icons, dropdown, menu, more, toggle-down)")] CaretSquareOutlineDown,
        [Description("caret-square-o-left (f191, Web Application Icons, Directional Icons, back, previous, toggle-left)")] CaretSquareOutlineLeft,
        [Description("caret-square-o-right (f152, Web Application Icons, Directional Icons, forward, next, toggle-right)")] CaretSquareOutlineRight,
        [Description("caret-square-o-up (f151, Web Application Icons, Directional Icons, toggle-up)")] CaretSquareOutlineUp,
        [Description("caret-up (f0d8, Directional Icons, arrow, triangle up)")] CaretUp,
        [Description("cart-arrow-down (f218, Web Application Icons, shopping)")] CartArrowDown,
        [Description("cart-plus (f217, Web Application Icons, add, shopping)")] CartPlus,
        [Description("cc (f20a, Web Application Icons, Accessibility Icons, closed-captioning)")] Cc,
        [Description("cc-amex (f1f3, Brand Icons, Payment Icons, amex)")] CcAmex,
        [Description("cc-by (f33e, Web Application Icons, Brand Icon)")] CcBy,
        [Description("cc-cc (f33f, Web Application Icons, Brand Icons, creative-commons-alt)")] CcCc,
        [Description("cc-diners-club (f24c, Brand Icons, Payment Icons)")] CcDinersClub,
        [Description("cc-discover (f1f2, Brand Icons, Payment Icons)")] CcDiscover,
        [Description("cc-jcb (f24b, Brand Icons, Payment Icons)")] CcJcb,
        [Description("cc-mastercard (f1f1, Brand Icons, Payment Icons)")] CcMastercard,
        [Description("cc-nc (f340, Web Application Icons, Brand Icons)")] CcNc,
        [Description("cc-nc-eu (f341, Web Application Icons, Brand Icons)")] CcNcEu,
        [Description("cc-nc-jp (f342, Web Application Icons, Brand Icons)")] CcNcJp,
        [Description("cc-nd (f343, Web Application Icons, Brand Icons)")] CcNd,
        [Description("cc-paypal (f1f4, Brand Icons, Payment Icons)")] CcPaypal,
        [Description("cc-pd (f344, Web Application Icons, Brand Icon)")] CcPd,
        [Description("cc-remix (f345, Web Application Icons, Brand Icons)")] CcRemix,
        [Description("cc-sa (f346, Web Application Icons, Brand Icon)")] CcSa,
        [Description("cc-share (f347, Web Application Icons, Brand Icons)")] CcShare,
        [Description("cc-stripe (f1f5, Brand Icons, Payment Icons)")] CcStripe,
        [Description("cc-visa (f1f0, Brand Icons, Payment Icons)")] CcVisa,
        [Description("cc-zero (f348, Web Application Icons, Brand Icons)")] CcZero,
        [Description("certificate (f0a3, Web Application Icons, badge, star)")] Certificate,
        [Description("chain-broken (f127, Text Editor Icons, remove, unlink)")] ChainBroken,
        [Description("check (f00c, Web Application Icons, accept, agree, checkmark, confirm, done, ok, tick, todo)")] Check,
        [Description("check-circle (f058, Web Application Icons, accept, agree, confirm, done, ok, todo)")] CheckCircle,
        [Description("check-circle-o (f05d, Web Application Icons, accept, agree, confirm, done, ok, todo)")] CheckCircleOutline,
        [Description("check-square (f14a, Web Application Icons, Form Control Icons, accept, agree, checkmark, confirm, done, ok, todo)")] CheckSquare,
        [Description("check-square-o (f046, Web Application Icons, Form Control Icons, accept, agree, confirm, done, ok, todo)")] CheckSquareOutline,
        [Description("chevron-circle-down (f13a, Directional Icons, arrow, dropdown, menu, more)")] ChevronCircleDown,
        [Description("chevron-circle-left (f137, Directional Icons, arrow, back, previous)")] ChevronCircleLeft,
        [Description("chevron-circle-right (f138, Directional Icons, arrow, forward, next)")] ChevronCircleRight,
        [Description("chevron-circle-up (f139, Directional Icons, arrow)")] ChevronCircleUp,
        [Description("chevron-down (f078, Directional Icons)")] ChevronDown,
        [Description("chevron-left (f053, Directional Icons, back, bracket, previous)")] ChevronLeft,
        [Description("chevron-right (f054, Directional Icons, bracket, forward, next)")] ChevronRight,
        [Description("chevron-up (f077, Directional Icons)")] ChevronUp,
        [Description("child (f1ae, Web Application Icons)")] Child,
        [Description("chrome (f268, Brand Icons, browser)")] Chrome,
        [Description("circle (f111, Web Application Icons, Form Control Icons, dot, notification)")] Circle,
        [Description("circle-o (f10c, Web Application Icons, Form Control Icons)")] CircleOutline,
        [Description("circle-o-notch (f1ce, Web Application Icons, Spinner Icons)")] CircleOutlineNotch,
        [Description("circle-thin (f1db, Web Application Icons)")] CircleThin,
        [Description("classicpress (f331, Brand Icons)")] Classicpress,
        [Description("classicpress-circle (f332, Brand Icons)")] ClassicpressCircle,
        [Description("clipboard (f0ea, Text Editor Icons, copy, paste)")] Clipboard,
        [Description("clock-o (f017, Web Application Icons, late, timer, timestamp, watch)")] ClockOutline,
        [Description("clone (f24d, Web Application Icons, copy)")] Clone,
        [Description("cloud (f0c2, Web Application Icons, save)")] Cloud,
        [Description("cloud-download (f0ed, Web Application Icons, import)")] CloudDownload,
        [Description("cloud-upload (f0ee, Web Application Icons, import)")] CloudUpload,
        [Description("code (f121, Web Application Icons, brackets, html)")] Code,
        [Description("code-fork (f126, Web Application Icons, code-branch, fork, git, github, merge, rebase, svn, vcs, version)")] CodeFork,
        [Description("codepen (f1cb, Brand Icons)")] Codepen,
        [Description("codiepie (f284, Brand Icons)")] Codiepie,
        [Description("coffee (f0f4, Web Application Icons, breakfast, cafe, drink, morning, mug, tea)")] Coffee,
        [Description("cog (f013, Web Application Icons, Spinner Icons, gear, settings)")] Cog,
        [Description("cogs (f085, Web Application Icons, gears, settings)")] Cogs,
        [Description("columns (f0db, Text Editor Icons, panes, split)")] Columns,
        [Description("comment (f075, Web Application Icons, bubble, chat, conversation, feedback, message, note, notification, sms, speech, texting)")] Comment,
        [Description("commenting (f27a, Web Application Icons, bubble, chat, conversation, feedback, message, note, notification, sms, speech, texting)")] Commenting,
        [Description("commenting-o (f27b, Web Application Icons, bubble, chat, conversation, feedback, message, note, notification, sms, speech, texting)")] CommentingOutline,
        [Description("comment-o (f0e5, Web Application Icons, bubble, chat, conversation, feedback, message, note, notification, sms, speech, texting)")] CommentOutline,
        [Description("comments (f086, Web Application Icons, bubble, chat, conversation, feedback, message, note, notification, sms, speech, texting)")] Comments,
        [Description("comments-o (f0e6, Web Application Icons, bubble, chat, conversation, feedback, message, note, notification, sms, speech, texting)")] CommentsOutline,
        [Description("compass (f14e, Web Application Icons, directory, location, menu, safari)")] Compass,
        [Description("compress (f066, Video Player Icons, collapse, combine, contract, merge, smaller)")] Compress,
        [Description("connectdevelop (f20e, Brand Icons)")] Connectdevelop,
        [Description("contao (f26d, Brand Icons)")] Contao,
        [Description("conway-glider (f349, Brand Icons, conway-hacker)")] ConwayGlider,
        [Description("copyright (f1f9, Web Application Icons)")] Copyright,
        [Description("creative-commons (f25e, Web Application Icons)")] CreativeCommons,
        [Description("credit-card (f09d, Web Application Icons, Payment Icons, buy, checkout, debit, money, payment, purchase)")] CreditCard,
        [Description("credit-card-alt (f283, Payment Icons, Web Application Icons, buy, checkout, credit card, debit, money, payment, purchase)")] CreditCardAlt,
        [Description("crop (f125, Web Application Icons)")] Crop,
        [Description("crosshairs (f05b, Web Application Icons, picker)")] Crosshairs,
        [Description("csharp (f34a, Brand Icons)")] Csharp,
        [Description("css3 (f13c, Brand Icons, code)")] Css3,
        [Description("cube (f1b2, Web Application Icons)")] Cube,
        [Description("cubes (f1b3, Web Application Icons)")] Cubes,
        [Description("cutlery (f0f5, Web Application Icons, dinner, eat, food, knife, restaurant, spoon, utensils)")] Cutlery,
        [Description("dashcube (f210, Brand Icons)")] Dashcube,
        [Description("database (f1c0, Web Application Icons)")] Database,
        [Description("deaf (f2a4, Web Application Icons, Accessibility Icons, deafness, hard-of-hearing)")] Deaf,
        [Description("debian (f2ff, Brand Icons)")] Debian,
        [Description("delicious (f1a5, Brand Icons)")] Delicious,
        [Description("desktop (f108, Web Application Icons, computer, demo, desktop, device, monitor, screen)")] Desktop,
        [Description("deviantart (f1bd, Brand Icons)")] Deviantart,
        [Description("dev-to (f316, Brand Icons)")] DevTo,
        [Description("diamond (f219, Web Application Icons, gem, gemstone)")] Diamond,
        [Description("diaspora (f2e5, Web Application Icons, Brand Icons, federation, social-network)")] Diaspora,
        [Description("digg (f1a6, Brand Icons)")] Digg,
        [Description("digitalocean (f31d, Brand Icons)")] Digitalocean,
        [Description("discord (f2ee, Web Application Icons, Brand Icons, chat)")] Discord,
        [Description("discord-alt (f2ef, Web Application Icons, Brand Icons, chat)")] DiscordAlt,
        [Description("dogmazic (f303, Brand Icons)")] Dogmazic,
        [Description("dot-circle-o (f192, Web Application Icons, Form Control Icons, bullseye, notification, target)")] DotCircleOutline,
        [Description("download (f019, Web Application Icons, import)")] Download,
        [Description("dribbble (f17d, Brand Icons)")] Dribbble,
        [Description("dropbox (f16b, Brand Icons)")] Dropbox,
        [Description("drupal (f1a9, Brand Icons)")] Drupal,
        [Description("edge (f282, Brand Icons, browser, ie)")] Edge,
        [Description("eercast (f2da, Brand Icons)")] Eercast,
        [Description("eject (f052, Video Player Icons)")] Eject,
        [Description("ellipsis-h (f141, Web Application Icons, dots)")] EllipsisH,
        [Description("ellipsis-v (f142, Web Application Icons, dots)")] EllipsisV,
        [Description("email-bulk (f34b, Web Application Icons, e-mail, email, letter, mail, message, notification, support)")] EmailBulk,
        [Description("email-bulk-o (f34c, Web Application Icons, e-mail, email, letter, mail, message, notification, support)")] EmailBulkOutline,
        [Description("emby (f319, Brand Icons)")] Emby,
        [Description("empire (f1d1, Brand Icons, ge)")] Empire,
        [Description("envelope (f0e0, Web Application Icons, e-mail, email, letter, mail, message, notification, support)")] Envelope,
        [Description("envelope-open (f2b6, Web Application Icons, e-mail, email, letter, mail, message, notification, support)")] EnvelopeOpen,
        [Description("envelope-o (f003, Web Application Icons, e-mail, email, letter, mail, message, notification, support)")] EnvelopeOutline,
        [Description("envelope-open-o (f2b7, Web Application Icons, e-mail, email, letter, mail, message, notification, support)")] EnvelopeOutlinepenOutline,
        [Description("envelope-square (f199, Web Application Icons, e-mail, email, letter, mail, message, notification, support)")] EnvelopeSquare,
        [Description("envira (f299, Brand Icons, leaf)")] Envira,
        [Description("eraser (f12d, Text Editor Icons, Web Application Icons, delete, remove)")] Eraser,
        [Description("ethereum (f2f3, Payment Icons, Brand Icons)")] Ethereum,
        [Description("etsy (f2d7, Brand Icons)")] Etsy,
        [Description("eur (f153, Currency Icons, euro)")] Eur,
        [Description("exchange (f0ec, Web Application Icons, Directional Icons, arrow, arrows, transfer)")] Exchange,
        [Description("exclamation (f12a, Web Application Icons, alert, error, notification, notify, problem, warning)")] Exclamation,
        [Description("exclamation-circle (f06a, Web Application Icons, alert, error, notification, problem, warning)")] ExclamationCircle,
        [Description("exclamation-triangle (f071, Web Application Icons, alert, error, notification, problem, warning)")] ExclamationTriangle,
        [Description("expand (f065, Video Player Icons, bigger, enlarge, resize)")] Expand,
        [Description("expeditedssl (f23e, Brand Icons)")] Expeditedssl,
        [Description("external-link (f08e, Web Application Icons, new, open)")] ExternalLink,
        [Description("external-link-square (f14c, Web Application Icons, new, open)")] ExternalLinkSquare,
        [Description("eye (f06e, Web Application Icons, show, views, visible)")] Eye,
        [Description("eyedropper (f1fb, Web Application Icons)")] Eyedropper,
        [Description("eye-slash (f070, Web Application Icons, hide, show, toggle, views, visible, visiblity)")] EyeSlash,
        [Description("facebook (f09a, Brand Icons, facebook-f, social network)")] Facebook,
        [Description("facebook-messenger (f2fe, Brand Icons, social network)")] FacebookMessenger,
        [Description("facebook-official (f230, Brand Icons)")] FacebookOfficial,
        [Description("facebook-square (f082, Brand Icons, social network)")] FacebookSquare,
        [Description("fast-backward (f049, Video Player Icons, beginning, first, previous, rewind, start)")] FastBackward,
        [Description("fast-forward (f050, Video Player Icons, end, last, next)")] FastForward,
        [Description("fax (f1ac, Web Application Icons)")] Fax,
        [Description("f-droid (f32a, Brand Icons)")] FDroid,
        [Description("female (f182, Web Application Icons, person, profile, user, woman)")] Female,
        [Description("ffmpeg (f30f, Brand Icons)")] Ffmpeg,
        [Description("fighter-jet (f0fb, Web Application Icons, Transportation Icons, airplane, fast, fly, plane, quick, travel)")] FighterJet,
        [Description("file (f15b, Text Editor Icons, File Type Icons, document, new, page, pdf)")] File,
        [Description("file-archive-o (f1c6, Web Application Icons, File Type Icons, file-zip-o)")] FileArchiveOutline,
        [Description("file-audio-o (f1c7, Web Application Icons, File Type Icons, file-sound-o)")] FileAudioOutline,
        [Description("file-code-o (f1c9, Web Application Icons, File Type Icons)")] FileCodeOutline,
        [Description("file-epub (f321, Web Application Icons, File Type Icons)")] FileEpub,
        [Description("file-excel-o (f1c3, Web Application Icons, File Type Icons)")] FileExcelOutline,
        [Description("file-image-o (f1c5, Web Application Icons, File Type Icons, file-photo-o, file-picture-o)")] FileImageOutline,
        [Description("file-o (f016, Text Editor Icons, File Type Icons, document, new, page, pdf)")] FileOutline,
        [Description("file-pdf-o (f1c1, Web Application Icons, File Type Icons)")] FilePdfOutline,
        [Description("file-powerpoint-o (f1c4, Web Application Icons, File Type Icons)")] FilePowerpointOutline,
        [Description("files-o (f0c5, Text Editor Icons, clone, copy, duplicate)")] FilesOutline,
        [Description("file-text (f15c, Text Editor Icons, File Type Icons, document, new, page, pdf)")] FileText,
        [Description("file-text-o (f0f6, Text Editor Icons, File Type Icons, document, new, page, pdf)")] FileTextOutline,
        [Description("file-video-o (f1c8, Web Application Icons, File Type Icons, file-movie-o)")] FileVideoOutline,
        [Description("file-word-o (f1c2, Web Application Icons, File Type Icons)")] FileWordOutline,
        [Description("film (f008, Web Application Icons, movie)")] Film,
        [Description("filter (f0b0, Web Application Icons, funnel, options)")] Filter,
        [Description("fire (f06d, Web Application Icons, flame, hot, popular)")] Fire,
        [Description("fire-extinguisher (f134, Web Application Icons)")] FireExtinguisher,
        [Description("firefox (f269, Brand Icons, browser)")] Firefox,
        [Description("first-order (f2b0, Brand Icons)")] FirstOrder,
        [Description("flag (f024, Web Application Icons, notification, notify, report)")] Flag,
        [Description("flag-checkered (f11e, Web Application Icons, notification, notify, report)")] FlagCheckered,
        [Description("flag-o (f11d, Web Application Icons, notification, report)")] FlagOutline,
        [Description("flask (f0c3, Web Application Icons, beaker, experimental, labs, science)")] Flask,
        [Description("flickr (f16e, Brand Icons)")] Flickr,
        [Description("floppy-o (f0c7, Text Editor Icons, save)")] FloppyOutline,
        [Description("folder (f07b, Web Application Icons)")] Folder,
        [Description("folder-open (f07c, Web Application Icons)")] FolderOpen,
        [Description("folder-o (f114, Web Application Icons)")] FolderOutline,
        [Description("folder-open-o (f115, Web Application Icons)")] FolderOutlinepenOutline,
        [Description("font (f031, Text Editor Icons, text)")] Font,
        [Description("font-awesome (f2b4, Brand Icons, fa)")] FontAwesome,
        [Description("fonticons (f280, Brand Icons)")] Fonticons,
        [Description("fork-awesome (f2e3, Brand Icons, font, fork, fork-circle)")] ForkAwesome,
        [Description("fort-awesome (f286, Brand Icons)")] FortAwesome,
        [Description("forumbee (f211, Brand Icons)")] Forumbee,
        [Description("forward (f04e, Video Player Icons, forward, next)")] Forward,
        [Description("foursquare (f180, Brand Icons)")] Foursquare,
        [Description("free-code-camp (f2c5, Brand Icons)")] FreeCodeCamp,
        [Description("freedombox (f2fd, Brand Icons)")] Freedombox,
        [Description("friendica (f2e6, Web Application Icons, Brand Icons, federation, social-network)")] Friendica,
        [Description("frown-o (f119, Web Application Icons, disapprove, emoticon, face, rating, sad)")] FrownOutline,
        [Description("funkwhale (f339, Brand Icons)")] Funkwhale,
        [Description("futbol-o (f1e3, Web Application Icons, soccer-ball-o)")] FutbolOutline,
        [Description("gamepad (f11b, Web Application Icons, controller)")] Gamepad,
        [Description("gavel (f0e3, Web Application Icons, judge, lawyer, legal, opinion)")] Gavel,
        [Description("gbp (f154, Currency Icons, pound)")] Gbp,
        [Description("genderless (f22d, Gender Icons)")] Genderless,
        [Description("get-pocket (f265, Brand Icons)")] GetPocket,
        [Description("gg (f260, Currency Icons, Brand Icons)")] Gg,
        [Description("gg-circle (f261, Currency Icons, Brand Icons)")] GgCircle,
        [Description("gift (f06b, Web Application Icons, present)")] Gift,
        [Description("gimp (f31b, Brand Icons)")] Gimp,
        [Description("git (f1d3, Brand Icons)")] Git,
        [Description("gitea (f31f, Brand Icons)")] Gitea,
        [Description("github (f09b, Brand Icons, octocat)")] Github,
        [Description("github-alt (f113, Brand Icons, octocat)")] GithubAlt,
        [Description("github-square (f092, Brand Icons, octocat)")] GithubSquare,
        [Description("gitlab (f296, Brand Icons)")] Gitlab,
        [Description("git-square (f1d2, Brand Icons)")] GitSquare,
        [Description("glass (f000, Web Application Icons, alcohol, bar, drink, liquor, martini)")] Glass,
        [Description("glide (f2a5, Brand Icons)")] Glide,
        [Description("glide-g (f2a6, Brand Icons)")] GlideG,
        [Description("globe (f0ac, Web Application Icons, all, coordinates, country, earth, global, language, localize, location, map, place, planet, translate, travel, world)")] Globe,
        [Description("globe-e (f304, Web Application Icons, all, coordinates, country, earth, eastern, global, language, localize, location, map, place, planet, translate, travel, world)")] GlobeE,
        [Description("globe-w (f305, Web Application Icons, all, coordinates, country, earth, global, language, localize, location, map, place, planet, translate, travel, western, world)")] GlobeW,
        [Description("gnu (f34d, Brand Icons)")] Gnu,
        [Description("gnupg (f30d, Brand Icons)")] Gnupg,
        [Description("gnu-social (f2e7, Web Application Icons, Brand Icons, federation, social-network)")] GnuSocial,
        [Description("google (f1a0, Brand Icons)")] Google,
        [Description("google-play (f34e, Brand Icons)")] GooglePlay,
        [Description("google-plus (f0d5, Brand Icons, google-plus-g, social network)")] GooglePlus,
        [Description("google-plus-official (f2b3, Brand Icons, google-plus-circle)")] GooglePlusOfficial,
        [Description("google-plus-square (f0d4, Brand Icons, social network)")] GooglePlusSquare,
        [Description("google-wallet (f1ee, Brand Icons, Payment Icons)")] GoogleWallet,
        [Description("graduation-cap (f19d, Web Application Icons, learning, mortar-board, school, student)")] GraduationCap,
        [Description("gratipay (f184, Brand Icons, favorite, gittip, heart, like, love)")] Gratipay,
        [Description("grav (f2d6, Brand Icons)")] Grav,
        [Description("hackaday (f30a, Brand Icons)")] Hackaday,
        [Description("hacker-news (f1d4, Brand Icons, y-combinator-square, yc-square)")] HackerNews,
        [Description("hackster (f326, Brand Icons)")] Hackster,
        [Description("hal (f333, Brand Icons, science)")] Hal,
        [Description("hand-lizard-o (f258, Web Application Icons, Hand Icons)")] HandLizardOutline,
        [Description("hand-o-down (f0a7, Directional Icons, Hand Icons, finger, point)")] HandOutlineDown,
        [Description("hand-o-left (f0a5, Directional Icons, Hand Icons, back, finger, left, point, previous)")] HandOutlineLeft,
        [Description("hand-o-right (f0a4, Directional Icons, Hand Icons, finger, forward, next, point, right)")] HandOutlineRight,
        [Description("hand-o-up (f0a6, Directional Icons, Hand Icons, finger, point)")] HandOutlineUp,
        [Description("hand-paper-o (f256, Web Application Icons, Hand Icons, hand-stop-o, stop)")] HandPaperOutline,
        [Description("hand-peace-o (f25b, Web Application Icons, Hand Icons)")] HandPeaceOutline,
        [Description("hand-pointer-o (f25a, Web Application Icons, Hand Icons)")] HandPointerOutline,
        [Description("hand-rock-o (f255, Web Application Icons, Hand Icons, hand-grab-o)")] HandRockOutline,
        [Description("hand-scissors-o (f257, Web Application Icons, Hand Icons)")] HandScissorsOutline,
        [Description("handshake-o (f2b5, Web Application Icons)")] HandshakeOutline,
        [Description("hand-spock-o (f259, Web Application Icons, Hand Icons)")] HandSpockOutline,
        [Description("hashnode (f317, Brand Icons)")] Hashnode,
        [Description("hashtag (f292, Web Application Icons)")] Hashtag,
        [Description("hdd-o (f0a0, Web Application Icons, hard drive, harddrive, save, storage)")] HddOutline,
        [Description("header (f1dc, Text Editor Icons, heading)")] Header,
        [Description("headphones (f025, Web Application Icons, audio, listen, music, sound)")] Headphones,
        [Description("heart (f004, Web Application Icons, Medical Icons, favorite, like, love)")] Heart,
        [Description("heartbeat (f21e, Web Application Icons, Medical Icons, ekg)")] Heartbeat,
        [Description("heart-o (f08a, Web Application Icons, Medical Icons, favorite, like, love)")] HeartOutline,
        [Description("heroku (f34f, Brand Icons)")] Heroku,
        [Description("history (f1da, Web Application Icons, recent)")] History,
        [Description("home (f015, Web Application Icons, house, main)")] Home,
        [Description("home-assistant (f350, Brand Icons, hassio)")] HomeAssistant,
        [Description("hospital-o (f0f8, Medical Icons, building)")] HospitalOutline,
        [Description("hourglass (f254, Web Application Icons)")] Hourglass,
        [Description("hourglass-end (f253, Web Application Icons, hourglass-3)")] HourglassEnd,
        [Description("hourglass-half (f252, Web Application Icons, hourglass-2)")] HourglassHalf,
        [Description("hourglass-o (f250, Web Application Icons)")] HourglassOutline,
        [Description("hourglass-start (f251, Web Application Icons, hourglass-1)")] HourglassStart,
        [Description("houzz (f27c, Brand Icons)")] Houzz,
        [Description("h-square (f0fd, Medical Icons, hospital, hotel)")] HSquare,
        [Description("html5 (f13b, Brand Icons)")] Html5,
        [Description("hubzilla (f2eb, Web Application Icons, Brand Icons, federation, social-network)")] Hubzilla,
        [Description("i-cursor (f246, Web Application Icons)")] ICursor,
        [Description("id-badge (f2c1, Web Application Icons)")] IdBadge,
        [Description("id-card (f2c2, Web Application Icons, drivers-license)")] IdCard,
        [Description("id-card-o (f2c3, Web Application Icons, drivers-license-o)")] IdCardOutline,
        [Description("ils (f20b, Currency Icons, shekel, sheqel)")] Ils,
        [Description("imdb (f2d8, Brand Icons)")] Imdb,
        [Description("inbox (f01c, Web Application Icons)")] Inbox,
        [Description("indent (f03c, Text Editor Icons)")] Indent,
        [Description("industry (f275, Web Application Icons, factory)")] Industry,
        [Description("info (f129, Web Application Icons, details, help, information, more)")] Info,
        [Description("info-circle (f05a, Web Application Icons, details, help, information, more)")] InfoCircle,
        [Description("inkscape (f312, Brand Icons)")] Inkscape,
        [Description("inr (f156, Currency Icons, rupee)")] Inr,
        [Description("instagram (f16d, Brand Icons)")] Instagram,
        [Description("internet-explorer (f26b, Brand Icons, browser, ie)")] InternetExplorer,
        [Description("ioxhost (f208, Brand Icons)")] Ioxhost,
        [Description("italic (f033, Text Editor Icons, italics)")] Italic,
        [Description("java (f351, Brand Icons)")] Java,
        [Description("jirafeau (f318, Brand Icons)")] Jirafeau,
        [Description("joomla (f1aa, Brand Icons)")] Joomla,
        [Description("joplin (f310, Brand Icons)")] Joplin,
        [Description("jpy (f157, Currency Icons, cny, rmb, yen)")] Jpy,
        [Description("jsfiddle (f1cc, Brand Icons)")] Jsfiddle,
        [Description("julia (f334, Brand Icons, science)")] Julia,
        [Description("jupyter (f335, Brand Icons, science)")] Jupyter,
        [Description("key (f084, Web Application Icons, password, unlock)")] Key,
        [Description("keybase (f2f4, Brand Icons)")] Keybase,
        [Description("keyboard-o (f11c, Web Application Icons, input, type)")] KeyboardOutline,
        [Description("key-modern (f2f7, Web Application Icons, cut-key, password, unlock)")] KeyModern,
        [Description("krw (f159, Currency Icons, won)")] Krw,
        [Description("language (f1ab, Web Application Icons, translate)")] Language,
        [Description("laptop (f109, Web Application Icons, computer, demo, device)")] Laptop,
        [Description("laravel (f30b, Brand Icons)")] Laravel,
        [Description("lastfm (f202, Brand Icons)")] Lastfm,
        [Description("lastfm-square (f203, Brand Icons)")] LastfmSquare,
        [Description("leaf (f06c, Web Application Icons, eco, nature, plant)")] Leaf,
        [Description("leanpub (f212, Brand Icons)")] Leanpub,
        [Description("lemon-o (f094, Web Application Icons, food)")] LemonOutline,
        [Description("level-down (f149, Web Application Icons, arrow)")] LevelDown,
        [Description("level-up (f148, Web Application Icons, arrow)")] LevelUp,
        [Description("liberapay (f2e9, Web Application Icons, Payment Icons, Brand Icons)")] Liberapay,
        [Description("liberapay-square (f2e8, Web Application Icons, Payment Icons, Brand Icons)")] LiberapaySquare,
        [Description("life-ring (f1cd, Web Application Icons, life-bouy, life-buoy, life-saver, support)")] LifeRing,
        [Description("lightbulb-o (f0eb, Web Application Icons, idea, inspiration)")] LightbulbOutline,
        [Description("line-chart (f201, Web Application Icons, Chart Icons, analytics, graph, statistics)")] LineChart,
        [Description("link (f0c1, Text Editor Icons, chain)")] Link,
        [Description("linkedin (f0e1, Brand Icons)")] Linkedin,
        [Description("linkedin-square (f08c, Brand Icons)")] LinkedinSquare,
        [Description("linode (f2b8, Brand Icons)")] Linode,
        [Description("linux (f17c, Brand Icons, tux)")] Linux,
        [Description("list (f03a, Text Editor Icons, checklist, completed, done, finished, ol, todo, ul)")] List,
        [Description("list-alt (f022, Text Editor Icons, checklist, completed, done, finished, ol, todo, ul)")] ListAlt,
        [Description("list-ol (f0cb, Text Editor Icons, checklist, list, numbers, ol, todo, ul)")] ListOl,
        [Description("list-ul (f0ca, Text Editor Icons, checklist, list, ol, todo, ul)")] ListUl,
        [Description("location-arrow (f124, Web Application Icons, address, coordinates, location, map, place, where)")] LocationArrow,
        [Description("lock (f023, Web Application Icons, admin, protect, security)")] Lock,
        [Description("long-arrow-down (f175, Directional Icons)")] LongArrowDown,
        [Description("long-arrow-left (f177, Directional Icons, back, previous)")] LongArrowLeft,
        [Description("long-arrow-right (f178, Directional Icons)")] LongArrowRight,
        [Description("long-arrow-up (f176, Directional Icons)")] LongArrowUp,
        [Description("low-vision (f2a8, Web Application Icons, Accessibility Icons)")] LowVision,
        [Description("magic (f0d0, Web Application Icons, autocomplete, automatic, wizard)")] Magic,
        [Description("magnet (f076, Web Application Icons)")] Magnet,
        [Description("male (f183, Web Application Icons, man, person, profile, user)")] Male,
        [Description("map (f279, Web Application Icons)")] Map,
        [Description("map-marker (f041, Web Application Icons, address, coordinates, localize, location, map, pin, place, travel, where)")] MapMarker,
        [Description("map-o (f278, Web Application Icons)")] MapOutline,
        [Description("map-pin (f276, Web Application Icons)")] MapPin,
        [Description("map-signs (f277, Web Application Icons)")] MapSigns,
        [Description("mariadb (f352, Brand Icons)")] Mariadb,
        [Description("markdown (f353, Brand Icons)")] Markdown,
        [Description("mars (f222, Gender Icons, male)")] Mars,
        [Description("mars-double (f227, Gender Icons)")] MarsDouble,
        [Description("mars-stroke (f229, Gender Icons)")] MarsStroke,
        [Description("mars-stroke-h (f22b, Gender Icons)")] MarsStrokeH,
        [Description("mars-stroke-v (f22a, Gender Icons)")] MarsStrokeV,
        [Description("mastodon (f2e1, Web Application Icons, Brand Icons, federation, social-network, toot)")] Mastodon,
        [Description("mastodon-alt (f2e2, Web Application Icons, Brand Icons, federation, social-network, toot)")] MastodonAlt,
        [Description("mastodon-square (f300, Brand Icons, social network)")] MastodonSquare,
        [Description("matrix-org (f313, Brand Icons, chat, federation, message)")] MatrixOrg,
        [Description("maxcdn (f136, Brand Icons)")] Maxcdn,
        [Description("meanpath (f20c, Brand Icons)")] Meanpath,
        [Description("medium (f23a, Brand Icons)")] Medium,
        [Description("medium-square (f2f8, Brand Icons)")] MediumSquare,
        [Description("medkit (f0fa, Medical Icons, first aid, firstaid, health, help, support)")] Medkit,
        [Description("meetup (f2e0, Brand Icons)")] Meetup,
        [Description("meh-o (f11a, Web Application Icons, emoticon, face, neutral, rating)")] MehOutline,
        [Description("mercury (f223, Gender Icons, transgender)")] Mercury,
        [Description("microchip (f2db, Web Application Icons)")] Microchip,
        [Description("microphone (f130, Web Application Icons, record, sound, voice)")] Microphone,
        [Description("microphone-slash (f131, Web Application Icons, mute, record, sound, voice)")] MicrophoneSlash,
        [Description("minus (f068, Web Application Icons, collapse, delete, hide, minify, remove, trash)")] Minus,
        [Description("minus-circle (f056, Web Application Icons, delete, hide, remove, trash)")] MinusCircle,
        [Description("minus-square (f146, Web Application Icons, Form Control Icons, collapse, delete, hide, minify, remove, trash)")] MinusSquare,
        [Description("minus-square-o (f147, Web Application Icons, Form Control Icons, collapse, delete, hide, minify, remove, trash)")] MinusSquareOutline,
        [Description("mixcloud (f289, Brand Icons)")] Mixcloud,
        [Description("mobile (f10b, Web Application Icons, call, cell phone, cellphone, iphone, mobile-phone, number, telephone, text)")] Mobile,
        [Description("modx (f285, Brand Icons)")] Modx,
        [Description("money (f0d6, Web Application Icons, Currency Icons, buy, cash, checkout, money, payment, purchase)")] Money,
        [Description("moon (f328, Web Application Icons, contrast, crescent, darker, night)")] Moon,
        [Description("moon-o (f186, Web Application Icons, contrast, crescent, darker, night)")] MoonOutline,
        [Description("motorcycle (f21c, Web Application Icons, Transportation Icons, bike, vehicle)")] Motorcycle,
        [Description("mouse-pointer (f245, Web Application Icons)")] MousePointer,
        [Description("music (f001, Web Application Icons, note, sound)")] Music,
        [Description("mysql (f354, Brand Icons)")] Mysql,
        [Description("neuter (f22c, Gender Icons)")] Neuter,
        [Description("newspaper-o (f1ea, Web Application Icons, press)")] NewspaperOutline,
        [Description("nextcloud (f306, Brand Icons)")] Nextcloud,
        [Description("nextcloud-square (f307, Brand Icons)")] NextcloudSquare,
        [Description("nodejs (f308, Brand Icons)")] Nodejs,
        [Description("nordcast (f355, Brand Icons)")] Nordcast,
        [Description("object-group (f247, Web Application Icons)")] ObjectGroup,
        [Description("object-ungroup (f248, Web Application Icons)")] ObjectUngroup,
        [Description("odnoklassniki (f263, Brand Icons)")] Odnoklassniki,
        [Description("odnoklassniki-square (f264, Brand Icons)")] OdnoklassnikiSquare,
        [Description("opencart (f23d, Brand Icons)")] Opencart,
        [Description("open-collective (f336, Brand Icons, funding platform)")] OpenCollective,
        [Description("openid (f19b, Brand Icons)")] Openid,
        [Description("opera (f26a, Brand Icons)")] Opera,
        [Description("optin-monster (f23c, Brand Icons)")] OptinMonster,
        [Description("orcid (f337, Brand Icons, science)")] Orcid,
        [Description("outdent (f03b, Text Editor Icons, dedent)")] Outdent,
        [Description("pagelines (f18c, Brand Icons, eco, leaf, leaves, nature, plant, tree)")] Pagelines,
        [Description("paint-brush (f1fc, Web Application Icons)")] PaintBrush,
        [Description("paperclip (f0c6, Text Editor Icons, attachment)")] Paperclip,
        [Description("paper-plane (f1d8, Web Application Icons, send)")] PaperPlane,
        [Description("paper-plane-o (f1d9, Web Application Icons, send-o)")] PaperPlaneOutline,
        [Description("paragraph (f1dd, Text Editor Icons)")] Paragraph,
        [Description("patreon (f2f0, Payment Icons, Brand Icons, funding)")] Patreon,
        [Description("pause (f04c, Video Player Icons, wait)")] Pause,
        [Description("pause-circle (f28b, Video Player Icons)")] PauseCircle,
        [Description("pause-circle-o (f28c, Video Player Icons)")] PauseCircleOutline,
        [Description("paw (f1b0, Web Application Icons, pet)")] Paw,
        [Description("paypal (f1ed, Brand Icons, Payment Icons)")] Paypal,
        [Description("peertube (f2e4, Web Application Icons, Brand Icons, federation, social-network, video)")] Peertube,
        [Description("pencil (f040, Web Application Icons, edit, update, write)")] Pencil,
        [Description("pencil-square (f14b, Web Application Icons, edit, update, write)")] PencilSquare,
        [Description("pencil-square-o (f044, Web Application Icons, edit, update, write)")] PencilSquareOutline,
        [Description("percent (f295, Web Application Icons)")] Percent,
        [Description("phone (f095, Web Application Icons, call, earphone, number, support, telephone, voice)")] Phone,
        [Description("phone-square (f098, Web Application Icons, call, number, support, telephone, voice)")] PhoneSquare,
        [Description("php (f30e, Brand Icons)")] Php,
        [Description("picture-o (f03e, Web Application Icons, image, photo)")] PictureOutline,
        [Description("pie-chart (f200, Web Application Icons, Chart Icons, analytics, graph, statistics)")] PieChart,
        [Description("pinterest (f0d2, Brand Icons)")] Pinterest,
        [Description("pinterest-p (f231, Brand Icons)")] PinterestP,
        [Description("pinterest-square (f0d3, Brand Icons)")] PinterestSquare,
        [Description("pixelfed (f314, Brand Icons, federation, photo, social-network)")] Pixelfed,
        [Description("plane (f072, Web Application Icons, Transportation Icons, airplane, destination, fly, location, mode, travel, trip)")] Plane,
        [Description("play (f04b, Video Player Icons, music, playing, sound, start)")] Play,
        [Description("play-circle (f144, Video Player Icons, playing, start)")] PlayCircle,
        [Description("play-circle-o (f01d, Video Player Icons)")] PlayCircleOutline,
        [Description("pleroma (f324, Brand Icons, Web Application Icons, federation, social-network)")] Pleroma,
        [Description("plug (f1e6, Web Application Icons, connect, power)")] Plug,
        [Description("plume (f356, Brand Icons)")] Plume,
        [Description("plus (f067, Web Application Icons, add, create, expand, new)")] Plus,
        [Description("plus-circle (f055, Web Application Icons, add, create, expand, new)")] PlusCircle,
        [Description("plus-square (f0fe, Medical Icons, Web Application Icons, Form Control Icons, add, create, expand, new)")] PlusSquare,
        [Description("plus-square-o (f196, Web Application Icons, Form Control Icons, add, create, expand, new)")] PlusSquareOutline,
        [Description("podcast (f2ce, Web Application Icons)")] Podcast,
        [Description("postgresql (f357, Brand Icons)")] Postgresql,
        [Description("power-off (f011, Web Application Icons, on)")] PowerOff,
        [Description("print (f02f, Web Application Icons)")] Print,
        [Description("product-hunt (f288, Brand Icons)")] ProductHunt,
        [Description("puzzle-piece (f12e, Web Application Icons, add-on, addon, section)")] PuzzlePiece,
        [Description("python (f322, Brand Icons)")] Python,
        [Description("qq (f1d6, Brand Icons)")] Qq,
        [Description("qrcode (f029, Web Application Icons, scan)")] Qrcode,
        [Description("question (f128, Web Application Icons, help, information, support, unknown)")] Question,
        [Description("question-circle (f059, Web Application Icons, help, information, support, unknown)")] QuestionCircle,
        [Description("question-circle-o (f29c, Web Application Icons, Accessibility Icons)")] QuestionCircleOutline,
        [Description("quora (f2c4, Brand Icons)")] Quora,
        [Description("quote-left (f10d, Web Application Icons)")] QuoteLeft,
        [Description("quote-right (f10e, Web Application Icons)")] QuoteRight,
        [Description("random (f074, Web Application Icons, Video Player Icons, shuffle, sort)")] Random,
        [Description("ravelry (f2d9, Brand Icons)")] Ravelry,
        [Description("react (f302, Brand Icons)")] React,
        [Description("rebel (f1d0, Brand Icons, ra, resistance)")] Rebel,
        [Description("recycle (f1b8, Web Application Icons)")] Recycle,
        [Description("reddit (f1a1, Brand Icons)")] Reddit,
        [Description("reddit-alien (f281, Brand Icons)")] RedditAlien,
        [Description("reddit-square (f1a2, Brand Icons)")] RedditSquare,
        [Description("refresh (f021, Web Application Icons, Spinner Icons, reload, sync)")] Refresh,
        [Description("registered (f25d, Web Application Icons)")] Registered,
        [Description("renren (f18b, Brand Icons)")] Renren,
        [Description("repeat (f01e, Text Editor Icons, forward, redo, rotate-right)")] Repeat,
        [Description("reply (f112, Web Application Icons, mail-reply)")] Reply,
        [Description("reply-all (f122, Web Application Icons, mail-reply-all)")] ReplyAll,
        [Description("researchgate (f338, Brand Icons, science)")] Researchgate,
        [Description("retweet (f079, Web Application Icons, refresh, reload, share)")] Retweet,
        [Description("road (f018, Web Application Icons, street)")] Road,
        [Description("rocket (f135, Web Application Icons, Transportation Icons, app)")] Rocket,
        [Description("rss (f09e, Web Application Icons, blog, feed)")] Rss,
        [Description("rss-square (f143, Web Application Icons, blog, feed)")] RssSquare,
        [Description("rub (f158, Currency Icons, rouble, ruble)")] Rub,
        [Description("safari (f267, Brand Icons, browser)")] Safari,
        [Description("sass (f358, Brand Icons)")] Sass,
        [Description("sass-alt (f359, Brand Icons)")] SassAlt,
        [Description("scissors (f0c4, Text Editor Icons, cut)")] Scissors,
        [Description("scribd (f28a, Brand Icons)")] Scribd,
        [Description("scuttlebutt (f2ea, Web Application Icons, Brand Icons, federation, social-network, ssb)")] Scuttlebutt,
        [Description("search (f002, Web Application Icons, bigger, enlarge, magnify, zoom)")] Search,
        [Description("search-minus (f010, Web Application Icons, magnify, minify, smaller, zoom)")] SearchMinus,
        [Description("search-plus (f00e, Web Application Icons, bigger, enlarge, magnify, zoom)")] SearchPlus,
        [Description("sellsy (f213, Brand Icons)")] Sellsy,
        [Description("server (f233, Web Application Icons)")] Server,
        [Description("shaarli (f2f5, Brand Icons)")] Shaarli,
        [Description("shaarli-o (f2f6, Brand Icons)")] ShaarliOutline,
        [Description("share (f064, Web Application Icons, mail-forward)")] Share,
        [Description("share-alt (f1e0, Web Application Icons, Brand Icons)")] ShareAlt,
        [Description("share-alt-square (f1e1, Web Application Icons, Brand Icons)")] ShareAltSquare,
        [Description("share-square (f14d, Web Application Icons, send, social)")] ShareSquare,
        [Description("share-square-o (f045, Web Application Icons, arrow, send, social)")] ShareSquareOutline,
        [Description("shield (f132, Web Application Icons, achievement, award, security, winner)")] Shield,
        [Description("ship (f21a, Web Application Icons, Transportation Icons, boat, sea)")] Ship,
        [Description("shirtsinbulk (f214, Brand Icons)")] Shirtsinbulk,
        [Description("shopping-bag (f290, Web Application Icons)")] ShoppingBag,
        [Description("shopping-basket (f291, Web Application Icons)")] ShoppingBasket,
        [Description("shopping-cart (f07a, Web Application Icons, buy, checkout, payment, purchase)")] ShoppingCart,
        [Description("shower (f2cc, Web Application Icons)")] Shower,
        [Description("signal (f012, Web Application Icons, bars, graph)")] Signal,
        [Description("signalapp (f30c, message, texting)")] Signalapp,
        [Description("sign-in (f090, Web Application Icons, arrow, enter, join, log in, login, sign in, sign up, signin, signup)")] SignIn,
        [Description("sign-language (f2a7, Web Application Icons, Accessibility Icons, signing)")] SignLanguage,
        [Description("sign-out (f08b, Web Application Icons, arrow, exit, leave, log out, logout)")] SignOut,
        [Description("simplybuilt (f215, Brand Icons)")] Simplybuilt,
        [Description("sitemap (f0e8, Web Application Icons, directory, hierarchy, organization)")] Sitemap,
        [Description("skate (f35a, Web Application Icons, Transportation Icons, vehicle)")] Skate,
        [Description("sketchfab (f35b, Brand Icons)")] Sketchfab,
        [Description("skyatlas (f216, Brand Icons)")] Skyatlas,
        [Description("skype (f17e, Brand Icons)")] Skype,
        [Description("slack (f198, Brand Icons, anchor, hash, hashtag)")] Slack,
        [Description("sliders (f1de, Web Application Icons, settings)")] Sliders,
        [Description("slideshare (f1e7, Brand Icons)")] Slideshare,
        [Description("smile-o (f118, Web Application Icons, approve, emoticon, face, happy, rating, satisfied)")] SmileOutline,
        [Description("snapchat (f2ab, Brand Icons)")] Snapchat,
        [Description("snapchat-ghost (f2ac, Brand Icons)")] SnapchatGhost,
        [Description("snapchat-square (f2ad, Brand Icons)")] SnapchatSquare,
        [Description("snowdrift (f2f1, Brand Icons)")] Snowdrift,
        [Description("snowflake-o (f2dc, Web Application Icons)")] SnowflakeOutline,
        [Description("social-home (f2ec, Web Application Icons, Brand Icons, federation, social-network)")] SocialHome,
        [Description("sort (f0dc, Web Application Icons, order, unsorted)")] Sort,
        [Description("sort-alpha-asc (f15d, Web Application Icons, sort-alpha-down)")] SortAlphaAsc,
        [Description("sort-alpha-desc (f15e, Web Application Icons, sort-alpha-up)")] SortAlphaDesc,
        [Description("sort-amount-asc (f160, Web Application Icons, sort-amount-down)")] SortAmountAsc,
        [Description("sort-amount-desc (f161, Web Application Icons, sort-amount-up)")] SortAmountDesc,
        [Description("sort-asc (f0de, Web Application Icons, arrow, sort-up)")] SortAsc,
        [Description("sort-desc (f0dd, Web Application Icons, arrow, dropdown, menu, more, sort-down)")] SortDesc,
        [Description("sort-numeric-asc (f162, Web Application Icons, numbers, sort-numeric-down)")] SortNumericAsc,
        [Description("sort-numeric-desc (f163, Web Application Icons, numbers, sort-numeric-up)")] SortNumericDesc,
        [Description("soundcloud (f1be, Brand Icons)")] Soundcloud,
        [Description("space-shuttle (f197, Web Application Icons, Transportation Icons)")] SpaceShuttle,
        [Description("spell-check (f327, Web Application Icons, checkmark, spelling)")] SpellCheck,
        [Description("spinner (f110, Web Application Icons, Spinner Icons, loading, progress)")] Spinner,
        [Description("spoon (f1b1, Web Application Icons, utensil-spoon)")] Spoon,
        [Description("spotify (f1bc, Brand Icons)")] Spotify,
        [Description("square (f0c8, Web Application Icons, Form Control Icons, block, box)")] Square,
        [Description("square-o (f096, Web Application Icons, Form Control Icons, block, box, square)")] SquareOutline,
        [Description("stack-exchange (f18d, Brand Icons)")] StackExchange,
        [Description("stack-overflow (f16c, Brand Icons)")] StackOverflow,
        [Description("star (f005, Web Application Icons, achievement, award, favorite, night, rating, score)")] Star,
        [Description("star-half (f089, Web Application Icons, achievement, award, rating, score)")] StarHalf,
        [Description("star-half-o (f123, Web Application Icons, achievement, award, rating, score, star-half-empty, star-half-full)")] StarHalfOutline,
        [Description("star-o (f006, Web Application Icons, achievement, award, favorite, night, rating, score)")] StarOutline,
        [Description("steam (f1b6, Brand Icons)")] Steam,
        [Description("steam-square (f1b7, Brand Icons)")] SteamSquare,
        [Description("step-backward (f048, Video Player Icons, beginning, first, previous, rewind, start)")] StepBackward,
        [Description("step-forward (f051, Video Player Icons, end, last, next)")] StepForward,
        [Description("stethoscope (f0f1, Medical Icons)")] Stethoscope,
        [Description("sticky-note (f249, Web Application Icons)")] StickyNote,
        [Description("sticky-note-o (f24a, Web Application Icons)")] StickyNoteOutline,
        [Description("stop (f04d, Video Player Icons, block, box, square)")] Stop,
        [Description("stop-circle (f28d, Video Player Icons)")] StopCircle,
        [Description("stop-circle-o (f28e, Video Player Icons)")] StopCircleOutline,
        [Description("street-view (f21d, Web Application Icons, map)")] StreetView,
        [Description("strikethrough (f0cc, Text Editor Icons)")] Strikethrough,
        [Description("stumbleupon (f1a4, Brand Icons)")] Stumbleupon,
        [Description("stumbleupon-circle (f1a3, Brand Icons)")] StumbleuponCircle,
        [Description("subscript (f12c, Text Editor Icons)")] Subscript,
        [Description("subway (f239, Transportation Icons)")] Subway,
        [Description("suitcase (f0f2, Web Application Icons, baggage, luggage, move, travel, trip)")] Suitcase,
        [Description("sun (f329, Web Application Icons, brighten, contrast, day, lighter, weather)")] Sun,
        [Description("sun-o (f185, Web Application Icons, brighten, contrast, day, lighter, weather)")] SunOutline,
        [Description("superpowers (f2dd, Brand Icons)")] Superpowers,
        [Description("superscript (f12b, Text Editor Icons, exponential)")] Superscript,
        [Description("syncthing (f311, Brand Icons)")] Syncthing,
        [Description("table (f0ce, Text Editor Icons, data, excel, spreadsheet)")] Table,
        [Description("tablet (f10a, Web Application Icons, device, ipad)")] Tablet,
        [Description("tachometer (f0e4, Web Application Icons, dashboard, fast, speedometer)")] Tachometer,
        [Description("tag (f02b, Web Application Icons, label)")] Tag,
        [Description("tags (f02c, Web Application Icons, labels)")] Tags,
        [Description("tasks (f0ae, Web Application Icons, downloading, downloads, loading, progress, settings)")] Tasks,
        [Description("taxi (f1ba, Web Application Icons, Transportation Icons, cab, vehicle)")] Taxi,
        [Description("telegram (f2c6, Brand Icons)")] Telegram,
        [Description("television (f26c, Web Application Icons, computer, display, monitor, tv)")] Television,
        [Description("tencent-weibo (f1d5, Brand Icons)")] TencentWeibo,
        [Description("terminal (f120, Web Application Icons, code, command, prompt)")] Terminal,
        [Description("tex (f35c, Brand Icons)")] Tex,
        [Description("text-height (f034, Text Editor Icons)")] TextHeight,
        [Description("textpattern (f35d, Brand Icons)")] Textpattern,
        [Description("text-width (f035, Text Editor Icons)")] TextWidth,
        [Description("th (f00a, Text Editor Icons, blocks, boxes, grid, squares)")] Th,
        [Description("themeisle (f2b2, Brand Icons)")] Themeisle,
        [Description("thermometer-empty (f2cb, Web Application Icons, thermometer-0)")] ThermometerEmpty,
        [Description("thermometer-full (f2c7, Web Application Icons, thermometer, thermometer-4)")] ThermometerFull,
        [Description("thermometer-half (f2c9, Web Application Icons, thermometer-2)")] ThermometerHalf,
        [Description("thermometer-quarter (f2ca, Web Application Icons, thermometer-1)")] ThermometerQuarter,
        [Description("thermometer-three-quarters (f2c8, Web Application Icons, thermometer-3)")] ThermometerThreeQuarters,
        [Description("th-large (f009, Text Editor Icons, blocks, boxes, grid, squares)")] ThLarge,
        [Description("th-list (f00b, Text Editor Icons, checklist, completed, done, finished, ol, todo, ul)")] ThList,
        [Description("thumbs-down (f165, Web Application Icons, Hand Icons, disagree, disapprove, dislike, hand)")] ThumbsDown,
        [Description("thumbs-o-down (f088, Web Application Icons, Hand Icons, disagree, disapprove, dislike, hand)")] ThumbsOutlineDown,
        [Description("thumbs-o-up (f087, Web Application Icons, Hand Icons, agree, approve, favorite, hand, like)")] ThumbsOutlineUp,
        [Description("thumbs-up (f164, Web Application Icons, Hand Icons, agree, approve, favorite, hand, like)")] ThumbsUp,
        [Description("thumb-tack (f08d, Web Application Icons, coordinates, location, marker, pin)")] ThumbTack,
        [Description("ticket (f145, Web Application Icons, movie, pass, support)")] Ticket,
        [Description("times (f00d, Web Application Icons, close, cross, exit, remove, x)")] Times,
        [Description("times-circle (f057, Web Application Icons, close, exit, x)")] TimesCircle,
        [Description("times-circle-o (f05c, Web Application Icons, close, exit, x)")] TimesCircleOutline,
        [Description("tint (f043, Web Application Icons, drop, droplet, raindrop, waterdrop)")] Tint,
        [Description("tipeee (f301, Payment Icons, Brand Icons, funding)")] Tipeee,
        [Description("toggle-off (f204, Web Application Icons, switch)")] ToggleOff,
        [Description("toggle-on (f205, Web Application Icons, switch)")] ToggleOn,
        [Description("tor-onion (f32e, Brand Icons, browser, network)")] TorOnion,
        [Description("trademark (f25c, Web Application Icons)")] Trademark,
        [Description("train (f238, Transportation Icons)")] Train,
        [Description("transgender (f224, Gender Icons, intersex)")] Transgender,
        [Description("transgender-alt (f225, Gender Icons)")] TransgenderAlt,
        [Description("trash (f1f8, Web Application Icons, delete, garbage, hide, remove)")] Trash,
        [Description("trash-o (f014, Web Application Icons, delete, garbage, hide, remove, trash)")] TrashOutline,
        [Description("tree (f1bb, Web Application Icons)")] Tree,
        [Description("trello (f181, Brand Icons)")] Trello,
        [Description("tripadvisor (f262, Brand Icons)")] Tripadvisor,
        [Description("trophy (f091, Web Application Icons, achievement, award, cup, game, winner)")] Trophy,
        [Description("truck (f0d1, Web Application Icons, Transportation Icons, shipping)")] Truck,
        [Description("try (f195, Currency Icons, turkish-lira)")] Try,
        [Description("tty (f1e4, Web Application Icons, Accessibility Icons)")] Tty,
        [Description("tumblr (f173, Brand Icons)")] Tumblr,
        [Description("tumblr-square (f174, Brand Icons)")] TumblrSquare,
        [Description("twitch (f1e8, Brand Icons)")] Twitch,
        [Description("twitter (f099, Brand Icons, social network, tweet)")] Twitter,
        [Description("twitter-square (f081, Brand Icons, social network, tweet)")] TwitterSquare,
        [Description("umbrella (f0e9, Web Application Icons)")] Umbrella,
        [Description("underline (f0cd, Text Editor Icons)")] Underline,
        [Description("undo (f0e2, Text Editor Icons, back, rotate-left)")] Undo,
        [Description("unity (f35e, Brand Icons)")] Unity,
        [Description("universal-access (f29a, Web Application Icons, Accessibility Icons)")] UniversalAccess,
        [Description("university (f19c, Web Application Icons, bank, institution)")] University,
        [Description("unlock (f09c, Web Application Icons, admin, lock, password, protect)")] Unlock,
        [Description("unlock-alt (f13e, Web Application Icons, admin, lock, password, protect)")] UnlockAlt,
        [Description("upload (f093, Web Application Icons, import)")] Upload,
        [Description("usb (f287, Brand Icons)")] Usb,
        [Description("usd (f155, Currency Icons, dollar)")] Usd,
        [Description("user (f007, Web Application Icons, head, man, person, profile)")] User,
        [Description("user-circle (f2bd, Web Application Icons)")] UserCircle,
        [Description("user-circle-o (f2be, Web Application Icons)")] UserCircleOutline,
        [Description("user-md (f0f0, Medical Icons, doctor, medical, nurse, profile)")] UserMd,
        [Description("user-o (f2c0, Web Application Icons)")] UserOutline,
        [Description("user-plus (f234, Web Application Icons, sign up, signup)")] UserPlus,
        [Description("users (f0c0, Web Application Icons, community, group, people, persons, profiles)")] Users,
        [Description("user-secret (f21b, Web Application Icons, incognito, privacy, spy, whisper)")] UserSecret,
        [Description("user-times (f235, Web Application Icons)")] UserTimes,
        [Description("venus (f221, Gender Icons, female)")] Venus,
        [Description("venus-double (f226, Gender Icons)")] VenusDouble,
        [Description("venus-mars (f228, Gender Icons)")] VenusMars,
        [Description("viacoin (f237, Currency Icons, Brand Icons)")] Viacoin,
        [Description("viadeo (f2a9, Brand Icons)")] Viadeo,
        [Description("viadeo-square (f2aa, Brand Icons)")] ViadeoSquare,
        [Description("video-camera (f03d, Web Application Icons, film, movie, record, video)")] VideoCamera,
        [Description("vimeo (f27d, Brand Icons, vimeo-v)")] Vimeo,
        [Description("vimeo-square (f194, Brand Icons)")] VimeoSquare,
        [Description("vine (f1ca, Brand Icons)")] Vine,
        [Description("vk (f189, Brand Icons)")] Vk,
        [Description("volume-control-phone (f2a0, Web Application Icons, Accessibility Icons, phone-volume, telephone)")] VolumeControlPhone,
        [Description("volume-down (f027, Web Application Icons, audio, lower, music, quieter, sound)")] VolumeDown,
        [Description("volume-mute (f32f, Web Application Icons, audio, music, mute, sound)")] VolumeMute,
        [Description("volume-off (f026, Web Application Icons, audio, music, mute, sound)")] VolumeOff,
        [Description("volume-up (f028, Web Application Icons, audio, higher, louder, music, sound)")] VolumeUp,
        [Description("weibo (f18a, Brand Icons)")] Weibo,
        [Description("weixin (f1d7, Brand Icons, wechat)")] Weixin,
        [Description("whatsapp (f232, Brand Icons)")] Whatsapp,
        [Description("wheelchair (f193, Web Application Icons, Medical Icons, Transportation Icons, Accessibility Icons, handicap, person)")] Wheelchair,
        [Description("wheelchair-alt (f29b, Web Application Icons, Medical Icons, Transportation Icons, Accessibility Icons, handicap, person)")] WheelchairAlt,
        [Description("wifi (f1eb, Web Application Icons)")] Wifi,
        [Description("wikidata (f31a, Brand Icons)")] Wikidata,
        [Description("wikipedia-w (f266, Brand Icons)")] WikipediaW,
        [Description("window-close (f2d3, Web Application Icons, times-rectangle)")] WindowClose,
        [Description("window-close-o (f2d4, Web Application Icons, times-rectangle-o)")] WindowCloseOutline,
        [Description("window-maximize (f2d0, Web Application Icons)")] WindowMaximize,
        [Description("window-minimize (f2d1, Web Application Icons)")] WindowMinimize,
        [Description("window-restore (f2d2, Web Application Icons)")] WindowRestore,
        [Description("windows (f17a, Brand Icons, microsoft)")] Windows,
        [Description("wire (f32c, Brand Icons, chat, message, messenger, social network)")] Wire,
        [Description("wordpress (f19a, Brand Icons)")] Wordpress,
        [Description("wpbeginner (f297, Brand Icons)")] Wpbeginner,
        [Description("wpexplorer (f2de, Brand Icons)")] Wpexplorer,
        [Description("wpforms (f298, Brand Icons)")] Wpforms,
        [Description("wrench (f0ad, Web Application Icons, fix, settings, spanner, update)")] Wrench,
        [Description("xing (f168, Brand Icons)")] Xing,
        [Description("xing-square (f169, Brand Icons)")] XingSquare,
        [Description("xmpp (f2f9, Brand Icons, iot, message)")] Xmpp,
        [Description("yahoo (f19e, Brand Icons)")] Yahoo,
        [Description("y-combinator (f23b, Brand Icons, yc)")] YCombinator,
        [Description("yelp (f1e9, Brand Icons)")] Yelp,
        [Description("yoast (f2b1, Brand Icons)")] Yoast,
        [Description("youtube (f167, Brand Icons, film, video)")] Youtube,
        [Description("youtube-play (f16a, Brand Icons, Video Player Icons, playing, start)")] YoutubePlay,
        [Description("youtube-square (f166, Brand Icons, film, video)")] YoutubeSquare,
        [Description("zotero (f309, Brand Icons)")] Zotero
    }
}