namespace MahApps.Metro.IconPacks
{
#if !(NETFX_CORE || WINDOWS_UWP)
    using System.ComponentModel;
#endif

    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIconOcticons" />.
    /// </summary>
    /// <remarks>
    /// All icons sourced from GitHub Octicons <see><cref>https://github.com/primer/octicons</cref></see>
    /// In accordance of <see><cref>https://github.com/primer/octicons?tab=MIT-1-ov-file#readme</cref></see>.
    /// </remarks>
    public enum PackIconOcticonsKind
    {
        [Description("Empty placeholder")] None,
        [Description("accessibility-24")] Accessibility,
        [Description("accessibility-16")] Accessibility16,
        [Description("accessibility-inset-24")] AccessibilityInset,
        [Description("accessibility-inset-16")] AccessibilityInset16,
        [Description("ai-model-24")] AiModel,
        [Description("ai-model-16 (ai, model, llm, models, copilot)")] AiModel16,
        [Description("alert-24")] Alert,
        [Description("alert-16 (warning, triangle, exclamation, point)")] Alert16,
        [Description("alert-fill-24")] AlertFill,
        [Description("alert-fill-12")] AlertFill12,
        [Description("alert-fill-16")] AlertFill16,
        [Description("apps-24")] Apps,
        [Description("apps-16")] Apps16,
        [Description("archive-24")] Archive,
        [Description("archive-16 (box, catalog)")] Archive16,
        [Description("arrow-both-24")] ArrowBoth,
        [Description("arrow-both-16 (point, direction, left, right)")] ArrowBoth16,
        [Description("arrow-down-24")] ArrowDown,
        [Description("arrow-down-16 (point, direction)")] ArrowDown16,
        [Description("arrow-down-left-24")] ArrowDownLeft,
        [Description("arrow-down-left-16")] ArrowDownLeft16,
        [Description("arrow-down-right-24")] ArrowDownRight,
        [Description("arrow-down-right-16")] ArrowDownRight16,
        [Description("arrow-left-24")] ArrowLeft,
        [Description("arrow-left-16 (point, direction)")] ArrowLeft16,
        [Description("arrow-right-24")] ArrowRight,
        [Description("arrow-right-16 (point, direction)")] ArrowRight16,
        [Description("arrow-switch-24")] ArrowSwitch,
        [Description("arrow-switch-16")] ArrowSwitch16,
        [Description("arrow-up-24")] ArrowUp,
        [Description("arrow-up-16 (point, direction)")] ArrowUp16,
        [Description("arrow-up-left-24")] ArrowUpLeft,
        [Description("arrow-up-left-16")] ArrowUpLeft16,
        [Description("arrow-up-right-24")] ArrowUpRight,
        [Description("arrow-up-right-16")] ArrowUpRight16,
        [Description("beaker-24")] Beaker,
        [Description("beaker-16 (experiment, labs, experimental, feature, test, science, education, study, development, testing)")] Beaker16,
        [Description("bell-24")] Bell,
        [Description("bell-16 (notification)")] Bell16,
        [Description("bell-fill-24")] BellFill,
        [Description("bell-fill-16")] BellFill16,
        [Description("bell-slash-24")] BellSlash,
        [Description("bell-slash-16")] BellSlash16,
        [Description("blocked-24")] Blocked,
        [Description("blocked-16")] Blocked16,
        [Description("bold-24")] Bold,
        [Description("bold-16 (markdown, bold, text)")] Bold16,
        [Description("book-24")] Book,
        [Description("book-16 (book, journal, wiki, readme)")] Book16,
        [Description("bookmark-24")] Bookmark,
        [Description("bookmark-16 (tab, star)")] Bookmark16,
        [Description("bookmark-fill-24")] BookmarkFill,
        [Description("bookmark-filled-16")] BookmarkFilled16,
        [Description("bookmark-slash-24")] BookmarkSlash,
        [Description("bookmark-slash-16")] BookmarkSlash16,
        [Description("bookmark-slash-fill-24")] BookmarkSlashFill,
        [Description("bookmark-slash-fill-16")] BookmarkSlashFill16,
        [Description("briefcase-24")] Briefcase,
        [Description("briefcase-16 (suitcase, business)")] Briefcase16,
        [Description("broadcast-24")] Broadcast,
        [Description("broadcast-16 (rss, radio, signal)")] Broadcast16,
        [Description("browser-24")] Browser,
        [Description("browser-16 (window, web)")] Browser16,
        [Description("bug-24")] Bug,
        [Description("bug-16 (insect, issue)")] Bug16,
        [Description("cache-24")] Cache,
        [Description("cache-16")] Cache16,
        [Description("calendar-24")] Calendar,
        [Description("calendar-16 (time, day, month, year, date, appointment)")] Calendar16,
        [Description("check-24")] Check,
        [Description("check-16 (mark, yes, confirm, accept, ok, success)")] Check16,
        [Description("checkbox-24")] Checkbox,
        [Description("checkbox-16")] Checkbox16,
        [Description("check-circle-24")] CheckCircle,
        [Description("check-circle-16")] CheckCircle16,
        [Description("check-circle-fill-24")] CheckCircleFill,
        [Description("check-circle-fill-12")] CheckCircleFill12,
        [Description("check-circle-fill-16")] CheckCircleFill16,
        [Description("checklist-24")] Checklist,
        [Description("checklist-16 (todo, tasks)")] Checklist16,
        [Description("chevron-down-24")] ChevronDown,
        [Description("chevron-down-12 (triangle, arrow)")] ChevronDown12,
        [Description("chevron-down-16 (triangle, arrow)")] ChevronDown16,
        [Description("chevron-left-24")] ChevronLeft,
        [Description("chevron-left-12 (triangle, arrow)")] ChevronLeft12,
        [Description("chevron-left-16 (triangle, arrow)")] ChevronLeft16,
        [Description("chevron-right-24")] ChevronRight,
        [Description("chevron-right-12 (triangle, arrow)")] ChevronRight12,
        [Description("chevron-right-16 (triangle, arrow)")] ChevronRight16,
        [Description("chevron-up-24")] ChevronUp,
        [Description("chevron-up-12 (triangle, arrow)")] ChevronUp12,
        [Description("chevron-up-16 (triangle, arrow)")] ChevronUp16,
        [Description("circle-24")] Circle,
        [Description("circle-16")] Circle16,
        [Description("circle-slash-24")] CircleSlash,
        [Description("circle-slash-16 (no, deny, fail, failure, error, bad)")] CircleSlash16,
        [Description("clock-24")] Clock,
        [Description("clock-16 (time, hour, minute, second, watch)")] Clock16,
        [Description("clock-fill-24")] ClockFill,
        [Description("clock-fill-16")] ClockFill16,
        [Description("cloud-24")] Cloud,
        [Description("cloud-16")] Cloud16,
        [Description("cloud-offline-24")] CloudOffline,
        [Description("cloud-offline-16")] CloudOffline16,
        [Description("code-24")] Code,
        [Description("code-16 (brackets)")] Code16,
        [Description("code-of-conduct-24")] CodeOfConduct,
        [Description("code-of-conduct-16")] CodeOfConduct16,
        [Description("code-review-24")] CodeReview,
        [Description("code-review-16")] CodeReview16,
        [Description("codescan-24")] Codescan,
        [Description("codescan-16")] Codescan16,
        [Description("codescan-checkmark-24")] CodescanCheckmark,
        [Description("codescan-checkmark-16")] CodescanCheckmark16,
        [Description("codespaces-24")] Codespaces,
        [Description("codespaces-16")] Codespaces16,
        [Description("code-square-24")] CodeSquare,
        [Description("code-square-16")] CodeSquare16,
        [Description("columns-24")] Columns,
        [Description("columns-16")] Columns16,
        [Description("command-palette-24")] CommandPalette,
        [Description("command-palette-16")] CommandPalette16,
        [Description("comment-24")] Comment,
        [Description("comment-16 (speak, bubble)")] Comment16,
        [Description("comment-discussion-24")] CommentDiscussion,
        [Description("comment-discussion-16 (converse, talk)")] CommentDiscussion16,
        [Description("container-24")] Container,
        [Description("container-16")] Container16,
        [Description("copilot-24")] Copilot,
        [Description("copilot-16")] Copilot16,
        [Description("copilot-48")] Copilot48,
        [Description("copilot-96")] Copilot96,
        [Description("copilot-error-16")] CopilotError16,
        [Description("copilot-warning-16")] CopilotWarning16,
        [Description("copy-24")] Copy,
        [Description("copy-16")] Copy16,
        [Description("cpu-24")] Cpu,
        [Description("cpu-16")] Cpu16,
        [Description("credit-card-24")] CreditCard,
        [Description("credit-card-16 (money, billing, payments, transactions)")] CreditCard16,
        [Description("cross-reference-24")] CrossReference,
        [Description("cross-reference-16")] CrossReference16,
        [Description("dash-24")] Dash,
        [Description("dash-16 (hyphen, range)")] Dash16,
        [Description("database-24")] Database,
        [Description("database-16 (disks, data)")] Database16,
        [Description("dependabot-24")] Dependabot,
        [Description("dependabot-16")] Dependabot16,
        [Description("desktop-download-24")] DesktopDownload,
        [Description("desktop-download-16 (clone, download)")] DesktopDownload16,
        [Description("device-camera-24")] DeviceCamera,
        [Description("device-camera-16 (photo, picture, image, snapshot)")] DeviceCamera16,
        [Description("device-camera-video-24")] DeviceCameraVideo,
        [Description("device-camera-video-16 (watch, view, media, stream)")] DeviceCameraVideo16,
        [Description("device-desktop-24")] DeviceDesktop,
        [Description("device-desktop-16 (computer, monitor)")] DeviceDesktop16,
        [Description("device-mobile-24")] DeviceMobile,
        [Description("device-mobile-16 (phone, iphone, cellphone)")] DeviceMobile16,
        [Description("devices-24")] Devices,
        [Description("devices-16")] Devices16,
        [Description("diamond-24")] Diamond,
        [Description("diamond-16")] Diamond16,
        [Description("diff-24")] Diff,
        [Description("diff-16 (difference, changes, compare)")] Diff16,
        [Description("diff-added-24")] DiffAdded,
        [Description("diff-added-16 (new, addition, plus)")] DiffAdded16,
        [Description("diff-ignored-24")] DiffIgnored,
        [Description("diff-ignored-16 (slash)")] DiffIgnored16,
        [Description("diff-modified-24")] DiffModified,
        [Description("diff-modified-16 (dot, changed, updated)")] DiffModified16,
        [Description("diff-removed-24")] DiffRemoved,
        [Description("diff-removed-16 (deleted, subtracted, dash)")] DiffRemoved16,
        [Description("diff-renamed-24")] DiffRenamed,
        [Description("diff-renamed-16 (moved, arrow)")] DiffRenamed16,
        [Description("discussion-closed-24")] DiscussionClosed,
        [Description("discussion-closed-16")] DiscussionClosed16,
        [Description("discussion-duplicate-24")] DiscussionDuplicate,
        [Description("discussion-duplicate-16")] DiscussionDuplicate16,
        [Description("discussion-outdated-24")] DiscussionOutdated,
        [Description("discussion-outdated-16")] DiscussionOutdated16,
        [Description("dot-24")] Dot,
        [Description("dot-16")] Dot16,
        [Description("dot-fill-24")] DotFill,
        [Description("dot-fill-16")] DotFill16,
        [Description("download-24")] Download,
        [Description("download-16")] Download16,
        [Description("duplicate-24")] Duplicate,
        [Description("duplicate-16")] Duplicate16,
        [Description("ellipsis-24")] Ellipsis,
        [Description("ellipsis-16 (dot, read, more, hidden, expand)")] Ellipsis16,
        [Description("eye-24")] Eye,
        [Description("eye-16 (look, watch, see)")] Eye16,
        [Description("eye-closed-24")] EyeClosed,
        [Description("eye-closed-16 (hidden, invisible, concealed, )")] EyeClosed16,
        [Description("feed-discussion-16")] FeedDiscussion16,
        [Description("feed-forked-16")] FeedForked16,
        [Description("feed-heart-16")] FeedHeart16,
        [Description("feed-issue-closed-16")] FeedIssueClosed16,
        [Description("feed-issue-draft-16")] FeedIssueDraft16,
        [Description("feed-issue-open-16")] FeedIssueOpen16,
        [Description("feed-issue-reopen-16")] FeedIssueReopen16,
        [Description("feed-merged-16")] FeedMerged16,
        [Description("feed-person-16")] FeedPerson16,
        [Description("feed-plus-16")] FeedPlus16,
        [Description("feed-public-16")] FeedPublic16,
        [Description("feed-pull-request-closed-16")] FeedPullRequestClosed16,
        [Description("feed-pull-request-draft-16")] FeedPullRequestDraft16,
        [Description("feed-pull-request-open-16")] FeedPullRequestOpen16,
        [Description("feed-repo-16")] FeedRepo16,
        [Description("feed-rocket-16")] FeedRocket16,
        [Description("feed-star-16")] FeedStar16,
        [Description("feed-tag-16")] FeedTag16,
        [Description("feed-trophy-16")] FeedTrophy16,
        [Description("file-24")] File,
        [Description("file-16 (file, text, words)")] File16,
        [Description("file-added-24")] FileAdded,
        [Description("file-added-16")] FileAdded16,
        [Description("file-badge-24")] FileBadge,
        [Description("file-badge-16")] FileBadge16,
        [Description("file-binary-24")] FileBinary,
        [Description("file-binary-16 (image, video, word, powerpoint, excel)")] FileBinary16,
        [Description("file-code-24")] FileCode,
        [Description("file-code-16 (text, javascript, html, css, php, ruby, coffeescript, sass, scss)")] FileCode16,
        [Description("file-diff-24")] FileDiff,
        [Description("file-diff-16")] FileDiff16,
        [Description("file-directory-24")] FileDirectory,
        [Description("file-directory-16 (folder)")] FileDirectory16,
        [Description("file-directory-fill-24")] FileDirectoryFill,
        [Description("file-directory-fill-16")] FileDirectoryFill16,
        [Description("file-directory-open-fill-24")] FileDirectoryOpenFill,
        [Description("file-directory-open-fill-16")] FileDirectoryOpenFill16,
        [Description("file-directory-symlink-24")] FileDirectorySymlink,
        [Description("file-directory-symlink-16")] FileDirectorySymlink16,
        [Description("file-media-24")] FileMedia,
        [Description("file-media-16 (image, video, audio)")] FileMedia16,
        [Description("file-moved-24")] FileMoved,
        [Description("file-moved-16")] FileMoved16,
        [Description("file-removed-24")] FileRemoved,
        [Description("file-removed-16")] FileRemoved16,
        [Description("file-submodule-24")] FileSubmodule,
        [Description("file-submodule-16 (folder)")] FileSubmodule16,
        [Description("file-symlink-file-24")] FileSymlinkFile,
        [Description("file-symlink-file-16 (link, alias)")] FileSymlinkFile16,
        [Description("file-zip-24")] FileZip,
        [Description("file-zip-16 (compress, archive)")] FileZip16,
        [Description("filter-24")] Filter,
        [Description("filter-16")] Filter16,
        [Description("filter-remove-24")] FilterRemove,
        [Description("filter-remove-16 (funnel, filter, remove, delete)")] FilterRemove16,
        [Description("fiscal-host-24")] FiscalHost,
        [Description("fiscal-host-16 (safe, money)")] FiscalHost16,
        [Description("flame-24")] Flame,
        [Description("flame-16 (fire, hot, burn, trending)")] Flame16,
        [Description("fold-24")] Fold,
        [Description("fold-16 (unfold, hide, collapse)")] Fold16,
        [Description("fold-down-24")] FoldDown,
        [Description("fold-down-16 (unfold, hide, collapse, down)")] FoldDown16,
        [Description("fold-up-24")] FoldUp,
        [Description("fold-up-16 (unfold, hide, collapse, up)")] FoldUp16,
        [Description("gear-24")] Gear,
        [Description("gear-16 (settings)")] Gear16,
        [Description("gift-24")] Gift,
        [Description("gift-16 (package, present, skill, craft, freebie)")] Gift16,
        [Description("git-branch-24")] GitBranch,
        [Description("git-branch-16 (fork, branch, git, duplicate)")] GitBranch16,
        [Description("git-commit-24")] GitCommit,
        [Description("git-commit-16 (save)")] GitCommit16,
        [Description("git-compare-24")] GitCompare,
        [Description("git-compare-16 (difference, changes)")] GitCompare16,
        [Description("git-merge-24")] GitMerge,
        [Description("git-merge-16 (join)")] GitMerge16,
        [Description("git-merge-queue-24")] GitMergeQueue,
        [Description("git-merge-queue-16")] GitMergeQueue16,
        [Description("git-pull-request-24")] GitPullRequest,
        [Description("git-pull-request-16 (review)")] GitPullRequest16,
        [Description("git-pull-request-closed-24")] GitPullRequestClosed,
        [Description("git-pull-request-closed-16")] GitPullRequestClosed16,
        [Description("git-pull-request-draft-24")] GitPullRequestDraft,
        [Description("git-pull-request-draft-16")] GitPullRequestDraft16,
        [Description("globe-24")] Globe,
        [Description("globe-16 (world, earth, planet, enterprise)")] Globe16,
        [Description("goal-24")] Goal,
        [Description("goal-16")] Goal16,
        [Description("grabber-24")] Grabber,
        [Description("grabber-16 (mover, drag, drop, sort)")] Grabber16,
        [Description("graph-24")] Graph,
        [Description("graph-16 (trend, stats, statistics)")] Graph16,
        [Description("hash-24")] Hash,
        [Description("hash-16")] Hash16,
        [Description("heading-24")] Heading,
        [Description("heading-16")] Heading16,
        [Description("heart-24")] Heart,
        [Description("heart-16 (love, beat)")] Heart16,
        [Description("heart-fill-24")] HeartFill,
        [Description("heart-fill-16")] HeartFill16,
        [Description("history-24")] History,
        [Description("history-16 (time, past, revert, back)")] History16,
        [Description("home-24")] Home,
        [Description("home-16 (welcome, index, house, building)")] Home16,
        [Description("home-fill-24")] HomeFill,
        [Description("home-fill-16")] HomeFill16,
        [Description("horizontal-rule-24")] HorizontalRule,
        [Description("horizontal-rule-16 (hr)")] HorizontalRule16,
        [Description("hourglass-24")] Hourglass,
        [Description("hourglass-16")] Hourglass16,
        [Description("hubot-24")] Hubot,
        [Description("hubot-16 (robot, bot)")] Hubot16,
        [Description("id-badge-24")] IdBadge,
        [Description("id-badge-16")] IdBadge16,
        [Description("image-24")] Image,
        [Description("image-16")] Image16,
        [Description("inbox-24")] Inbox,
        [Description("inbox-16 (mail, todo, new, messages)")] Inbox16,
        [Description("infinity-24")] Infinity,
        [Description("infinity-16 (unlimited, infinite)")] Infinity16,
        [Description("info-24")] Info,
        [Description("info-16 (help)")] Info16,
        [Description("issue-closed-24")] IssueClosed,
        [Description("issue-closed-16 (done, complete)")] IssueClosed16,
        [Description("issue-draft-24")] IssueDraft,
        [Description("issue-draft-16")] IssueDraft16,
        [Description("issue-opened-24")] IssueOpened,
        [Description("issue-opened-16 (new)")] IssueOpened16,
        [Description("issue-reopened-24")] IssueReopened,
        [Description("issue-reopened-16 (regression)")] IssueReopened16,
        [Description("issue-tracked-by-24")] IssueTrackedBy,
        [Description("issue-tracked-by-16")] IssueTrackedBy16,
        [Description("issue-tracks-24")] IssueTracks,
        [Description("issue-tracks-16")] IssueTracks16,
        [Description("italic-24")] Italic,
        [Description("italic-16 (font, italic, style)")] Italic16,
        [Description("iterations-24")] Iterations,
        [Description("iterations-16")] Iterations16,
        [Description("kebab-horizontal-24")] KebabHorizontal,
        [Description("kebab-horizontal-16 (kebab, dot, menu, more)")] KebabHorizontal16,
        [Description("key-24")] Key,
        [Description("key-16 (key, lock, secure, safe)")] Key16,
        [Description("key-asterisk-24")] KeyAsterisk,
        [Description("key-asterisk-16")] KeyAsterisk16,
        [Description("law-24")] Law,
        [Description("law-16 (legal, bill)")] Law16,
        [Description("light-bulb-24")] LightBulb,
        [Description("light-bulb-16 (idea)")] LightBulb16,
        [Description("link-24")] Link,
        [Description("link-16 (connect, hyperlink)")] Link16,
        [Description("link-external-24")] LinkExternal,
        [Description("link-external-16 (out, see, more, go, to)")] LinkExternal16,
        [Description("list-ordered-24")] ListOrdered,
        [Description("list-ordered-16 (numbers, tasks, todo, items)")] ListOrdered16,
        [Description("list-unordered-24")] ListUnordered,
        [Description("list-unordered-16 (bullet, point, tasks, todo, items)")] ListUnordered16,
        [Description("location-24")] Location,
        [Description("location-16 (here, marker)")] Location16,
        [Description("lock-24")] Lock,
        [Description("lock-16 (secure, safe, protected)")] Lock16,
        [Description("log-24")] Log,
        [Description("log-16")] Log16,
        [Description("logo-gist-24")] LogoGist,
        [Description("logo-gist-16 (brand, github, logo)")] LogoGist16,
        [Description("logo-github-24")] LogoGithub,
        [Description("logo-github-16 (brand, github, logo)")] LogoGithub16,
        [Description("mail-24")] Mail,
        [Description("mail-16 (email, unread)")] Mail16,
        [Description("markdown-24")] Markdown,
        [Description("markdown-16 (markup, style)")] Markdown16,
        [Description("mark-github-24")] MarkGithub,
        [Description("mark-github-16 (octocat, brand, github, logo)")] MarkGithub16,
        [Description("megaphone-24")] Megaphone,
        [Description("megaphone-16 (bullhorn, loud, shout, broadcast)")] Megaphone16,
        [Description("mention-24")] Mention,
        [Description("mention-16 (at, ping)")] Mention16,
        [Description("meter-24")] Meter,
        [Description("meter-16")] Meter16,
        [Description("milestone-24")] Milestone,
        [Description("milestone-16 (marker)")] Milestone16,
        [Description("mirror-24")] Mirror,
        [Description("mirror-16 (reflect)")] Mirror16,
        [Description("moon-24")] Moon,
        [Description("moon-16")] Moon16,
        [Description("mortar-board-24")] MortarBoard,
        [Description("mortar-board-16 (education, learn, teach)")] MortarBoard16,
        [Description("move-to-bottom-24")] MoveToBottom,
        [Description("move-to-bottom-16 (terminal, end, down, end)")] MoveToBottom16,
        [Description("move-to-end-24")] MoveToEnd,
        [Description("move-to-end-16 (terminal, right, finish)")] MoveToEnd16,
        [Description("move-to-start-24")] MoveToStart,
        [Description("move-to-start-16 (terminal, left, beginning)")] MoveToStart16,
        [Description("move-to-top-24")] MoveToTop,
        [Description("move-to-top-16 (terminal, up, start, beginning)")] MoveToTop16,
        [Description("multi-select-24")] MultiSelect,
        [Description("multi-select-16")] MultiSelect16,
        [Description("mute-24")] Mute,
        [Description("mute-16 (quiet, sound, audio, turn, off)")] Mute16,
        [Description("no-entry-24")] NoEntry,
        [Description("no-entry-16")] NoEntry16,
        [Description("no-entry-fill-12")] NoEntryFill12,
        [Description("north-star-24")] NorthStar,
        [Description("north-star-16 (star, snowflake, asterisk)")] NorthStar16,
        [Description("note-24")] Note,
        [Description("note-16 (card, paper, ticket)")] Note16,
        [Description("number-24")] Number,
        [Description("number-16")] Number16,
        [Description("organization-24")] Organization,
        [Description("organization-16 (people, group, team)")] Organization16,
        [Description("package-24")] Package,
        [Description("package-16 (box, ship)")] Package16,
        [Description("package-dependencies-24")] PackageDependencies,
        [Description("package-dependencies-16")] PackageDependencies16,
        [Description("package-dependents-24")] PackageDependents,
        [Description("package-dependents-16")] PackageDependents16,
        [Description("paintbrush-24")] Paintbrush,
        [Description("paintbrush-16")] Paintbrush16,
        [Description("paper-airplane-24")] PaperAirplane,
        [Description("paper-airplane-16")] PaperAirplane16,
        [Description("paperclip-24")] Paperclip,
        [Description("paperclip-16")] Paperclip16,
        [Description("passkey-fill-24")] PasskeyFill,
        [Description("passkey-fill-16")] PasskeyFill16,
        [Description("paste-24")] Paste,
        [Description("paste-16")] Paste16,
        [Description("pause-24")] Pause,
        [Description("pause-16 (stop, interupt, block, pause)")] Pause16,
        [Description("pencil-24")] Pencil,
        [Description("pencil-16 (edit, change, update, write)")] Pencil16,
        [Description("people-24")] People,
        [Description("people-16")] People16,
        [Description("person-24")] Person,
        [Description("person-16 (people, man, woman, human)")] Person16,
        [Description("person-add-24")] PersonAdd,
        [Description("person-add-16")] PersonAdd16,
        [Description("person-fill-24")] PersonFill,
        [Description("person-fill-16")] PersonFill16,
        [Description("pin-24")] Pin,
        [Description("pin-16 (save, star, bookmark)")] Pin16,
        [Description("pin-slash-24")] PinSlash,
        [Description("pin-slash-16 (unpin, unsave, unstar, unbookmark)")] PinSlash16,
        [Description("pivot-column-24")] PivotColumn,
        [Description("pivot-column-16 (pivot, column, table, project, filter)")] PivotColumn16,
        [Description("play-24")] Play,
        [Description("play-16 (play, start, begin, action)")] Play16,
        [Description("plug-24")] Plug,
        [Description("plug-16 (hook, webhook)")] Plug16,
        [Description("plus-24")] Plus,
        [Description("plus-16 (add, new, more)")] Plus16,
        [Description("plus-circle-24")] PlusCircle,
        [Description("plus-circle-16")] PlusCircle16,
        [Description("project-24")] Project,
        [Description("project-16 (board, kanban, columns, scrum)")] Project16,
        [Description("project-roadmap-24")] ProjectRoadmap,
        [Description("project-roadmap-16")] ProjectRoadmap16,
        [Description("project-symlink-24")] ProjectSymlink,
        [Description("project-symlink-16")] ProjectSymlink16,
        [Description("project-template-24")] ProjectTemplate,
        [Description("project-template-16")] ProjectTemplate16,
        [Description("pulse-24")] Pulse,
        [Description("pulse-16 (graph, trend, line, activity)")] Pulse16,
        [Description("question-24")] Question,
        [Description("question-16 (help, explain)")] Question16,
        [Description("quote-24")] Quote,
        [Description("quote-16 (quotation)")] Quote16,
        [Description("read-24")] Read,
        [Description("read-16")] Read16,
        [Description("redo-24")] Redo,
        [Description("redo-16")] Redo16,
        [Description("rel-file-path-24")] RelFilePath,
        [Description("rel-file-path-16")] RelFilePath16,
        [Description("reply-24")] Reply,
        [Description("reply-16 (reply all, back)")] Reply16,
        [Description("repo-24")] Repo,
        [Description("repo-16 (book, journal, repository)")] Repo16,
        [Description("repo-clone-24")] RepoClone,
        [Description("repo-clone-16 (book, journal, repository)")] RepoClone16,
        [Description("repo-delete-24")] RepoDelete,
        [Description("repo-deleted-16")] RepoDeleted16,
        [Description("repo-forked-24")] RepoForked,
        [Description("repo-forked-16 (book, journal, copy)")] RepoForked16,
        [Description("repo-locked-24")] RepoLocked,
        [Description("repo-locked-16")] RepoLocked16,
        [Description("repo-pull-24")] RepoPull,
        [Description("repo-pull-16 (book, journal, get)")] RepoPull16,
        [Description("repo-push-24")] RepoPush,
        [Description("repo-push-16 (book, journal, repository, put)")] RepoPush16,
        [Description("report-24")] Report,
        [Description("report-16 (report, abuse, flag)")] Report16,
        [Description("repo-template-24")] RepoTemplate,
        [Description("repo-template-16 (book, new, add, template)")] RepoTemplate16,
        [Description("rocket-24")] Rocket,
        [Description("rocket-16 (staff, stafftools, blast, off, space, launch, ship)")] Rocket16,
        [Description("rows-24")] Rows,
        [Description("rows-16")] Rows16,
        [Description("rss-24")] Rss,
        [Description("rss-16 (broadcast, feed, atom)")] Rss16,
        [Description("ruby-24")] Ruby,
        [Description("ruby-16 (code, language)")] Ruby16,
        [Description("screen-full-24")] ScreenFull,
        [Description("screen-full-16 (fullscreen, expand)")] ScreenFull16,
        [Description("screen-normal-24")] ScreenNormal,
        [Description("screen-normal-16 (fullscreen, expand, exit)")] ScreenNormal16,
        [Description("search-24")] Search,
        [Description("search-16 (magnifying, glass)")] Search16,
        [Description("server-24")] Server,
        [Description("server-16 (computers, racks, ops)")] Server16,
        [Description("share-24")] Share,
        [Description("share-16")] Share16,
        [Description("share-android-24")] ShareAndroid,
        [Description("share-android-16")] ShareAndroid16,
        [Description("shield-24")] Shield,
        [Description("shield-16 (security, shield, protection)")] Shield16,
        [Description("shield-check-24")] ShieldCheck,
        [Description("shield-check-16 (security, shield, protection, check, success)")] ShieldCheck16,
        [Description("shield-lock-24")] ShieldLock,
        [Description("shield-lock-16 (protect, shield, lock)")] ShieldLock16,
        [Description("shield-slash-24")] ShieldSlash,
        [Description("shield-slash-16 (shield, slash, protect, unsafe, unprotected, security)")] ShieldSlash16,
        [Description("shield-x-24")] ShieldX,
        [Description("shield-x-16 (security, shield, protection, fail)")] ShieldX16,
        [Description("sidebar-collapse-24")] SidebarCollapse,
        [Description("sidebar-collapse-16")] SidebarCollapse16,
        [Description("sidebar-expand-24")] SidebarExpand,
        [Description("sidebar-expand-16")] SidebarExpand16,
        [Description("sign-in-24")] SignIn,
        [Description("sign-in-16 (door, arrow, direction, enter, log in)")] SignIn16,
        [Description("sign-out-24")] SignOut,
        [Description("sign-out-16 (door, arrow, direction, leave, log out)")] SignOut16,
        [Description("single-select-24")] SingleSelect,
        [Description("single-select-16")] SingleSelect16,
        [Description("skip-24")] Skip,
        [Description("skip-16 (skip, slash)")] Skip16,
        [Description("skip-fill-24")] SkipFill,
        [Description("skip-fill-16")] SkipFill16,
        [Description("sliders-24")] Sliders,
        [Description("sliders-16")] Sliders16,
        [Description("smiley-24")] Smiley,
        [Description("smiley-16 (emoji, smile, mood, emotion)")] Smiley16,
        [Description("sort-asc-24")] SortAsc,
        [Description("sort-asc-16")] SortAsc16,
        [Description("sort-desc-24")] SortDesc,
        [Description("sort-desc-16")] SortDesc16,
        [Description("sparkle-24")] Sparkle,
        [Description("sparkle-16 (spark, ai, generate, shine)")] Sparkle16,
        [Description("sparkle-fill-24")] SparkleFill,
        [Description("sparkle-fill-16")] SparkleFill16,
        [Description("sparkles-fill-24")] SparklesFill,
        [Description("sparkles-fill-16")] SparklesFill16,
        [Description("sponsor-tiers-24")] SponsorTiers,
        [Description("sponsor-tiers-16")] SponsorTiers16,
        [Description("square-24")] Square,
        [Description("square-16")] Square16,
        [Description("square-circle-24")] SquareCircle,
        [Description("square-circle-16 (stop, interupt, block, pause)")] SquareCircle16,
        [Description("square-fill-24")] SquareFill,
        [Description("square-fill-16")] SquareFill16,
        [Description("squirrel-24")] Squirrel,
        [Description("squirrel-16 (ship, shipit, launch)")] Squirrel16,
        [Description("stack-24")] Stack,
        [Description("stack-16")] Stack16,
        [Description("star-24")] Star,
        [Description("star-16 (save, remember, like)")] Star16,
        [Description("star-fill-24")] StarFill,
        [Description("star-fill-16")] StarFill16,
        [Description("stop-24")] Stop,
        [Description("stop-16 (block, spam, report)")] Stop16,
        [Description("stopwatch-24")] Stopwatch,
        [Description("stopwatch-16")] Stopwatch16,
        [Description("strikethrough-24")] Strikethrough,
        [Description("strikethrough-16")] Strikethrough16,
        [Description("sun-24")] Sun,
        [Description("sun-16")] Sun16,
        [Description("sync-24")] Sync,
        [Description("sync-16 (cycle, refresh, loop)")] Sync16,
        [Description("tab-24")] Tab,
        [Description("tab-16")] Tab16,
        [Description("tab-external-24")] TabExternal,
        [Description("tab-external-16")] TabExternal16,
        [Description("table-24")] Table,
        [Description("table-16")] Table16,
        [Description("tag-24")] Tag,
        [Description("tag-16 (release)")] Tag16,
        [Description("tasklist-24")] Tasklist,
        [Description("tasklist-16 (todo)")] Tasklist16,
        [Description("telescope-24")] Telescope,
        [Description("telescope-16 (science, space, look, view, explore)")] Telescope16,
        [Description("telescope-fill-24")] TelescopeFill,
        [Description("telescope-fill-16")] TelescopeFill16,
        [Description("terminal-24")] Terminal,
        [Description("terminal-16 (code, ops, shell)")] Terminal16,
        [Description("three-bars-24")] ThreeBars,
        [Description("three-bars-16 (hamburger, menu, dropdown)")] ThreeBars16,
        [Description("thumbsdown-24")] Thumbsdown,
        [Description("thumbsdown-16 (thumb, thumbsdown, rejected, dislike)")] Thumbsdown16,
        [Description("thumbsup-24")] Thumbsup,
        [Description("thumbsup-16 (thumb, thumbsup, prop, ship, like)")] Thumbsup16,
        [Description("tools-24")] Tools,
        [Description("tools-16 (screwdriver, wrench, settings)")] Tools16,
        [Description("tracked-by-closed-completed-24")] TrackedByClosedCompleted,
        [Description("tracked-by-closed-completed-16")] TrackedByClosedCompleted16,
        [Description("tracked-by-closed-not-planned-24")] TrackedByClosedNotPlanned,
        [Description("tracked-by-closed-not-planned-16")] TrackedByClosedNotPlanned16,
        [Description("trash-24")] Trash,
        [Description("trash-16")] Trash16,
        [Description("triangle-down-24")] TriangleDown,
        [Description("triangle-down-16 (arrow, point, direction)")] TriangleDown16,
        [Description("triangle-left-24")] TriangleLeft,
        [Description("triangle-left-16 (arrow, point, direction)")] TriangleLeft16,
        [Description("triangle-right-24")] TriangleRight,
        [Description("triangle-right-16 (arrow, point, direction)")] TriangleRight16,
        [Description("triangle-up-24")] TriangleUp,
        [Description("triangle-up-16 (arrow, point, direction)")] TriangleUp16,
        [Description("trophy-24")] Trophy,
        [Description("trophy-16")] Trophy16,
        [Description("typography-24")] Typography,
        [Description("typography-16")] Typography16,
        [Description("undo-24")] Undo,
        [Description("undo-16")] Undo16,
        [Description("unfold-24")] Unfold,
        [Description("unfold-16 (expand, open, reveal)")] Unfold16,
        [Description("unlink-24")] Unlink,
        [Description("unlink-16")] Unlink16,
        [Description("unlock-24")] Unlock,
        [Description("unlock-16")] Unlock16,
        [Description("unmute-24")] Unmute,
        [Description("unmute-16 (loud, volume, audio, sound, play)")] Unmute16,
        [Description("unread-24")] Unread,
        [Description("unread-16")] Unread16,
        [Description("unverified-24")] Unverified,
        [Description("unverified-16 (insecure, untrusted, signed)")] Unverified16,
        [Description("upload-24")] Upload,
        [Description("upload-16")] Upload16,
        [Description("verified-24")] Verified,
        [Description("verified-16 (trusted, secure, trustworthy, signed)")] Verified16,
        [Description("versions-24")] Versions,
        [Description("versions-16 (history, commits)")] Versions16,
        [Description("video-24")] Video,
        [Description("video-16")] Video16,
        [Description("webhook-16")] Webhook16,
        [Description("workflow-24")] Workflow,
        [Description("workflow-16 (workflow, actions)")] Workflow16,
        [Description("x-24")] X,
        [Description("x-12 (remove, close, delete)")] X12,
        [Description("x-16 (remove, close, delete)")] X16,
        [Description("x-circle-24")] XCircle,
        [Description("x-circle-16")] XCircle16,
        [Description("x-circle-fill-24")] XCircleFill,
        [Description("x-circle-fill-12")] XCircleFill12,
        [Description("x-circle-fill-16")] XCircleFill16,
        [Description("zap-24")] Zap,
        [Description("zap-16 (electricity, lightning, props, like, star, save)")] Zap16,
        [Description("zoom-in-24")] ZoomIn,
        [Description("zoom-in-16 (zoom, in, plus, bigger)")] ZoomIn16,
        [Description("zoom-out-24")] ZoomOut,
        [Description("zoom-out-16 (zoom, out, minus, smaller)")] ZoomOut16
    }
}